In [39]:
import random
import numpy as np
import pandas as pd

In [40]:
# 正常抽獎
def normal_draw():
    r = random.random() # 0 ~ 1
    if r < 0.05:
        return '頭獎'
    elif r < 0.15:
        return '貳獎'
    else:
        return '未中獎'

In [41]:
# 保底抽獎
def guaranteed_draw():
    r = random.random()
    if r < 1/3:
        return '頭獎' # 0.33 中頭獎
    else:
        return '貳獎' # 0.66 中貳獎

In [42]:
# 帳號狀態清單 可更動
accounts = {
    '611211101':{'is_new_player': True, "new_draws": 0, "new_has_won": False, "lose_conti": 0},
    '611211102':{'is_new_player': True, "new_draws": 2, "new_has_won": False, "lose_conti": 0},
    '611211104':{'is_new_player': True, "new_draws": 3, "new_has_won": True, "lose_conti": 0},
    '611211105':{'is_new_player': True, "new_draws": 2, "new_has_won": True, "lose_conti": 0},
}

# 遊戲機制
def play_game(account, times): # (帳號, 遊玩次數)
    
    if account not in accounts:
        # 新手期：前 5 期至少中 1 次
        accounts[account] = {
            'is_new_player': True,
            'new_draws': 0, # 新手期已抽幾次
            'new_has_won': False, # 新手期是否已中過
            'lose_conti': 0 # 非新手期連續未中次數
        }
        print(f'帳號：{account}，新建立玩家資料')
    else:
        print(f'帳號：{account}，已存在玩家資料')

    player = accounts[account]
    
    if player['new_draws'] >= 5:
        player['is_new_player'] = False

    # 帳號狀態確認
    if player['is_new_player']:
        if player['new_has_won']:
            print('目前狀態：新手期，但您已中獎，不會再觸發新手保底')
        else:
            print('目前狀態：新手期，尚未中獎，仍具有新手保底')
    else:
        print('目前狀態：非新手期，您不具有新手保底')

    print(f'開始遊玩{times}次')

    rewards = [] # 紀錄每次獎金
    
    for i in range(1, times+1):
        trigger = '正常抽獎'
        mes = False
        
        # 新手期 前 5 抽至少中 1
        if player['is_new_player'] and player['new_draws'] < 5:
            if player['new_draws'] == 4 and player['new_has_won'] == False:
                result = guaranteed_draw()
                trigger = '新手保底'
            else:
                result = normal_draw()

            player['new_draws'] = player['new_draws'] + 1

            if result != '未中獎':
                if player['new_has_won'] == False:
                    mes = True
                player['new_has_won'] = True
                player['is_new_player'] = False

            elif player['new_draws'] == 5:
                player['is_new_player'] = False
        
        # 非新手期 20 抽至少中 1
        else:
            if player['lose_conti'] >= 19:
                result = guaranteed_draw()
                trigger = '20抽大保'
            else:
                result = normal_draw()

            if result == '未中獎':
                player['lose_conti'] = player['lose_conti'] + 1
            else:
                player['lose_conti'] = 0

        if result == '頭獎':
            reward = 500
            text = '頭獎 500 元'
        elif result == '貳獎':
            reward = 200
            text = '貳獎 200元'
        else:
            reward = 0
            text = '未中獎 再接再厲'

        rewards.append(reward)

        print(f'第{i}次：{text}，觸發{trigger}')

        if mes:
            print('您已不是新手期，之後不具有新手保底')
            
    print('遊玩結束後玩家狀態：')
    print(player)

    rewards = np.array(rewards)
    n = len(rewards)

    x_bar = rewards.mean()
    s = rewards.std(ddof=1)
    se = s / (n**(1/2))

    z = 1.96
    CI_UPPER = x_bar + z * se
    CI_LOWER = x_bar - z * se
    
    summary = pd.DataFrame(
        {
            '樣本數': [n],
            '單次遊玩獎金期望值估計':[f'{x_bar:.2f}'],
            '標準誤': [f'{se:.2f}'],
            'CI下界': [round(CI_LOWER, 2)],
            'CI上界': [round(CI_UPPER, 2)]
        }
    )
    return summary

In [43]:
while True:
    account = input('請輸入帳號（輸入 /c 離開）：')
    
    if account == '/c':
        print('程式結束')
        break

    summary = play_game(account, times=5000)
    display(summary)

帳號：1，新建立玩家資料
目前狀態：新手期，尚未中獎，仍具有新手保底
開始遊玩5000次
第1次：未中獎 再接再厲，觸發正常抽獎
第2次：未中獎 再接再厲，觸發正常抽獎
第3次：未中獎 再接再厲，觸發正常抽獎
第4次：未中獎 再接再厲，觸發正常抽獎
第5次：貳獎 200元，觸發新手保底
您已不是新手期，之後不具有新手保底
第6次：未中獎 再接再厲，觸發正常抽獎
第7次：未中獎 再接再厲，觸發正常抽獎
第8次：未中獎 再接再厲，觸發正常抽獎
第9次：貳獎 200元，觸發正常抽獎
第10次：未中獎 再接再厲，觸發正常抽獎
第11次：未中獎 再接再厲，觸發正常抽獎
第12次：未中獎 再接再厲，觸發正常抽獎
第13次：貳獎 200元，觸發正常抽獎
第14次：未中獎 再接再厲，觸發正常抽獎
第15次：未中獎 再接再厲，觸發正常抽獎
第16次：未中獎 再接再厲，觸發正常抽獎
第17次：未中獎 再接再厲，觸發正常抽獎
第18次：未中獎 再接再厲，觸發正常抽獎
第19次：未中獎 再接再厲，觸發正常抽獎
第20次：未中獎 再接再厲，觸發正常抽獎
第21次：未中獎 再接再厲，觸發正常抽獎
第22次：頭獎 500 元，觸發正常抽獎
第23次：未中獎 再接再厲，觸發正常抽獎
第24次：未中獎 再接再厲，觸發正常抽獎
第25次：未中獎 再接再厲，觸發正常抽獎
第26次：未中獎 再接再厲，觸發正常抽獎
第27次：未中獎 再接再厲，觸發正常抽獎
第28次：未中獎 再接再厲，觸發正常抽獎
第29次：未中獎 再接再厲，觸發正常抽獎
第30次：未中獎 再接再厲，觸發正常抽獎
第31次：頭獎 500 元，觸發正常抽獎
第32次：未中獎 再接再厲，觸發正常抽獎
第33次：未中獎 再接再厲，觸發正常抽獎
第34次：未中獎 再接再厲，觸發正常抽獎
第35次：未中獎 再接再厲，觸發正常抽獎
第36次：未中獎 再接再厲，觸發正常抽獎
第37次：未中獎 再接再厲，觸發正常抽獎
第38次：未中獎 再接再厲，觸發正常抽獎
第39次：未中獎 再接再厲，觸發正常抽獎
第40次：未中獎 再接再厲，觸發正常抽獎
第41次：未中獎 再接再厲，觸發正常抽獎
第42次：貳獎 200元，觸發正常抽獎
第43次：未中獎 再接再厲，觸發正常抽獎
第44次：未中獎 再接再厲，觸發正常抽獎
第45次：未中獎 再接再厲，觸發正常抽獎
第46次：未中獎 再接再厲，觸發正常抽獎
第47次：未中獎 再接再厲，觸發正常抽獎
第48次：未中獎 再接再厲，觸發正常抽獎
第49次：未中獎 再接再厲，觸發正常抽獎
第50次：未中獎 再接再厲，觸發正常抽獎
第51次：未中獎 再接再厲，觸發正常抽獎
第52次：未中獎 再接再厲，觸發正常抽獎
第53次：未中獎 再接再厲，觸發正常抽獎
第54次：未中獎 再接再厲，觸發正常抽獎
第55次：未中獎 再接再厲，觸發正常抽獎
第56次：未中獎 再接再厲，觸發正常抽獎
第57次：未中獎 再接再厲，觸發正常抽獎
第58次：未中獎 再接再厲，觸發正常抽獎
第59次：未中獎 再接再厲，觸發正常抽獎
第60次：未中獎 再接再厲，觸發正常抽獎
第61次：未中獎 再接再厲，觸發正常抽獎
第62次：頭獎 500 元，觸發20抽大保
第63次：未中獎 再接再厲，觸發正常抽獎
第64次：貳獎 200元，觸發正常抽獎
第65次：未中獎 再接再厲，觸發正常抽獎
第66次：未中獎 再接再厲，觸發正常抽獎
第67次：貳獎 200元，觸發正常抽獎
第68次：未中獎 再接再厲，觸發正常抽獎
第69次：未中獎 再接再厲，觸發正常抽獎
第70次：未中獎 再接再厲，觸發正常抽獎
第71次：未中獎 再接再厲，觸發正常抽獎
第72次：未中獎 再接再厲，觸發正常抽獎
第73次：未中獎 再接再厲，觸發正常抽獎
第74次：未中獎 再接再厲，觸發正常抽獎
第75次：未中獎 再接再厲，觸發正常抽獎
第76次：未中獎 再接再厲，觸發正常抽獎
第77次：未中獎 再接再厲，觸發正常抽獎
第78次：未中獎 再接再厲，觸發正常抽獎
第79次：貳獎 200元，觸發正常抽獎
第80次：未中獎 再接再厲，觸發正常抽獎
第81次：未中獎 再接再厲，觸發正常抽獎
第82次：未中獎 再接再厲，觸發正常抽獎
第83次：未中獎 再接再厲，觸發正常抽獎
第84次：未中獎 再接再厲，觸發正常抽獎
第85次：貳獎 200元，觸發正常抽獎
第86次：未中獎 再接再厲，觸發正常抽獎
第87次：未中獎 再接再厲，觸發正常抽獎
第88次：未中獎 再接再厲，觸發正常抽獎
第89次：未中獎 再接再厲，觸發正常抽獎
第90次：未中獎 再接再厲，觸發正常抽獎
第91次：未中獎 再接再厲，觸發正常抽獎
第92次：未中獎 再接再厲，觸發正常抽獎
第93次：貳獎 200元，觸發正常抽獎
第94次：未中獎 再接再厲，觸發正常抽獎
第95次：未中獎 再接再厲，觸發正常抽獎
第96次：未中獎 再接再厲，觸發正常抽獎
第97次：未中獎 再接再厲，觸發正常抽獎
第98次：未中獎 再接再厲，觸發正常抽獎
第99次：未中獎 再接再厲，觸發正常抽獎
第100次：未中獎 再接再厲，觸發正常抽獎
第101次：未中獎 再接再厲，觸發正常抽獎
第102次：未中獎 再接再厲，觸發正常抽獎
第103次：未中獎 再接再厲，觸發正常抽獎
第104次：未中獎 再接再厲，觸發正常抽獎
第105次：未中獎 再接再厲，觸發正常抽獎
第106次：未中獎 再接再厲，觸發正常抽獎
第107次：未中獎 再接再厲，觸發正常抽獎
第108次：未中獎 再接再厲，觸發正常抽獎
第109次：頭獎 500 元，觸發正常抽獎
第110次：未中獎 再接再厲，觸發正常抽獎
第111次：未中獎 再接再厲，觸發正常抽獎
第112次：未中獎 再接再厲，觸發正常抽獎
第113次：未中獎 再接再厲，觸發正常抽獎
第114次：貳獎 200元，觸發正常抽獎
第115次：頭獎 500 元，觸發正常抽獎
第116次：未中獎 再接再厲，觸發正常抽獎
第117次：未中獎 再接再厲，觸發正常抽獎
第118次：未中獎 再接再厲，觸發正常抽獎
第119次：貳獎 200元，觸發正常抽獎
第120次：未中獎 再接再厲，觸發正常抽獎
第121次：未中獎 再接再厲，觸發正常抽獎
第122次：未中獎 再接再厲，觸發正常抽獎
第123次：未中獎 再接再厲，觸發正常抽獎
第124次：未中獎 再接再厲，觸發正常抽獎
第125次：未中獎 再接再厲，觸發正常抽獎
第126次：未中獎 再接再厲，觸發正常抽獎
第127次：頭獎 500 元，觸發正常抽獎
第128次：未中獎 再接再厲，觸發正常抽獎
第129次：頭獎 500 元，觸發正常抽獎
第130次：未中獎 再接再厲，觸發正常抽獎
第131次：未中獎 再接再厲，觸發正常抽獎
第132次：未中獎 再接再厲，觸發正常抽獎
第133次：未中獎 再接再厲，觸發正常抽獎
第134次：頭獎 500 元，觸發正常抽獎
第135次：未中獎 再接再厲，觸發正常抽獎
第136次：未中獎 再接再厲，觸發正常抽獎
第137次：未中獎 再接再厲，觸發正常抽獎
第138次：未中獎 再接再厲，觸發正常抽獎
第139次：未中獎 再接再厲，觸發正常抽獎
第140次：未中獎 再接再厲，觸發正常抽獎
第141次：未中獎 再接再厲，觸發正常抽獎
第142次：未中獎 再接再厲，觸發正常抽獎
第143次：未中獎 再接再厲，觸發正常抽獎
第144次：未中獎 再接再厲，觸發正常抽獎
第145次：未中獎 再接再厲，觸發正常抽獎
第146次：未中獎 再接再厲，觸發正常抽獎
第147次：未中獎 再接再厲，觸發正常抽獎
第148次：未中獎 再接再厲，觸發正常抽獎
第149次：未中獎 再接再厲，觸發正常抽獎
第150次：未中獎 再接再厲，觸發正常抽獎
第151次：未中獎 再接再厲，觸發正常抽獎
第152次：未中獎 再接再厲，觸發正常抽獎
第153次：未中獎 再接再厲，觸發正常抽獎
第154次：貳獎 200元，觸發20抽大保
第155次：貳獎 200元，觸發正常抽獎
第156次：未中獎 再接再厲，觸發正常抽獎
第157次：未中獎 再接再厲，觸發正常抽獎
第158次：未中獎 再接再厲，觸發正常抽獎
第159次：未中獎 再接再厲，觸發正常抽獎
第160次：未中獎 再接再厲，觸發正常抽獎
第161次：未中獎 再接再厲，觸發正常抽獎
第162次：未中獎 再接再厲，觸發正常抽獎
第163次：未中獎 再接再厲，觸發正常抽獎
第164次：未中獎 再接再厲，觸發正常抽獎
第165次：未中獎 再接再厲，觸發正常抽獎
第166次：未中獎 再接再厲，觸發正常抽獎
第167次：未中獎 再接再厲，觸發正常抽獎
第168次：未中獎 再接再厲，觸發正常抽獎
第169次：未中獎 再接再厲，觸發正常抽獎
第170次：未中獎 再接再厲，觸發正常抽獎
第171次：未中獎 再接再厲，觸發正常抽獎
第172次：未中獎 再接再厲，觸發正常抽獎
第173次：未中獎 再接再厲，觸發正常抽獎
第174次：未中獎 再接再厲，觸發正常抽獎
第175次：貳獎 200元，觸發20抽大保
第176次：未中獎 再接再厲，觸發正常抽獎
第177次：未中獎 再接再厲，觸發正常抽獎
第178次：未中獎 再接再厲，觸發正常抽獎
第179次：貳獎 200元，觸發正常抽獎
第180次：貳獎 200元，觸發正常抽獎
第181次：未中獎 再接再厲，觸發正常抽獎
第182次：未中獎 再接再厲，觸發正常抽獎
第183次：未中獎 再接再厲，觸發正常抽獎
第184次：未中獎 再接再厲，觸發正常抽獎
第185次：貳獎 200元，觸發正常抽獎
第186次：貳獎 200元，觸發正常抽獎
第187次：頭獎 500 元，觸發正常抽獎
第188次：未中獎 再接再厲，觸發正常抽獎
第189次：未中獎 再接再厲，觸發正常抽獎
第190次：貳獎 200元，觸發正常抽獎
第191次：未中獎 再接再厲，觸發正常抽獎
第192次：未中獎 再接再厲，觸發正常抽獎
第193次：未中獎 再接再厲，觸發正常抽獎
第194次：未中獎 再接再厲，觸發正常抽獎
第195次：未中獎 再接再厲，觸發正常抽獎
第196次：未中獎 再接再厲，觸發正常抽獎
第197次：未中獎 再接再厲，觸發正常抽獎
第198次：未中獎 再接再厲，觸發正常抽獎
第199次：未中獎 再接再厲，觸發正常抽獎
第200次：未中獎 再接再厲，觸發正常抽獎
第201次：未中獎 再接再厲，觸發正常抽獎
第202次：未中獎 再接再厲，觸發正常抽獎
第203次：未中獎 再接再厲，觸發正常抽獎
第204次：貳獎 200元，觸發正常抽獎
第205次：未中獎 再接再厲，觸發正常抽獎
第206次：未中獎 再接再厲，觸發正常抽獎
第207次：未中獎 再接再厲，觸發正常抽獎
第208次：未中獎 再接再厲，觸發正常抽獎
第209次：未中獎 再接再厲，觸發正常抽獎
第210次：未中獎 再接再厲，觸發正常抽獎
第211次：貳獎 200元，觸發正常抽獎
第212次：未中獎 再接再厲，觸發正常抽獎
第213次：未中獎 再接再厲，觸發正常抽獎
第214次：未中獎 再接再厲，觸發正常抽獎
第215次：未中獎 再接再厲，觸發正常抽獎
第216次：未中獎 再接再厲，觸發正常抽獎
第217次：未中獎 再接再厲，觸發正常抽獎
第218次：貳獎 200元，觸發正常抽獎
第219次：未中獎 再接再厲，觸發正常抽獎
第220次：未中獎 再接再厲，觸發正常抽獎
第221次：未中獎 再接再厲，觸發正常抽獎
第222次：貳獎 200元，觸發正常抽獎
第223次：未中獎 再接再厲，觸發正常抽獎
第224次：未中獎 再接再厲，觸發正常抽獎
第225次：頭獎 500 元，觸發正常抽獎
第226次：未中獎 再接再厲，觸發正常抽獎
第227次：未中獎 再接再厲，觸發正常抽獎
第228次：未中獎 再接再厲，觸發正常抽獎
第229次：頭獎 500 元，觸發正常抽獎
第230次：未中獎 再接再厲，觸發正常抽獎
第231次：未中獎 再接再厲，觸發正常抽獎
第232次：未中獎 再接再厲，觸發正常抽獎
第233次：未中獎 再接再厲，觸發正常抽獎
第234次：未中獎 再接再厲，觸發正常抽獎
第235次：未中獎 再接再厲，觸發正常抽獎
第236次：頭獎 500 元，觸發正常抽獎
第237次：未中獎 再接再厲，觸發正常抽獎
第238次：未中獎 再接再厲，觸發正常抽獎
第239次：未中獎 再接再厲，觸發正常抽獎
第240次：未中獎 再接再厲，觸發正常抽獎
第241次：未中獎 再接再厲，觸發正常抽獎
第242次：未中獎 再接再厲，觸發正常抽獎
第243次：未中獎 再接再厲，觸發正常抽獎
第244次：未中獎 再接再厲，觸發正常抽獎
第245次：未中獎 再接再厲，觸發正常抽獎
第246次：貳獎 200元，觸發正常抽獎
第247次：頭獎 500 元，觸發正常抽獎
第248次：未中獎 再接再厲，觸發正常抽獎
第249次：未中獎 再接再厲，觸發正常抽獎
第250次：貳獎 200元，觸發正常抽獎
第251次：未中獎 再接再厲，觸發正常抽獎
第252次：頭獎 500 元，觸發正常抽獎
第253次：未中獎 再接再厲，觸發正常抽獎
第254次：頭獎 500 元，觸發正常抽獎
第255次：未中獎 再接再厲，觸發正常抽獎
第256次：未中獎 再接再厲，觸發正常抽獎
第257次：未中獎 再接再厲，觸發正常抽獎
第258次：貳獎 200元，觸發正常抽獎
第259次：未中獎 再接再厲，觸發正常抽獎
第260次：貳獎 200元，觸發正常抽獎
第261次：未中獎 再接再厲，觸發正常抽獎
第262次：未中獎 再接再厲，觸發正常抽獎
第263次：未中獎 再接再厲，觸發正常抽獎
第264次：未中獎 再接再厲，觸發正常抽獎
第265次：未中獎 再接再厲，觸發正常抽獎
第266次：未中獎 再接再厲，觸發正常抽獎
第267次：未中獎 再接再厲，觸發正常抽獎
第268次：未中獎 再接再厲，觸發正常抽獎
第269次：未中獎 再接再厲，觸發正常抽獎
第270次：未中獎 再接再厲，觸發正常抽獎
第271次：未中獎 再接再厲，觸發正常抽獎
第272次：未中獎 再接再厲，觸發正常抽獎
第273次：未中獎 再接再厲，觸發正常抽獎
第274次：未中獎 再接再厲，觸發正常抽獎
第275次：未中獎 再接再厲，觸發正常抽獎
第276次：未中獎 再接再厲，觸發正常抽獎
第277次：頭獎 500 元，觸發正常抽獎
第278次：未中獎 再接再厲，觸發正常抽獎
第279次：未中獎 再接再厲，觸發正常抽獎
第280次：未中獎 再接再厲，觸發正常抽獎
第281次：貳獎 200元，觸發正常抽獎
第282次：未中獎 再接再厲，觸發正常抽獎
第283次：未中獎 再接再厲，觸發正常抽獎
第284次：未中獎 再接再厲，觸發正常抽獎
第285次：未中獎 再接再厲，觸發正常抽獎
第286次：未中獎 再接再厲，觸發正常抽獎
第287次：未中獎 再接再厲，觸發正常抽獎
第288次：頭獎 500 元，觸發正常抽獎
第289次：貳獎 200元，觸發正常抽獎
第290次：未中獎 再接再厲，觸發正常抽獎
第291次：未中獎 再接再厲，觸發正常抽獎
第292次：未中獎 再接再厲，觸發正常抽獎
第293次：貳獎 200元，觸發正常抽獎
第294次：未中獎 再接再厲，觸發正常抽獎
第295次：未中獎 再接再厲，觸發正常抽獎
第296次：未中獎 再接再厲，觸發正常抽獎
第297次：未中獎 再接再厲，觸發正常抽獎
第298次：未中獎 再接再厲，觸發正常抽獎
第299次：未中獎 再接再厲，觸發正常抽獎
第300次：未中獎 再接再厲，觸發正常抽獎
第301次：未中獎 再接再厲，觸發正常抽獎
第302次：未中獎 再接再厲，觸發正常抽獎
第303次：未中獎 再接再厲，觸發正常抽獎
第304次：未中獎 再接再厲，觸發正常抽獎
第305次：未中獎 再接再厲，觸發正常抽獎
第306次：未中獎 再接再厲，觸發正常抽獎
第307次：頭獎 500 元，觸發正常抽獎
第308次：未中獎 再接再厲，觸發正常抽獎
第309次：未中獎 再接再厲，觸發正常抽獎
第310次：貳獎 200元，觸發正常抽獎
第311次：未中獎 再接再厲，觸發正常抽獎
第312次：未中獎 再接再厲，觸發正常抽獎
第313次：未中獎 再接再厲，觸發正常抽獎
第314次：未中獎 再接再厲，觸發正常抽獎
第315次：未中獎 再接再厲，觸發正常抽獎
第316次：頭獎 500 元，觸發正常抽獎
第317次：貳獎 200元，觸發正常抽獎
第318次：未中獎 再接再厲，觸發正常抽獎
第319次：未中獎 再接再厲，觸發正常抽獎
第320次：未中獎 再接再厲，觸發正常抽獎
第321次：未中獎 再接再厲，觸發正常抽獎
第322次：頭獎 500 元，觸發正常抽獎
第323次：貳獎 200元，觸發正常抽獎
第324次：未中獎 再接再厲，觸發正常抽獎
第325次：未中獎 再接再厲，觸發正常抽獎
第326次：未中獎 再接再厲，觸發正常抽獎
第327次：未中獎 再接再厲，觸發正常抽獎
第328次：未中獎 再接再厲，觸發正常抽獎
第329次：未中獎 再接再厲，觸發正常抽獎
第330次：未中獎 再接再厲，觸發正常抽獎
第331次：未中獎 再接再厲，觸發正常抽獎
第332次：未中獎 再接再厲，觸發正常抽獎
第333次：未中獎 再接再厲，觸發正常抽獎
第334次：未中獎 再接再厲，觸發正常抽獎
第335次：貳獎 200元，觸發正常抽獎
第336次：頭獎 500 元，觸發正常抽獎
第337次：未中獎 再接再厲，觸發正常抽獎
第338次：未中獎 再接再厲，觸發正常抽獎
第339次：未中獎 再接再厲，觸發正常抽獎
第340次：未中獎 再接再厲，觸發正常抽獎
第341次：頭獎 500 元，觸發正常抽獎
第342次：未中獎 再接再厲，觸發正常抽獎
第343次：頭獎 500 元，觸發正常抽獎
第344次：未中獎 再接再厲，觸發正常抽獎
第345次：未中獎 再接再厲，觸發正常抽獎
第346次：未中獎 再接再厲，觸發正常抽獎
第347次：貳獎 200元，觸發正常抽獎
第348次：未中獎 再接再厲，觸發正常抽獎
第349次：未中獎 再接再厲，觸發正常抽獎
第350次：未中獎 再接再厲，觸發正常抽獎
第351次：頭獎 500 元，觸發正常抽獎
第352次：未中獎 再接再厲，觸發正常抽獎
第353次：未中獎 再接再厲，觸發正常抽獎
第354次：未中獎 再接再厲，觸發正常抽獎
第355次：未中獎 再接再厲，觸發正常抽獎
第356次：貳獎 200元，觸發正常抽獎
第357次：未中獎 再接再厲，觸發正常抽獎
第358次：未中獎 再接再厲，觸發正常抽獎
第359次：未中獎 再接再厲，觸發正常抽獎
第360次：未中獎 再接再厲，觸發正常抽獎
第361次：未中獎 再接再厲，觸發正常抽獎
第362次：未中獎 再接再厲，觸發正常抽獎
第363次：未中獎 再接再厲，觸發正常抽獎
第364次：未中獎 再接再厲，觸發正常抽獎
第365次：未中獎 再接再厲，觸發正常抽獎
第366次：未中獎 再接再厲，觸發正常抽獎
第367次：未中獎 再接再厲，觸發正常抽獎
第368次：未中獎 再接再厲，觸發正常抽獎
第369次：頭獎 500 元，觸發正常抽獎
第370次：未中獎 再接再厲，觸發正常抽獎
第371次：未中獎 再接再厲，觸發正常抽獎
第372次：未中獎 再接再厲，觸發正常抽獎
第373次：未中獎 再接再厲，觸發正常抽獎
第374次：未中獎 再接再厲，觸發正常抽獎
第375次：未中獎 再接再厲，觸發正常抽獎
第376次：貳獎 200元，觸發正常抽獎
第377次：貳獎 200元，觸發正常抽獎
第378次：未中獎 再接再厲，觸發正常抽獎
第379次：頭獎 500 元，觸發正常抽獎
第380次：未中獎 再接再厲，觸發正常抽獎
第381次：未中獎 再接再厲，觸發正常抽獎
第382次：未中獎 再接再厲，觸發正常抽獎
第383次：未中獎 再接再厲，觸發正常抽獎
第384次：未中獎 再接再厲，觸發正常抽獎
第385次：未中獎 再接再厲，觸發正常抽獎
第386次：未中獎 再接再厲，觸發正常抽獎
第387次：未中獎 再接再厲，觸發正常抽獎
第388次：未中獎 再接再厲，觸發正常抽獎
第389次：未中獎 再接再厲，觸發正常抽獎
第390次：未中獎 再接再厲，觸發正常抽獎
第391次：未中獎 再接再厲，觸發正常抽獎
第392次：未中獎 再接再厲，觸發正常抽獎
第393次：未中獎 再接再厲，觸發正常抽獎
第394次：未中獎 再接再厲，觸發正常抽獎
第395次：未中獎 再接再厲，觸發正常抽獎
第396次：貳獎 200元，觸發正常抽獎
第397次：未中獎 再接再厲，觸發正常抽獎
第398次：頭獎 500 元，觸發正常抽獎
第399次：未中獎 再接再厲，觸發正常抽獎
第400次：未中獎 再接再厲，觸發正常抽獎
第401次：未中獎 再接再厲，觸發正常抽獎
第402次：未中獎 再接再厲，觸發正常抽獎
第403次：未中獎 再接再厲，觸發正常抽獎
第404次：未中獎 再接再厲，觸發正常抽獎
第405次：未中獎 再接再厲，觸發正常抽獎
第406次：未中獎 再接再厲，觸發正常抽獎
第407次：貳獎 200元，觸發正常抽獎
第408次：未中獎 再接再厲，觸發正常抽獎
第409次：未中獎 再接再厲，觸發正常抽獎
第410次：貳獎 200元，觸發正常抽獎
第411次：未中獎 再接再厲，觸發正常抽獎
第412次：未中獎 再接再厲，觸發正常抽獎
第413次：未中獎 再接再厲，觸發正常抽獎
第414次：未中獎 再接再厲，觸發正常抽獎
第415次：未中獎 再接再厲，觸發正常抽獎
第416次：未中獎 再接再厲，觸發正常抽獎
第417次：未中獎 再接再厲，觸發正常抽獎
第418次：未中獎 再接再厲，觸發正常抽獎
第419次：未中獎 再接再厲，觸發正常抽獎
第420次：貳獎 200元，觸發正常抽獎
第421次：未中獎 再接再厲，觸發正常抽獎
第422次：未中獎 再接再厲，觸發正常抽獎
第423次：未中獎 再接再厲，觸發正常抽獎
第424次：貳獎 200元，觸發正常抽獎
第425次：未中獎 再接再厲，觸發正常抽獎
第426次：頭獎 500 元，觸發正常抽獎
第427次：未中獎 再接再厲，觸發正常抽獎
第428次：未中獎 再接再厲，觸發正常抽獎
第429次：未中獎 再接再厲，觸發正常抽獎
第430次：未中獎 再接再厲，觸發正常抽獎
第431次：未中獎 再接再厲，觸發正常抽獎
第432次：未中獎 再接再厲，觸發正常抽獎
第433次：未中獎 再接再厲，觸發正常抽獎
第434次：未中獎 再接再厲，觸發正常抽獎
第435次：未中獎 再接再厲，觸發正常抽獎
第436次：未中獎 再接再厲，觸發正常抽獎
第437次：未中獎 再接再厲，觸發正常抽獎
第438次：未中獎 再接再厲，觸發正常抽獎
第439次：未中獎 再接再厲，觸發正常抽獎
第440次：未中獎 再接再厲，觸發正常抽獎
第441次：未中獎 再接再厲，觸發正常抽獎
第442次：未中獎 再接再厲，觸發正常抽獎
第443次：未中獎 再接再厲，觸發正常抽獎
第444次：未中獎 再接再厲，觸發正常抽獎
第445次：貳獎 200元，觸發正常抽獎
第446次：貳獎 200元，觸發正常抽獎
第447次：未中獎 再接再厲，觸發正常抽獎
第448次：未中獎 再接再厲，觸發正常抽獎
第449次：未中獎 再接再厲，觸發正常抽獎
第450次：貳獎 200元，觸發正常抽獎
第451次：未中獎 再接再厲，觸發正常抽獎
第452次：未中獎 再接再厲，觸發正常抽獎
第453次：未中獎 再接再厲，觸發正常抽獎
第454次：貳獎 200元，觸發正常抽獎
第455次：未中獎 再接再厲，觸發正常抽獎
第456次：未中獎 再接再厲，觸發正常抽獎
第457次：未中獎 再接再厲，觸發正常抽獎
第458次：未中獎 再接再厲，觸發正常抽獎
第459次：貳獎 200元，觸發正常抽獎
第460次：貳獎 200元，觸發正常抽獎
第461次：未中獎 再接再厲，觸發正常抽獎
第462次：未中獎 再接再厲，觸發正常抽獎
第463次：未中獎 再接再厲，觸發正常抽獎
第464次：未中獎 再接再厲，觸發正常抽獎
第465次：貳獎 200元，觸發正常抽獎
第466次：貳獎 200元，觸發正常抽獎
第467次：未中獎 再接再厲，觸發正常抽獎
第468次：未中獎 再接再厲，觸發正常抽獎
第469次：未中獎 再接再厲，觸發正常抽獎
第470次：未中獎 再接再厲，觸發正常抽獎
第471次：未中獎 再接再厲，觸發正常抽獎
第472次：貳獎 200元，觸發正常抽獎
第473次：未中獎 再接再厲，觸發正常抽獎
第474次：未中獎 再接再厲，觸發正常抽獎
第475次：貳獎 200元，觸發正常抽獎
第476次：未中獎 再接再厲，觸發正常抽獎
第477次：未中獎 再接再厲，觸發正常抽獎
第478次：未中獎 再接再厲，觸發正常抽獎
第479次：未中獎 再接再厲，觸發正常抽獎
第480次：未中獎 再接再厲，觸發正常抽獎
第481次：未中獎 再接再厲，觸發正常抽獎
第482次：未中獎 再接再厲，觸發正常抽獎
第483次：未中獎 再接再厲，觸發正常抽獎
第484次：貳獎 200元，觸發正常抽獎
第485次：未中獎 再接再厲，觸發正常抽獎
第486次：未中獎 再接再厲，觸發正常抽獎
第487次：未中獎 再接再厲，觸發正常抽獎
第488次：未中獎 再接再厲，觸發正常抽獎
第489次：未中獎 再接再厲，觸發正常抽獎
第490次：未中獎 再接再厲，觸發正常抽獎
第491次：未中獎 再接再厲，觸發正常抽獎
第492次：未中獎 再接再厲，觸發正常抽獎
第493次：未中獎 再接再厲，觸發正常抽獎
第494次：未中獎 再接再厲，觸發正常抽獎
第495次：未中獎 再接再厲，觸發正常抽獎
第496次：未中獎 再接再厲，觸發正常抽獎
第497次：未中獎 再接再厲，觸發正常抽獎
第498次：未中獎 再接再厲，觸發正常抽獎
第499次：未中獎 再接再厲，觸發正常抽獎
第500次：未中獎 再接再厲，觸發正常抽獎
第501次：未中獎 再接再厲，觸發正常抽獎
第502次：未中獎 再接再厲，觸發正常抽獎
第503次：頭獎 500 元，觸發正常抽獎
第504次：貳獎 200元，觸發正常抽獎
第505次：頭獎 500 元，觸發正常抽獎
第506次：未中獎 再接再厲，觸發正常抽獎
第507次：未中獎 再接再厲，觸發正常抽獎
第508次：未中獎 再接再厲，觸發正常抽獎
第509次：貳獎 200元，觸發正常抽獎
第510次：未中獎 再接再厲，觸發正常抽獎
第511次：未中獎 再接再厲，觸發正常抽獎
第512次：未中獎 再接再厲，觸發正常抽獎
第513次：未中獎 再接再厲，觸發正常抽獎
第514次：未中獎 再接再厲，觸發正常抽獎
第515次：貳獎 200元，觸發正常抽獎
第516次：未中獎 再接再厲，觸發正常抽獎
第517次：貳獎 200元，觸發正常抽獎
第518次：未中獎 再接再厲，觸發正常抽獎
第519次：未中獎 再接再厲，觸發正常抽獎
第520次：未中獎 再接再厲，觸發正常抽獎
第521次：未中獎 再接再厲，觸發正常抽獎
第522次：未中獎 再接再厲，觸發正常抽獎
第523次：未中獎 再接再厲，觸發正常抽獎
第524次：未中獎 再接再厲，觸發正常抽獎
第525次：頭獎 500 元，觸發正常抽獎
第526次：貳獎 200元，觸發正常抽獎
第527次：未中獎 再接再厲，觸發正常抽獎
第528次：未中獎 再接再厲，觸發正常抽獎
第529次：貳獎 200元，觸發正常抽獎
第530次：頭獎 500 元，觸發正常抽獎
第531次：未中獎 再接再厲，觸發正常抽獎
第532次：未中獎 再接再厲，觸發正常抽獎
第533次：貳獎 200元，觸發正常抽獎
第534次：未中獎 再接再厲，觸發正常抽獎
第535次：未中獎 再接再厲，觸發正常抽獎
第536次：貳獎 200元，觸發正常抽獎
第537次：未中獎 再接再厲，觸發正常抽獎
第538次：未中獎 再接再厲，觸發正常抽獎
第539次：未中獎 再接再厲，觸發正常抽獎
第540次：未中獎 再接再厲，觸發正常抽獎
第541次：未中獎 再接再厲，觸發正常抽獎
第542次：未中獎 再接再厲，觸發正常抽獎
第543次：未中獎 再接再厲，觸發正常抽獎
第544次：未中獎 再接再厲，觸發正常抽獎
第545次：貳獎 200元，觸發正常抽獎
第546次：未中獎 再接再厲，觸發正常抽獎
第547次：未中獎 再接再厲，觸發正常抽獎
第548次：未中獎 再接再厲，觸發正常抽獎
第549次：未中獎 再接再厲，觸發正常抽獎
第550次：頭獎 500 元，觸發正常抽獎
第551次：未中獎 再接再厲，觸發正常抽獎
第552次：未中獎 再接再厲，觸發正常抽獎
第553次：貳獎 200元，觸發正常抽獎
第554次：未中獎 再接再厲，觸發正常抽獎
第555次：未中獎 再接再厲，觸發正常抽獎
第556次：未中獎 再接再厲，觸發正常抽獎
第557次：未中獎 再接再厲，觸發正常抽獎
第558次：未中獎 再接再厲，觸發正常抽獎
第559次：未中獎 再接再厲，觸發正常抽獎
第560次：未中獎 再接再厲，觸發正常抽獎
第561次：未中獎 再接再厲，觸發正常抽獎
第562次：未中獎 再接再厲，觸發正常抽獎
第563次：貳獎 200元，觸發正常抽獎
第564次：未中獎 再接再厲，觸發正常抽獎
第565次：未中獎 再接再厲，觸發正常抽獎
第566次：未中獎 再接再厲，觸發正常抽獎
第567次：未中獎 再接再厲，觸發正常抽獎
第568次：未中獎 再接再厲，觸發正常抽獎
第569次：未中獎 再接再厲，觸發正常抽獎
第570次：未中獎 再接再厲，觸發正常抽獎
第571次：未中獎 再接再厲，觸發正常抽獎
第572次：未中獎 再接再厲，觸發正常抽獎
第573次：未中獎 再接再厲，觸發正常抽獎
第574次：未中獎 再接再厲，觸發正常抽獎
第575次：未中獎 再接再厲，觸發正常抽獎
第576次：未中獎 再接再厲，觸發正常抽獎
第577次：未中獎 再接再厲，觸發正常抽獎
第578次：未中獎 再接再厲，觸發正常抽獎
第579次：未中獎 再接再厲，觸發正常抽獎
第580次：未中獎 再接再厲，觸發正常抽獎
第581次：未中獎 再接再厲，觸發正常抽獎
第582次：未中獎 再接再厲，觸發正常抽獎
第583次：貳獎 200元，觸發20抽大保
第584次：未中獎 再接再厲，觸發正常抽獎
第585次：未中獎 再接再厲，觸發正常抽獎
第586次：未中獎 再接再厲，觸發正常抽獎
第587次：貳獎 200元，觸發正常抽獎
第588次：未中獎 再接再厲，觸發正常抽獎
第589次：未中獎 再接再厲，觸發正常抽獎
第590次：貳獎 200元，觸發正常抽獎
第591次：未中獎 再接再厲，觸發正常抽獎
第592次：未中獎 再接再厲，觸發正常抽獎
第593次：未中獎 再接再厲，觸發正常抽獎
第594次：未中獎 再接再厲，觸發正常抽獎
第595次：貳獎 200元，觸發正常抽獎
第596次：貳獎 200元，觸發正常抽獎
第597次：未中獎 再接再厲，觸發正常抽獎
第598次：貳獎 200元，觸發正常抽獎
第599次：未中獎 再接再厲，觸發正常抽獎
第600次：未中獎 再接再厲，觸發正常抽獎
第601次：未中獎 再接再厲，觸發正常抽獎
第602次：未中獎 再接再厲，觸發正常抽獎
第603次：未中獎 再接再厲，觸發正常抽獎
第604次：未中獎 再接再厲，觸發正常抽獎
第605次：未中獎 再接再厲，觸發正常抽獎
第606次：未中獎 再接再厲，觸發正常抽獎
第607次：未中獎 再接再厲，觸發正常抽獎
第608次：未中獎 再接再厲，觸發正常抽獎
第609次：未中獎 再接再厲，觸發正常抽獎
第610次：未中獎 再接再厲，觸發正常抽獎
第611次：未中獎 再接再厲，觸發正常抽獎
第612次：未中獎 再接再厲，觸發正常抽獎
第613次：未中獎 再接再厲，觸發正常抽獎
第614次：未中獎 再接再厲，觸發正常抽獎
第615次：未中獎 再接再厲，觸發正常抽獎
第616次：貳獎 200元，觸發正常抽獎
第617次：貳獎 200元，觸發正常抽獎
第618次：貳獎 200元，觸發正常抽獎
第619次：未中獎 再接再厲，觸發正常抽獎
第620次：未中獎 再接再厲，觸發正常抽獎
第621次：未中獎 再接再厲，觸發正常抽獎
第622次：貳獎 200元，觸發正常抽獎
第623次：未中獎 再接再厲，觸發正常抽獎
第624次：未中獎 再接再厲，觸發正常抽獎
第625次：未中獎 再接再厲，觸發正常抽獎
第626次：未中獎 再接再厲，觸發正常抽獎
第627次：未中獎 再接再厲，觸發正常抽獎
第628次：未中獎 再接再厲，觸發正常抽獎
第629次：未中獎 再接再厲，觸發正常抽獎
第630次：未中獎 再接再厲，觸發正常抽獎
第631次：未中獎 再接再厲，觸發正常抽獎
第632次：未中獎 再接再厲，觸發正常抽獎
第633次：未中獎 再接再厲，觸發正常抽獎
第634次：未中獎 再接再厲，觸發正常抽獎
第635次：未中獎 再接再厲，觸發正常抽獎
第636次：未中獎 再接再厲，觸發正常抽獎
第637次：未中獎 再接再厲，觸發正常抽獎
第638次：貳獎 200元，觸發正常抽獎
第639次：未中獎 再接再厲，觸發正常抽獎
第640次：未中獎 再接再厲，觸發正常抽獎
第641次：未中獎 再接再厲，觸發正常抽獎
第642次：貳獎 200元，觸發正常抽獎
第643次：未中獎 再接再厲，觸發正常抽獎
第644次：未中獎 再接再厲，觸發正常抽獎
第645次：未中獎 再接再厲，觸發正常抽獎
第646次：未中獎 再接再厲，觸發正常抽獎
第647次：未中獎 再接再厲，觸發正常抽獎
第648次：未中獎 再接再厲，觸發正常抽獎
第649次：未中獎 再接再厲，觸發正常抽獎
第650次：頭獎 500 元，觸發正常抽獎
第651次：頭獎 500 元，觸發正常抽獎
第652次：未中獎 再接再厲，觸發正常抽獎
第653次：未中獎 再接再厲，觸發正常抽獎
第654次：未中獎 再接再厲，觸發正常抽獎
第655次：貳獎 200元，觸發正常抽獎
第656次：未中獎 再接再厲，觸發正常抽獎
第657次：未中獎 再接再厲，觸發正常抽獎
第658次：未中獎 再接再厲，觸發正常抽獎
第659次：未中獎 再接再厲，觸發正常抽獎
第660次：未中獎 再接再厲，觸發正常抽獎
第661次：未中獎 再接再厲，觸發正常抽獎
第662次：未中獎 再接再厲，觸發正常抽獎
第663次：未中獎 再接再厲，觸發正常抽獎
第664次：未中獎 再接再厲，觸發正常抽獎
第665次：未中獎 再接再厲，觸發正常抽獎
第666次：貳獎 200元，觸發正常抽獎
第667次：未中獎 再接再厲，觸發正常抽獎
第668次：頭獎 500 元，觸發正常抽獎
第669次：未中獎 再接再厲，觸發正常抽獎
第670次：未中獎 再接再厲，觸發正常抽獎
第671次：未中獎 再接再厲，觸發正常抽獎
第672次：未中獎 再接再厲，觸發正常抽獎
第673次：未中獎 再接再厲，觸發正常抽獎
第674次：未中獎 再接再厲，觸發正常抽獎
第675次：未中獎 再接再厲，觸發正常抽獎
第676次：未中獎 再接再厲，觸發正常抽獎
第677次：未中獎 再接再厲，觸發正常抽獎
第678次：未中獎 再接再厲，觸發正常抽獎
第679次：未中獎 再接再厲，觸發正常抽獎
第680次：未中獎 再接再厲，觸發正常抽獎
第681次：未中獎 再接再厲，觸發正常抽獎
第682次：未中獎 再接再厲，觸發正常抽獎
第683次：未中獎 再接再厲，觸發正常抽獎
第684次：未中獎 再接再厲，觸發正常抽獎
第685次：未中獎 再接再厲，觸發正常抽獎
第686次：未中獎 再接再厲，觸發正常抽獎
第687次：未中獎 再接再厲，觸發正常抽獎
第688次：貳獎 200元，觸發20抽大保
第689次：未中獎 再接再厲，觸發正常抽獎
第690次：頭獎 500 元，觸發正常抽獎
第691次：未中獎 再接再厲，觸發正常抽獎
第692次：貳獎 200元，觸發正常抽獎
第693次：未中獎 再接再厲，觸發正常抽獎
第694次：未中獎 再接再厲，觸發正常抽獎
第695次：未中獎 再接再厲，觸發正常抽獎
第696次：未中獎 再接再厲，觸發正常抽獎
第697次：未中獎 再接再厲，觸發正常抽獎
第698次：貳獎 200元，觸發正常抽獎
第699次：貳獎 200元，觸發正常抽獎
第700次：未中獎 再接再厲，觸發正常抽獎
第701次：未中獎 再接再厲，觸發正常抽獎
第702次：未中獎 再接再厲，觸發正常抽獎
第703次：未中獎 再接再厲，觸發正常抽獎
第704次：未中獎 再接再厲，觸發正常抽獎
第705次：未中獎 再接再厲，觸發正常抽獎
第706次：未中獎 再接再厲，觸發正常抽獎
第707次：未中獎 再接再厲，觸發正常抽獎
第708次：未中獎 再接再厲，觸發正常抽獎
第709次：未中獎 再接再厲，觸發正常抽獎
第710次：未中獎 再接再厲，觸發正常抽獎
第711次：未中獎 再接再厲，觸發正常抽獎
第712次：未中獎 再接再厲，觸發正常抽獎
第713次：未中獎 再接再厲，觸發正常抽獎
第714次：貳獎 200元，觸發正常抽獎
第715次：未中獎 再接再厲，觸發正常抽獎
第716次：未中獎 再接再厲，觸發正常抽獎
第717次：未中獎 再接再厲，觸發正常抽獎
第718次：未中獎 再接再厲，觸發正常抽獎
第719次：貳獎 200元，觸發正常抽獎
第720次：未中獎 再接再厲，觸發正常抽獎
第721次：未中獎 再接再厲，觸發正常抽獎
第722次：未中獎 再接再厲，觸發正常抽獎
第723次：未中獎 再接再厲，觸發正常抽獎
第724次：未中獎 再接再厲，觸發正常抽獎
第725次：未中獎 再接再厲，觸發正常抽獎
第726次：貳獎 200元，觸發正常抽獎
第727次：未中獎 再接再厲，觸發正常抽獎
第728次：未中獎 再接再厲，觸發正常抽獎
第729次：未中獎 再接再厲，觸發正常抽獎
第730次：未中獎 再接再厲，觸發正常抽獎
第731次：未中獎 再接再厲，觸發正常抽獎
第732次：未中獎 再接再厲，觸發正常抽獎
第733次：未中獎 再接再厲，觸發正常抽獎
第734次：未中獎 再接再厲，觸發正常抽獎
第735次：未中獎 再接再厲，觸發正常抽獎
第736次：未中獎 再接再厲，觸發正常抽獎
第737次：未中獎 再接再厲，觸發正常抽獎
第738次：頭獎 500 元，觸發正常抽獎
第739次：未中獎 再接再厲，觸發正常抽獎
第740次：未中獎 再接再厲，觸發正常抽獎
第741次：未中獎 再接再厲，觸發正常抽獎
第742次：未中獎 再接再厲，觸發正常抽獎
第743次：未中獎 再接再厲，觸發正常抽獎
第744次：未中獎 再接再厲，觸發正常抽獎
第745次：未中獎 再接再厲，觸發正常抽獎
第746次：未中獎 再接再厲，觸發正常抽獎
第747次：未中獎 再接再厲，觸發正常抽獎
第748次：未中獎 再接再厲，觸發正常抽獎
第749次：未中獎 再接再厲，觸發正常抽獎
第750次：貳獎 200元，觸發正常抽獎
第751次：頭獎 500 元，觸發正常抽獎
第752次：未中獎 再接再厲，觸發正常抽獎
第753次：未中獎 再接再厲，觸發正常抽獎
第754次：未中獎 再接再厲，觸發正常抽獎
第755次：未中獎 再接再厲，觸發正常抽獎
第756次：未中獎 再接再厲，觸發正常抽獎
第757次：未中獎 再接再厲，觸發正常抽獎
第758次：未中獎 再接再厲，觸發正常抽獎
第759次：未中獎 再接再厲，觸發正常抽獎
第760次：未中獎 再接再厲，觸發正常抽獎
第761次：未中獎 再接再厲，觸發正常抽獎
第762次：未中獎 再接再厲，觸發正常抽獎
第763次：未中獎 再接再厲，觸發正常抽獎
第764次：未中獎 再接再厲，觸發正常抽獎
第765次：貳獎 200元，觸發正常抽獎
第766次：未中獎 再接再厲，觸發正常抽獎
第767次：未中獎 再接再厲，觸發正常抽獎
第768次：未中獎 再接再厲，觸發正常抽獎
第769次：未中獎 再接再厲，觸發正常抽獎
第770次：未中獎 再接再厲，觸發正常抽獎
第771次：未中獎 再接再厲，觸發正常抽獎
第772次：未中獎 再接再厲，觸發正常抽獎
第773次：未中獎 再接再厲，觸發正常抽獎
第774次：頭獎 500 元，觸發正常抽獎
第775次：未中獎 再接再厲，觸發正常抽獎
第776次：未中獎 再接再厲，觸發正常抽獎
第777次：未中獎 再接再厲，觸發正常抽獎
第778次：未中獎 再接再厲，觸發正常抽獎
第779次：未中獎 再接再厲，觸發正常抽獎
第780次：未中獎 再接再厲，觸發正常抽獎
第781次：未中獎 再接再厲，觸發正常抽獎
第782次：未中獎 再接再厲，觸發正常抽獎
第783次：貳獎 200元，觸發正常抽獎
第784次：未中獎 再接再厲，觸發正常抽獎
第785次：未中獎 再接再厲，觸發正常抽獎
第786次：未中獎 再接再厲，觸發正常抽獎
第787次：未中獎 再接再厲，觸發正常抽獎
第788次：未中獎 再接再厲，觸發正常抽獎
第789次：貳獎 200元，觸發正常抽獎
第790次：未中獎 再接再厲，觸發正常抽獎
第791次：未中獎 再接再厲，觸發正常抽獎
第792次：未中獎 再接再厲，觸發正常抽獎
第793次：未中獎 再接再厲，觸發正常抽獎
第794次：未中獎 再接再厲，觸發正常抽獎
第795次：未中獎 再接再厲，觸發正常抽獎
第796次：未中獎 再接再厲，觸發正常抽獎
第797次：貳獎 200元，觸發正常抽獎
第798次：未中獎 再接再厲，觸發正常抽獎
第799次：未中獎 再接再厲，觸發正常抽獎
第800次：未中獎 再接再厲，觸發正常抽獎
第801次：未中獎 再接再厲，觸發正常抽獎
第802次：貳獎 200元，觸發正常抽獎
第803次：未中獎 再接再厲，觸發正常抽獎
第804次：未中獎 再接再厲，觸發正常抽獎
第805次：未中獎 再接再厲，觸發正常抽獎
第806次：未中獎 再接再厲，觸發正常抽獎
第807次：未中獎 再接再厲，觸發正常抽獎
第808次：未中獎 再接再厲，觸發正常抽獎
第809次：未中獎 再接再厲，觸發正常抽獎
第810次：頭獎 500 元，觸發正常抽獎
第811次：未中獎 再接再厲，觸發正常抽獎
第812次：未中獎 再接再厲，觸發正常抽獎
第813次：未中獎 再接再厲，觸發正常抽獎
第814次：未中獎 再接再厲，觸發正常抽獎
第815次：未中獎 再接再厲，觸發正常抽獎
第816次：頭獎 500 元，觸發正常抽獎
第817次：未中獎 再接再厲，觸發正常抽獎
第818次：未中獎 再接再厲，觸發正常抽獎
第819次：未中獎 再接再厲，觸發正常抽獎
第820次：未中獎 再接再厲，觸發正常抽獎
第821次：未中獎 再接再厲，觸發正常抽獎
第822次：未中獎 再接再厲，觸發正常抽獎
第823次：頭獎 500 元，觸發正常抽獎
第824次：頭獎 500 元，觸發正常抽獎
第825次：貳獎 200元，觸發正常抽獎
第826次：未中獎 再接再厲，觸發正常抽獎
第827次：未中獎 再接再厲，觸發正常抽獎
第828次：未中獎 再接再厲，觸發正常抽獎
第829次：未中獎 再接再厲，觸發正常抽獎
第830次：貳獎 200元，觸發正常抽獎
第831次：未中獎 再接再厲，觸發正常抽獎
第832次：未中獎 再接再厲，觸發正常抽獎
第833次：未中獎 再接再厲，觸發正常抽獎
第834次：未中獎 再接再厲，觸發正常抽獎
第835次：未中獎 再接再厲，觸發正常抽獎
第836次：未中獎 再接再厲，觸發正常抽獎
第837次：未中獎 再接再厲，觸發正常抽獎
第838次：未中獎 再接再厲，觸發正常抽獎
第839次：未中獎 再接再厲，觸發正常抽獎
第840次：未中獎 再接再厲，觸發正常抽獎
第841次：未中獎 再接再厲，觸發正常抽獎
第842次：未中獎 再接再厲，觸發正常抽獎
第843次：貳獎 200元，觸發正常抽獎
第844次：未中獎 再接再厲，觸發正常抽獎
第845次：未中獎 再接再厲，觸發正常抽獎
第846次：未中獎 再接再厲，觸發正常抽獎
第847次：未中獎 再接再厲，觸發正常抽獎
第848次：未中獎 再接再厲，觸發正常抽獎
第849次：未中獎 再接再厲，觸發正常抽獎
第850次：未中獎 再接再厲，觸發正常抽獎
第851次：未中獎 再接再厲，觸發正常抽獎
第852次：未中獎 再接再厲，觸發正常抽獎
第853次：未中獎 再接再厲，觸發正常抽獎
第854次：貳獎 200元，觸發正常抽獎
第855次：未中獎 再接再厲，觸發正常抽獎
第856次：未中獎 再接再厲，觸發正常抽獎
第857次：未中獎 再接再厲，觸發正常抽獎
第858次：貳獎 200元，觸發正常抽獎
第859次：未中獎 再接再厲，觸發正常抽獎
第860次：頭獎 500 元，觸發正常抽獎
第861次：未中獎 再接再厲，觸發正常抽獎
第862次：未中獎 再接再厲，觸發正常抽獎
第863次：未中獎 再接再厲，觸發正常抽獎
第864次：未中獎 再接再厲，觸發正常抽獎
第865次：未中獎 再接再厲，觸發正常抽獎
第866次：未中獎 再接再厲，觸發正常抽獎
第867次：未中獎 再接再厲，觸發正常抽獎
第868次：未中獎 再接再厲，觸發正常抽獎
第869次：未中獎 再接再厲，觸發正常抽獎
第870次：貳獎 200元，觸發正常抽獎
第871次：未中獎 再接再厲，觸發正常抽獎
第872次：未中獎 再接再厲，觸發正常抽獎
第873次：未中獎 再接再厲，觸發正常抽獎
第874次：貳獎 200元，觸發正常抽獎
第875次：未中獎 再接再厲，觸發正常抽獎
第876次：未中獎 再接再厲，觸發正常抽獎
第877次：未中獎 再接再厲，觸發正常抽獎
第878次：未中獎 再接再厲，觸發正常抽獎
第879次：未中獎 再接再厲，觸發正常抽獎
第880次：未中獎 再接再厲，觸發正常抽獎
第881次：未中獎 再接再厲，觸發正常抽獎
第882次：未中獎 再接再厲，觸發正常抽獎
第883次：未中獎 再接再厲，觸發正常抽獎
第884次：未中獎 再接再厲，觸發正常抽獎
第885次：貳獎 200元，觸發正常抽獎
第886次：未中獎 再接再厲，觸發正常抽獎
第887次：未中獎 再接再厲，觸發正常抽獎
第888次：未中獎 再接再厲，觸發正常抽獎
第889次：貳獎 200元，觸發正常抽獎
第890次：未中獎 再接再厲，觸發正常抽獎
第891次：未中獎 再接再厲，觸發正常抽獎
第892次：未中獎 再接再厲，觸發正常抽獎
第893次：未中獎 再接再厲，觸發正常抽獎
第894次：未中獎 再接再厲，觸發正常抽獎
第895次：貳獎 200元，觸發正常抽獎
第896次：未中獎 再接再厲，觸發正常抽獎
第897次：未中獎 再接再厲，觸發正常抽獎
第898次：未中獎 再接再厲，觸發正常抽獎
第899次：未中獎 再接再厲，觸發正常抽獎
第900次：頭獎 500 元，觸發正常抽獎
第901次：未中獎 再接再厲，觸發正常抽獎
第902次：未中獎 再接再厲，觸發正常抽獎
第903次：未中獎 再接再厲，觸發正常抽獎
第904次：未中獎 再接再厲，觸發正常抽獎
第905次：貳獎 200元，觸發正常抽獎
第906次：未中獎 再接再厲，觸發正常抽獎
第907次：未中獎 再接再厲，觸發正常抽獎
第908次：未中獎 再接再厲，觸發正常抽獎
第909次：未中獎 再接再厲，觸發正常抽獎
第910次：未中獎 再接再厲，觸發正常抽獎
第911次：未中獎 再接再厲，觸發正常抽獎
第912次：未中獎 再接再厲，觸發正常抽獎
第913次：未中獎 再接再厲，觸發正常抽獎
第914次：頭獎 500 元，觸發正常抽獎
第915次：貳獎 200元，觸發正常抽獎

    樣本數 單次遊玩獎金期望值估計   標準誤   CI下界   CI上界
0  5000       46.84  1.72  43.46  50.22

帳號：2，新建立玩家資料
目前狀態：新手期，尚未中獎，仍具有新手保底
開始遊玩5000次
第1次：未中獎 再接再厲，觸發正常抽獎
第2次：未中獎 再接再厲，觸發正常抽獎
第3次：未中獎 再接再厲，觸發正常抽獎
第4次：貳獎 200元，觸發正常抽獎
您已不是新手期，之後不具有新手保底
第5次：未中獎 再接再厲，觸發正常抽獎
第6次：未中獎 再接再厲，觸發正常抽獎
第7次：未中獎 再接再厲，觸發正常抽獎
第8次：未中獎 再接再厲，觸發正常抽獎
第9次：未中獎 再接再厲，觸發正常抽獎
第10次：未中獎 再接再厲，觸發正常抽獎
第11次：未中獎 再接再厲，觸發正常抽獎
第12次：貳獎 200元，觸發正常抽獎
第13次：貳獎 200元，觸發正常抽獎
第14次：未中獎 再接再厲，觸發正常抽獎
第15次：未中獎 再接再厲，觸發正常抽獎
第16次：未中獎 再接再厲，觸發正常抽獎
第17次：頭獎 500 元，觸發正常抽獎
第18次：未中獎 再接再厲，觸發正常抽獎
第19次：未中獎 再接再厲，觸發正常抽獎
第20次：未中獎 再接再厲，觸發正常抽獎
第21次：頭獎 500 元，觸發正常抽獎
第22次：未中獎 再接再厲，觸發正常抽獎
第23次：未中獎 再接再厲，觸發正常抽獎
第24次：未中獎 再接再厲，觸發正常抽獎
第25次：未中獎 再接再厲，觸發正常抽獎
第26次：未中獎 再接再厲，觸發正常抽獎
第27次：未中獎 再接再厲，觸發正常抽獎
第28次：未中獎 再接再厲，觸發正常抽獎
第29次：未中獎 再接再厲，觸發正常抽獎
第30次：未中獎 再接再厲，觸發正常抽獎
第31次：未中獎 再接再厲，觸發正常抽獎
第32次：貳獎 200元，觸發正常抽獎
第33次：貳獎 200元，觸發正常抽獎
第34次：未中獎 再接再厲，觸發正常抽獎
第35次：未中獎 再接再厲，觸發正常抽獎
第36次：未中獎 再接再厲，觸發正常抽獎
第37次：未中獎 再接再厲，觸發正常抽獎
第38次：未中獎 再接再厲，觸發正常抽獎
第39次：未中獎 再接再厲，觸發正常抽獎
第40次：未中獎 再接再厲，觸發正常抽獎
第41次：貳獎 200元，觸發正常抽獎
第42次：未中獎 再接再厲，觸發正常抽獎
第43次：未中獎 再接再厲，觸發正常抽獎
第44次：未中獎 再接再厲，觸發正常抽獎
第45次：貳獎 200元，觸發正常抽獎
第46次：未中獎 再接再厲，觸發正常抽獎
第47次：未中獎 再接再厲，觸發正常抽獎
第48次：未中獎 再接再厲，觸發正常抽獎
第49次：未中獎 再接再厲，觸發正常抽獎
第50次：未中獎 再接再厲，觸發正常抽獎
第51次：貳獎 200元，觸發正常抽獎
第52次：未中獎 再接再厲，觸發正常抽獎
第53次：未中獎 再接再厲，觸發正常抽獎
第54次：未中獎 再接再厲，觸發正常抽獎
第55次：未中獎 再接再厲，觸發正常抽獎
第56次：未中獎 再接再厲，觸發正常抽獎
第57次：未中獎 再接再厲，觸發正常抽獎
第58次：頭獎 500 元，觸發正常抽獎
第59次：未中獎 再接再厲，觸發正常抽獎
第60次：貳獎 200元，觸發正常抽獎
第61次：未中獎 再接再厲，觸發正常抽獎
第62次：頭獎 500 元，觸發正常抽獎
第63次：未中獎 再接再厲，觸發正常抽獎
第64次：未中獎 再接再厲，觸發正常抽獎
第65次：未中獎 再接再厲，觸發正常抽獎
第66次：貳獎 200元，觸發正常抽獎
第67次：未中獎 再接再厲，觸發正常抽獎
第68次：未中獎 再接再厲，觸發正常抽獎
第69次：貳獎 200元，觸發正常抽獎
第70次：未中獎 再接再厲，觸發正常抽獎
第71次：未中獎 再接再厲，觸發正常抽獎
第72次：未中獎 再接再厲，觸發正常抽獎
第73次：未中獎 再接再厲，觸發正常抽獎
第74次：未中獎 再接再厲，觸發正常抽獎
第75次：未中獎 再接再厲，觸發正常抽獎
第76次：未中獎 再接再厲，觸發正常抽獎
第77次：未中獎 再接再厲，觸發正常抽獎
第78次：貳獎 200元，觸發正常抽獎
第79次：未中獎 再接再厲，觸發正常抽獎
第80次：貳獎 200元，觸發正常抽獎
第81次：未中獎 再接再厲，觸發正常抽獎
第82次：未中獎 再接再厲，觸發正常抽獎
第83次：貳獎 200元，觸發正常抽獎
第84次：未中獎 再接再厲，觸發正常抽獎
第85次：未中獎 再接再厲，觸發正常抽獎
第86次：未中獎 再接再厲，觸發正常抽獎
第87次：貳獎 200元，觸發正常抽獎
第88次：未中獎 再接再厲，觸發正常抽獎
第89次：未中獎 再接再厲，觸發正常抽獎
第90次：未中獎 再接再厲，觸發正常抽獎
第91次：貳獎 200元，觸發正常抽獎
第92次：未中獎 再接再厲，觸發正常抽獎
第93次：未中獎 再接再厲，觸發正常抽獎
第94次：未中獎 再接再厲，觸發正常抽獎
第95次：未中獎 再接再厲，觸發正常抽獎
第96次：頭獎 500 元，觸發正常抽獎
第97次：未中獎 再接再厲，觸發正常抽獎
第98次：未中獎 再接再厲，觸發正常抽獎
第99次：未中獎 再接再厲，觸發正常抽獎
第100次：未中獎 再接再厲，觸發正常抽獎
第101次：未中獎 再接再厲，觸發正常抽獎
第102次：未中獎 再接再厲，觸發正常抽獎
第103次：貳獎 200元，觸發正常抽獎
第104次：未中獎 再接再厲，觸發正常抽獎
第105次：未中獎 再接再厲，觸發正常抽獎
第106次：未中獎 再接再厲，觸發正常抽獎
第107次：未中獎 再接再厲，觸發正常抽獎
第108次：未中獎 再接再厲，觸發正常抽獎
第109次：未中獎 再接再厲，觸發正常抽獎
第110次：頭獎 500 元，觸發正常抽獎
第111次：未中獎 再接再厲，觸發正常抽獎
第112次：未中獎 再接再厲，觸發正常抽獎
第113次：未中獎 再接再厲，觸發正常抽獎
第114次：頭獎 500 元，觸發正常抽獎
第115次：未中獎 再接再厲，觸發正常抽獎
第116次：未中獎 再接再厲，觸發正常抽獎
第117次：未中獎 再接再厲，觸發正常抽獎
第118次：貳獎 200元，觸發正常抽獎
第119次：未中獎 再接再厲，觸發正常抽獎
第120次：未中獎 再接再厲，觸發正常抽獎
第121次：未中獎 再接再厲，觸發正常抽獎
第122次：未中獎 再接再厲，觸發正常抽獎
第123次：頭獎 500 元，觸發正常抽獎
第124次：未中獎 再接再厲，觸發正常抽獎
第125次：貳獎 200元，觸發正常抽獎
第126次：未中獎 再接再厲，觸發正常抽獎
第127次：未中獎 再接再厲，觸發正常抽獎
第128次：貳獎 200元，觸發正常抽獎
第129次：頭獎 500 元，觸發正常抽獎
第130次：未中獎 再接再厲，觸發正常抽獎
第131次：未中獎 再接再厲，觸發正常抽獎
第132次：未中獎 再接再厲，觸發正常抽獎
第133次：頭獎 500 元，觸發正常抽獎
第134次：未中獎 再接再厲，觸發正常抽獎
第135次：未中獎 再接再厲，觸發正常抽獎
第136次：未中獎 再接再厲，觸發正常抽獎
第137次：未中獎 再接再厲，觸發正常抽獎
第138次：未中獎 再接再厲，觸發正常抽獎
第139次：未中獎 再接再厲，觸發正常抽獎
第140次：未中獎 再接再厲，觸發正常抽獎
第141次：未中獎 再接再厲，觸發正常抽獎
第142次：未中獎 再接再厲，觸發正常抽獎
第143次：未中獎 再接再厲，觸發正常抽獎
第144次：未中獎 再接再厲，觸發正常抽獎
第145次：未中獎 再接再厲，觸發正常抽獎
第146次：未中獎 再接再厲，觸發正常抽獎
第147次：未中獎 再接再厲，觸發正常抽獎
第148次：未中獎 再接再厲，觸發正常抽獎
第149次：未中獎 再接再厲，觸發正常抽獎
第150次：未中獎 再接再厲，觸發正常抽獎
第151次：未中獎 再接再厲，觸發正常抽獎
第152次：未中獎 再接再厲，觸發正常抽獎
第153次：貳獎 200元，觸發20抽大保
第154次：未中獎 再接再厲，觸發正常抽獎
第155次：頭獎 500 元，觸發正常抽獎
第156次：未中獎 再接再厲，觸發正常抽獎
第157次：貳獎 200元，觸發正常抽獎
第158次：未中獎 再接再厲，觸發正常抽獎
第159次：未中獎 再接再厲，觸發正常抽獎
第160次：未中獎 再接再厲，觸發正常抽獎
第161次：頭獎 500 元，觸發正常抽獎
第162次：未中獎 再接再厲，觸發正常抽獎
第163次：未中獎 再接再厲，觸發正常抽獎
第164次：未中獎 再接再厲，觸發正常抽獎
第165次：未中獎 再接再厲，觸發正常抽獎
第166次：貳獎 200元，觸發正常抽獎
第167次：頭獎 500 元，觸發正常抽獎
第168次：未中獎 再接再厲，觸發正常抽獎
第169次：未中獎 再接再厲，觸發正常抽獎
第170次：未中獎 再接再厲，觸發正常抽獎
第171次：未中獎 再接再厲，觸發正常抽獎
第172次：未中獎 再接再厲，觸發正常抽獎
第173次：未中獎 再接再厲，觸發正常抽獎
第174次：未中獎 再接再厲，觸發正常抽獎
第175次：貳獎 200元，觸發正常抽獎
第176次：貳獎 200元，觸發正常抽獎
第177次：未中獎 再接再厲，觸發正常抽獎
第178次：未中獎 再接再厲，觸發正常抽獎
第179次：未中獎 再接再厲，觸發正常抽獎
第180次：未中獎 再接再厲，觸發正常抽獎
第181次：未中獎 再接再厲，觸發正常抽獎
第182次：未中獎 再接再厲，觸發正常抽獎
第183次：未中獎 再接再厲，觸發正常抽獎
第184次：未中獎 再接再厲，觸發正常抽獎
第185次：頭獎 500 元，觸發正常抽獎
第186次：未中獎 再接再厲，觸發正常抽獎
第187次：貳獎 200元，觸發正常抽獎
第188次：未中獎 再接再厲，觸發正常抽獎
第189次：未中獎 再接再厲，觸發正常抽獎
第190次：未中獎 再接再厲，觸發正常抽獎
第191次：未中獎 再接再厲，觸發正常抽獎
第192次：未中獎 再接再厲，觸發正常抽獎
第193次：貳獎 200元，觸發正常抽獎
第194次：未中獎 再接再厲，觸發正常抽獎
第195次：未中獎 再接再厲，觸發正常抽獎
第196次：未中獎 再接再厲，觸發正常抽獎
第197次：未中獎 再接再厲，觸發正常抽獎
第198次：未中獎 再接再厲，觸發正常抽獎
第199次：未中獎 再接再厲，觸發正常抽獎
第200次：未中獎 再接再厲，觸發正常抽獎
第201次：未中獎 再接再厲，觸發正常抽獎
第202次：未中獎 再接再厲，觸發正常抽獎
第203次：未中獎 再接再厲，觸發正常抽獎
第204次：未中獎 再接再厲，觸發正常抽獎
第205次：未中獎 再接再厲，觸發正常抽獎
第206次：未中獎 再接再厲，觸發正常抽獎
第207次：未中獎 再接再厲，觸發正常抽獎
第208次：未中獎 再接再厲，觸發正常抽獎
第209次：未中獎 再接再厲，觸發正常抽獎
第210次：未中獎 再接再厲，觸發正常抽獎
第211次：未中獎 再接再厲，觸發正常抽獎
第212次：貳獎 200元，觸發正常抽獎
第213次：未中獎 再接再厲，觸發正常抽獎
第214次：未中獎 再接再厲，觸發正常抽獎
第215次：未中獎 再接再厲，觸發正常抽獎
第216次：未中獎 再接再厲，觸發正常抽獎
第217次：貳獎 200元，觸發正常抽獎
第218次：未中獎 再接再厲，觸發正常抽獎
第219次：未中獎 再接再厲，觸發正常抽獎
第220次：未中獎 再接再厲，觸發正常抽獎
第221次：未中獎 再接再厲，觸發正常抽獎
第222次：頭獎 500 元，觸發正常抽獎
第223次：未中獎 再接再厲，觸發正常抽獎
第224次：未中獎 再接再厲，觸發正常抽獎
第225次：未中獎 再接再厲，觸發正常抽獎
第226次：未中獎 再接再厲，觸發正常抽獎
第227次：頭獎 500 元，觸發正常抽獎
第228次：未中獎 再接再厲，觸發正常抽獎
第229次：未中獎 再接再厲，觸發正常抽獎
第230次：頭獎 500 元，觸發正常抽獎
第231次：未中獎 再接再厲，觸發正常抽獎
第232次：未中獎 再接再厲，觸發正常抽獎
第233次：未中獎 再接再厲，觸發正常抽獎
第234次：未中獎 再接再厲，觸發正常抽獎
第235次：未中獎 再接再厲，觸發正常抽獎
第236次：未中獎 再接再厲，觸發正常抽獎
第237次：未中獎 再接再厲，觸發正常抽獎
第238次：未中獎 再接再厲，觸發正常抽獎
第239次：未中獎 再接再厲，觸發正常抽獎
第240次：未中獎 再接再厲，觸發正常抽獎
第241次：未中獎 再接再厲，觸發正常抽獎
第242次：頭獎 500 元，觸發正常抽獎
第243次：未中獎 再接再厲，觸發正常抽獎
第244次：未中獎 再接再厲，觸發正常抽獎
第245次：未中獎 再接再厲，觸發正常抽獎
第246次：貳獎 200元，觸發正常抽獎
第247次：未中獎 再接再厲，觸發正常抽獎
第248次：未中獎 再接再厲，觸發正常抽獎
第249次：未中獎 再接再厲，觸發正常抽獎
第250次：未中獎 再接再厲，觸發正常抽獎
第251次：未中獎 再接再厲，觸發正常抽獎
第252次：未中獎 再接再厲，觸發正常抽獎
第253次：未中獎 再接再厲，觸發正常抽獎
第254次：貳獎 200元，觸發正常抽獎
第255次：未中獎 再接再厲，觸發正常抽獎
第256次：未中獎 再接再厲，觸發正常抽獎
第257次：未中獎 再接再厲，觸發正常抽獎
第258次：未中獎 再接再厲，觸發正常抽獎
第259次：未中獎 再接再厲，觸發正常抽獎
第260次：未中獎 再接再厲，觸發正常抽獎
第261次：未中獎 再接再厲，觸發正常抽獎
第262次：未中獎 再接再厲，觸發正常抽獎
第263次：未中獎 再接再厲，觸發正常抽獎
第264次：未中獎 再接再厲，觸發正常抽獎
第265次：未中獎 再接再厲，觸發正常抽獎
第266次：未中獎 再接再厲，觸發正常抽獎
第267次：未中獎 再接再厲，觸發正常抽獎
第268次：貳獎 200元，觸發正常抽獎
第269次：未中獎 再接再厲，觸發正常抽獎
第270次：未中獎 再接再厲，觸發正常抽獎
第271次：未中獎 再接再厲，觸發正常抽獎
第272次：未中獎 再接再厲，觸發正常抽獎
第273次：未中獎 再接再厲，觸發正常抽獎
第274次：未中獎 再接再厲，觸發正常抽獎
第275次：未中獎 再接再厲，觸發正常抽獎
第276次：貳獎 200元，觸發正常抽獎
第277次：未中獎 再接再厲，觸發正常抽獎
第278次：未中獎 再接再厲，觸發正常抽獎
第279次：未中獎 再接再厲，觸發正常抽獎
第280次：未中獎 再接再厲，觸發正常抽獎
第281次：未中獎 再接再厲，觸發正常抽獎
第282次：未中獎 再接再厲，觸發正常抽獎
第283次：未中獎 再接再厲，觸發正常抽獎
第284次：未中獎 再接再厲，觸發正常抽獎
第285次：未中獎 再接再厲，觸發正常抽獎
第286次：頭獎 500 元，觸發正常抽獎
第287次：未中獎 再接再厲，觸發正常抽獎
第288次：未中獎 再接再厲，觸發正常抽獎
第289次：未中獎 再接再厲，觸發正常抽獎
第290次：未中獎 再接再厲，觸發正常抽獎
第291次：未中獎 再接再厲，觸發正常抽獎
第292次：頭獎 500 元，觸發正常抽獎
第293次：未中獎 再接再厲，觸發正常抽獎
第294次：未中獎 再接再厲，觸發正常抽獎
第295次：未中獎 再接再厲，觸發正常抽獎
第296次：未中獎 再接再厲，觸發正常抽獎
第297次：未中獎 再接再厲，觸發正常抽獎
第298次：頭獎 500 元，觸發正常抽獎
第299次：未中獎 再接再厲，觸發正常抽獎
第300次：頭獎 500 元，觸發正常抽獎
第301次：未中獎 再接再厲，觸發正常抽獎
第302次：未中獎 再接再厲，觸發正常抽獎
第303次：未中獎 再接再厲，觸發正常抽獎
第304次：未中獎 再接再厲，觸發正常抽獎
第305次：未中獎 再接再厲，觸發正常抽獎
第306次：頭獎 500 元，觸發正常抽獎
第307次：未中獎 再接再厲，觸發正常抽獎
第308次：未中獎 再接再厲，觸發正常抽獎
第309次：未中獎 再接再厲，觸發正常抽獎
第310次：未中獎 再接再厲，觸發正常抽獎
第311次：未中獎 再接再厲，觸發正常抽獎
第312次：未中獎 再接再厲，觸發正常抽獎
第313次：未中獎 再接再厲，觸發正常抽獎
第314次：未中獎 再接再厲，觸發正常抽獎
第315次：未中獎 再接再厲，觸發正常抽獎
第316次：未中獎 再接再厲，觸發正常抽獎
第317次：未中獎 再接再厲，觸發正常抽獎
第318次：未中獎 再接再厲，觸發正常抽獎
第319次：未中獎 再接再厲，觸發正常抽獎
第320次：未中獎 再接再厲，觸發正常抽獎
第321次：未中獎 再接再厲，觸發正常抽獎
第322次：未中獎 再接再厲，觸發正常抽獎
第323次：未中獎 再接再厲，觸發正常抽獎
第324次：未中獎 再接再厲，觸發正常抽獎
第325次：未中獎 再接再厲，觸發正常抽獎
第326次：貳獎 200元，觸發20抽大保
第327次：未中獎 再接再厲，觸發正常抽獎
第328次：未中獎 再接再厲，觸發正常抽獎
第329次：未中獎 再接再厲，觸發正常抽獎
第330次：未中獎 再接再厲，觸發正常抽獎
第331次：未中獎 再接再厲，觸發正常抽獎
第332次：未中獎 再接再厲，觸發正常抽獎
第333次：未中獎 再接再厲，觸發正常抽獎
第334次：未中獎 再接再厲，觸發正常抽獎
第335次：貳獎 200元，觸發正常抽獎
第336次：未中獎 再接再厲，觸發正常抽獎
第337次：未中獎 再接再厲，觸發正常抽獎
第338次：未中獎 再接再厲，觸發正常抽獎
第339次：未中獎 再接再厲，觸發正常抽獎
第340次：未中獎 再接再厲，觸發正常抽獎
第341次：未中獎 再接再厲，觸發正常抽獎
第342次：未中獎 再接再厲，觸發正常抽獎
第343次：未中獎 再接再厲，觸發正常抽獎
第344次：未中獎 再接再厲，觸發正常抽獎
第345次：未中獎 再接再厲，觸發正常抽獎
第346次：未中獎 再接再厲，觸發正常抽獎
第347次：未中獎 再接再厲，觸發正常抽獎
第348次：未中獎 再接再厲，觸發正常抽獎
第349次：貳獎 200元，觸發正常抽獎
第350次：未中獎 再接再厲，觸發正常抽獎
第351次：未中獎 再接再厲，觸發正常抽獎
第352次：未中獎 再接再厲，觸發正常抽獎
第353次：未中獎 再接再厲，觸發正常抽獎
第354次：未中獎 再接再厲，觸發正常抽獎
第355次：未中獎 再接再厲，觸發正常抽獎
第356次：未中獎 再接再厲，觸發正常抽獎
第357次：未中獎 再接再厲，觸發正常抽獎
第358次：未中獎 再接再厲，觸發正常抽獎
第359次：未中獎 再接再厲，觸發正常抽獎
第360次：未中獎 再接再厲，觸發正常抽獎
第361次：未中獎 再接再厲，觸發正常抽獎
第362次：未中獎 再接再厲，觸發正常抽獎
第363次：未中獎 再接再厲，觸發正常抽獎
第364次：未中獎 再接再厲，觸發正常抽獎
第365次：頭獎 500 元，觸發正常抽獎
第366次：未中獎 再接再厲，觸發正常抽獎
第367次：未中獎 再接再厲，觸發正常抽獎
第368次：未中獎 再接再厲，觸發正常抽獎
第369次：未中獎 再接再厲，觸發正常抽獎
第370次：未中獎 再接再厲，觸發正常抽獎
第371次：貳獎 200元，觸發正常抽獎
第372次：未中獎 再接再厲，觸發正常抽獎
第373次：未中獎 再接再厲，觸發正常抽獎
第374次：未中獎 再接再厲，觸發正常抽獎
第375次：未中獎 再接再厲，觸發正常抽獎
第376次：未中獎 再接再厲，觸發正常抽獎
第377次：未中獎 再接再厲，觸發正常抽獎
第378次：未中獎 再接再厲，觸發正常抽獎
第379次：未中獎 再接再厲，觸發正常抽獎
第380次：貳獎 200元，觸發正常抽獎
第381次：未中獎 再接再厲，觸發正常抽獎
第382次：頭獎 500 元，觸發正常抽獎
第383次：未中獎 再接再厲，觸發正常抽獎
第384次：未中獎 再接再厲，觸發正常抽獎
第385次：未中獎 再接再厲，觸發正常抽獎
第386次：未中獎 再接再厲，觸發正常抽獎
第387次：未中獎 再接再厲，觸發正常抽獎
第388次：未中獎 再接再厲，觸發正常抽獎
第389次：未中獎 再接再厲，觸發正常抽獎
第390次：未中獎 再接再厲，觸發正常抽獎
第391次：未中獎 再接再厲，觸發正常抽獎
第392次：未中獎 再接再厲，觸發正常抽獎
第393次：未中獎 再接再厲，觸發正常抽獎
第394次：未中獎 再接再厲，觸發正常抽獎
第395次：未中獎 再接再厲，觸發正常抽獎
第396次：未中獎 再接再厲，觸發正常抽獎
第397次：未中獎 再接再厲，觸發正常抽獎
第398次：未中獎 再接再厲，觸發正常抽獎
第399次：未中獎 再接再厲，觸發正常抽獎
第400次：未中獎 再接再厲，觸發正常抽獎
第401次：未中獎 再接再厲，觸發正常抽獎
第402次：貳獎 200元，觸發20抽大保
第403次：未中獎 再接再厲，觸發正常抽獎
第404次：未中獎 再接再厲，觸發正常抽獎
第405次：未中獎 再接再厲，觸發正常抽獎
第406次：未中獎 再接再厲，觸發正常抽獎
第407次：未中獎 再接再厲，觸發正常抽獎
第408次：未中獎 再接再厲，觸發正常抽獎
第409次：未中獎 再接再厲，觸發正常抽獎
第410次：未中獎 再接再厲，觸發正常抽獎
第411次：未中獎 再接再厲，觸發正常抽獎
第412次：未中獎 再接再厲，觸發正常抽獎
第413次：未中獎 再接再厲，觸發正常抽獎
第414次：未中獎 再接再厲，觸發正常抽獎
第415次：未中獎 再接再厲，觸發正常抽獎
第416次：未中獎 再接再厲，觸發正常抽獎
第417次：未中獎 再接再厲，觸發正常抽獎
第418次：未中獎 再接再厲，觸發正常抽獎
第419次：未中獎 再接再厲，觸發正常抽獎
第420次：未中獎 再接再厲，觸發正常抽獎
第421次：未中獎 再接再厲，觸發正常抽獎
第422次：頭獎 500 元，觸發20抽大保
第423次：未中獎 再接再厲，觸發正常抽獎
第424次：未中獎 再接再厲，觸發正常抽獎
第425次：未中獎 再接再厲，觸發正常抽獎
第426次：未中獎 再接再厲，觸發正常抽獎
第427次：未中獎 再接再厲，觸發正常抽獎
第428次：未中獎 再接再厲，觸發正常抽獎
第429次：未中獎 再接再厲，觸發正常抽獎
第430次：未中獎 再接再厲，觸發正常抽獎
第431次：未中獎 再接再厲，觸發正常抽獎
第432次：未中獎 再接再厲，觸發正常抽獎
第433次：未中獎 再接再厲，觸發正常抽獎
第434次：貳獎 200元，觸發正常抽獎
第435次：未中獎 再接再厲，觸發正常抽獎
第436次：未中獎 再接再厲，觸發正常抽獎
第437次：未中獎 再接再厲，觸發正常抽獎
第438次：未中獎 再接再厲，觸發正常抽獎
第439次：貳獎 200元，觸發正常抽獎
第440次：未中獎 再接再厲，觸發正常抽獎
第441次：未中獎 再接再厲，觸發正常抽獎
第442次：未中獎 再接再厲，觸發正常抽獎
第443次：未中獎 再接再厲，觸發正常抽獎
第444次：未中獎 再接再厲，觸發正常抽獎
第445次：未中獎 再接再厲，觸發正常抽獎
第446次：未中獎 再接再厲，觸發正常抽獎
第447次：貳獎 200元，觸發正常抽獎
第448次：未中獎 再接再厲，觸發正常抽獎
第449次：頭獎 500 元，觸發正常抽獎
第450次：未中獎 再接再厲，觸發正常抽獎
第451次：未中獎 再接再厲，觸發正常抽獎
第452次：未中獎 再接再厲，觸發正常抽獎
第453次：貳獎 200元，觸發正常抽獎
第454次：未中獎 再接再厲，觸發正常抽獎
第455次：未中獎 再接再厲，觸發正常抽獎
第456次：未中獎 再接再厲，觸發正常抽獎
第457次：未中獎 再接再厲，觸發正常抽獎
第458次：未中獎 再接再厲，觸發正常抽獎
第459次：貳獎 200元，觸發正常抽獎
第460次：未中獎 再接再厲，觸發正常抽獎
第461次：未中獎 再接再厲，觸發正常抽獎
第462次：貳獎 200元，觸發正常抽獎
第463次：未中獎 再接再厲，觸發正常抽獎
第464次：未中獎 再接再厲，觸發正常抽獎
第465次：未中獎 再接再厲，觸發正常抽獎
第466次：未中獎 再接再厲，觸發正常抽獎
第467次：未中獎 再接再厲，觸發正常抽獎
第468次：未中獎 再接再厲，觸發正常抽獎
第469次：未中獎 再接再厲，觸發正常抽獎
第470次：未中獎 再接再厲，觸發正常抽獎
第471次：未中獎 再接再厲，觸發正常抽獎
第472次：未中獎 再接再厲，觸發正常抽獎
第473次：貳獎 200元，觸發正常抽獎
第474次：未中獎 再接再厲，觸發正常抽獎
第475次：未中獎 再接再厲，觸發正常抽獎
第476次：未中獎 再接再厲，觸發正常抽獎
第477次：未中獎 再接再厲，觸發正常抽獎
第478次：未中獎 再接再厲，觸發正常抽獎
第479次：未中獎 再接再厲，觸發正常抽獎
第480次：未中獎 再接再厲，觸發正常抽獎
第481次：未中獎 再接再厲，觸發正常抽獎
第482次：貳獎 200元，觸發正常抽獎
第483次：貳獎 200元，觸發正常抽獎
第484次：未中獎 再接再厲，觸發正常抽獎
第485次：未中獎 再接再厲，觸發正常抽獎
第486次：未中獎 再接再厲，觸發正常抽獎
第487次：未中獎 再接再厲，觸發正常抽獎
第488次：未中獎 再接再厲，觸發正常抽獎
第489次：貳獎 200元，觸發正常抽獎
第490次：未中獎 再接再厲，觸發正常抽獎
第491次：未中獎 再接再厲，觸發正常抽獎
第492次：未中獎 再接再厲，觸發正常抽獎
第493次：未中獎 再接再厲，觸發正常抽獎
第494次：未中獎 再接再厲，觸發正常抽獎
第495次：未中獎 再接再厲，觸發正常抽獎
第496次：未中獎 再接再厲，觸發正常抽獎
第497次：未中獎 再接再厲，觸發正常抽獎
第498次：未中獎 再接再厲，觸發正常抽獎
第499次：未中獎 再接再厲，觸發正常抽獎
第500次：未中獎 再接再厲，觸發正常抽獎
第501次：未中獎 再接再厲，觸發正常抽獎
第502次：未中獎 再接再厲，觸發正常抽獎
第503次：頭獎 500 元，觸發正常抽獎
第504次：未中獎 再接再厲，觸發正常抽獎
第505次：未中獎 再接再厲，觸發正常抽獎
第506次：未中獎 再接再厲，觸發正常抽獎
第507次：未中獎 再接再厲，觸發正常抽獎
第508次：未中獎 再接再厲，觸發正常抽獎
第509次：未中獎 再接再厲，觸發正常抽獎
第510次：未中獎 再接再厲，觸發正常抽獎
第511次：未中獎 再接再厲，觸發正常抽獎
第512次：未中獎 再接再厲，觸發正常抽獎
第513次：未中獎 再接再厲，觸發正常抽獎
第514次：未中獎 再接再厲，觸發正常抽獎
第515次：貳獎 200元，觸發正常抽獎
第516次：未中獎 再接再厲，觸發正常抽獎
第517次：未中獎 再接再厲，觸發正常抽獎
第518次：頭獎 500 元，觸發正常抽獎
第519次：未中獎 再接再厲，觸發正常抽獎
第520次：未中獎 再接再厲，觸發正常抽獎
第521次：頭獎 500 元，觸發正常抽獎
第522次：貳獎 200元，觸發正常抽獎
第523次：未中獎 再接再厲，觸發正常抽獎
第524次：貳獎 200元，觸發正常抽獎
第525次：未中獎 再接再厲，觸發正常抽獎
第526次：頭獎 500 元，觸發正常抽獎
第527次：貳獎 200元，觸發正常抽獎
第528次：未中獎 再接再厲，觸發正常抽獎
第529次：未中獎 再接再厲，觸發正常抽獎
第530次：未中獎 再接再厲，觸發正常抽獎
第531次：未中獎 再接再厲，觸發正常抽獎
第532次：未中獎 再接再厲，觸發正常抽獎
第533次：未中獎 再接再厲，觸發正常抽獎
第534次：未中獎 再接再厲，觸發正常抽獎
第535次：未中獎 再接再厲，觸發正常抽獎
第536次：未中獎 再接再厲，觸發正常抽獎
第537次：未中獎 再接再厲，觸發正常抽獎
第538次：未中獎 再接再厲，觸發正常抽獎
第539次：未中獎 再接再厲，觸發正常抽獎
第540次：未中獎 再接再厲，觸發正常抽獎
第541次：未中獎 再接再厲，觸發正常抽獎
第542次：未中獎 再接再厲，觸發正常抽獎
第543次：未中獎 再接再厲，觸發正常抽獎
第544次：未中獎 再接再厲，觸發正常抽獎
第545次：未中獎 再接再厲，觸發正常抽獎
第546次：未中獎 再接再厲，觸發正常抽獎
第547次：頭獎 500 元，觸發20抽大保
第548次：未中獎 再接再厲，觸發正常抽獎
第549次：未中獎 再接再厲，觸發正常抽獎
第550次：未中獎 再接再厲，觸發正常抽獎
第551次：未中獎 再接再厲，觸發正常抽獎
第552次：未中獎 再接再厲，觸發正常抽獎
第553次：未中獎 再接再厲，觸發正常抽獎
第554次：未中獎 再接再厲，觸發正常抽獎
第555次：未中獎 再接再厲，觸發正常抽獎
第556次：未中獎 再接再厲，觸發正常抽獎
第557次：未中獎 再接再厲，觸發正常抽獎
第558次：未中獎 再接再厲，觸發正常抽獎
第559次：未中獎 再接再厲，觸發正常抽獎
第560次：未中獎 再接再厲，觸發正常抽獎
第561次：貳獎 200元，觸發正常抽獎
第562次：未中獎 再接再厲，觸發正常抽獎
第563次：未中獎 再接再厲，觸發正常抽獎
第564次：未中獎 再接再厲，觸發正常抽獎
第565次：未中獎 再接再厲，觸發正常抽獎
第566次：未中獎 再接再厲，觸發正常抽獎
第567次：貳獎 200元，觸發正常抽獎
第568次：未中獎 再接再厲，觸發正常抽獎
第569次：未中獎 再接再厲，觸發正常抽獎
第570次：未中獎 再接再厲，觸發正常抽獎
第571次：未中獎 再接再厲，觸發正常抽獎
第572次：未中獎 再接再厲，觸發正常抽獎
第573次：未中獎 再接再厲，觸發正常抽獎
第574次：未中獎 再接再厲，觸發正常抽獎
第575次：未中獎 再接再厲，觸發正常抽獎
第576次：未中獎 再接再厲，觸發正常抽獎
第577次：未中獎 再接再厲，觸發正常抽獎
第578次：未中獎 再接再厲，觸發正常抽獎
第579次：未中獎 再接再厲，觸發正常抽獎
第580次：未中獎 再接再厲，觸發正常抽獎
第581次：未中獎 再接再厲，觸發正常抽獎
第582次：未中獎 再接再厲，觸發正常抽獎
第583次：未中獎 再接再厲，觸發正常抽獎
第584次：未中獎 再接再厲，觸發正常抽獎
第585次：未中獎 再接再厲，觸發正常抽獎
第586次：未中獎 再接再厲，觸發正常抽獎
第587次：貳獎 200元，觸發20抽大保
第588次：未中獎 再接再厲，觸發正常抽獎
第589次：未中獎 再接再厲，觸發正常抽獎
第590次：未中獎 再接再厲，觸發正常抽獎
第591次：未中獎 再接再厲，觸發正常抽獎
第592次：未中獎 再接再厲，觸發正常抽獎
第593次：未中獎 再接再厲，觸發正常抽獎
第594次：未中獎 再接再厲，觸發正常抽獎
第595次：未中獎 再接再厲，觸發正常抽獎
第596次：未中獎 再接再厲，觸發正常抽獎
第597次：未中獎 再接再厲，觸發正常抽獎
第598次：未中獎 再接再厲，觸發正常抽獎
第599次：未中獎 再接再厲，觸發正常抽獎
第600次：未中獎 再接再厲，觸發正常抽獎
第601次：未中獎 再接再厲，觸發正常抽獎
第602次：未中獎 再接再厲，觸發正常抽獎
第603次：未中獎 再接再厲，觸發正常抽獎
第604次：未中獎 再接再厲，觸發正常抽獎
第605次：未中獎 再接再厲，觸發正常抽獎
第606次：未中獎 再接再厲，觸發正常抽獎
第607次：頭獎 500 元，觸發20抽大保
第608次：未中獎 再接再厲，觸發正常抽獎
第609次：未中獎 再接再厲，觸發正常抽獎
第610次：未中獎 再接再厲，觸發正常抽獎
第611次：未中獎 再接再厲，觸發正常抽獎
第612次：頭獎 500 元，觸發正常抽獎
第613次：未中獎 再接再厲，觸發正常抽獎
第614次：未中獎 再接再厲，觸發正常抽獎
第615次：未中獎 再接再厲，觸發正常抽獎
第616次：未中獎 再接再厲，觸發正常抽獎
第617次：未中獎 再接再厲，觸發正常抽獎
第618次：未中獎 再接再厲，觸發正常抽獎
第619次：未中獎 再接再厲，觸發正常抽獎
第620次：貳獎 200元，觸發正常抽獎
第621次：未中獎 再接再厲，觸發正常抽獎
第622次：未中獎 再接再厲，觸發正常抽獎
第623次：未中獎 再接再厲，觸發正常抽獎
第624次：未中獎 再接再厲，觸發正常抽獎
第625次：頭獎 500 元，觸發正常抽獎
第626次：未中獎 再接再厲，觸發正常抽獎
第627次：未中獎 再接再厲，觸發正常抽獎
第628次：未中獎 再接再厲，觸發正常抽獎
第629次：未中獎 再接再厲，觸發正常抽獎
第630次：未中獎 再接再厲，觸發正常抽獎
第631次：未中獎 再接再厲，觸發正常抽獎
第632次：未中獎 再接再厲，觸發正常抽獎
第633次：未中獎 再接再厲，觸發正常抽獎
第634次：未中獎 再接再厲，觸發正常抽獎
第635次：未中獎 再接再厲，觸發正常抽獎
第636次：未中獎 再接再厲，觸發正常抽獎
第637次：未中獎 再接再厲，觸發正常抽獎
第638次：貳獎 200元，觸發正常抽獎
第639次：未中獎 再接再厲，觸發正常抽獎
第640次：未中獎 再接再厲，觸發正常抽獎
第641次：未中獎 再接再厲，觸發正常抽獎
第642次：未中獎 再接再厲，觸發正常抽獎
第643次：未中獎 再接再厲，觸發正常抽獎
第644次：未中獎 再接再厲，觸發正常抽獎
第645次：未中獎 再接再厲，觸發正常抽獎
第646次：未中獎 再接再厲，觸發正常抽獎
第647次：未中獎 再接再厲，觸發正常抽獎
第648次：未中獎 再接再厲，觸發正常抽獎
第649次：未中獎 再接再厲，觸發正常抽獎
第650次：貳獎 200元，觸發正常抽獎
第651次：未中獎 再接再厲，觸發正常抽獎
第652次：未中獎 再接再厲，觸發正常抽獎
第653次：未中獎 再接再厲，觸發正常抽獎
第654次：頭獎 500 元，觸發正常抽獎
第655次：未中獎 再接再厲，觸發正常抽獎
第656次：未中獎 再接再厲，觸發正常抽獎
第657次：未中獎 再接再厲，觸發正常抽獎
第658次：未中獎 再接再厲，觸發正常抽獎
第659次：未中獎 再接再厲，觸發正常抽獎
第660次：未中獎 再接再厲，觸發正常抽獎
第661次：未中獎 再接再厲，觸發正常抽獎
第662次：未中獎 再接再厲，觸發正常抽獎
第663次：未中獎 再接再厲，觸發正常抽獎
第664次：貳獎 200元，觸發正常抽獎
第665次：貳獎 200元，觸發正常抽獎
第666次：未中獎 再接再厲，觸發正常抽獎
第667次：未中獎 再接再厲，觸發正常抽獎
第668次：貳獎 200元，觸發正常抽獎
第669次：未中獎 再接再厲，觸發正常抽獎
第670次：未中獎 再接再厲，觸發正常抽獎
第671次：未中獎 再接再厲，觸發正常抽獎
第672次：未中獎 再接再厲，觸發正常抽獎
第673次：貳獎 200元，觸發正常抽獎
第674次：未中獎 再接再厲，觸發正常抽獎
第675次：未中獎 再接再厲，觸發正常抽獎
第676次：未中獎 再接再厲，觸發正常抽獎
第677次：貳獎 200元，觸發正常抽獎
第678次：未中獎 再接再厲，觸發正常抽獎
第679次：未中獎 再接再厲，觸發正常抽獎
第680次：未中獎 再接再厲，觸發正常抽獎
第681次：未中獎 再接再厲，觸發正常抽獎
第682次：未中獎 再接再厲，觸發正常抽獎
第683次：未中獎 再接再厲，觸發正常抽獎
第684次：未中獎 再接再厲，觸發正常抽獎
第685次：未中獎 再接再厲，觸發正常抽獎
第686次：未中獎 再接再厲，觸發正常抽獎
第687次：頭獎 500 元，觸發正常抽獎
第688次：未中獎 再接再厲，觸發正常抽獎
第689次：未中獎 再接再厲，觸發正常抽獎
第690次：貳獎 200元，觸發正常抽獎
第691次：未中獎 再接再厲，觸發正常抽獎
第692次：未中獎 再接再厲，觸發正常抽獎
第693次：未中獎 再接再厲，觸發正常抽獎
第694次：未中獎 再接再厲，觸發正常抽獎
第695次：未中獎 再接再厲，觸發正常抽獎
第696次：未中獎 再接再厲，觸發正常抽獎
第697次：頭獎 500 元，觸發正常抽獎
第698次：未中獎 再接再厲，觸發正常抽獎
第699次：未中獎 再接再厲，觸發正常抽獎
第700次：未中獎 再接再厲，觸發正常抽獎
第701次：未中獎 再接再厲，觸發正常抽獎
第702次：未中獎 再接再厲，觸發正常抽獎
第703次：貳獎 200元，觸發正常抽獎
第704次：貳獎 200元，觸發正常抽獎
第705次：未中獎 再接再厲，觸發正常抽獎
第706次：未中獎 再接再厲，觸發正常抽獎
第707次：頭獎 500 元，觸發正常抽獎
第708次：貳獎 200元，觸發正常抽獎
第709次：頭獎 500 元，觸發正常抽獎
第710次：未中獎 再接再厲，觸發正常抽獎
第711次：未中獎 再接再厲，觸發正常抽獎
第712次：未中獎 再接再厲，觸發正常抽獎
第713次：未中獎 再接再厲，觸發正常抽獎
第714次：未中獎 再接再厲，觸發正常抽獎
第715次：未中獎 再接再厲，觸發正常抽獎
第716次：未中獎 再接再厲，觸發正常抽獎
第717次：未中獎 再接再厲，觸發正常抽獎
第718次：頭獎 500 元，觸發正常抽獎
第719次：未中獎 再接再厲，觸發正常抽獎
第720次：貳獎 200元，觸發正常抽獎
第721次：未中獎 再接再厲，觸發正常抽獎
第722次：頭獎 500 元，觸發正常抽獎
第723次：未中獎 再接再厲，觸發正常抽獎
第724次：未中獎 再接再厲，觸發正常抽獎
第725次：未中獎 再接再厲，觸發正常抽獎
第726次：未中獎 再接再厲，觸發正常抽獎
第727次：未中獎 再接再厲，觸發正常抽獎
第728次：未中獎 再接再厲，觸發正常抽獎
第729次：未中獎 再接再厲，觸發正常抽獎
第730次：未中獎 再接再厲，觸發正常抽獎
第731次：未中獎 再接再厲，觸發正常抽獎
第732次：未中獎 再接再厲，觸發正常抽獎
第733次：貳獎 200元，觸發正常抽獎
第734次：未中獎 再接再厲，觸發正常抽獎
第735次：未中獎 再接再厲，觸發正常抽獎
第736次：未中獎 再接再厲，觸發正常抽獎
第737次：未中獎 再接再厲，觸發正常抽獎
第738次：未中獎 再接再厲，觸發正常抽獎
第739次：未中獎 再接再厲，觸發正常抽獎
第740次：未中獎 再接再厲，觸發正常抽獎
第741次：貳獎 200元，觸發正常抽獎
第742次：未中獎 再接再厲，觸發正常抽獎
第743次：未中獎 再接再厲，觸發正常抽獎
第744次：未中獎 再接再厲，觸發正常抽獎
第745次：貳獎 200元，觸發正常抽獎
第746次：未中獎 再接再厲，觸發正常抽獎
第747次：未中獎 再接再厲，觸發正常抽獎
第748次：頭獎 500 元，觸發正常抽獎
第749次：未中獎 再接再厲，觸發正常抽獎
第750次：未中獎 再接再厲，觸發正常抽獎
第751次：貳獎 200元，觸發正常抽獎
第752次：未中獎 再接再厲，觸發正常抽獎
第753次：未中獎 再接再厲，觸發正常抽獎
第754次：未中獎 再接再厲，觸發正常抽獎
第755次：未中獎 再接再厲，觸發正常抽獎
第756次：未中獎 再接再厲，觸發正常抽獎
第757次：未中獎 再接再厲，觸發正常抽獎
第758次：未中獎 再接再厲，觸發正常抽獎
第759次：未中獎 再接再厲，觸發正常抽獎
第760次：未中獎 再接再厲，觸發正常抽獎
第761次：未中獎 再接再厲，觸發正常抽獎
第762次：貳獎 200元，觸發正常抽獎
第763次：未中獎 再接再厲，觸發正常抽獎
第764次：貳獎 200元，觸發正常抽獎
第765次：未中獎 再接再厲，觸發正常抽獎
第766次：未中獎 再接再厲，觸發正常抽獎
第767次：未中獎 再接再厲，觸發正常抽獎
第768次：未中獎 再接再厲，觸發正常抽獎
第769次：未中獎 再接再厲，觸發正常抽獎
第770次：未中獎 再接再厲，觸發正常抽獎
第771次：未中獎 再接再厲，觸發正常抽獎
第772次：未中獎 再接再厲，觸發正常抽獎
第773次：未中獎 再接再厲，觸發正常抽獎
第774次：未中獎 再接再厲，觸發正常抽獎
第775次：貳獎 200元，觸發正常抽獎
第776次：頭獎 500 元，觸發正常抽獎
第777次：未中獎 再接再厲，觸發正常抽獎
第778次：未中獎 再接再厲，觸發正常抽獎
第779次：貳獎 200元，觸發正常抽獎
第780次：未中獎 再接再厲，觸發正常抽獎
第781次：未中獎 再接再厲，觸發正常抽獎
第782次：未中獎 再接再厲，觸發正常抽獎
第783次：未中獎 再接再厲，觸發正常抽獎
第784次：未中獎 再接再厲，觸發正常抽獎
第785次：未中獎 再接再厲，觸發正常抽獎
第786次：未中獎 再接再厲，觸發正常抽獎
第787次：未中獎 再接再厲，觸發正常抽獎
第788次：未中獎 再接再厲，觸發正常抽獎
第789次：未中獎 再接再厲，觸發正常抽獎
第790次：貳獎 200元，觸發正常抽獎
第791次：未中獎 再接再厲，觸發正常抽獎
第792次：頭獎 500 元，觸發正常抽獎
第793次：未中獎 再接再厲，觸發正常抽獎
第794次：貳獎 200元，觸發正常抽獎
第795次：未中獎 再接再厲，觸發正常抽獎
第796次：未中獎 再接再厲，觸發正常抽獎
第797次：貳獎 200元，觸發正常抽獎
第798次：未中獎 再接再厲，觸發正常抽獎
第799次：未中獎 再接再厲，觸發正常抽獎
第800次：未中獎 再接再厲，觸發正常抽獎
第801次：未中獎 再接再厲，觸發正常抽獎
第802次：未中獎 再接再厲，觸發正常抽獎
第803次：未中獎 再接再厲，觸發正常抽獎
第804次：未中獎 再接再厲，觸發正常抽獎
第805次：未中獎 再接再厲，觸發正常抽獎
第806次：未中獎 再接再厲，觸發正常抽獎
第807次：未中獎 再接再厲，觸發正常抽獎
第808次：未中獎 再接再厲，觸發正常抽獎
第809次：未中獎 再接再厲，觸發正常抽獎
第810次：未中獎 再接再厲，觸發正常抽獎
第811次：未中獎 再接再厲，觸發正常抽獎
第812次：未中獎 再接再厲，觸發正常抽獎
第813次：未中獎 再接再厲，觸發正常抽獎
第814次：未中獎 再接再厲，觸發正常抽獎
第815次：未中獎 再接再厲，觸發正常抽獎
第816次：未中獎 再接再厲，觸發正常抽獎
第817次：頭獎 500 元，觸發20抽大保
第818次：貳獎 200元，觸發正常抽獎
第819次：貳獎 200元，觸發正常抽獎
第820次：未中獎 再接再厲，觸發正常抽獎
第821次：未中獎 再接再厲，觸發正常抽獎
第822次：貳獎 200元，觸發正常抽獎
第823次：未中獎 再接再厲，觸發正常抽獎
第824次：未中獎 再接再厲，觸發正常抽獎
第825次：未中獎 再接再厲，觸發正常抽獎
第826次：頭獎 500 元，觸發正常抽獎
第827次：未中獎 再接再厲，觸發正常抽獎
第828次：頭獎 500 元，觸發正常抽獎
第829次：未中獎 再接再厲，觸發正常抽獎
第830次：未中獎 再接再厲，觸發正常抽獎
第831次：未中獎 再接再厲，觸發正常抽獎
第832次：未中獎 再接再厲，觸發正常抽獎
第833次：未中獎 再接再厲，觸發正常抽獎
第834次：未中獎 再接再厲，觸發正常抽獎
第835次：未中獎 再接再厲，觸發正常抽獎
第836次：未中獎 再接再厲，觸發正常抽獎
第837次：未中獎 再接再厲，觸發正常抽獎
第838次：頭獎 500 元，觸發正常抽獎
第839次：未中獎 再接再厲，觸發正常抽獎
第840次：未中獎 再接再厲，觸發正常抽獎
第841次：未中獎 再接再厲，觸發正常抽獎
第842次：未中獎 再接再厲，觸發正常抽獎
第843次：未中獎 再接再厲，觸發正常抽獎
第844次：未中獎 再接再厲，觸發正常抽獎
第845次：未中獎 再接再厲，觸發正常抽獎
第846次：未中獎 再接再厲，觸發正常抽獎
第847次：未中獎 再接再厲，觸發正常抽獎
第848次：未中獎 再接再厲，觸發正常抽獎
第849次：未中獎 再接再厲，觸發正常抽獎
第850次：未中獎 再接再厲，觸發正常抽獎
第851次：未中獎 再接再厲，觸發正常抽獎
第852次：未中獎 再接再厲，觸發正常抽獎
第853次：未中獎 再接再厲，觸發正常抽獎
第854次：未中獎 再接再厲，觸發正常抽獎
第855次：頭獎 500 元，觸發正常抽獎
第856次：未中獎 再接再厲，觸發正常抽獎
第857次：未中獎 再接再厲，觸發正常抽獎
第858次：未中獎 再接再厲，觸發正常抽獎
第859次：未中獎 再接再厲，觸發正常抽獎
第860次：未中獎 再接再厲，觸發正常抽獎
第861次：未中獎 再接再厲，觸發正常抽獎
第862次：未中獎 再接再厲，觸發正常抽獎
第863次：未中獎 再接再厲，觸發正常抽獎
第864次：貳獎 200元，觸發正常抽獎
第865次：未中獎 再接再厲，觸發正常抽獎
第866次：貳獎 200元，觸發正常抽獎
第867次：未中獎 再接再厲，觸發正常抽獎
第868次：未中獎 再接再厲，觸發正常抽獎
第869次：未中獎 再接再厲，觸發正常抽獎
第870次：未中獎 再接再厲，觸發正常抽獎
第871次：未中獎 再接再厲，觸發正常抽獎
第872次：未中獎 再接再厲，觸發正常抽獎
第873次：未中獎 再接再厲，觸發正常抽獎
第874次：未中獎 再接再厲，觸發正常抽獎
第875次：未中獎 再接再厲，觸發正常抽獎
第876次：未中獎 再接再厲，觸發正常抽獎
第877次：未中獎 再接再厲，觸發正常抽獎
第878次：未中獎 再接再厲，觸發正常抽獎
第879次：未中獎 再接再厲，觸發正常抽獎
第880次：未中獎 再接再厲，觸發正常抽獎
第881次：未中獎 再接再厲，觸發正常抽獎
第882次：未中獎 再接再厲，觸發正常抽獎
第883次：未中獎 再接再厲，觸發正常抽獎
第884次：貳獎 200元，觸發正常抽獎
第885次：未中獎 再接再厲，觸發正常抽獎
第886次：未中獎 再接再厲，觸發正常抽獎
第887次：未中獎 再接再厲，觸發正常抽獎
第888次：頭獎 500 元，觸發正常抽獎
第889次：未中獎 再接再厲，觸發正常抽獎
第890次：未中獎 再接再厲，觸發正常抽獎
第891次：未中獎 再接再厲，觸發正常抽獎
第892次：未中獎 再接再厲，觸發正常抽獎
第893次：未中獎 再接再厲，觸發正常抽獎
第894次：未中獎 再接再厲，觸發正常抽獎
第895次：未中獎 再接再厲，觸發正常抽獎
第896次：未中獎 再接再厲，觸發正常抽獎
第897次：未中獎 再接再厲，觸發正常抽獎
第898次：未中獎 再接再厲，觸發正常抽獎
第899次：未中獎 再接再厲，觸發正常抽獎
第900次：未中獎 再接再厲，觸發正常抽獎
第901次：未中獎 再接再厲，觸發正常抽獎
第902次：未中獎 再接再厲，觸發正常抽獎
第903次：頭獎 500 元，觸發正常抽獎
第904次：未中獎 再接再厲，觸發正常抽獎
第905次：未中獎 再接再厲，觸發正常抽獎
第906次：未中獎 再接再厲，觸發正常抽獎
第907次：未中獎 再接再厲，觸發正常抽獎
第908次：未中獎 再接再厲，觸發正常抽獎
第909次：未中獎 再接再厲，觸發正常抽獎
第910次：未中獎 再接再厲，觸發正常抽獎
第911次：未中獎 再接再厲，觸發正常抽獎
第912次：未中獎 再接再厲，觸發正常抽獎
第913次：未中獎 再接再厲，觸發正常抽獎
第914次：頭獎 500 元，觸發正常抽獎

    樣本數 單次遊玩獎金期望值估計   標準誤  CI下界   CI上界
0  5000       46.94  1.71  43.6  50.28

帳號：3，新建立玩家資料
目前狀態：新手期，尚未中獎，仍具有新手保底
開始遊玩5000次
第1次：貳獎 200元，觸發正常抽獎
您已不是新手期，之後不具有新手保底
第2次：未中獎 再接再厲，觸發正常抽獎
第3次：未中獎 再接再厲，觸發正常抽獎
第4次：未中獎 再接再厲，觸發正常抽獎
第5次：頭獎 500 元，觸發正常抽獎
第6次：未中獎 再接再厲，觸發正常抽獎
第7次：未中獎 再接再厲，觸發正常抽獎
第8次：未中獎 再接再厲，觸發正常抽獎
第9次：頭獎 500 元，觸發正常抽獎
第10次：貳獎 200元，觸發正常抽獎
第11次：未中獎 再接再厲，觸發正常抽獎
第12次：未中獎 再接再厲，觸發正常抽獎
第13次：未中獎 再接再厲，觸發正常抽獎
第14次：未中獎 再接再厲，觸發正常抽獎
第15次：貳獎 200元，觸發正常抽獎
第16次：未中獎 再接再厲，觸發正常抽獎
第17次：未中獎 再接再厲，觸發正常抽獎
第18次：未中獎 再接再厲，觸發正常抽獎
第19次：未中獎 再接再厲，觸發正常抽獎
第20次：未中獎 再接再厲，觸發正常抽獎
第21次：未中獎 再接再厲，觸發正常抽獎
第22次：未中獎 再接再厲，觸發正常抽獎
第23次：未中獎 再接再厲，觸發正常抽獎
第24次：未中獎 再接再厲，觸發正常抽獎
第25次：貳獎 200元，觸發正常抽獎
第26次：未中獎 再接再厲，觸發正常抽獎
第27次：未中獎 再接再厲，觸發正常抽獎
第28次：未中獎 再接再厲，觸發正常抽獎
第29次：未中獎 再接再厲，觸發正常抽獎
第30次：未中獎 再接再厲，觸發正常抽獎
第31次：未中獎 再接再厲，觸發正常抽獎
第32次：未中獎 再接再厲，觸發正常抽獎
第33次：未中獎 再接再厲，觸發正常抽獎
第34次：未中獎 再接再厲，觸發正常抽獎
第35次：未中獎 再接再厲，觸發正常抽獎
第36次：未中獎 再接再厲，觸發正常抽獎
第37次：未中獎 再接再厲，觸發正常抽獎
第38次：未中獎 再接再厲，觸發正常抽獎
第39次：貳獎 200元，觸發正常抽獎
第40次：未中獎 再接再厲，觸發正常抽獎
第41次：頭獎 500 元，觸發正常抽獎
第42次：未中獎 再接再厲，觸發正常抽獎
第43次：未中獎 再接再厲，觸發正常抽獎
第44次：未中獎 再接再厲，觸發正常抽獎
第45次：未中獎 再接再厲，觸發正常抽獎
第46次：未中獎 再接再厲，觸發正常抽獎
第47次：未中獎 再接再厲，觸發正常抽獎
第48次：貳獎 200元，觸發正常抽獎
第49次：未中獎 再接再厲，觸發正常抽獎
第50次：未中獎 再接再厲，觸發正常抽獎
第51次：貳獎 200元，觸發正常抽獎
第52次：未中獎 再接再厲，觸發正常抽獎
第53次：未中獎 再接再厲，觸發正常抽獎
第54次：未中獎 再接再厲，觸發正常抽獎
第55次：未中獎 再接再厲，觸發正常抽獎
第56次：未中獎 再接再厲，觸發正常抽獎
第57次：頭獎 500 元，觸發正常抽獎
第58次：未中獎 再接再厲，觸發正常抽獎
第59次：未中獎 再接再厲，觸發正常抽獎
第60次：未中獎 再接再厲，觸發正常抽獎
第61次：未中獎 再接再厲，觸發正常抽獎
第62次：未中獎 再接再厲，觸發正常抽獎
第63次：未中獎 再接再厲，觸發正常抽獎
第64次：未中獎 再接再厲，觸發正常抽獎
第65次：未中獎 再接再厲，觸發正常抽獎
第66次：未中獎 再接再厲，觸發正常抽獎
第67次：未中獎 再接再厲，觸發正常抽獎
第68次：未中獎 再接再厲，觸發正常抽獎
第69次：未中獎 再接再厲，觸發正常抽獎
第70次：貳獎 200元，觸發正常抽獎
第71次：未中獎 再接再厲，觸發正常抽獎
第72次：未中獎 再接再厲，觸發正常抽獎
第73次：未中獎 再接再厲，觸發正常抽獎
第74次：未中獎 再接再厲，觸發正常抽獎
第75次：未中獎 再接再厲，觸發正常抽獎
第76次：未中獎 再接再厲，觸發正常抽獎
第77次：未中獎 再接再厲，觸發正常抽獎
第78次：貳獎 200元，觸發正常抽獎
第79次：頭獎 500 元，觸發正常抽獎
第80次：未中獎 再接再厲，觸發正常抽獎
第81次：未中獎 再接再厲，觸發正常抽獎
第82次：頭獎 500 元，觸發正常抽獎
第83次：未中獎 再接再厲，觸發正常抽獎
第84次：未中獎 再接再厲，觸發正常抽獎
第85次：未中獎 再接再厲，觸發正常抽獎
第86次：未中獎 再接再厲，觸發正常抽獎
第87次：未中獎 再接再厲，觸發正常抽獎
第88次：未中獎 再接再厲，觸發正常抽獎
第89次：未中獎 再接再厲，觸發正常抽獎
第90次：貳獎 200元，觸發正常抽獎
第91次：未中獎 再接再厲，觸發正常抽獎
第92次：未中獎 再接再厲，觸發正常抽獎
第93次：未中獎 再接再厲，觸發正常抽獎
第94次：貳獎 200元，觸發正常抽獎
第95次：未中獎 再接再厲，觸發正常抽獎
第96次：未中獎 再接再厲，觸發正常抽獎
第97次：未中獎 再接再厲，觸發正常抽獎
第98次：未中獎 再接再厲，觸發正常抽獎
第99次：未中獎 再接再厲，觸發正常抽獎
第100次：未中獎 再接再厲，觸發正常抽獎
第101次：未中獎 再接再厲，觸發正常抽獎
第102次：未中獎 再接再厲，觸發正常抽獎
第103次：未中獎 再接再厲，觸發正常抽獎
第104次：貳獎 200元，觸發正常抽獎
第105次：未中獎 再接再厲，觸發正常抽獎
第106次：未中獎 再接再厲，觸發正常抽獎
第107次：未中獎 再接再厲，觸發正常抽獎
第108次：未中獎 再接再厲，觸發正常抽獎
第109次：未中獎 再接再厲，觸發正常抽獎
第110次：未中獎 再接再厲，觸發正常抽獎
第111次：未中獎 再接再厲，觸發正常抽獎
第112次：未中獎 再接再厲，觸發正常抽獎
第113次：未中獎 再接再厲，觸發正常抽獎
第114次：未中獎 再接再厲，觸發正常抽獎
第115次：貳獎 200元，觸發正常抽獎
第116次：未中獎 再接再厲，觸發正常抽獎
第117次：貳獎 200元，觸發正常抽獎
第118次：未中獎 再接再厲，觸發正常抽獎
第119次：頭獎 500 元，觸發正常抽獎
第120次：未中獎 再接再厲，觸發正常抽獎
第121次：未中獎 再接再厲，觸發正常抽獎
第122次：未中獎 再接再厲，觸發正常抽獎
第123次：未中獎 再接再厲，觸發正常抽獎
第124次：未中獎 再接再厲，觸發正常抽獎
第125次：未中獎 再接再厲，觸發正常抽獎
第126次：未中獎 再接再厲，觸發正常抽獎
第127次：未中獎 再接再厲，觸發正常抽獎
第128次：未中獎 再接再厲，觸發正常抽獎
第129次：未中獎 再接再厲，觸發正常抽獎
第130次：未中獎 再接再厲，觸發正常抽獎
第131次：貳獎 200元，觸發正常抽獎
第132次：未中獎 再接再厲，觸發正常抽獎
第133次：貳獎 200元，觸發正常抽獎
第134次：未中獎 再接再厲，觸發正常抽獎
第135次：未中獎 再接再厲，觸發正常抽獎
第136次：未中獎 再接再厲，觸發正常抽獎
第137次：未中獎 再接再厲，觸發正常抽獎
第138次：未中獎 再接再厲，觸發正常抽獎
第139次：未中獎 再接再厲，觸發正常抽獎
第140次：未中獎 再接再厲，觸發正常抽獎
第141次：未中獎 再接再厲，觸發正常抽獎
第142次：未中獎 再接再厲，觸發正常抽獎
第143次：未中獎 再接再厲，觸發正常抽獎
第144次：貳獎 200元，觸發正常抽獎
第145次：未中獎 再接再厲，觸發正常抽獎
第146次：未中獎 再接再厲，觸發正常抽獎
第147次：貳獎 200元，觸發正常抽獎
第148次：未中獎 再接再厲，觸發正常抽獎
第149次：未中獎 再接再厲，觸發正常抽獎
第150次：未中獎 再接再厲，觸發正常抽獎
第151次：未中獎 再接再厲，觸發正常抽獎
第152次：貳獎 200元，觸發正常抽獎
第153次：未中獎 再接再厲，觸發正常抽獎
第154次：未中獎 再接再厲，觸發正常抽獎
第155次：貳獎 200元，觸發正常抽獎
第156次：未中獎 再接再厲，觸發正常抽獎
第157次：未中獎 再接再厲，觸發正常抽獎
第158次：貳獎 200元，觸發正常抽獎
第159次：未中獎 再接再厲，觸發正常抽獎
第160次：貳獎 200元，觸發正常抽獎
第161次：未中獎 再接再厲，觸發正常抽獎
第162次：未中獎 再接再厲，觸發正常抽獎
第163次：未中獎 再接再厲，觸發正常抽獎
第164次：未中獎 再接再厲，觸發正常抽獎
第165次：未中獎 再接再厲，觸發正常抽獎
第166次：未中獎 再接再厲，觸發正常抽獎
第167次：未中獎 再接再厲，觸發正常抽獎
第168次：未中獎 再接再厲，觸發正常抽獎
第169次：頭獎 500 元，觸發正常抽獎
第170次：貳獎 200元，觸發正常抽獎
第171次：未中獎 再接再厲，觸發正常抽獎
第172次：貳獎 200元，觸發正常抽獎
第173次：未中獎 再接再厲，觸發正常抽獎
第174次：未中獎 再接再厲，觸發正常抽獎
第175次：未中獎 再接再厲，觸發正常抽獎
第176次：未中獎 再接再厲，觸發正常抽獎
第177次：未中獎 再接再厲，觸發正常抽獎
第178次：未中獎 再接再厲，觸發正常抽獎
第179次：未中獎 再接再厲，觸發正常抽獎
第180次：未中獎 再接再厲，觸發正常抽獎
第181次：未中獎 再接再厲，觸發正常抽獎
第182次：未中獎 再接再厲，觸發正常抽獎
第183次：未中獎 再接再厲，觸發正常抽獎
第184次：未中獎 再接再厲，觸發正常抽獎
第185次：未中獎 再接再厲，觸發正常抽獎
第186次：未中獎 再接再厲，觸發正常抽獎
第187次：未中獎 再接再厲，觸發正常抽獎
第188次：頭獎 500 元，觸發正常抽獎
第189次：未中獎 再接再厲，觸發正常抽獎
第190次：未中獎 再接再厲，觸發正常抽獎
第191次：未中獎 再接再厲，觸發正常抽獎
第192次：未中獎 再接再厲，觸發正常抽獎
第193次：未中獎 再接再厲，觸發正常抽獎
第194次：頭獎 500 元，觸發正常抽獎
第195次：貳獎 200元，觸發正常抽獎
第196次：未中獎 再接再厲，觸發正常抽獎
第197次：未中獎 再接再厲，觸發正常抽獎
第198次：未中獎 再接再厲，觸發正常抽獎
第199次：未中獎 再接再厲，觸發正常抽獎
第200次：未中獎 再接再厲，觸發正常抽獎
第201次：未中獎 再接再厲，觸發正常抽獎
第202次：未中獎 再接再厲，觸發正常抽獎
第203次：未中獎 再接再厲，觸發正常抽獎
第204次：未中獎 再接再厲，觸發正常抽獎
第205次：未中獎 再接再厲，觸發正常抽獎
第206次：未中獎 再接再厲，觸發正常抽獎
第207次：貳獎 200元，觸發正常抽獎
第208次：未中獎 再接再厲，觸發正常抽獎
第209次：未中獎 再接再厲，觸發正常抽獎
第210次：未中獎 再接再厲，觸發正常抽獎
第211次：未中獎 再接再厲，觸發正常抽獎
第212次：頭獎 500 元，觸發正常抽獎
第213次：未中獎 再接再厲，觸發正常抽獎
第214次：未中獎 再接再厲，觸發正常抽獎
第215次：未中獎 再接再厲，觸發正常抽獎
第216次：貳獎 200元，觸發正常抽獎
第217次：未中獎 再接再厲，觸發正常抽獎
第218次：未中獎 再接再厲，觸發正常抽獎
第219次：未中獎 再接再厲，觸發正常抽獎
第220次：未中獎 再接再厲，觸發正常抽獎
第221次：未中獎 再接再厲，觸發正常抽獎
第222次：未中獎 再接再厲，觸發正常抽獎
第223次：未中獎 再接再厲，觸發正常抽獎
第224次：未中獎 再接再厲，觸發正常抽獎
第225次：未中獎 再接再厲，觸發正常抽獎
第226次：未中獎 再接再厲，觸發正常抽獎
第227次：未中獎 再接再厲，觸發正常抽獎
第228次：未中獎 再接再厲，觸發正常抽獎
第229次：未中獎 再接再厲，觸發正常抽獎
第230次：未中獎 再接再厲，觸發正常抽獎
第231次：未中獎 再接再厲，觸發正常抽獎
第232次：頭獎 500 元，觸發正常抽獎
第233次：未中獎 再接再厲，觸發正常抽獎
第234次：頭獎 500 元，觸發正常抽獎
第235次：頭獎 500 元，觸發正常抽獎
第236次：未中獎 再接再厲，觸發正常抽獎
第237次：未中獎 再接再厲，觸發正常抽獎
第238次：未中獎 再接再厲，觸發正常抽獎
第239次：未中獎 再接再厲，觸發正常抽獎
第240次：未中獎 再接再厲，觸發正常抽獎
第241次：貳獎 200元，觸發正常抽獎
第242次：未中獎 再接再厲，觸發正常抽獎
第243次：未中獎 再接再厲，觸發正常抽獎
第244次：貳獎 200元，觸發正常抽獎
第245次：未中獎 再接再厲，觸發正常抽獎
第246次：未中獎 再接再厲，觸發正常抽獎
第247次：未中獎 再接再厲，觸發正常抽獎
第248次：未中獎 再接再厲，觸發正常抽獎
第249次：貳獎 200元，觸發正常抽獎
第250次：未中獎 再接再厲，觸發正常抽獎
第251次：頭獎 500 元，觸發正常抽獎
第252次：未中獎 再接再厲，觸發正常抽獎
第253次：未中獎 再接再厲，觸發正常抽獎
第254次：貳獎 200元，觸發正常抽獎
第255次：未中獎 再接再厲，觸發正常抽獎
第256次：未中獎 再接再厲，觸發正常抽獎
第257次：未中獎 再接再厲，觸發正常抽獎
第258次：未中獎 再接再厲，觸發正常抽獎
第259次：未中獎 再接再厲，觸發正常抽獎
第260次：未中獎 再接再厲，觸發正常抽獎
第261次：未中獎 再接再厲，觸發正常抽獎
第262次：未中獎 再接再厲，觸發正常抽獎
第263次：未中獎 再接再厲，觸發正常抽獎
第264次：未中獎 再接再厲，觸發正常抽獎
第265次：未中獎 再接再厲，觸發正常抽獎
第266次：未中獎 再接再厲，觸發正常抽獎
第267次：未中獎 再接再厲，觸發正常抽獎
第268次：未中獎 再接再厲，觸發正常抽獎
第269次：未中獎 再接再厲，觸發正常抽獎
第270次：未中獎 再接再厲，觸發正常抽獎
第271次：頭獎 500 元，觸發正常抽獎
第272次：未中獎 再接再厲，觸發正常抽獎
第273次：未中獎 再接再厲，觸發正常抽獎
第274次：未中獎 再接再厲，觸發正常抽獎
第275次：未中獎 再接再厲，觸發正常抽獎
第276次：未中獎 再接再厲，觸發正常抽獎
第277次：未中獎 再接再厲，觸發正常抽獎
第278次：未中獎 再接再厲，觸發正常抽獎
第279次：未中獎 再接再厲，觸發正常抽獎
第280次：未中獎 再接再厲，觸發正常抽獎
第281次：未中獎 再接再厲，觸發正常抽獎
第282次：未中獎 再接再厲，觸發正常抽獎
第283次：未中獎 再接再厲，觸發正常抽獎
第284次：未中獎 再接再厲，觸發正常抽獎
第285次：未中獎 再接再厲，觸發正常抽獎
第286次：未中獎 再接再厲，觸發正常抽獎
第287次：未中獎 再接再厲，觸發正常抽獎
第288次：未中獎 再接再厲，觸發正常抽獎
第289次：未中獎 再接再厲，觸發正常抽獎
第290次：貳獎 200元，觸發正常抽獎
第291次：未中獎 再接再厲，觸發正常抽獎
第292次：未中獎 再接再厲，觸發正常抽獎
第293次：未中獎 再接再厲，觸發正常抽獎
第294次：未中獎 再接再厲，觸發正常抽獎
第295次：貳獎 200元，觸發正常抽獎
第296次：未中獎 再接再厲，觸發正常抽獎
第297次：未中獎 再接再厲，觸發正常抽獎
第298次：未中獎 再接再厲，觸發正常抽獎
第299次：未中獎 再接再厲，觸發正常抽獎
第300次：未中獎 再接再厲，觸發正常抽獎
第301次：未中獎 再接再厲，觸發正常抽獎
第302次：未中獎 再接再厲，觸發正常抽獎
第303次：未中獎 再接再厲，觸發正常抽獎
第304次：未中獎 再接再厲，觸發正常抽獎
第305次：未中獎 再接再厲，觸發正常抽獎
第306次：未中獎 再接再厲，觸發正常抽獎
第307次：未中獎 再接再厲，觸發正常抽獎
第308次：未中獎 再接再厲，觸發正常抽獎
第309次：未中獎 再接再厲，觸發正常抽獎
第310次：未中獎 再接再厲，觸發正常抽獎
第311次：未中獎 再接再厲，觸發正常抽獎
第312次：未中獎 再接再厲，觸發正常抽獎
第313次：未中獎 再接再厲，觸發正常抽獎
第314次：未中獎 再接再厲，觸發正常抽獎
第315次：貳獎 200元，觸發20抽大保
第316次：未中獎 再接再厲，觸發正常抽獎
第317次：未中獎 再接再厲，觸發正常抽獎
第318次：未中獎 再接再厲，觸發正常抽獎
第319次：貳獎 200元，觸發正常抽獎
第320次：未中獎 再接再厲，觸發正常抽獎
第321次：未中獎 再接再厲，觸發正常抽獎
第322次：未中獎 再接再厲，觸發正常抽獎
第323次：未中獎 再接再厲，觸發正常抽獎
第324次：未中獎 再接再厲，觸發正常抽獎
第325次：未中獎 再接再厲，觸發正常抽獎
第326次：未中獎 再接再厲，觸發正常抽獎
第327次：未中獎 再接再厲，觸發正常抽獎
第328次：未中獎 再接再厲，觸發正常抽獎
第329次：未中獎 再接再厲，觸發正常抽獎
第330次：未中獎 再接再厲，觸發正常抽獎
第331次：未中獎 再接再厲，觸發正常抽獎
第332次：未中獎 再接再厲，觸發正常抽獎
第333次：未中獎 再接再厲，觸發正常抽獎
第334次：未中獎 再接再厲，觸發正常抽獎
第335次：未中獎 再接再厲，觸發正常抽獎
第336次：未中獎 再接再厲，觸發正常抽獎
第337次：未中獎 再接再厲，觸發正常抽獎
第338次：未中獎 再接再厲，觸發正常抽獎
第339次：頭獎 500 元，觸發20抽大保
第340次：未中獎 再接再厲，觸發正常抽獎
第341次：未中獎 再接再厲，觸發正常抽獎
第342次：頭獎 500 元，觸發正常抽獎
第343次：未中獎 再接再厲，觸發正常抽獎
第344次：未中獎 再接再厲，觸發正常抽獎
第345次：未中獎 再接再厲，觸發正常抽獎
第346次：未中獎 再接再厲，觸發正常抽獎
第347次：未中獎 再接再厲，觸發正常抽獎
第348次：未中獎 再接再厲，觸發正常抽獎
第349次：未中獎 再接再厲，觸發正常抽獎
第350次：未中獎 再接再厲，觸發正常抽獎
第351次：未中獎 再接再厲，觸發正常抽獎
第352次：未中獎 再接再厲，觸發正常抽獎
第353次：未中獎 再接再厲，觸發正常抽獎
第354次：未中獎 再接再厲，觸發正常抽獎
第355次：未中獎 再接再厲，觸發正常抽獎
第356次：未中獎 再接再厲，觸發正常抽獎
第357次：貳獎 200元，觸發正常抽獎
第358次：未中獎 再接再厲，觸發正常抽獎
第359次：未中獎 再接再厲，觸發正常抽獎
第360次：未中獎 再接再厲，觸發正常抽獎
第361次：未中獎 再接再厲，觸發正常抽獎
第362次：未中獎 再接再厲，觸發正常抽獎
第363次：未中獎 再接再厲，觸發正常抽獎
第364次：未中獎 再接再厲，觸發正常抽獎
第365次：未中獎 再接再厲，觸發正常抽獎
第366次：未中獎 再接再厲，觸發正常抽獎
第367次：未中獎 再接再厲，觸發正常抽獎
第368次：未中獎 再接再厲，觸發正常抽獎
第369次：未中獎 再接再厲，觸發正常抽獎
第370次：未中獎 再接再厲，觸發正常抽獎
第371次：未中獎 再接再厲，觸發正常抽獎
第372次：未中獎 再接再厲，觸發正常抽獎
第373次：未中獎 再接再厲，觸發正常抽獎
第374次：未中獎 再接再厲，觸發正常抽獎
第375次：未中獎 再接再厲，觸發正常抽獎
第376次：未中獎 再接再厲，觸發正常抽獎
第377次：貳獎 200元，觸發20抽大保
第378次：未中獎 再接再厲，觸發正常抽獎
第379次：未中獎 再接再厲，觸發正常抽獎
第380次：未中獎 再接再厲，觸發正常抽獎
第381次：未中獎 再接再厲，觸發正常抽獎
第382次：未中獎 再接再厲，觸發正常抽獎
第383次：未中獎 再接再厲，觸發正常抽獎
第384次：未中獎 再接再厲，觸發正常抽獎
第385次：未中獎 再接再厲，觸發正常抽獎
第386次：未中獎 再接再厲，觸發正常抽獎
第387次：未中獎 再接再厲，觸發正常抽獎
第388次：未中獎 再接再厲，觸發正常抽獎
第389次：未中獎 再接再厲，觸發正常抽獎
第390次：頭獎 500 元，觸發正常抽獎
第391次：未中獎 再接再厲，觸發正常抽獎
第392次：未中獎 再接再厲，觸發正常抽獎
第393次：未中獎 再接再厲，觸發正常抽獎
第394次：貳獎 200元，觸發正常抽獎
第395次：未中獎 再接再厲，觸發正常抽獎
第396次：未中獎 再接再厲，觸發正常抽獎
第397次：未中獎 再接再厲，觸發正常抽獎
第398次：未中獎 再接再厲，觸發正常抽獎
第399次：未中獎 再接再厲，觸發正常抽獎
第400次：未中獎 再接再厲，觸發正常抽獎
第401次：未中獎 再接再厲，觸發正常抽獎
第402次：未中獎 再接再厲，觸發正常抽獎
第403次：未中獎 再接再厲，觸發正常抽獎
第404次：未中獎 再接再厲，觸發正常抽獎
第405次：未中獎 再接再厲，觸發正常抽獎
第406次：未中獎 再接再厲，觸發正常抽獎
第407次：未中獎 再接再厲，觸發正常抽獎
第408次：未中獎 再接再厲，觸發正常抽獎
第409次：未中獎 再接再厲，觸發正常抽獎
第410次：未中獎 再接再厲，觸發正常抽獎
第411次：未中獎 再接再厲，觸發正常抽獎
第412次：未中獎 再接再厲，觸發正常抽獎
第413次：未中獎 再接再厲，觸發正常抽獎
第414次：頭獎 500 元，觸發20抽大保
第415次：未中獎 再接再厲，觸發正常抽獎
第416次：未中獎 再接再厲，觸發正常抽獎
第417次：未中獎 再接再厲，觸發正常抽獎
第418次：未中獎 再接再厲，觸發正常抽獎
第419次：未中獎 再接再厲，觸發正常抽獎
第420次：未中獎 再接再厲，觸發正常抽獎
第421次：未中獎 再接再厲，觸發正常抽獎
第422次：貳獎 200元，觸發正常抽獎
第423次：貳獎 200元，觸發正常抽獎
第424次：頭獎 500 元，觸發正常抽獎
第425次：未中獎 再接再厲，觸發正常抽獎
第426次：未中獎 再接再厲，觸發正常抽獎
第427次：未中獎 再接再厲，觸發正常抽獎
第428次：貳獎 200元，觸發正常抽獎
第429次：未中獎 再接再厲，觸發正常抽獎
第430次：未中獎 再接再厲，觸發正常抽獎
第431次：未中獎 再接再厲，觸發正常抽獎
第432次：貳獎 200元，觸發正常抽獎
第433次：未中獎 再接再厲，觸發正常抽獎
第434次：未中獎 再接再厲，觸發正常抽獎
第435次：未中獎 再接再厲，觸發正常抽獎
第436次：未中獎 再接再厲，觸發正常抽獎
第437次：未中獎 再接再厲，觸發正常抽獎
第438次：未中獎 再接再厲，觸發正常抽獎
第439次：未中獎 再接再厲，觸發正常抽獎
第440次：未中獎 再接再厲，觸發正常抽獎
第441次：未中獎 再接再厲，觸發正常抽獎
第442次：未中獎 再接再厲，觸發正常抽獎
第443次：未中獎 再接再厲，觸發正常抽獎
第444次：未中獎 再接再厲，觸發正常抽獎
第445次：未中獎 再接再厲，觸發正常抽獎
第446次：未中獎 再接再厲，觸發正常抽獎
第447次：未中獎 再接再厲，觸發正常抽獎
第448次：未中獎 再接再厲，觸發正常抽獎
第449次：未中獎 再接再厲，觸發正常抽獎
第450次：未中獎 再接再厲，觸發正常抽獎
第451次：未中獎 再接再厲，觸發正常抽獎
第452次：頭獎 500 元，觸發20抽大保
第453次：未中獎 再接再厲，觸發正常抽獎
第454次：未中獎 再接再厲，觸發正常抽獎
第455次：貳獎 200元，觸發正常抽獎
第456次：未中獎 再接再厲，觸發正常抽獎
第457次：未中獎 再接再厲，觸發正常抽獎
第458次：未中獎 再接再厲，觸發正常抽獎
第459次：未中獎 再接再厲，觸發正常抽獎
第460次：未中獎 再接再厲，觸發正常抽獎
第461次：頭獎 500 元，觸發正常抽獎
第462次：未中獎 再接再厲，觸發正常抽獎
第463次：未中獎 再接再厲，觸發正常抽獎
第464次：未中獎 再接再厲，觸發正常抽獎
第465次：未中獎 再接再厲，觸發正常抽獎
第466次：未中獎 再接再厲，觸發正常抽獎
第467次：貳獎 200元，觸發正常抽獎
第468次：未中獎 再接再厲，觸發正常抽獎
第469次：未中獎 再接再厲，觸發正常抽獎
第470次：未中獎 再接再厲，觸發正常抽獎
第471次：未中獎 再接再厲，觸發正常抽獎
第472次：未中獎 再接再厲，觸發正常抽獎
第473次：貳獎 200元，觸發正常抽獎
第474次：未中獎 再接再厲，觸發正常抽獎
第475次：未中獎 再接再厲，觸發正常抽獎
第476次：未中獎 再接再厲，觸發正常抽獎
第477次：未中獎 再接再厲，觸發正常抽獎
第478次：未中獎 再接再厲，觸發正常抽獎
第479次：貳獎 200元，觸發正常抽獎
第480次：未中獎 再接再厲，觸發正常抽獎
第481次：未中獎 再接再厲，觸發正常抽獎
第482次：未中獎 再接再厲，觸發正常抽獎
第483次：貳獎 200元，觸發正常抽獎
第484次：未中獎 再接再厲，觸發正常抽獎
第485次：未中獎 再接再厲，觸發正常抽獎
第486次：未中獎 再接再厲，觸發正常抽獎
第487次：未中獎 再接再厲，觸發正常抽獎
第488次：貳獎 200元，觸發正常抽獎
第489次：未中獎 再接再厲，觸發正常抽獎
第490次：未中獎 再接再厲，觸發正常抽獎
第491次：未中獎 再接再厲，觸發正常抽獎
第492次：未中獎 再接再厲，觸發正常抽獎
第493次：未中獎 再接再厲，觸發正常抽獎
第494次：頭獎 500 元，觸發正常抽獎
第495次：未中獎 再接再厲，觸發正常抽獎
第496次：未中獎 再接再厲，觸發正常抽獎
第497次：未中獎 再接再厲，觸發正常抽獎
第498次：未中獎 再接再厲，觸發正常抽獎
第499次：未中獎 再接再厲，觸發正常抽獎
第500次：未中獎 再接再厲，觸發正常抽獎
第501次：未中獎 再接再厲，觸發正常抽獎
第502次：貳獎 200元，觸發正常抽獎
第503次：未中獎 再接再厲，觸發正常抽獎
第504次：未中獎 再接再厲，觸發正常抽獎
第505次：未中獎 再接再厲，觸發正常抽獎
第506次：未中獎 再接再厲，觸發正常抽獎
第507次：貳獎 200元，觸發正常抽獎
第508次：貳獎 200元，觸發正常抽獎
第509次：未中獎 再接再厲，觸發正常抽獎
第510次：頭獎 500 元，觸發正常抽獎
第511次：未中獎 再接再厲，觸發正常抽獎
第512次：未中獎 再接再厲，觸發正常抽獎
第513次：未中獎 再接再厲，觸發正常抽獎
第514次：未中獎 再接再厲，觸發正常抽獎
第515次：未中獎 再接再厲，觸發正常抽獎
第516次：未中獎 再接再厲，觸發正常抽獎
第517次：未中獎 再接再厲，觸發正常抽獎
第518次：未中獎 再接再厲，觸發正常抽獎
第519次：未中獎 再接再厲，觸發正常抽獎
第520次：未中獎 再接再厲，觸發正常抽獎
第521次：未中獎 再接再厲，觸發正常抽獎
第522次：未中獎 再接再厲，觸發正常抽獎
第523次：未中獎 再接再厲，觸發正常抽獎
第524次：頭獎 500 元，觸發正常抽獎
第525次：未中獎 再接再厲，觸發正常抽獎
第526次：未中獎 再接再厲，觸發正常抽獎
第527次：未中獎 再接再厲，觸發正常抽獎
第528次：未中獎 再接再厲，觸發正常抽獎
第529次：未中獎 再接再厲，觸發正常抽獎
第530次：貳獎 200元，觸發正常抽獎
第531次：未中獎 再接再厲，觸發正常抽獎
第532次：未中獎 再接再厲，觸發正常抽獎
第533次：頭獎 500 元，觸發正常抽獎
第534次：未中獎 再接再厲，觸發正常抽獎
第535次：未中獎 再接再厲，觸發正常抽獎
第536次：未中獎 再接再厲，觸發正常抽獎
第537次：頭獎 500 元，觸發正常抽獎
第538次：未中獎 再接再厲，觸發正常抽獎
第539次：未中獎 再接再厲，觸發正常抽獎
第540次：未中獎 再接再厲，觸發正常抽獎
第541次：頭獎 500 元，觸發正常抽獎
第542次：貳獎 200元，觸發正常抽獎
第543次：未中獎 再接再厲，觸發正常抽獎
第544次：未中獎 再接再厲，觸發正常抽獎
第545次：未中獎 再接再厲，觸發正常抽獎
第546次：未中獎 再接再厲，觸發正常抽獎
第547次：貳獎 200元，觸發正常抽獎
第548次：貳獎 200元，觸發正常抽獎
第549次：未中獎 再接再厲，觸發正常抽獎
第550次：未中獎 再接再厲，觸發正常抽獎
第551次：未中獎 再接再厲，觸發正常抽獎
第552次：未中獎 再接再厲，觸發正常抽獎
第553次：未中獎 再接再厲，觸發正常抽獎
第554次：未中獎 再接再厲，觸發正常抽獎
第555次：未中獎 再接再厲，觸發正常抽獎
第556次：未中獎 再接再厲，觸發正常抽獎
第557次：未中獎 再接再厲，觸發正常抽獎
第558次：未中獎 再接再厲，觸發正常抽獎
第559次：未中獎 再接再厲，觸發正常抽獎
第560次：未中獎 再接再厲，觸發正常抽獎
第561次：未中獎 再接再厲，觸發正常抽獎
第562次：未中獎 再接再厲，觸發正常抽獎
第563次：未中獎 再接再厲，觸發正常抽獎
第564次：頭獎 500 元，觸發正常抽獎
第565次：未中獎 再接再厲，觸發正常抽獎
第566次：貳獎 200元，觸發正常抽獎
第567次：未中獎 再接再厲，觸發正常抽獎
第568次：未中獎 再接再厲，觸發正常抽獎
第569次：未中獎 再接再厲，觸發正常抽獎
第570次：未中獎 再接再厲，觸發正常抽獎
第571次：未中獎 再接再厲，觸發正常抽獎
第572次：未中獎 再接再厲，觸發正常抽獎
第573次：未中獎 再接再厲，觸發正常抽獎
第574次：未中獎 再接再厲，觸發正常抽獎
第575次：未中獎 再接再厲，觸發正常抽獎
第576次：未中獎 再接再厲，觸發正常抽獎
第577次：未中獎 再接再厲，觸發正常抽獎
第578次：未中獎 再接再厲，觸發正常抽獎
第579次：未中獎 再接再厲，觸發正常抽獎
第580次：未中獎 再接再厲，觸發正常抽獎
第581次：未中獎 再接再厲，觸發正常抽獎
第582次：未中獎 再接再厲，觸發正常抽獎
第583次：未中獎 再接再厲，觸發正常抽獎
第584次：未中獎 再接再厲，觸發正常抽獎
第585次：未中獎 再接再厲，觸發正常抽獎
第586次：貳獎 200元，觸發20抽大保
第587次：未中獎 再接再厲，觸發正常抽獎
第588次：未中獎 再接再厲，觸發正常抽獎
第589次：貳獎 200元，觸發正常抽獎
第590次：未中獎 再接再厲，觸發正常抽獎
第591次：未中獎 再接再厲，觸發正常抽獎
第592次：未中獎 再接再厲，觸發正常抽獎
第593次：未中獎 再接再厲，觸發正常抽獎
第594次：貳獎 200元，觸發正常抽獎
第595次：未中獎 再接再厲，觸發正常抽獎
第596次：貳獎 200元，觸發正常抽獎
第597次：未中獎 再接再厲，觸發正常抽獎
第598次：未中獎 再接再厲，觸發正常抽獎
第599次：未中獎 再接再厲，觸發正常抽獎
第600次：未中獎 再接再厲，觸發正常抽獎
第601次：未中獎 再接再厲，觸發正常抽獎
第602次：未中獎 再接再厲，觸發正常抽獎
第603次：未中獎 再接再厲，觸發正常抽獎
第604次：未中獎 再接再厲，觸發正常抽獎
第605次：未中獎 再接再厲，觸發正常抽獎
第606次：未中獎 再接再厲，觸發正常抽獎
第607次：未中獎 再接再厲，觸發正常抽獎
第608次：未中獎 再接再厲，觸發正常抽獎
第609次：未中獎 再接再厲，觸發正常抽獎
第610次：未中獎 再接再厲，觸發正常抽獎
第611次：未中獎 再接再厲，觸發正常抽獎
第612次：頭獎 500 元，觸發正常抽獎
第613次：貳獎 200元，觸發正常抽獎
第614次：未中獎 再接再厲，觸發正常抽獎
第615次：未中獎 再接再厲，觸發正常抽獎
第616次：貳獎 200元，觸發正常抽獎
第617次：未中獎 再接再厲，觸發正常抽獎
第618次：未中獎 再接再厲，觸發正常抽獎
第619次：貳獎 200元，觸發正常抽獎
第620次：頭獎 500 元，觸發正常抽獎
第621次：未中獎 再接再厲，觸發正常抽獎
第622次：未中獎 再接再厲，觸發正常抽獎
第623次：未中獎 再接再厲，觸發正常抽獎
第624次：未中獎 再接再厲，觸發正常抽獎
第625次：貳獎 200元，觸發正常抽獎
第626次：未中獎 再接再厲，觸發正常抽獎
第627次：未中獎 再接再厲，觸發正常抽獎
第628次：未中獎 再接再厲，觸發正常抽獎
第629次：貳獎 200元，觸發正常抽獎
第630次：未中獎 再接再厲，觸發正常抽獎
第631次：未中獎 再接再厲，觸發正常抽獎
第632次：貳獎 200元，觸發正常抽獎
第633次：貳獎 200元，觸發正常抽獎
第634次：未中獎 再接再厲，觸發正常抽獎
第635次：頭獎 500 元，觸發正常抽獎
第636次：未中獎 再接再厲，觸發正常抽獎
第637次：未中獎 再接再厲，觸發正常抽獎
第638次：頭獎 500 元，觸發正常抽獎
第639次：貳獎 200元，觸發正常抽獎
第640次：未中獎 再接再厲，觸發正常抽獎
第641次：未中獎 再接再厲，觸發正常抽獎
第642次：未中獎 再接再厲，觸發正常抽獎
第643次：未中獎 再接再厲，觸發正常抽獎
第644次：未中獎 再接再厲，觸發正常抽獎
第645次：未中獎 再接再厲，觸發正常抽獎
第646次：貳獎 200元，觸發正常抽獎
第647次：貳獎 200元，觸發正常抽獎
第648次：未中獎 再接再厲，觸發正常抽獎
第649次：未中獎 再接再厲，觸發正常抽獎
第650次：未中獎 再接再厲，觸發正常抽獎
第651次：未中獎 再接再厲，觸發正常抽獎
第652次：未中獎 再接再厲，觸發正常抽獎
第653次：未中獎 再接再厲，觸發正常抽獎
第654次：未中獎 再接再厲，觸發正常抽獎
第655次：未中獎 再接再厲，觸發正常抽獎
第656次：未中獎 再接再厲，觸發正常抽獎
第657次：未中獎 再接再厲，觸發正常抽獎
第658次：貳獎 200元，觸發正常抽獎
第659次：未中獎 再接再厲，觸發正常抽獎
第660次：未中獎 再接再厲，觸發正常抽獎
第661次：未中獎 再接再厲，觸發正常抽獎
第662次：未中獎 再接再厲，觸發正常抽獎
第663次：未中獎 再接再厲，觸發正常抽獎
第664次：未中獎 再接再厲，觸發正常抽獎
第665次：貳獎 200元，觸發正常抽獎
第666次：未中獎 再接再厲，觸發正常抽獎
第667次：未中獎 再接再厲，觸發正常抽獎
第668次：未中獎 再接再厲，觸發正常抽獎
第669次：未中獎 再接再厲，觸發正常抽獎
第670次：頭獎 500 元，觸發正常抽獎
第671次：頭獎 500 元，觸發正常抽獎
第672次：未中獎 再接再厲，觸發正常抽獎
第673次：未中獎 再接再厲，觸發正常抽獎
第674次：未中獎 再接再厲，觸發正常抽獎
第675次：貳獎 200元，觸發正常抽獎
第676次：貳獎 200元，觸發正常抽獎
第677次：未中獎 再接再厲，觸發正常抽獎
第678次：未中獎 再接再厲，觸發正常抽獎
第679次：未中獎 再接再厲，觸發正常抽獎
第680次：貳獎 200元，觸發正常抽獎
第681次：未中獎 再接再厲，觸發正常抽獎
第682次：未中獎 再接再厲，觸發正常抽獎
第683次：未中獎 再接再厲，觸發正常抽獎
第684次：未中獎 再接再厲，觸發正常抽獎
第685次：未中獎 再接再厲，觸發正常抽獎
第686次：未中獎 再接再厲，觸發正常抽獎
第687次：未中獎 再接再厲，觸發正常抽獎
第688次：未中獎 再接再厲，觸發正常抽獎
第689次：未中獎 再接再厲，觸發正常抽獎
第690次：未中獎 再接再厲，觸發正常抽獎
第691次：頭獎 500 元，觸發正常抽獎
第692次：未中獎 再接再厲，觸發正常抽獎
第693次：未中獎 再接再厲，觸發正常抽獎
第694次：未中獎 再接再厲，觸發正常抽獎
第695次：未中獎 再接再厲，觸發正常抽獎
第696次：未中獎 再接再厲，觸發正常抽獎
第697次：未中獎 再接再厲，觸發正常抽獎
第698次：未中獎 再接再厲，觸發正常抽獎
第699次：未中獎 再接再厲，觸發正常抽獎
第700次：未中獎 再接再厲，觸發正常抽獎
第701次：貳獎 200元，觸發正常抽獎
第702次：貳獎 200元，觸發正常抽獎
第703次：頭獎 500 元，觸發正常抽獎
第704次：未中獎 再接再厲，觸發正常抽獎
第705次：未中獎 再接再厲，觸發正常抽獎
第706次：未中獎 再接再厲，觸發正常抽獎
第707次：未中獎 再接再厲，觸發正常抽獎
第708次：未中獎 再接再厲，觸發正常抽獎
第709次：未中獎 再接再厲，觸發正常抽獎
第710次：未中獎 再接再厲，觸發正常抽獎
第711次：頭獎 500 元，觸發正常抽獎
第712次：未中獎 再接再厲，觸發正常抽獎
第713次：未中獎 再接再厲，觸發正常抽獎
第714次：貳獎 200元，觸發正常抽獎
第715次：未中獎 再接再厲，觸發正常抽獎
第716次：未中獎 再接再厲，觸發正常抽獎
第717次：未中獎 再接再厲，觸發正常抽獎
第718次：未中獎 再接再厲，觸發正常抽獎
第719次：貳獎 200元，觸發正常抽獎
第720次：未中獎 再接再厲，觸發正常抽獎
第721次：未中獎 再接再厲，觸發正常抽獎
第722次：未中獎 再接再厲，觸發正常抽獎
第723次：未中獎 再接再厲，觸發正常抽獎
第724次：貳獎 200元，觸發正常抽獎
第725次：未中獎 再接再厲，觸發正常抽獎
第726次：未中獎 再接再厲，觸發正常抽獎
第727次：未中獎 再接再厲，觸發正常抽獎
第728次：未中獎 再接再厲，觸發正常抽獎
第729次：未中獎 再接再厲，觸發正常抽獎
第730次：未中獎 再接再厲，觸發正常抽獎
第731次：未中獎 再接再厲，觸發正常抽獎
第732次：未中獎 再接再厲，觸發正常抽獎
第733次：未中獎 再接再厲，觸發正常抽獎
第734次：未中獎 再接再厲，觸發正常抽獎
第735次：未中獎 再接再厲，觸發正常抽獎
第736次：未中獎 再接再厲，觸發正常抽獎
第737次：未中獎 再接再厲，觸發正常抽獎
第738次：未中獎 再接再厲，觸發正常抽獎
第739次：未中獎 再接再厲，觸發正常抽獎
第740次：未中獎 再接再厲，觸發正常抽獎
第741次：貳獎 200元，觸發正常抽獎
第742次：未中獎 再接再厲，觸發正常抽獎
第743次：未中獎 再接再厲，觸發正常抽獎
第744次：未中獎 再接再厲，觸發正常抽獎
第745次：未中獎 再接再厲，觸發正常抽獎
第746次：未中獎 再接再厲，觸發正常抽獎
第747次：未中獎 再接再厲，觸發正常抽獎
第748次：未中獎 再接再厲，觸發正常抽獎
第749次：未中獎 再接再厲，觸發正常抽獎
第750次：未中獎 再接再厲，觸發正常抽獎
第751次：貳獎 200元，觸發正常抽獎
第752次：貳獎 200元，觸發正常抽獎
第753次：未中獎 再接再厲，觸發正常抽獎
第754次：未中獎 再接再厲，觸發正常抽獎
第755次：未中獎 再接再厲，觸發正常抽獎
第756次：未中獎 再接再厲，觸發正常抽獎
第757次：貳獎 200元，觸發正常抽獎
第758次：貳獎 200元，觸發正常抽獎
第759次：未中獎 再接再厲，觸發正常抽獎
第760次：未中獎 再接再厲，觸發正常抽獎
第761次：未中獎 再接再厲，觸發正常抽獎
第762次：未中獎 再接再厲，觸發正常抽獎
第763次：未中獎 再接再厲，觸發正常抽獎
第764次：未中獎 再接再厲，觸發正常抽獎
第765次：未中獎 再接再厲，觸發正常抽獎
第766次：未中獎 再接再厲，觸發正常抽獎
第767次：未中獎 再接再厲，觸發正常抽獎
第768次：未中獎 再接再厲，觸發正常抽獎
第769次：未中獎 再接再厲，觸發正常抽獎
第770次：未中獎 再接再厲，觸發正常抽獎
第771次：未中獎 再接再厲，觸發正常抽獎
第772次：未中獎 再接再厲，觸發正常抽獎
第773次：貳獎 200元，觸發正常抽獎
第774次：未中獎 再接再厲，觸發正常抽獎
第775次：未中獎 再接再厲，觸發正常抽獎
第776次：未中獎 再接再厲，觸發正常抽獎
第777次：未中獎 再接再厲，觸發正常抽獎
第778次：未中獎 再接再厲，觸發正常抽獎
第779次：未中獎 再接再厲，觸發正常抽獎
第780次：未中獎 再接再厲，觸發正常抽獎
第781次：未中獎 再接再厲，觸發正常抽獎
第782次：未中獎 再接再厲，觸發正常抽獎
第783次：未中獎 再接再厲，觸發正常抽獎
第784次：未中獎 再接再厲，觸發正常抽獎
第785次：未中獎 再接再厲，觸發正常抽獎
第786次：貳獎 200元，觸發正常抽獎
第787次：未中獎 再接再厲，觸發正常抽獎
第788次：未中獎 再接再厲，觸發正常抽獎
第789次：未中獎 再接再厲，觸發正常抽獎
第790次：未中獎 再接再厲，觸發正常抽獎
第791次：貳獎 200元，觸發正常抽獎
第792次：未中獎 再接再厲，觸發正常抽獎
第793次：未中獎 再接再厲，觸發正常抽獎
第794次：未中獎 再接再厲，觸發正常抽獎
第795次：未中獎 再接再厲，觸發正常抽獎
第796次：未中獎 再接再厲，觸發正常抽獎
第797次：未中獎 再接再厲，觸發正常抽獎
第798次：未中獎 再接再厲，觸發正常抽獎
第799次：貳獎 200元，觸發正常抽獎
第800次：未中獎 再接再厲，觸發正常抽獎
第801次：未中獎 再接再厲，觸發正常抽獎
第802次：未中獎 再接再厲，觸發正常抽獎
第803次：未中獎 再接再厲，觸發正常抽獎
第804次：未中獎 再接再厲，觸發正常抽獎
第805次：未中獎 再接再厲，觸發正常抽獎
第806次：未中獎 再接再厲，觸發正常抽獎
第807次：未中獎 再接再厲，觸發正常抽獎
第808次：未中獎 再接再厲，觸發正常抽獎
第809次：未中獎 再接再厲，觸發正常抽獎
第810次：未中獎 再接再厲，觸發正常抽獎
第811次：貳獎 200元，觸發正常抽獎
第812次：未中獎 再接再厲，觸發正常抽獎
第813次：未中獎 再接再厲，觸發正常抽獎
第814次：未中獎 再接再厲，觸發正常抽獎
第815次：未中獎 再接再厲，觸發正常抽獎
第816次：貳獎 200元，觸發正常抽獎
第817次：未中獎 再接再厲，觸發正常抽獎
第818次：未中獎 再接再厲，觸發正常抽獎
第819次：未中獎 再接再厲，觸發正常抽獎
第820次：貳獎 200元，觸發正常抽獎
第821次：未中獎 再接再厲，觸發正常抽獎
第822次：未中獎 再接再厲，觸發正常抽獎
第823次：未中獎 再接再厲，觸發正常抽獎
第824次：未中獎 再接再厲，觸發正常抽獎
第825次：未中獎 再接再厲，觸發正常抽獎
第826次：貳獎 200元，觸發正常抽獎
第827次：未中獎 再接再厲，觸發正常抽獎
第828次：未中獎 再接再厲，觸發正常抽獎
第829次：未中獎 再接再厲，觸發正常抽獎
第830次：未中獎 再接再厲，觸發正常抽獎
第831次：未中獎 再接再厲，觸發正常抽獎
第832次：未中獎 再接再厲，觸發正常抽獎
第833次：未中獎 再接再厲，觸發正常抽獎
第834次：貳獎 200元，觸發正常抽獎
第835次：未中獎 再接再厲，觸發正常抽獎
第836次：貳獎 200元，觸發正常抽獎
第837次：未中獎 再接再厲，觸發正常抽獎
第838次：頭獎 500 元，觸發正常抽獎
第839次：未中獎 再接再厲，觸發正常抽獎
第840次：未中獎 再接再厲，觸發正常抽獎
第841次：未中獎 再接再厲，觸發正常抽獎
第842次：未中獎 再接再厲，觸發正常抽獎
第843次：未中獎 再接再厲，觸發正常抽獎
第844次：貳獎 200元，觸發正常抽獎
第845次：未中獎 再接再厲，觸發正常抽獎
第846次：未中獎 再接再厲，觸發正常抽獎
第847次：未中獎 再接再厲，觸發正常抽獎
第848次：未中獎 再接再厲，觸發正常抽獎
第849次：未中獎 再接再厲，觸發正常抽獎
第850次：未中獎 再接再厲，觸發正常抽獎
第851次：未中獎 再接再厲，觸發正常抽獎
第852次：未中獎 再接再厲，觸發正常抽獎
第853次：未中獎 再接再厲，觸發正常抽獎
第854次：未中獎 再接再厲，觸發正常抽獎
第855次：未中獎 再接再厲，觸發正常抽獎
第856次：未中獎 再接再厲，觸發正常抽獎
第857次：未中獎 再接再厲，觸發正常抽獎
第858次：未中獎 再接再厲，觸發正常抽獎
第859次：未中獎 再接再厲，觸發正常抽獎
第860次：未中獎 再接再厲，觸發正常抽獎
第861次：未中獎 再接再厲，觸發正常抽獎
第862次：未中獎 再接再厲，觸發正常抽獎
第863次：未中獎 再接再厲，觸發正常抽獎
第864次：貳獎 200元，觸發20抽大保
第865次：未中獎 再接再厲，觸發正常抽獎
第866次：未中獎 再接再厲，觸發正常抽獎
第867次：頭獎 500 元，觸發正常抽獎
第868次：未中獎 再接再厲，觸發正常抽獎
第869次：未中獎 再接再厲，觸發正常抽獎
第870次：未中獎 再接再厲，觸發正常抽獎
第871次：未中獎 再接再厲，觸發正常抽獎
第872次：未中獎 再接再厲，觸發正常抽獎
第873次：未中獎 再接再厲，觸發正常抽獎
第874次：未中獎 再接再厲，觸發正常抽獎
第875次：未中獎 再接再厲，觸發正常抽獎
第876次：未中獎 再接再厲，觸發正常抽獎
第877次：未中獎 再接再厲，觸發正常抽獎
第878次：未中獎 再接再厲，觸發正常抽獎
第879次：頭獎 500 元，觸發正常抽獎
第880次：未中獎 再接再厲，觸發正常抽獎
第881次：未中獎 再接再厲，觸發正常抽獎
第882次：未中獎 再接再厲，觸發正常抽獎
第883次：未中獎 再接再厲，觸發正常抽獎
第884次：未中獎 再接再厲，觸發正常抽獎
第885次：未中獎 再接再厲，觸發正常抽獎
第886次：未中獎 再接再厲，觸發正常抽獎
第887次：未中獎 再接再厲，觸發正常抽獎
第888次：貳獎 200元，觸發正常抽獎
第889次：未中獎 再接再厲，觸發正常抽獎
第890次：未中獎 再接再厲，觸發正常抽獎
第891次：未中獎 再接再厲，觸發正常抽獎
第892次：未中獎 再接再厲，觸發正常抽獎
第893次：貳獎 200元，觸發正常抽獎
第894次：未中獎 再接再厲，觸發正常抽獎
第895次：未中獎 再接再厲，觸發正常抽獎
第896次：貳獎 200元，觸發正常抽獎
第897次：未中獎 再接再厲，觸發正常抽獎
第898次：未中獎 再接再厲，觸發正常抽獎
第899次：未中獎 再接再厲，觸發正常抽獎
第900次：未中獎 再接再厲，觸發正常抽獎
第901次：未中獎 再接再厲，觸發正常抽獎
第902次：未中獎 再接再厲，觸發正常抽獎
第903次：未中獎 再接再厲，觸發正常抽獎
第904次：未中獎 再接再厲，觸發正常抽獎
第905次：未中獎 再接再厲，觸發正常抽獎
第906次：未中獎 再接再厲，觸發正常抽獎
第907次：未中獎 再接再厲，觸發正常抽獎
第908次：未中獎 再接再厲，觸發正常抽獎
第909次：未中獎 再接再厲，觸發正常抽獎
第910次：未中獎 再接再厲，觸發正常抽獎
第911次：未中獎 再接再厲，觸發正常抽獎
第912次：未中獎 再接再厲，觸發正常抽獎
第913次：未中獎 再接再厲，觸發正常抽獎
第914次：未中獎 再接再厲，觸發正常抽獎
第915次：未中獎 再接再厲，觸發正常抽獎

    樣本數 單次遊玩獎金期望值估計   標準誤   CI下界   CI上界
0  5000       45.98  1.71  42.63  49.33

帳號：611211101，已存在玩家資料
目前狀態：新手期，尚未中獎，仍具有新手保底
開始遊玩5000次
第1次：頭獎 500 元，觸發正常抽獎
您已不是新手期，之後不具有新手保底
第2次：未中獎 再接再厲，觸發正常抽獎
第3次：未中獎 再接再厲，觸發正常抽獎
第4次：未中獎 再接再厲，觸發正常抽獎
第5次：未中獎 再接再厲，觸發正常抽獎
第6次：未中獎 再接再厲，觸發正常抽獎
第7次：未中獎 再接再厲，觸發正常抽獎
第8次：未中獎 再接再厲，觸發正常抽獎
第9次：頭獎 500 元，觸發正常抽獎
第10次：未中獎 再接再厲，觸發正常抽獎
第11次：未中獎 再接再厲，觸發正常抽獎
第12次：未中獎 再接再厲，觸發正常抽獎
第13次：未中獎 再接再厲，觸發正常抽獎
第14次：未中獎 再接再厲，觸發正常抽獎
第15次：貳獎 200元，觸發正常抽獎
第16次：未中獎 再接再厲，觸發正常抽獎
第17次：未中獎 再接再厲，觸發正常抽獎
第18次：未中獎 再接再厲，觸發正常抽獎
第19次：未中獎 再接再厲，觸發正常抽獎
第20次：未中獎 再接再厲，觸發正常抽獎
第21次：未中獎 再接再厲，觸發正常抽獎
第22次：未中獎 再接再厲，觸發正常抽獎
第23次：未中獎 再接再厲，觸發正常抽獎
第24次：未中獎 再接再厲，觸發正常抽獎
第25次：未中獎 再接再厲，觸發正常抽獎
第26次：未中獎 再接再厲，觸發正常抽獎
第27次：未中獎 再接再厲，觸發正常抽獎
第28次：貳獎 200元，觸發正常抽獎
第29次：未中獎 再接再厲，觸發正常抽獎
第30次：未中獎 再接再厲，觸發正常抽獎
第31次：貳獎 200元，觸發正常抽獎
第32次：未中獎 再接再厲，觸發正常抽獎
第33次：未中獎 再接再厲，觸發正常抽獎
第34次：未中獎 再接再厲，觸發正常抽獎
第35次：未中獎 再接再厲，觸發正常抽獎
第36次：未中獎 再接再厲，觸發正常抽獎
第37次：未中獎 再接再厲，觸發正常抽獎
第38次：未中獎 再接再厲，觸發正常抽獎
第39次：未中獎 再接再厲，觸發正常抽獎
第40次：未中獎 再接再厲，觸發正常抽獎
第41次：未中獎 再接再厲，觸發正常抽獎
第42次：未中獎 再接再厲，觸發正常抽獎
第43次：未中獎 再接再厲，觸發正常抽獎
第44次：未中獎 再接再厲，觸發正常抽獎
第45次：未中獎 再接再厲，觸發正常抽獎
第46次：未中獎 再接再厲，觸發正常抽獎
第47次：未中獎 再接再厲，觸發正常抽獎
第48次：未中獎 再接再厲，觸發正常抽獎
第49次：貳獎 200元，觸發正常抽獎
第50次：未中獎 再接再厲，觸發正常抽獎
第51次：貳獎 200元，觸發正常抽獎
第52次：未中獎 再接再厲，觸發正常抽獎
第53次：未中獎 再接再厲，觸發正常抽獎
第54次：未中獎 再接再厲，觸發正常抽獎
第55次：未中獎 再接再厲，觸發正常抽獎
第56次：未中獎 再接再厲，觸發正常抽獎
第57次：未中獎 再接再厲，觸發正常抽獎
第58次：未中獎 再接再厲，觸發正常抽獎
第59次：未中獎 再接再厲，觸發正常抽獎
第60次：未中獎 再接再厲，觸發正常抽獎
第61次：未中獎 再接再厲，觸發正常抽獎
第62次：未中獎 再接再厲，觸發正常抽獎
第63次：未中獎 再接再厲，觸發正常抽獎
第64次：貳獎 200元，觸發正常抽獎
第65次：未中獎 再接再厲，觸發正常抽獎
第66次：未中獎 再接再厲，觸發正常抽獎
第67次：未中獎 再接再厲，觸發正常抽獎
第68次：頭獎 500 元，觸發正常抽獎
第69次：未中獎 再接再厲，觸發正常抽獎
第70次：未中獎 再接再厲，觸發正常抽獎
第71次：未中獎 再接再厲，觸發正常抽獎
第72次：未中獎 再接再厲，觸發正常抽獎
第73次：未中獎 再接再厲，觸發正常抽獎
第74次：未中獎 再接再厲，觸發正常抽獎
第75次：未中獎 再接再厲，觸發正常抽獎
第76次：未中獎 再接再厲，觸發正常抽獎
第77次：未中獎 再接再厲，觸發正常抽獎
第78次：未中獎 再接再厲，觸發正常抽獎
第79次：未中獎 再接再厲，觸發正常抽獎
第80次：未中獎 再接再厲，觸發正常抽獎
第81次：未中獎 再接再厲，觸發正常抽獎
第82次：未中獎 再接再厲，觸發正常抽獎
第83次：未中獎 再接再厲，觸發正常抽獎
第84次：貳獎 200元，觸發正常抽獎
第85次：未中獎 再接再厲，觸發正常抽獎
第86次：頭獎 500 元，觸發正常抽獎
第87次：貳獎 200元，觸發正常抽獎
第88次：未中獎 再接再厲，觸發正常抽獎
第89次：未中獎 再接再厲，觸發正常抽獎
第90次：未中獎 再接再厲，觸發正常抽獎
第91次：未中獎 再接再厲，觸發正常抽獎
第92次：未中獎 再接再厲，觸發正常抽獎
第93次：未中獎 再接再厲，觸發正常抽獎
第94次：貳獎 200元，觸發正常抽獎
第95次：未中獎 再接再厲，觸發正常抽獎
第96次：未中獎 再接再厲，觸發正常抽獎
第97次：未中獎 再接再厲，觸發正常抽獎
第98次：未中獎 再接再厲，觸發正常抽獎
第99次：未中獎 再接再厲，觸發正常抽獎
第100次：未中獎 再接再厲，觸發正常抽獎
第101次：貳獎 200元，觸發正常抽獎
第102次：未中獎 再接再厲，觸發正常抽獎
第103次：未中獎 再接再厲，觸發正常抽獎
第104次：未中獎 再接再厲，觸發正常抽獎
第105次：未中獎 再接再厲，觸發正常抽獎
第106次：未中獎 再接再厲，觸發正常抽獎
第107次：未中獎 再接再厲，觸發正常抽獎
第108次：未中獎 再接再厲，觸發正常抽獎
第109次：未中獎 再接再厲，觸發正常抽獎
第110次：未中獎 再接再厲，觸發正常抽獎
第111次：未中獎 再接再厲，觸發正常抽獎
第112次：未中獎 再接再厲，觸發正常抽獎
第113次：未中獎 再接再厲，觸發正常抽獎
第114次：未中獎 再接再厲，觸發正常抽獎
第115次：未中獎 再接再厲，觸發正常抽獎
第116次：未中獎 再接再厲，觸發正常抽獎
第117次：未中獎 再接再厲，觸發正常抽獎
第118次：未中獎 再接再厲，觸發正常抽獎
第119次：未中獎 再接再厲，觸發正常抽獎
第120次：未中獎 再接再厲，觸發正常抽獎
第121次：頭獎 500 元，觸發20抽大保
第122次：未中獎 再接再厲，觸發正常抽獎
第123次：未中獎 再接再厲，觸發正常抽獎
第124次：未中獎 再接再厲，觸發正常抽獎
第125次：未中獎 再接再厲，觸發正常抽獎
第126次：未中獎 再接再厲，觸發正常抽獎
第127次：未中獎 再接再厲，觸發正常抽獎
第128次：未中獎 再接再厲，觸發正常抽獎
第129次：未中獎 再接再厲，觸發正常抽獎
第130次：未中獎 再接再厲，觸發正常抽獎
第131次：未中獎 再接再厲，觸發正常抽獎
第132次：未中獎 再接再厲，觸發正常抽獎
第133次：未中獎 再接再厲，觸發正常抽獎
第134次：未中獎 再接再厲，觸發正常抽獎
第135次：未中獎 再接再厲，觸發正常抽獎
第136次：未中獎 再接再厲，觸發正常抽獎
第137次：未中獎 再接再厲，觸發正常抽獎
第138次：頭獎 500 元，觸發正常抽獎
第139次：未中獎 再接再厲，觸發正常抽獎
第140次：未中獎 再接再厲，觸發正常抽獎
第141次：未中獎 再接再厲，觸發正常抽獎
第142次：頭獎 500 元，觸發正常抽獎
第143次：未中獎 再接再厲，觸發正常抽獎
第144次：未中獎 再接再厲，觸發正常抽獎
第145次：未中獎 再接再厲，觸發正常抽獎
第146次：未中獎 再接再厲，觸發正常抽獎
第147次：未中獎 再接再厲，觸發正常抽獎
第148次：貳獎 200元，觸發正常抽獎
第149次：未中獎 再接再厲，觸發正常抽獎
第150次：貳獎 200元，觸發正常抽獎
第151次：未中獎 再接再厲，觸發正常抽獎
第152次：未中獎 再接再厲，觸發正常抽獎
第153次：未中獎 再接再厲，觸發正常抽獎
第154次：未中獎 再接再厲，觸發正常抽獎
第155次：未中獎 再接再厲，觸發正常抽獎
第156次：未中獎 再接再厲，觸發正常抽獎
第157次：未中獎 再接再厲，觸發正常抽獎
第158次：未中獎 再接再厲，觸發正常抽獎
第159次：未中獎 再接再厲，觸發正常抽獎
第160次：未中獎 再接再厲，觸發正常抽獎
第161次：未中獎 再接再厲，觸發正常抽獎
第162次：未中獎 再接再厲，觸發正常抽獎
第163次：未中獎 再接再厲，觸發正常抽獎
第164次：未中獎 再接再厲，觸發正常抽獎
第165次：未中獎 再接再厲，觸發正常抽獎
第166次：未中獎 再接再厲，觸發正常抽獎
第167次：頭獎 500 元，觸發正常抽獎
第168次：未中獎 再接再厲，觸發正常抽獎
第169次：未中獎 再接再厲，觸發正常抽獎
第170次：未中獎 再接再厲，觸發正常抽獎
第171次：貳獎 200元，觸發正常抽獎
第172次：未中獎 再接再厲，觸發正常抽獎
第173次：未中獎 再接再厲，觸發正常抽獎
第174次：未中獎 再接再厲，觸發正常抽獎
第175次：未中獎 再接再厲，觸發正常抽獎
第176次：未中獎 再接再厲，觸發正常抽獎
第177次：未中獎 再接再厲，觸發正常抽獎
第178次：未中獎 再接再厲，觸發正常抽獎
第179次：未中獎 再接再厲，觸發正常抽獎
第180次：未中獎 再接再厲，觸發正常抽獎
第181次：未中獎 再接再厲，觸發正常抽獎
第182次：未中獎 再接再厲，觸發正常抽獎
第183次：未中獎 再接再厲，觸發正常抽獎
第184次：頭獎 500 元，觸發正常抽獎
第185次：未中獎 再接再厲，觸發正常抽獎
第186次：未中獎 再接再厲，觸發正常抽獎
第187次：未中獎 再接再厲，觸發正常抽獎
第188次：未中獎 再接再厲，觸發正常抽獎
第189次：未中獎 再接再厲，觸發正常抽獎
第190次：未中獎 再接再厲，觸發正常抽獎
第191次：未中獎 再接再厲，觸發正常抽獎
第192次：貳獎 200元，觸發正常抽獎
第193次：未中獎 再接再厲，觸發正常抽獎
第194次：貳獎 200元，觸發正常抽獎
第195次：未中獎 再接再厲，觸發正常抽獎
第196次：頭獎 500 元，觸發正常抽獎
第197次：貳獎 200元，觸發正常抽獎
第198次：未中獎 再接再厲，觸發正常抽獎
第199次：未中獎 再接再厲，觸發正常抽獎
第200次：未中獎 再接再厲，觸發正常抽獎
第201次：未中獎 再接再厲，觸發正常抽獎
第202次：貳獎 200元，觸發正常抽獎
第203次：未中獎 再接再厲，觸發正常抽獎
第204次：未中獎 再接再厲，觸發正常抽獎
第205次：未中獎 再接再厲，觸發正常抽獎
第206次：未中獎 再接再厲，觸發正常抽獎
第207次：未中獎 再接再厲，觸發正常抽獎
第208次：未中獎 再接再厲，觸發正常抽獎
第209次：未中獎 再接再厲，觸發正常抽獎
第210次：貳獎 200元，觸發正常抽獎
第211次：未中獎 再接再厲，觸發正常抽獎
第212次：未中獎 再接再厲，觸發正常抽獎
第213次：未中獎 再接再厲，觸發正常抽獎
第214次：未中獎 再接再厲，觸發正常抽獎
第215次：未中獎 再接再厲，觸發正常抽獎
第216次：未中獎 再接再厲，觸發正常抽獎
第217次：未中獎 再接再厲，觸發正常抽獎
第218次：未中獎 再接再厲，觸發正常抽獎
第219次：未中獎 再接再厲，觸發正常抽獎
第220次：頭獎 500 元，觸發正常抽獎
第221次：未中獎 再接再厲，觸發正常抽獎
第222次：未中獎 再接再厲，觸發正常抽獎
第223次：未中獎 再接再厲，觸發正常抽獎
第224次：未中獎 再接再厲，觸發正常抽獎
第225次：未中獎 再接再厲，觸發正常抽獎
第226次：未中獎 再接再厲，觸發正常抽獎
第227次：未中獎 再接再厲，觸發正常抽獎
第228次：未中獎 再接再厲，觸發正常抽獎
第229次：未中獎 再接再厲，觸發正常抽獎
第230次：未中獎 再接再厲，觸發正常抽獎
第231次：未中獎 再接再厲，觸發正常抽獎
第232次：貳獎 200元，觸發正常抽獎
第233次：未中獎 再接再厲，觸發正常抽獎
第234次：頭獎 500 元，觸發正常抽獎
第235次：貳獎 200元，觸發正常抽獎
第236次：未中獎 再接再厲，觸發正常抽獎
第237次：未中獎 再接再厲，觸發正常抽獎
第238次：未中獎 再接再厲，觸發正常抽獎
第239次：貳獎 200元，觸發正常抽獎
第240次：未中獎 再接再厲，觸發正常抽獎
第241次：未中獎 再接再厲，觸發正常抽獎
第242次：未中獎 再接再厲，觸發正常抽獎
第243次：未中獎 再接再厲，觸發正常抽獎
第244次：未中獎 再接再厲，觸發正常抽獎
第245次：未中獎 再接再厲，觸發正常抽獎
第246次：未中獎 再接再厲，觸發正常抽獎
第247次：未中獎 再接再厲，觸發正常抽獎
第248次：未中獎 再接再厲，觸發正常抽獎
第249次：未中獎 再接再厲，觸發正常抽獎
第250次：未中獎 再接再厲，觸發正常抽獎
第251次：未中獎 再接再厲，觸發正常抽獎
第252次：頭獎 500 元，觸發正常抽獎
第253次：未中獎 再接再厲，觸發正常抽獎
第254次：未中獎 再接再厲，觸發正常抽獎
第255次：未中獎 再接再厲，觸發正常抽獎
第256次：未中獎 再接再厲，觸發正常抽獎
第257次：未中獎 再接再厲，觸發正常抽獎
第258次：未中獎 再接再厲，觸發正常抽獎
第259次：未中獎 再接再厲，觸發正常抽獎
第260次：未中獎 再接再厲，觸發正常抽獎
第261次：未中獎 再接再厲，觸發正常抽獎
第262次：未中獎 再接再厲，觸發正常抽獎
第263次：未中獎 再接再厲，觸發正常抽獎
第264次：未中獎 再接再厲，觸發正常抽獎
第265次：未中獎 再接再厲，觸發正常抽獎
第266次：未中獎 再接再厲，觸發正常抽獎
第267次：未中獎 再接再厲，觸發正常抽獎
第268次：未中獎 再接再厲，觸發正常抽獎
第269次：未中獎 再接再厲，觸發正常抽獎
第270次：貳獎 200元，觸發正常抽獎
第271次：未中獎 再接再厲，觸發正常抽獎
第272次：未中獎 再接再厲，觸發正常抽獎
第273次：未中獎 再接再厲，觸發正常抽獎
第274次：未中獎 再接再厲，觸發正常抽獎
第275次：未中獎 再接再厲，觸發正常抽獎
第276次：未中獎 再接再厲，觸發正常抽獎
第277次：未中獎 再接再厲，觸發正常抽獎
第278次：未中獎 再接再厲，觸發正常抽獎
第279次：未中獎 再接再厲，觸發正常抽獎
第280次：未中獎 再接再厲，觸發正常抽獎
第281次：未中獎 再接再厲，觸發正常抽獎
第282次：未中獎 再接再厲，觸發正常抽獎
第283次：未中獎 再接再厲，觸發正常抽獎
第284次：未中獎 再接再厲，觸發正常抽獎
第285次：未中獎 再接再厲，觸發正常抽獎
第286次：貳獎 200元，觸發正常抽獎
第287次：未中獎 再接再厲，觸發正常抽獎
第288次：貳獎 200元，觸發正常抽獎
第289次：貳獎 200元，觸發正常抽獎
第290次：未中獎 再接再厲，觸發正常抽獎
第291次：未中獎 再接再厲，觸發正常抽獎
第292次：未中獎 再接再厲，觸發正常抽獎
第293次：未中獎 再接再厲，觸發正常抽獎
第294次：貳獎 200元，觸發正常抽獎
第295次：頭獎 500 元，觸發正常抽獎
第296次：未中獎 再接再厲，觸發正常抽獎
第297次：未中獎 再接再厲，觸發正常抽獎
第298次：未中獎 再接再厲，觸發正常抽獎
第299次：未中獎 再接再厲，觸發正常抽獎
第300次：未中獎 再接再厲，觸發正常抽獎
第301次：未中獎 再接再厲，觸發正常抽獎
第302次：未中獎 再接再厲，觸發正常抽獎
第303次：貳獎 200元，觸發正常抽獎
第304次：未中獎 再接再厲，觸發正常抽獎
第305次：未中獎 再接再厲，觸發正常抽獎
第306次：未中獎 再接再厲，觸發正常抽獎
第307次：未中獎 再接再厲，觸發正常抽獎
第308次：未中獎 再接再厲，觸發正常抽獎
第309次：未中獎 再接再厲，觸發正常抽獎
第310次：未中獎 再接再厲，觸發正常抽獎
第311次：未中獎 再接再厲，觸發正常抽獎
第312次：未中獎 再接再厲，觸發正常抽獎
第313次：未中獎 再接再厲，觸發正常抽獎
第314次：未中獎 再接再厲，觸發正常抽獎
第315次：未中獎 再接再厲，觸發正常抽獎
第316次：未中獎 再接再厲，觸發正常抽獎
第317次：未中獎 再接再厲，觸發正常抽獎
第318次：未中獎 再接再厲，觸發正常抽獎
第319次：未中獎 再接再厲，觸發正常抽獎
第320次：未中獎 再接再厲，觸發正常抽獎
第321次：貳獎 200元，觸發正常抽獎
第322次：未中獎 再接再厲，觸發正常抽獎
第323次：未中獎 再接再厲，觸發正常抽獎
第324次：未中獎 再接再厲，觸發正常抽獎
第325次：未中獎 再接再厲，觸發正常抽獎
第326次：未中獎 再接再厲，觸發正常抽獎
第327次：未中獎 再接再厲，觸發正常抽獎
第328次：未中獎 再接再厲，觸發正常抽獎
第329次：貳獎 200元，觸發正常抽獎
第330次：未中獎 再接再厲，觸發正常抽獎
第331次：未中獎 再接再厲，觸發正常抽獎
第332次：未中獎 再接再厲，觸發正常抽獎
第333次：未中獎 再接再厲，觸發正常抽獎
第334次：未中獎 再接再厲，觸發正常抽獎
第335次：未中獎 再接再厲，觸發正常抽獎
第336次：未中獎 再接再厲，觸發正常抽獎
第337次：未中獎 再接再厲，觸發正常抽獎
第338次：未中獎 再接再厲，觸發正常抽獎
第339次：未中獎 再接再厲，觸發正常抽獎
第340次：未中獎 再接再厲，觸發正常抽獎
第341次：未中獎 再接再厲，觸發正常抽獎
第342次：未中獎 再接再厲，觸發正常抽獎
第343次：未中獎 再接再厲，觸發正常抽獎
第344次：頭獎 500 元，觸發正常抽獎
第345次：未中獎 再接再厲，觸發正常抽獎
第346次：未中獎 再接再厲，觸發正常抽獎
第347次：未中獎 再接再厲，觸發正常抽獎
第348次：貳獎 200元，觸發正常抽獎
第349次：貳獎 200元，觸發正常抽獎
第350次：未中獎 再接再厲，觸發正常抽獎
第351次：未中獎 再接再厲，觸發正常抽獎
第352次：未中獎 再接再厲，觸發正常抽獎
第353次：未中獎 再接再厲，觸發正常抽獎
第354次：未中獎 再接再厲，觸發正常抽獎
第355次：貳獎 200元，觸發正常抽獎
第356次：未中獎 再接再厲，觸發正常抽獎
第357次：未中獎 再接再厲，觸發正常抽獎
第358次：未中獎 再接再厲，觸發正常抽獎
第359次：未中獎 再接再厲，觸發正常抽獎
第360次：未中獎 再接再厲，觸發正常抽獎
第361次：未中獎 再接再厲，觸發正常抽獎
第362次：未中獎 再接再厲，觸發正常抽獎
第363次：未中獎 再接再厲，觸發正常抽獎
第364次：未中獎 再接再厲，觸發正常抽獎
第365次：未中獎 再接再厲，觸發正常抽獎
第366次：未中獎 再接再厲，觸發正常抽獎
第367次：未中獎 再接再厲，觸發正常抽獎
第368次：未中獎 再接再厲，觸發正常抽獎
第369次：貳獎 200元，觸發正常抽獎
第370次：未中獎 再接再厲，觸發正常抽獎
第371次：未中獎 再接再厲，觸發正常抽獎
第372次：未中獎 再接再厲，觸發正常抽獎
第373次：未中獎 再接再厲，觸發正常抽獎
第374次：未中獎 再接再厲，觸發正常抽獎
第375次：未中獎 再接再厲，觸發正常抽獎
第376次：頭獎 500 元，觸發正常抽獎
第377次：未中獎 再接再厲，觸發正常抽獎
第378次：未中獎 再接再厲，觸發正常抽獎
第379次：未中獎 再接再厲，觸發正常抽獎
第380次：未中獎 再接再厲，觸發正常抽獎
第381次：未中獎 再接再厲，觸發正常抽獎
第382次：未中獎 再接再厲，觸發正常抽獎
第383次：貳獎 200元，觸發正常抽獎
第384次：頭獎 500 元，觸發正常抽獎
第385次：頭獎 500 元，觸發正常抽獎
第386次：未中獎 再接再厲，觸發正常抽獎
第387次：未中獎 再接再厲，觸發正常抽獎
第388次：未中獎 再接再厲，觸發正常抽獎
第389次：未中獎 再接再厲，觸發正常抽獎
第390次：未中獎 再接再厲，觸發正常抽獎
第391次：頭獎 500 元，觸發正常抽獎
第392次：未中獎 再接再厲，觸發正常抽獎
第393次：頭獎 500 元，觸發正常抽獎
第394次：未中獎 再接再厲，觸發正常抽獎
第395次：未中獎 再接再厲，觸發正常抽獎
第396次：未中獎 再接再厲，觸發正常抽獎
第397次：未中獎 再接再厲，觸發正常抽獎
第398次：未中獎 再接再厲，觸發正常抽獎
第399次：未中獎 再接再厲，觸發正常抽獎
第400次：未中獎 再接再厲，觸發正常抽獎
第401次：未中獎 再接再厲，觸發正常抽獎
第402次：未中獎 再接再厲，觸發正常抽獎
第403次：未中獎 再接再厲，觸發正常抽獎
第404次：未中獎 再接再厲，觸發正常抽獎
第405次：未中獎 再接再厲，觸發正常抽獎
第406次：未中獎 再接再厲，觸發正常抽獎
第407次：未中獎 再接再厲，觸發正常抽獎
第408次：未中獎 再接再厲，觸發正常抽獎
第409次：未中獎 再接再厲，觸發正常抽獎
第410次：未中獎 再接再厲，觸發正常抽獎
第411次：貳獎 200元，觸發正常抽獎
第412次：未中獎 再接再厲，觸發正常抽獎
第413次：未中獎 再接再厲，觸發正常抽獎
第414次：未中獎 再接再厲，觸發正常抽獎
第415次：未中獎 再接再厲，觸發正常抽獎
第416次：未中獎 再接再厲，觸發正常抽獎
第417次：未中獎 再接再厲，觸發正常抽獎
第418次：未中獎 再接再厲，觸發正常抽獎
第419次：貳獎 200元，觸發正常抽獎
第420次：未中獎 再接再厲，觸發正常抽獎
第421次：未中獎 再接再厲，觸發正常抽獎
第422次：未中獎 再接再厲，觸發正常抽獎
第423次：未中獎 再接再厲，觸發正常抽獎
第424次：未中獎 再接再厲，觸發正常抽獎
第425次：貳獎 200元，觸發正常抽獎
第426次：貳獎 200元，觸發正常抽獎
第427次：未中獎 再接再厲，觸發正常抽獎
第428次：未中獎 再接再厲，觸發正常抽獎
第429次：未中獎 再接再厲，觸發正常抽獎
第430次：未中獎 再接再厲，觸發正常抽獎
第431次：未中獎 再接再厲，觸發正常抽獎
第432次：未中獎 再接再厲，觸發正常抽獎
第433次：未中獎 再接再厲，觸發正常抽獎
第434次：貳獎 200元，觸發正常抽獎
第435次：未中獎 再接再厲，觸發正常抽獎
第436次：未中獎 再接再厲，觸發正常抽獎
第437次：未中獎 再接再厲，觸發正常抽獎
第438次：未中獎 再接再厲，觸發正常抽獎
第439次：頭獎 500 元，觸發正常抽獎
第440次：未中獎 再接再厲，觸發正常抽獎
第441次：未中獎 再接再厲，觸發正常抽獎
第442次：貳獎 200元，觸發正常抽獎
第443次：未中獎 再接再厲，觸發正常抽獎
第444次：未中獎 再接再厲，觸發正常抽獎
第445次：貳獎 200元，觸發正常抽獎
第446次：未中獎 再接再厲，觸發正常抽獎
第447次：頭獎 500 元，觸發正常抽獎
第448次：貳獎 200元，觸發正常抽獎
第449次：未中獎 再接再厲，觸發正常抽獎
第450次：未中獎 再接再厲，觸發正常抽獎
第451次：未中獎 再接再厲，觸發正常抽獎
第452次：頭獎 500 元，觸發正常抽獎
第453次：未中獎 再接再厲，觸發正常抽獎
第454次：頭獎 500 元，觸發正常抽獎
第455次：貳獎 200元，觸發正常抽獎
第456次：未中獎 再接再厲，觸發正常抽獎
第457次：未中獎 再接再厲，觸發正常抽獎
第458次：未中獎 再接再厲，觸發正常抽獎
第459次：未中獎 再接再厲，觸發正常抽獎
第460次：未中獎 再接再厲，觸發正常抽獎
第461次：未中獎 再接再厲，觸發正常抽獎
第462次：貳獎 200元，觸發正常抽獎
第463次：未中獎 再接再厲，觸發正常抽獎
第464次：未中獎 再接再厲，觸發正常抽獎
第465次：未中獎 再接再厲，觸發正常抽獎
第466次：未中獎 再接再厲，觸發正常抽獎
第467次：未中獎 再接再厲，觸發正常抽獎
第468次：未中獎 再接再厲，觸發正常抽獎
第469次：未中獎 再接再厲，觸發正常抽獎
第470次：頭獎 500 元，觸發正常抽獎
第471次：未中獎 再接再厲，觸發正常抽獎
第472次：未中獎 再接再厲，觸發正常抽獎
第473次：未中獎 再接再厲，觸發正常抽獎
第474次：未中獎 再接再厲，觸發正常抽獎
第475次：貳獎 200元，觸發正常抽獎
第476次：未中獎 再接再厲，觸發正常抽獎
第477次：未中獎 再接再厲，觸發正常抽獎
第478次：未中獎 再接再厲，觸發正常抽獎
第479次：未中獎 再接再厲，觸發正常抽獎
第480次：未中獎 再接再厲，觸發正常抽獎
第481次：頭獎 500 元，觸發正常抽獎
第482次：未中獎 再接再厲，觸發正常抽獎
第483次：未中獎 再接再厲，觸發正常抽獎
第484次：未中獎 再接再厲，觸發正常抽獎
第485次：未中獎 再接再厲，觸發正常抽獎
第486次：未中獎 再接再厲，觸發正常抽獎
第487次：未中獎 再接再厲，觸發正常抽獎
第488次：未中獎 再接再厲，觸發正常抽獎
第489次：未中獎 再接再厲，觸發正常抽獎
第490次：貳獎 200元，觸發正常抽獎
第491次：未中獎 再接再厲，觸發正常抽獎
第492次：未中獎 再接再厲，觸發正常抽獎
第493次：未中獎 再接再厲，觸發正常抽獎
第494次：未中獎 再接再厲，觸發正常抽獎
第495次：未中獎 再接再厲，觸發正常抽獎
第496次：未中獎 再接再厲，觸發正常抽獎
第497次：頭獎 500 元，觸發正常抽獎
第498次：貳獎 200元，觸發正常抽獎
第499次：未中獎 再接再厲，觸發正常抽獎
第500次：貳獎 200元，觸發正常抽獎
第501次：貳獎 200元，觸發正常抽獎
第502次：未中獎 再接再厲，觸發正常抽獎
第503次：未中獎 再接再厲，觸發正常抽獎
第504次：未中獎 再接再厲，觸發正常抽獎
第505次：未中獎 再接再厲，觸發正常抽獎
第506次：未中獎 再接再厲，觸發正常抽獎
第507次：未中獎 再接再厲，觸發正常抽獎
第508次：未中獎 再接再厲，觸發正常抽獎
第509次：未中獎 再接再厲，觸發正常抽獎
第510次：未中獎 再接再厲，觸發正常抽獎
第511次：未中獎 再接再厲，觸發正常抽獎
第512次：未中獎 再接再厲，觸發正常抽獎
第513次：未中獎 再接再厲，觸發正常抽獎
第514次：貳獎 200元，觸發正常抽獎
第515次：未中獎 再接再厲，觸發正常抽獎
第516次：未中獎 再接再厲，觸發正常抽獎
第517次：未中獎 再接再厲，觸發正常抽獎
第518次：未中獎 再接再厲，觸發正常抽獎
第519次：未中獎 再接再厲，觸發正常抽獎
第520次：未中獎 再接再厲，觸發正常抽獎
第521次：貳獎 200元，觸發正常抽獎
第522次：頭獎 500 元，觸發正常抽獎
第523次：未中獎 再接再厲，觸發正常抽獎
第524次：未中獎 再接再厲，觸發正常抽獎
第525次：未中獎 再接再厲，觸發正常抽獎
第526次：未中獎 再接再厲，觸發正常抽獎
第527次：未中獎 再接再厲，觸發正常抽獎
第528次：未中獎 再接再厲，觸發正常抽獎
第529次：未中獎 再接再厲，觸發正常抽獎
第530次：未中獎 再接再厲，觸發正常抽獎
第531次：未中獎 再接再厲，觸發正常抽獎
第532次：頭獎 500 元，觸發正常抽獎
第533次：未中獎 再接再厲，觸發正常抽獎
第534次：未中獎 再接再厲，觸發正常抽獎
第535次：未中獎 再接再厲，觸發正常抽獎
第536次：未中獎 再接再厲，觸發正常抽獎
第537次：未中獎 再接再厲，觸發正常抽獎
第538次：貳獎 200元，觸發正常抽獎
第539次：未中獎 再接再厲，觸發正常抽獎
第540次：未中獎 再接再厲，觸發正常抽獎
第541次：未中獎 再接再厲，觸發正常抽獎
第542次：未中獎 再接再厲，觸發正常抽獎
第543次：貳獎 200元，觸發正常抽獎
第544次：未中獎 再接再厲，觸發正常抽獎
第545次：未中獎 再接再厲，觸發正常抽獎
第546次：未中獎 再接再厲，觸發正常抽獎
第547次：未中獎 再接再厲，觸發正常抽獎
第548次：未中獎 再接再厲，觸發正常抽獎
第549次：未中獎 再接再厲，觸發正常抽獎
第550次：未中獎 再接再厲，觸發正常抽獎
第551次：貳獎 200元，觸發正常抽獎
第552次：未中獎 再接再厲，觸發正常抽獎
第553次：未中獎 再接再厲，觸發正常抽獎
第554次：未中獎 再接再厲，觸發正常抽獎
第555次：未中獎 再接再厲，觸發正常抽獎
第556次：未中獎 再接再厲，觸發正常抽獎
第557次：未中獎 再接再厲，觸發正常抽獎
第558次：未中獎 再接再厲，觸發正常抽獎
第559次：未中獎 再接再厲，觸發正常抽獎
第560次：未中獎 再接再厲，觸發正常抽獎
第561次：未中獎 再接再厲，觸發正常抽獎
第562次：未中獎 再接再厲，觸發正常抽獎
第563次：未中獎 再接再厲，觸發正常抽獎
第564次：未中獎 再接再厲，觸發正常抽獎
第565次：頭獎 500 元，觸發正常抽獎
第566次：貳獎 200元，觸發正常抽獎
第567次：未中獎 再接再厲，觸發正常抽獎
第568次：未中獎 再接再厲，觸發正常抽獎
第569次：未中獎 再接再厲，觸發正常抽獎
第570次：未中獎 再接再厲，觸發正常抽獎
第571次：未中獎 再接再厲，觸發正常抽獎
第572次：頭獎 500 元，觸發正常抽獎
第573次：未中獎 再接再厲，觸發正常抽獎
第574次：貳獎 200元，觸發正常抽獎
第575次：未中獎 再接再厲，觸發正常抽獎
第576次：未中獎 再接再厲，觸發正常抽獎
第577次：未中獎 再接再厲，觸發正常抽獎
第578次：未中獎 再接再厲，觸發正常抽獎
第579次：未中獎 再接再厲，觸發正常抽獎
第580次：未中獎 再接再厲，觸發正常抽獎
第581次：未中獎 再接再厲，觸發正常抽獎
第582次：未中獎 再接再厲，觸發正常抽獎
第583次：未中獎 再接再厲，觸發正常抽獎
第584次：未中獎 再接再厲，觸發正常抽獎
第585次：未中獎 再接再厲，觸發正常抽獎
第586次：未中獎 再接再厲，觸發正常抽獎
第587次：未中獎 再接再厲，觸發正常抽獎
第588次：貳獎 200元，觸發正常抽獎
第589次：未中獎 再接再厲，觸發正常抽獎
第590次：未中獎 再接再厲，觸發正常抽獎
第591次：未中獎 再接再厲，觸發正常抽獎
第592次：貳獎 200元，觸發正常抽獎
第593次：未中獎 再接再厲，觸發正常抽獎
第594次：未中獎 再接再厲，觸發正常抽獎
第595次：未中獎 再接再厲，觸發正常抽獎
第596次：未中獎 再接再厲，觸發正常抽獎
第597次：未中獎 再接再厲，觸發正常抽獎
第598次：未中獎 再接再厲，觸發正常抽獎
第599次：未中獎 再接再厲，觸發正常抽獎
第600次：未中獎 再接再厲，觸發正常抽獎
第601次：未中獎 再接再厲，觸發正常抽獎
第602次：未中獎 再接再厲，觸發正常抽獎
第603次：未中獎 再接再厲，觸發正常抽獎
第604次：未中獎 再接再厲，觸發正常抽獎
第605次：未中獎 再接再厲，觸發正常抽獎
第606次：未中獎 再接再厲，觸發正常抽獎
第607次：未中獎 再接再厲，觸發正常抽獎
第608次：未中獎 再接再厲，觸發正常抽獎
第609次：未中獎 再接再厲，觸發正常抽獎
第610次：未中獎 再接再厲，觸發正常抽獎
第611次：未中獎 再接再厲，觸發正常抽獎
第612次：貳獎 200元，觸發20抽大保
第613次：未中獎 再接再厲，觸發正常抽獎
第614次：未中獎 再接再厲，觸發正常抽獎
第615次：未中獎 再接再厲，觸發正常抽獎
第616次：未中獎 再接再厲，觸發正常抽獎
第617次：頭獎 500 元，觸發正常抽獎
第618次：未中獎 再接再厲，觸發正常抽獎
第619次：未中獎 再接再厲，觸發正常抽獎
第620次：未中獎 再接再厲，觸發正常抽獎
第621次：貳獎 200元，觸發正常抽獎
第622次：未中獎 再接再厲，觸發正常抽獎
第623次：未中獎 再接再厲，觸發正常抽獎
第624次：未中獎 再接再厲，觸發正常抽獎
第625次：未中獎 再接再厲，觸發正常抽獎
第626次：未中獎 再接再厲，觸發正常抽獎
第627次：未中獎 再接再厲，觸發正常抽獎
第628次：未中獎 再接再厲，觸發正常抽獎
第629次：未中獎 再接再厲，觸發正常抽獎
第630次：貳獎 200元，觸發正常抽獎
第631次：未中獎 再接再厲，觸發正常抽獎
第632次：未中獎 再接再厲，觸發正常抽獎
第633次：未中獎 再接再厲，觸發正常抽獎
第634次：未中獎 再接再厲，觸發正常抽獎
第635次：未中獎 再接再厲，觸發正常抽獎
第636次：未中獎 再接再厲，觸發正常抽獎
第637次：未中獎 再接再厲，觸發正常抽獎
第638次：貳獎 200元，觸發正常抽獎
第639次：未中獎 再接再厲，觸發正常抽獎
第640次：未中獎 再接再厲，觸發正常抽獎
第641次：未中獎 再接再厲，觸發正常抽獎
第642次：未中獎 再接再厲，觸發正常抽獎
第643次：未中獎 再接再厲，觸發正常抽獎
第644次：未中獎 再接再厲，觸發正常抽獎
第645次：未中獎 再接再厲，觸發正常抽獎
第646次：未中獎 再接再厲，觸發正常抽獎
第647次：未中獎 再接再厲，觸發正常抽獎
第648次：未中獎 再接再厲，觸發正常抽獎
第649次：未中獎 再接再厲，觸發正常抽獎
第650次：未中獎 再接再厲，觸發正常抽獎
第651次：未中獎 再接再厲，觸發正常抽獎
第652次：未中獎 再接再厲，觸發正常抽獎
第653次：未中獎 再接再厲，觸發正常抽獎
第654次：未中獎 再接再厲，觸發正常抽獎
第655次：未中獎 再接再厲，觸發正常抽獎
第656次：未中獎 再接再厲，觸發正常抽獎
第657次：未中獎 再接再厲，觸發正常抽獎
第658次：貳獎 200元，觸發20抽大保
第659次：未中獎 再接再厲，觸發正常抽獎
第660次：未中獎 再接再厲，觸發正常抽獎
第661次：未中獎 再接再厲，觸發正常抽獎
第662次：未中獎 再接再厲，觸發正常抽獎
第663次：未中獎 再接再厲，觸發正常抽獎
第664次：貳獎 200元，觸發正常抽獎
第665次：未中獎 再接再厲，觸發正常抽獎
第666次：頭獎 500 元，觸發正常抽獎
第667次：未中獎 再接再厲，觸發正常抽獎
第668次：未中獎 再接再厲，觸發正常抽獎
第669次：未中獎 再接再厲，觸發正常抽獎
第670次：未中獎 再接再厲，觸發正常抽獎
第671次：未中獎 再接再厲，觸發正常抽獎
第672次：未中獎 再接再厲，觸發正常抽獎
第673次：未中獎 再接再厲，觸發正常抽獎
第674次：未中獎 再接再厲，觸發正常抽獎
第675次：未中獎 再接再厲，觸發正常抽獎
第676次：未中獎 再接再厲，觸發正常抽獎
第677次：未中獎 再接再厲，觸發正常抽獎
第678次：頭獎 500 元，觸發正常抽獎
第679次：未中獎 再接再厲，觸發正常抽獎
第680次：未中獎 再接再厲，觸發正常抽獎
第681次：未中獎 再接再厲，觸發正常抽獎
第682次：未中獎 再接再厲，觸發正常抽獎
第683次：未中獎 再接再厲，觸發正常抽獎
第684次：未中獎 再接再厲，觸發正常抽獎
第685次：未中獎 再接再厲，觸發正常抽獎
第686次：未中獎 再接再厲，觸發正常抽獎
第687次：未中獎 再接再厲，觸發正常抽獎
第688次：未中獎 再接再厲，觸發正常抽獎
第689次：未中獎 再接再厲，觸發正常抽獎
第690次：頭獎 500 元，觸發正常抽獎
第691次：未中獎 再接再厲，觸發正常抽獎
第692次：未中獎 再接再厲，觸發正常抽獎
第693次：頭獎 500 元，觸發正常抽獎
第694次：貳獎 200元，觸發正常抽獎
第695次：貳獎 200元，觸發正常抽獎
第696次：未中獎 再接再厲，觸發正常抽獎
第697次：未中獎 再接再厲，觸發正常抽獎
第698次：未中獎 再接再厲，觸發正常抽獎
第699次：未中獎 再接再厲，觸發正常抽獎
第700次：未中獎 再接再厲，觸發正常抽獎
第701次：未中獎 再接再厲，觸發正常抽獎
第702次：未中獎 再接再厲，觸發正常抽獎
第703次：貳獎 200元，觸發正常抽獎
第704次：貳獎 200元，觸發正常抽獎
第705次：未中獎 再接再厲，觸發正常抽獎
第706次：未中獎 再接再厲，觸發正常抽獎
第707次：未中獎 再接再厲，觸發正常抽獎
第708次：未中獎 再接再厲，觸發正常抽獎
第709次：未中獎 再接再厲，觸發正常抽獎
第710次：未中獎 再接再厲，觸發正常抽獎
第711次：未中獎 再接再厲，觸發正常抽獎
第712次：未中獎 再接再厲，觸發正常抽獎
第713次：未中獎 再接再厲，觸發正常抽獎
第714次：未中獎 再接再厲，觸發正常抽獎
第715次：未中獎 再接再厲，觸發正常抽獎
第716次：未中獎 再接再厲，觸發正常抽獎
第717次：未中獎 再接再厲，觸發正常抽獎
第718次：未中獎 再接再厲，觸發正常抽獎
第719次：未中獎 再接再厲，觸發正常抽獎
第720次：未中獎 再接再厲，觸發正常抽獎
第721次：貳獎 200元，觸發正常抽獎
第722次：未中獎 再接再厲，觸發正常抽獎
第723次：未中獎 再接再厲，觸發正常抽獎
第724次：未中獎 再接再厲，觸發正常抽獎
第725次：未中獎 再接再厲，觸發正常抽獎
第726次：未中獎 再接再厲，觸發正常抽獎
第727次：未中獎 再接再厲，觸發正常抽獎
第728次：未中獎 再接再厲，觸發正常抽獎
第729次：未中獎 再接再厲，觸發正常抽獎
第730次：未中獎 再接再厲，觸發正常抽獎
第731次：未中獎 再接再厲，觸發正常抽獎
第732次：未中獎 再接再厲，觸發正常抽獎
第733次：未中獎 再接再厲，觸發正常抽獎
第734次：未中獎 再接再厲，觸發正常抽獎
第735次：未中獎 再接再厲，觸發正常抽獎
第736次：貳獎 200元，觸發正常抽獎
第737次：未中獎 再接再厲，觸發正常抽獎
第738次：未中獎 再接再厲，觸發正常抽獎
第739次：未中獎 再接再厲，觸發正常抽獎
第740次：未中獎 再接再厲，觸發正常抽獎
第741次：未中獎 再接再厲，觸發正常抽獎
第742次：未中獎 再接再厲，觸發正常抽獎
第743次：貳獎 200元，觸發正常抽獎
第744次：未中獎 再接再厲，觸發正常抽獎
第745次：未中獎 再接再厲，觸發正常抽獎
第746次：貳獎 200元，觸發正常抽獎
第747次：未中獎 再接再厲，觸發正常抽獎
第748次：未中獎 再接再厲，觸發正常抽獎
第749次：貳獎 200元，觸發正常抽獎
第750次：未中獎 再接再厲，觸發正常抽獎
第751次：未中獎 再接再厲，觸發正常抽獎
第752次：頭獎 500 元，觸發正常抽獎
第753次：未中獎 再接再厲，觸發正常抽獎
第754次：未中獎 再接再厲，觸發正常抽獎
第755次：未中獎 再接再厲，觸發正常抽獎
第756次：頭獎 500 元，觸發正常抽獎
第757次：頭獎 500 元，觸發正常抽獎
第758次：貳獎 200元，觸發正常抽獎
第759次：未中獎 再接再厲，觸發正常抽獎
第760次：未中獎 再接再厲，觸發正常抽獎
第761次：貳獎 200元，觸發正常抽獎
第762次：未中獎 再接再厲，觸發正常抽獎
第763次：未中獎 再接再厲，觸發正常抽獎
第764次：未中獎 再接再厲，觸發正常抽獎
第765次：貳獎 200元，觸發正常抽獎
第766次：未中獎 再接再厲，觸發正常抽獎
第767次：未中獎 再接再厲，觸發正常抽獎
第768次：未中獎 再接再厲，觸發正常抽獎
第769次：未中獎 再接再厲，觸發正常抽獎
第770次：未中獎 再接再厲，觸發正常抽獎
第771次：未中獎 再接再厲，觸發正常抽獎
第772次：未中獎 再接再厲，觸發正常抽獎
第773次：未中獎 再接再厲，觸發正常抽獎
第774次：未中獎 再接再厲，觸發正常抽獎
第775次：未中獎 再接再厲，觸發正常抽獎
第776次：未中獎 再接再厲，觸發正常抽獎
第777次：未中獎 再接再厲，觸發正常抽獎
第778次：未中獎 再接再厲，觸發正常抽獎
第779次：頭獎 500 元，觸發正常抽獎
第780次：頭獎 500 元，觸發正常抽獎
第781次：未中獎 再接再厲，觸發正常抽獎
第782次：頭獎 500 元，觸發正常抽獎
第783次：未中獎 再接再厲，觸發正常抽獎
第784次：未中獎 再接再厲，觸發正常抽獎
第785次：未中獎 再接再厲，觸發正常抽獎
第786次：未中獎 再接再厲，觸發正常抽獎
第787次：未中獎 再接再厲，觸發正常抽獎
第788次：未中獎 再接再厲，觸發正常抽獎
第789次：頭獎 500 元，觸發正常抽獎
第790次：未中獎 再接再厲，觸發正常抽獎
第791次：未中獎 再接再厲，觸發正常抽獎
第792次：未中獎 再接再厲，觸發正常抽獎
第793次：未中獎 再接再厲，觸發正常抽獎
第794次：未中獎 再接再厲，觸發正常抽獎
第795次：未中獎 再接再厲，觸發正常抽獎
第796次：未中獎 再接再厲，觸發正常抽獎
第797次：貳獎 200元，觸發正常抽獎
第798次：未中獎 再接再厲，觸發正常抽獎
第799次：未中獎 再接再厲，觸發正常抽獎
第800次：未中獎 再接再厲，觸發正常抽獎
第801次：未中獎 再接再厲，觸發正常抽獎
第802次：未中獎 再接再厲，觸發正常抽獎
第803次：未中獎 再接再厲，觸發正常抽獎
第804次：未中獎 再接再厲，觸發正常抽獎
第805次：未中獎 再接再厲，觸發正常抽獎
第806次：未中獎 再接再厲，觸發正常抽獎
第807次：貳獎 200元，觸發正常抽獎
第808次：未中獎 再接再厲，觸發正常抽獎
第809次：未中獎 再接再厲，觸發正常抽獎
第810次：未中獎 再接再厲，觸發正常抽獎
第811次：未中獎 再接再厲，觸發正常抽獎
第812次：未中獎 再接再厲，觸發正常抽獎
第813次：未中獎 再接再厲，觸發正常抽獎
第814次：未中獎 再接再厲，觸發正常抽獎
第815次：未中獎 再接再厲，觸發正常抽獎
第816次：貳獎 200元，觸發正常抽獎
第817次：未中獎 再接再厲，觸發正常抽獎
第818次：未中獎 再接再厲，觸發正常抽獎
第819次：未中獎 再接再厲，觸發正常抽獎
第820次：未中獎 再接再厲，觸發正常抽獎
第821次：未中獎 再接再厲，觸發正常抽獎
第822次：未中獎 再接再厲，觸發正常抽獎
第823次：未中獎 再接再厲，觸發正常抽獎
第824次：未中獎 再接再厲，觸發正常抽獎
第825次：未中獎 再接再厲，觸發正常抽獎
第826次：未中獎 再接再厲，觸發正常抽獎
第827次：未中獎 再接再厲，觸發正常抽獎
第828次：未中獎 再接再厲，觸發正常抽獎
第829次：未中獎 再接再厲，觸發正常抽獎
第830次：未中獎 再接再厲，觸發正常抽獎
第831次：未中獎 再接再厲，觸發正常抽獎
第832次：未中獎 再接再厲，觸發正常抽獎
第833次：未中獎 再接再厲，觸發正常抽獎
第834次：未中獎 再接再厲，觸發正常抽獎
第835次：未中獎 再接再厲，觸發正常抽獎
第836次：貳獎 200元，觸發20抽大保
第837次：未中獎 再接再厲，觸發正常抽獎
第838次：未中獎 再接再厲，觸發正常抽獎
第839次：未中獎 再接再厲，觸發正常抽獎
第840次：未中獎 再接再厲，觸發正常抽獎
第841次：未中獎 再接再厲，觸發正常抽獎
第842次：未中獎 再接再厲，觸發正常抽獎
第843次：未中獎 再接再厲，觸發正常抽獎
第844次：未中獎 再接再厲，觸發正常抽獎
第845次：未中獎 再接再厲，觸發正常抽獎
第846次：未中獎 再接再厲，觸發正常抽獎
第847次：未中獎 再接再厲，觸發正常抽獎
第848次：未中獎 再接再厲，觸發正常抽獎
第849次：未中獎 再接再厲，觸發正常抽獎
第850次：未中獎 再接再厲，觸發正常抽獎
第851次：未中獎 再接再厲，觸發正常抽獎
第852次：未中獎 再接再厲，觸發正常抽獎
第853次：未中獎 再接再厲，觸發正常抽獎
第854次：未中獎 再接再厲，觸發正常抽獎
第855次：未中獎 再接再厲，觸發正常抽獎
第856次：頭獎 500 元，觸發20抽大保
第857次：未中獎 再接再厲，觸發正常抽獎
第858次：未中獎 再接再厲，觸發正常抽獎
第859次：未中獎 再接再厲，觸發正常抽獎
第860次：未中獎 再接再厲，觸發正常抽獎
第861次：未中獎 再接再厲，觸發正常抽獎
第862次：未中獎 再接再厲，觸發正常抽獎
第863次：未中獎 再接再厲，觸發正常抽獎
第864次：未中獎 再接再厲，觸發正常抽獎
第865次：未中獎 再接再厲，觸發正常抽獎
第866次：未中獎 再接再厲，觸發正常抽獎
第867次：未中獎 再接再厲，觸發正常抽獎
第868次：未中獎 再接再厲，觸發正常抽獎
第869次：未中獎 再接再厲，觸發正常抽獎
第870次：頭獎 500 元，觸發正常抽獎
第871次：未中獎 再接再厲，觸發正常抽獎
第872次：未中獎 再接再厲，觸發正常抽獎
第873次：未中獎 再接再厲，觸發正常抽獎
第874次：未中獎 再接再厲，觸發正常抽獎
第875次：未中獎 再接再厲，觸發正常抽獎
第876次：頭獎 500 元，觸發正常抽獎
第877次：未中獎 再接再厲，觸發正常抽獎
第878次：未中獎 再接再厲，觸發正常抽獎
第879次：未中獎 再接再厲，觸發正常抽獎
第880次：未中獎 再接再厲，觸發正常抽獎
第881次：未中獎 再接再厲，觸發正常抽獎
第882次：未中獎 再接再厲，觸發正常抽獎
第883次：頭獎 500 元，觸發正常抽獎
第884次：未中獎 再接再厲，觸發正常抽獎
第885次：未中獎 再接再厲，觸發正常抽獎
第886次：未中獎 再接再厲，觸發正常抽獎
第887次：貳獎 200元，觸發正常抽獎
第888次：未中獎 再接再厲，觸發正常抽獎
第889次：未中獎 再接再厲，觸發正常抽獎
第890次：頭獎 500 元，觸發正常抽獎
第891次：未中獎 再接再厲，觸發正常抽獎
第892次：未中獎 再接再厲，觸發正常抽獎
第893次：未中獎 再接再厲，觸發正常抽獎
第894次：未中獎 再接再厲，觸發正常抽獎
第895次：貳獎 200元，觸發正常抽獎
第896次：未中獎 再接再厲，觸發正常抽獎
第897次：貳獎 200元，觸發正常抽獎
第898次：未中獎 再接再厲，觸發正常抽獎
第899次：貳獎 200元，觸發正常抽獎
第900次：未中獎 再接再厲，觸發正常抽獎
第901次：未中獎 再接再厲，觸發正常抽獎
第902次：未中獎 再接再厲，觸發正常抽獎
第903次：未中獎 再接再厲，觸發正常抽獎
第904次：未中獎 再接再厲，觸發正常抽獎
第905次：貳獎 200元，觸發正常抽獎
第906次：未中獎 再接再厲，觸發正常抽獎
第907次：未中獎 再接再厲，觸發正常抽獎
第908次：未中獎 再接再厲，觸發正常抽獎
第909次：未中獎 再接再厲，觸發正常抽獎
第910次：貳獎 200元，觸發正常抽獎
第911次：貳獎 200元，觸發正常抽獎
第912次：未中獎 再接再厲，觸發正常抽獎
第913次：未中獎 再接再厲，觸發正常抽獎
第914次：頭獎 500 元，觸發正常抽獎

    樣本數 單次遊玩獎金期望值估計   標準誤   CI下界   CI上界
0  5000       49.86  1.78  46.38  53.34

帳號：1，已存在玩家資料
目前狀態：非新手期，您不具有新手保底
開始遊玩5000次
第1次：未中獎 再接再厲，觸發正常抽獎
第2次：未中獎 再接再厲，觸發正常抽獎
第3次：未中獎 再接再厲，觸發正常抽獎
第4次：未中獎 再接再厲，觸發正常抽獎
第5次：未中獎 再接再厲，觸發正常抽獎
第6次：貳獎 200元，觸發正常抽獎
第7次：未中獎 再接再厲，觸發正常抽獎
第8次：貳獎 200元，觸發正常抽獎
第9次：未中獎 再接再厲，觸發正常抽獎
第10次：未中獎 再接再厲，觸發正常抽獎
第11次：貳獎 200元，觸發正常抽獎
第12次：未中獎 再接再厲，觸發正常抽獎
第13次：未中獎 再接再厲，觸發正常抽獎
第14次：未中獎 再接再厲，觸發正常抽獎
第15次：未中獎 再接再厲，觸發正常抽獎
第16次：頭獎 500 元，觸發正常抽獎
第17次：未中獎 再接再厲，觸發正常抽獎
第18次：未中獎 再接再厲，觸發正常抽獎
第19次：貳獎 200元，觸發正常抽獎
第20次：未中獎 再接再厲，觸發正常抽獎
第21次：未中獎 再接再厲，觸發正常抽獎
第22次：未中獎 再接再厲，觸發正常抽獎
第23次：未中獎 再接再厲，觸發正常抽獎
第24次：貳獎 200元，觸發正常抽獎
第25次：未中獎 再接再厲，觸發正常抽獎
第26次：未中獎 再接再厲，觸發正常抽獎
第27次：未中獎 再接再厲，觸發正常抽獎
第28次：未中獎 再接再厲，觸發正常抽獎
第29次：未中獎 再接再厲，觸發正常抽獎
第30次：未中獎 再接再厲，觸發正常抽獎
第31次：未中獎 再接再厲，觸發正常抽獎
第32次：貳獎 200元，觸發正常抽獎
第33次：未中獎 再接再厲，觸發正常抽獎
第34次：未中獎 再接再厲，觸發正常抽獎
第35次：未中獎 再接再厲，觸發正常抽獎
第36次：未中獎 再接再厲，觸發正常抽獎
第37次：未中獎 再接再厲，觸發正常抽獎
第38次：未中獎 再接再厲，觸發正常抽獎
第39次：未中獎 再接再厲，觸發正常抽獎
第40次：未中獎 再接再厲，觸發正常抽獎
第41次：未中獎 再接再厲，觸發正常抽獎
第42次：未中獎 再接再厲，觸發正常抽獎
第43次：未中獎 再接再厲，觸發正常抽獎
第44次：未中獎 再接再厲，觸發正常抽獎
第45次：貳獎 200元，觸發正常抽獎
第46次：未中獎 再接再厲，觸發正常抽獎
第47次：未中獎 再接再厲，觸發正常抽獎
第48次：頭獎 500 元，觸發正常抽獎
第49次：未中獎 再接再厲，觸發正常抽獎
第50次：未中獎 再接再厲，觸發正常抽獎
第51次：未中獎 再接再厲，觸發正常抽獎
第52次：未中獎 再接再厲，觸發正常抽獎
第53次：未中獎 再接再厲，觸發正常抽獎
第54次：未中獎 再接再厲，觸發正常抽獎
第55次：未中獎 再接再厲，觸發正常抽獎
第56次：未中獎 再接再厲，觸發正常抽獎
第57次：貳獎 200元，觸發正常抽獎
第58次：未中獎 再接再厲，觸發正常抽獎
第59次：未中獎 再接再厲，觸發正常抽獎
第60次：未中獎 再接再厲，觸發正常抽獎
第61次：未中獎 再接再厲，觸發正常抽獎
第62次：貳獎 200元，觸發正常抽獎
第63次：未中獎 再接再厲，觸發正常抽獎
第64次：未中獎 再接再厲，觸發正常抽獎
第65次：未中獎 再接再厲，觸發正常抽獎
第66次：未中獎 再接再厲，觸發正常抽獎
第67次：未中獎 再接再厲，觸發正常抽獎
第68次：未中獎 再接再厲，觸發正常抽獎
第69次：未中獎 再接再厲，觸發正常抽獎
第70次：未中獎 再接再厲，觸發正常抽獎
第71次：未中獎 再接再厲，觸發正常抽獎
第72次：未中獎 再接再厲，觸發正常抽獎
第73次：未中獎 再接再厲，觸發正常抽獎
第74次：未中獎 再接再厲，觸發正常抽獎
第75次：未中獎 再接再厲，觸發正常抽獎
第76次：頭獎 500 元，觸發正常抽獎
第77次：未中獎 再接再厲，觸發正常抽獎
第78次：貳獎 200元，觸發正常抽獎
第79次：未中獎 再接再厲，觸發正常抽獎
第80次：未中獎 再接再厲，觸發正常抽獎
第81次：未中獎 再接再厲，觸發正常抽獎
第82次：未中獎 再接再厲，觸發正常抽獎
第83次：貳獎 200元，觸發正常抽獎
第84次：未中獎 再接再厲，觸發正常抽獎
第85次：未中獎 再接再厲，觸發正常抽獎
第86次：未中獎 再接再厲，觸發正常抽獎
第87次：未中獎 再接再厲，觸發正常抽獎
第88次：未中獎 再接再厲，觸發正常抽獎
第89次：未中獎 再接再厲，觸發正常抽獎
第90次：未中獎 再接再厲，觸發正常抽獎
第91次：未中獎 再接再厲，觸發正常抽獎
第92次：未中獎 再接再厲，觸發正常抽獎
第93次：未中獎 再接再厲，觸發正常抽獎
第94次：未中獎 再接再厲，觸發正常抽獎
第95次：未中獎 再接再厲，觸發正常抽獎
第96次：未中獎 再接再厲，觸發正常抽獎
第97次：未中獎 再接再厲，觸發正常抽獎
第98次：未中獎 再接再厲，觸發正常抽獎
第99次：未中獎 再接再厲，觸發正常抽獎
第100次：未中獎 再接再厲，觸發正常抽獎
第101次：未中獎 再接再厲，觸發正常抽獎
第102次：未中獎 再接再厲，觸發正常抽獎
第103次：頭獎 500 元，觸發20抽大保
第104次：未中獎 再接再厲，觸發正常抽獎
第105次：未中獎 再接再厲，觸發正常抽獎
第106次：未中獎 再接再厲，觸發正常抽獎
第107次：頭獎 500 元，觸發正常抽獎
第108次：未中獎 再接再厲，觸發正常抽獎
第109次：未中獎 再接再厲，觸發正常抽獎
第110次：頭獎 500 元，觸發正常抽獎
第111次：未中獎 再接再厲，觸發正常抽獎
第112次：頭獎 500 元，觸發正常抽獎
第113次：未中獎 再接再厲，觸發正常抽獎
第114次：未中獎 再接再厲，觸發正常抽獎
第115次：未中獎 再接再厲，觸發正常抽獎
第116次：未中獎 再接再厲，觸發正常抽獎
第117次：未中獎 再接再厲，觸發正常抽獎
第118次：未中獎 再接再厲，觸發正常抽獎
第119次：貳獎 200元，觸發正常抽獎
第120次：未中獎 再接再厲，觸發正常抽獎
第121次：未中獎 再接再厲，觸發正常抽獎
第122次：未中獎 再接再厲，觸發正常抽獎
第123次：未中獎 再接再厲，觸發正常抽獎
第124次：未中獎 再接再厲，觸發正常抽獎
第125次：未中獎 再接再厲，觸發正常抽獎
第126次：未中獎 再接再厲，觸發正常抽獎
第127次：未中獎 再接再厲，觸發正常抽獎
第128次：未中獎 再接再厲，觸發正常抽獎
第129次：未中獎 再接再厲，觸發正常抽獎
第130次：未中獎 再接再厲，觸發正常抽獎
第131次：未中獎 再接再厲，觸發正常抽獎
第132次：未中獎 再接再厲，觸發正常抽獎
第133次：未中獎 再接再厲，觸發正常抽獎
第134次：未中獎 再接再厲，觸發正常抽獎
第135次：未中獎 再接再厲，觸發正常抽獎
第136次：未中獎 再接再厲，觸發正常抽獎
第137次：未中獎 再接再厲，觸發正常抽獎
第138次：未中獎 再接再厲，觸發正常抽獎
第139次：頭獎 500 元，觸發20抽大保
第140次：未中獎 再接再厲，觸發正常抽獎
第141次：未中獎 再接再厲，觸發正常抽獎
第142次：未中獎 再接再厲，觸發正常抽獎
第143次：未中獎 再接再厲，觸發正常抽獎
第144次：未中獎 再接再厲，觸發正常抽獎
第145次：未中獎 再接再厲，觸發正常抽獎
第146次：未中獎 再接再厲，觸發正常抽獎
第147次：未中獎 再接再厲，觸發正常抽獎
第148次：未中獎 再接再厲，觸發正常抽獎
第149次：未中獎 再接再厲，觸發正常抽獎
第150次：貳獎 200元，觸發正常抽獎
第151次：未中獎 再接再厲，觸發正常抽獎
第152次：未中獎 再接再厲，觸發正常抽獎
第153次：未中獎 再接再厲，觸發正常抽獎
第154次：未中獎 再接再厲，觸發正常抽獎
第155次：未中獎 再接再厲，觸發正常抽獎
第156次：未中獎 再接再厲，觸發正常抽獎
第157次：未中獎 再接再厲，觸發正常抽獎
第158次：未中獎 再接再厲，觸發正常抽獎
第159次：未中獎 再接再厲，觸發正常抽獎
第160次：未中獎 再接再厲，觸發正常抽獎
第161次：未中獎 再接再厲，觸發正常抽獎
第162次：未中獎 再接再厲，觸發正常抽獎
第163次：未中獎 再接再厲，觸發正常抽獎
第164次：未中獎 再接再厲，觸發正常抽獎
第165次：未中獎 再接再厲，觸發正常抽獎
第166次：未中獎 再接再厲，觸發正常抽獎
第167次：未中獎 再接再厲，觸發正常抽獎
第168次：未中獎 再接再厲，觸發正常抽獎
第169次：未中獎 再接再厲，觸發正常抽獎
第170次：貳獎 200元，觸發20抽大保
第171次：未中獎 再接再厲，觸發正常抽獎
第172次：未中獎 再接再厲，觸發正常抽獎
第173次：貳獎 200元，觸發正常抽獎
第174次：未中獎 再接再厲，觸發正常抽獎
第175次：未中獎 再接再厲，觸發正常抽獎
第176次：未中獎 再接再厲，觸發正常抽獎
第177次：頭獎 500 元，觸發正常抽獎
第178次：未中獎 再接再厲，觸發正常抽獎
第179次：未中獎 再接再厲，觸發正常抽獎
第180次：未中獎 再接再厲，觸發正常抽獎
第181次：未中獎 再接再厲，觸發正常抽獎
第182次：未中獎 再接再厲，觸發正常抽獎
第183次：未中獎 再接再厲，觸發正常抽獎
第184次：未中獎 再接再厲，觸發正常抽獎
第185次：未中獎 再接再厲，觸發正常抽獎
第186次：未中獎 再接再厲，觸發正常抽獎
第187次：未中獎 再接再厲，觸發正常抽獎
第188次：未中獎 再接再厲，觸發正常抽獎
第189次：未中獎 再接再厲，觸發正常抽獎
第190次：未中獎 再接再厲，觸發正常抽獎
第191次：未中獎 再接再厲，觸發正常抽獎
第192次：未中獎 再接再厲，觸發正常抽獎
第193次：未中獎 再接再厲，觸發正常抽獎
第194次：未中獎 再接再厲，觸發正常抽獎
第195次：未中獎 再接再厲，觸發正常抽獎
第196次：未中獎 再接再厲，觸發正常抽獎
第197次：頭獎 500 元，觸發20抽大保
第198次：未中獎 再接再厲，觸發正常抽獎
第199次：未中獎 再接再厲，觸發正常抽獎
第200次：未中獎 再接再厲，觸發正常抽獎
第201次：未中獎 再接再厲，觸發正常抽獎
第202次：未中獎 再接再厲，觸發正常抽獎
第203次：頭獎 500 元，觸發正常抽獎
第204次：未中獎 再接再厲，觸發正常抽獎
第205次：未中獎 再接再厲，觸發正常抽獎
第206次：未中獎 再接再厲，觸發正常抽獎
第207次：未中獎 再接再厲，觸發正常抽獎
第208次：未中獎 再接再厲，觸發正常抽獎
第209次：未中獎 再接再厲，觸發正常抽獎
第210次：未中獎 再接再厲，觸發正常抽獎
第211次：未中獎 再接再厲，觸發正常抽獎
第212次：未中獎 再接再厲，觸發正常抽獎
第213次：未中獎 再接再厲，觸發正常抽獎
第214次：頭獎 500 元，觸發正常抽獎
第215次：未中獎 再接再厲，觸發正常抽獎
第216次：未中獎 再接再厲，觸發正常抽獎
第217次：未中獎 再接再厲，觸發正常抽獎
第218次：未中獎 再接再厲，觸發正常抽獎
第219次：未中獎 再接再厲，觸發正常抽獎
第220次：貳獎 200元，觸發正常抽獎
第221次：未中獎 再接再厲，觸發正常抽獎
第222次：未中獎 再接再厲，觸發正常抽獎
第223次：未中獎 再接再厲，觸發正常抽獎
第224次：未中獎 再接再厲，觸發正常抽獎
第225次：貳獎 200元，觸發正常抽獎
第226次：未中獎 再接再厲，觸發正常抽獎
第227次：未中獎 再接再厲，觸發正常抽獎
第228次：未中獎 再接再厲，觸發正常抽獎
第229次：未中獎 再接再厲，觸發正常抽獎
第230次：未中獎 再接再厲，觸發正常抽獎
第231次：未中獎 再接再厲，觸發正常抽獎
第232次：未中獎 再接再厲，觸發正常抽獎
第233次：未中獎 再接再厲，觸發正常抽獎
第234次：未中獎 再接再厲，觸發正常抽獎
第235次：未中獎 再接再厲，觸發正常抽獎
第236次：未中獎 再接再厲，觸發正常抽獎
第237次：未中獎 再接再厲，觸發正常抽獎
第238次：未中獎 再接再厲，觸發正常抽獎
第239次：未中獎 再接再厲，觸發正常抽獎
第240次：未中獎 再接再厲，觸發正常抽獎
第241次：未中獎 再接再厲，觸發正常抽獎
第242次：未中獎 再接再厲，觸發正常抽獎
第243次：未中獎 再接再厲，觸發正常抽獎
第244次：未中獎 再接再厲，觸發正常抽獎
第245次：貳獎 200元，觸發20抽大保
第246次：未中獎 再接再厲，觸發正常抽獎
第247次：未中獎 再接再厲，觸發正常抽獎
第248次：頭獎 500 元，觸發正常抽獎
第249次：未中獎 再接再厲，觸發正常抽獎
第250次：未中獎 再接再厲，觸發正常抽獎
第251次：未中獎 再接再厲，觸發正常抽獎
第252次：未中獎 再接再厲，觸發正常抽獎
第253次：未中獎 再接再厲，觸發正常抽獎
第254次：未中獎 再接再厲，觸發正常抽獎
第255次：未中獎 再接再厲，觸發正常抽獎
第256次：未中獎 再接再厲，觸發正常抽獎
第257次：未中獎 再接再厲，觸發正常抽獎
第258次：未中獎 再接再厲，觸發正常抽獎
第259次：未中獎 再接再厲，觸發正常抽獎
第260次：未中獎 再接再厲，觸發正常抽獎
第261次：未中獎 再接再厲，觸發正常抽獎
第262次：貳獎 200元，觸發正常抽獎
第263次：未中獎 再接再厲，觸發正常抽獎
第264次：未中獎 再接再厲，觸發正常抽獎
第265次：未中獎 再接再厲，觸發正常抽獎
第266次：未中獎 再接再厲，觸發正常抽獎
第267次：未中獎 再接再厲，觸發正常抽獎
第268次：未中獎 再接再厲，觸發正常抽獎
第269次：未中獎 再接再厲，觸發正常抽獎
第270次：未中獎 再接再厲，觸發正常抽獎
第271次：未中獎 再接再厲，觸發正常抽獎
第272次：貳獎 200元，觸發正常抽獎
第273次：未中獎 再接再厲，觸發正常抽獎
第274次：未中獎 再接再厲，觸發正常抽獎
第275次：未中獎 再接再厲，觸發正常抽獎
第276次：貳獎 200元，觸發正常抽獎
第277次：未中獎 再接再厲，觸發正常抽獎
第278次：未中獎 再接再厲，觸發正常抽獎
第279次：未中獎 再接再厲，觸發正常抽獎
第280次：貳獎 200元，觸發正常抽獎
第281次：未中獎 再接再厲，觸發正常抽獎
第282次：未中獎 再接再厲，觸發正常抽獎
第283次：未中獎 再接再厲，觸發正常抽獎
第284次：未中獎 再接再厲，觸發正常抽獎
第285次：未中獎 再接再厲，觸發正常抽獎
第286次：未中獎 再接再厲，觸發正常抽獎
第287次：未中獎 再接再厲，觸發正常抽獎
第288次：未中獎 再接再厲，觸發正常抽獎
第289次：未中獎 再接再厲，觸發正常抽獎
第290次：未中獎 再接再厲，觸發正常抽獎
第291次：未中獎 再接再厲，觸發正常抽獎
第292次：未中獎 再接再厲，觸發正常抽獎
第293次：未中獎 再接再厲，觸發正常抽獎
第294次：未中獎 再接再厲，觸發正常抽獎
第295次：未中獎 再接再厲，觸發正常抽獎
第296次：未中獎 再接再厲，觸發正常抽獎
第297次：未中獎 再接再厲，觸發正常抽獎
第298次：未中獎 再接再厲，觸發正常抽獎
第299次：未中獎 再接再厲，觸發正常抽獎
第300次：貳獎 200元，觸發20抽大保
第301次：未中獎 再接再厲，觸發正常抽獎
第302次：未中獎 再接再厲，觸發正常抽獎
第303次：未中獎 再接再厲，觸發正常抽獎
第304次：頭獎 500 元，觸發正常抽獎
第305次：未中獎 再接再厲，觸發正常抽獎
第306次：頭獎 500 元，觸發正常抽獎
第307次：未中獎 再接再厲，觸發正常抽獎
第308次：貳獎 200元，觸發正常抽獎
第309次：未中獎 再接再厲，觸發正常抽獎
第310次：未中獎 再接再厲，觸發正常抽獎
第311次：未中獎 再接再厲，觸發正常抽獎
第312次：貳獎 200元，觸發正常抽獎
第313次：頭獎 500 元，觸發正常抽獎
第314次：未中獎 再接再厲，觸發正常抽獎
第315次：未中獎 再接再厲，觸發正常抽獎
第316次：未中獎 再接再厲，觸發正常抽獎
第317次：未中獎 再接再厲，觸發正常抽獎
第318次：未中獎 再接再厲，觸發正常抽獎
第319次：頭獎 500 元，觸發正常抽獎
第320次：未中獎 再接再厲，觸發正常抽獎
第321次：未中獎 再接再厲，觸發正常抽獎
第322次：未中獎 再接再厲，觸發正常抽獎
第323次：未中獎 再接再厲，觸發正常抽獎
第324次：未中獎 再接再厲，觸發正常抽獎
第325次：未中獎 再接再厲，觸發正常抽獎
第326次：未中獎 再接再厲，觸發正常抽獎
第327次：貳獎 200元，觸發正常抽獎
第328次：未中獎 再接再厲，觸發正常抽獎
第329次：未中獎 再接再厲，觸發正常抽獎
第330次：未中獎 再接再厲，觸發正常抽獎
第331次：未中獎 再接再厲，觸發正常抽獎
第332次：未中獎 再接再厲，觸發正常抽獎
第333次：未中獎 再接再厲，觸發正常抽獎
第334次：未中獎 再接再厲，觸發正常抽獎
第335次：貳獎 200元，觸發正常抽獎
第336次：未中獎 再接再厲，觸發正常抽獎
第337次：未中獎 再接再厲，觸發正常抽獎
第338次：未中獎 再接再厲，觸發正常抽獎
第339次：未中獎 再接再厲，觸發正常抽獎
第340次：未中獎 再接再厲，觸發正常抽獎
第341次：未中獎 再接再厲，觸發正常抽獎
第342次：頭獎 500 元，觸發正常抽獎
第343次：未中獎 再接再厲，觸發正常抽獎
第344次：未中獎 再接再厲，觸發正常抽獎
第345次：未中獎 再接再厲，觸發正常抽獎
第346次：未中獎 再接再厲，觸發正常抽獎
第347次：未中獎 再接再厲，觸發正常抽獎
第348次：未中獎 再接再厲，觸發正常抽獎
第349次：未中獎 再接再厲，觸發正常抽獎
第350次：未中獎 再接再厲，觸發正常抽獎
第351次：未中獎 再接再厲，觸發正常抽獎
第352次：未中獎 再接再厲，觸發正常抽獎
第353次：未中獎 再接再厲，觸發正常抽獎
第354次：未中獎 再接再厲，觸發正常抽獎
第355次：未中獎 再接再厲，觸發正常抽獎
第356次：未中獎 再接再厲，觸發正常抽獎
第357次：貳獎 200元，觸發正常抽獎
第358次：未中獎 再接再厲，觸發正常抽獎
第359次：未中獎 再接再厲，觸發正常抽獎
第360次：未中獎 再接再厲，觸發正常抽獎
第361次：未中獎 再接再厲，觸發正常抽獎
第362次：貳獎 200元，觸發正常抽獎
第363次：未中獎 再接再厲，觸發正常抽獎
第364次：未中獎 再接再厲，觸發正常抽獎
第365次：未中獎 再接再厲，觸發正常抽獎
第366次：貳獎 200元，觸發正常抽獎
第367次：未中獎 再接再厲，觸發正常抽獎
第368次：未中獎 再接再厲，觸發正常抽獎
第369次：未中獎 再接再厲，觸發正常抽獎
第370次：未中獎 再接再厲，觸發正常抽獎
第371次：未中獎 再接再厲，觸發正常抽獎
第372次：未中獎 再接再厲，觸發正常抽獎
第373次：未中獎 再接再厲，觸發正常抽獎
第374次：未中獎 再接再厲，觸發正常抽獎
第375次：未中獎 再接再厲，觸發正常抽獎
第376次：貳獎 200元，觸發正常抽獎
第377次：未中獎 再接再厲，觸發正常抽獎
第378次：未中獎 再接再厲，觸發正常抽獎
第379次：未中獎 再接再厲，觸發正常抽獎
第380次：未中獎 再接再厲，觸發正常抽獎
第381次：未中獎 再接再厲，觸發正常抽獎
第382次：未中獎 再接再厲，觸發正常抽獎
第383次：未中獎 再接再厲，觸發正常抽獎
第384次：貳獎 200元，觸發正常抽獎
第385次：貳獎 200元，觸發正常抽獎
第386次：未中獎 再接再厲，觸發正常抽獎
第387次：未中獎 再接再厲，觸發正常抽獎
第388次：未中獎 再接再厲，觸發正常抽獎
第389次：未中獎 再接再厲，觸發正常抽獎
第390次：未中獎 再接再厲，觸發正常抽獎
第391次：未中獎 再接再厲，觸發正常抽獎
第392次：未中獎 再接再厲，觸發正常抽獎
第393次：未中獎 再接再厲，觸發正常抽獎
第394次：未中獎 再接再厲，觸發正常抽獎
第395次：貳獎 200元，觸發正常抽獎
第396次：貳獎 200元，觸發正常抽獎
第397次：未中獎 再接再厲，觸發正常抽獎
第398次：未中獎 再接再厲，觸發正常抽獎
第399次：未中獎 再接再厲，觸發正常抽獎
第400次：未中獎 再接再厲，觸發正常抽獎
第401次：未中獎 再接再厲，觸發正常抽獎
第402次：未中獎 再接再厲，觸發正常抽獎
第403次：未中獎 再接再厲，觸發正常抽獎
第404次：未中獎 再接再厲，觸發正常抽獎
第405次：未中獎 再接再厲，觸發正常抽獎
第406次：未中獎 再接再厲，觸發正常抽獎
第407次：未中獎 再接再厲，觸發正常抽獎
第408次：未中獎 再接再厲，觸發正常抽獎
第409次：頭獎 500 元，觸發正常抽獎
第410次：未中獎 再接再厲，觸發正常抽獎
第411次：未中獎 再接再厲，觸發正常抽獎
第412次：未中獎 再接再厲，觸發正常抽獎
第413次：未中獎 再接再厲，觸發正常抽獎
第414次：未中獎 再接再厲，觸發正常抽獎
第415次：貳獎 200元，觸發正常抽獎
第416次：未中獎 再接再厲，觸發正常抽獎
第417次：未中獎 再接再厲，觸發正常抽獎
第418次：未中獎 再接再厲，觸發正常抽獎
第419次：未中獎 再接再厲，觸發正常抽獎
第420次：貳獎 200元，觸發正常抽獎
第421次：未中獎 再接再厲，觸發正常抽獎
第422次：未中獎 再接再厲，觸發正常抽獎
第423次：未中獎 再接再厲，觸發正常抽獎
第424次：未中獎 再接再厲，觸發正常抽獎
第425次：頭獎 500 元，觸發正常抽獎
第426次：未中獎 再接再厲，觸發正常抽獎
第427次：貳獎 200元，觸發正常抽獎
第428次：貳獎 200元，觸發正常抽獎
第429次：未中獎 再接再厲，觸發正常抽獎
第430次：未中獎 再接再厲，觸發正常抽獎
第431次：未中獎 再接再厲，觸發正常抽獎
第432次：未中獎 再接再厲，觸發正常抽獎
第433次：未中獎 再接再厲，觸發正常抽獎
第434次：未中獎 再接再厲，觸發正常抽獎
第435次：貳獎 200元，觸發正常抽獎
第436次：未中獎 再接再厲，觸發正常抽獎
第437次：未中獎 再接再厲，觸發正常抽獎
第438次：未中獎 再接再厲，觸發正常抽獎
第439次：未中獎 再接再厲，觸發正常抽獎
第440次：未中獎 再接再厲，觸發正常抽獎
第441次：未中獎 再接再厲，觸發正常抽獎
第442次：未中獎 再接再厲，觸發正常抽獎
第443次：貳獎 200元，觸發正常抽獎
第444次：未中獎 再接再厲，觸發正常抽獎
第445次：未中獎 再接再厲，觸發正常抽獎
第446次：未中獎 再接再厲，觸發正常抽獎
第447次：未中獎 再接再厲，觸發正常抽獎
第448次：未中獎 再接再厲，觸發正常抽獎
第449次：貳獎 200元，觸發正常抽獎
第450次：未中獎 再接再厲，觸發正常抽獎
第451次：未中獎 再接再厲，觸發正常抽獎
第452次：未中獎 再接再厲，觸發正常抽獎
第453次：貳獎 200元，觸發正常抽獎
第454次：未中獎 再接再厲，觸發正常抽獎
第455次：未中獎 再接再厲，觸發正常抽獎
第456次：未中獎 再接再厲，觸發正常抽獎
第457次：貳獎 200元，觸發正常抽獎
第458次：未中獎 再接再厲，觸發正常抽獎
第459次：未中獎 再接再厲，觸發正常抽獎
第460次：未中獎 再接再厲，觸發正常抽獎
第461次：未中獎 再接再厲，觸發正常抽獎
第462次：未中獎 再接再厲，觸發正常抽獎
第463次：未中獎 再接再厲，觸發正常抽獎
第464次：未中獎 再接再厲，觸發正常抽獎
第465次：未中獎 再接再厲，觸發正常抽獎
第466次：未中獎 再接再厲，觸發正常抽獎
第467次：未中獎 再接再厲，觸發正常抽獎
第468次：未中獎 再接再厲，觸發正常抽獎
第469次：未中獎 再接再厲，觸發正常抽獎
第470次：貳獎 200元，觸發正常抽獎
第471次：未中獎 再接再厲，觸發正常抽獎
第472次：未中獎 再接再厲，觸發正常抽獎
第473次：未中獎 再接再厲，觸發正常抽獎
第474次：未中獎 再接再厲，觸發正常抽獎
第475次：頭獎 500 元，觸發正常抽獎
第476次：頭獎 500 元，觸發正常抽獎
第477次：未中獎 再接再厲，觸發正常抽獎
第478次：頭獎 500 元，觸發正常抽獎
第479次：未中獎 再接再厲，觸發正常抽獎
第480次：未中獎 再接再厲，觸發正常抽獎
第481次：貳獎 200元，觸發正常抽獎
第482次：未中獎 再接再厲，觸發正常抽獎
第483次：未中獎 再接再厲，觸發正常抽獎
第484次：未中獎 再接再厲，觸發正常抽獎
第485次：未中獎 再接再厲，觸發正常抽獎
第486次：未中獎 再接再厲，觸發正常抽獎
第487次：未中獎 再接再厲，觸發正常抽獎
第488次：貳獎 200元，觸發正常抽獎
第489次：未中獎 再接再厲，觸發正常抽獎
第490次：未中獎 再接再厲，觸發正常抽獎
第491次：未中獎 再接再厲，觸發正常抽獎
第492次：未中獎 再接再厲，觸發正常抽獎
第493次：未中獎 再接再厲，觸發正常抽獎
第494次：未中獎 再接再厲，觸發正常抽獎
第495次：未中獎 再接再厲，觸發正常抽獎
第496次：未中獎 再接再厲，觸發正常抽獎
第497次：未中獎 再接再厲，觸發正常抽獎
第498次：未中獎 再接再厲，觸發正常抽獎
第499次：未中獎 再接再厲，觸發正常抽獎
第500次：未中獎 再接再厲，觸發正常抽獎
第501次：未中獎 再接再厲，觸發正常抽獎
第502次：未中獎 再接再厲，觸發正常抽獎
第503次：未中獎 再接再厲，觸發正常抽獎
第504次：未中獎 再接再厲，觸發正常抽獎
第505次：未中獎 再接再厲，觸發正常抽獎
第506次：未中獎 再接再厲，觸發正常抽獎
第507次：未中獎 再接再厲，觸發正常抽獎
第508次：貳獎 200元，觸發20抽大保
第509次：未中獎 再接再厲，觸發正常抽獎
第510次：未中獎 再接再厲，觸發正常抽獎
第511次：未中獎 再接再厲，觸發正常抽獎
第512次：未中獎 再接再厲，觸發正常抽獎
第513次：未中獎 再接再厲，觸發正常抽獎
第514次：未中獎 再接再厲，觸發正常抽獎
第515次：未中獎 再接再厲，觸發正常抽獎
第516次：貳獎 200元，觸發正常抽獎
第517次：未中獎 再接再厲，觸發正常抽獎
第518次：未中獎 再接再厲，觸發正常抽獎
第519次：未中獎 再接再厲，觸發正常抽獎
第520次：貳獎 200元，觸發正常抽獎
第521次：未中獎 再接再厲，觸發正常抽獎
第522次：未中獎 再接再厲，觸發正常抽獎
第523次：未中獎 再接再厲，觸發正常抽獎
第524次：貳獎 200元，觸發正常抽獎
第525次：未中獎 再接再厲，觸發正常抽獎
第526次：未中獎 再接再厲，觸發正常抽獎
第527次：未中獎 再接再厲，觸發正常抽獎
第528次：未中獎 再接再厲，觸發正常抽獎
第529次：未中獎 再接再厲，觸發正常抽獎
第530次：未中獎 再接再厲，觸發正常抽獎
第531次：未中獎 再接再厲，觸發正常抽獎
第532次：未中獎 再接再厲，觸發正常抽獎
第533次：貳獎 200元，觸發正常抽獎
第534次：頭獎 500 元，觸發正常抽獎
第535次：未中獎 再接再厲，觸發正常抽獎
第536次：未中獎 再接再厲，觸發正常抽獎
第537次：貳獎 200元，觸發正常抽獎
第538次：未中獎 再接再厲，觸發正常抽獎
第539次：未中獎 再接再厲，觸發正常抽獎
第540次：未中獎 再接再厲，觸發正常抽獎
第541次：貳獎 200元，觸發正常抽獎
第542次：貳獎 200元，觸發正常抽獎
第543次：貳獎 200元，觸發正常抽獎
第544次：未中獎 再接再厲，觸發正常抽獎
第545次：未中獎 再接再厲，觸發正常抽獎
第546次：未中獎 再接再厲，觸發正常抽獎
第547次：貳獎 200元，觸發正常抽獎
第548次：未中獎 再接再厲，觸發正常抽獎
第549次：貳獎 200元，觸發正常抽獎
第550次：未中獎 再接再厲，觸發正常抽獎
第551次：未中獎 再接再厲，觸發正常抽獎
第552次：未中獎 再接再厲，觸發正常抽獎
第553次：未中獎 再接再厲，觸發正常抽獎
第554次：未中獎 再接再厲，觸發正常抽獎
第555次：未中獎 再接再厲，觸發正常抽獎
第556次：貳獎 200元，觸發正常抽獎
第557次：未中獎 再接再厲，觸發正常抽獎
第558次：未中獎 再接再厲，觸發正常抽獎
第559次：未中獎 再接再厲，觸發正常抽獎
第560次：未中獎 再接再厲，觸發正常抽獎
第561次：貳獎 200元，觸發正常抽獎
第562次：貳獎 200元，觸發正常抽獎
第563次：未中獎 再接再厲，觸發正常抽獎
第564次：未中獎 再接再厲，觸發正常抽獎
第565次：未中獎 再接再厲，觸發正常抽獎
第566次：未中獎 再接再厲，觸發正常抽獎
第567次：未中獎 再接再厲，觸發正常抽獎
第568次：未中獎 再接再厲，觸發正常抽獎
第569次：未中獎 再接再厲，觸發正常抽獎
第570次：未中獎 再接再厲，觸發正常抽獎
第571次：未中獎 再接再厲，觸發正常抽獎
第572次：貳獎 200元，觸發正常抽獎
第573次：未中獎 再接再厲，觸發正常抽獎
第574次：未中獎 再接再厲，觸發正常抽獎
第575次：未中獎 再接再厲，觸發正常抽獎
第576次：未中獎 再接再厲，觸發正常抽獎
第577次：未中獎 再接再厲，觸發正常抽獎
第578次：未中獎 再接再厲，觸發正常抽獎
第579次：貳獎 200元，觸發正常抽獎
第580次：未中獎 再接再厲，觸發正常抽獎
第581次：未中獎 再接再厲，觸發正常抽獎
第582次：未中獎 再接再厲，觸發正常抽獎
第583次：未中獎 再接再厲，觸發正常抽獎
第584次：未中獎 再接再厲，觸發正常抽獎
第585次：頭獎 500 元，觸發正常抽獎
第586次：頭獎 500 元，觸發正常抽獎
第587次：貳獎 200元，觸發正常抽獎
第588次：貳獎 200元，觸發正常抽獎
第589次：未中獎 再接再厲，觸發正常抽獎
第590次：未中獎 再接再厲，觸發正常抽獎
第591次：未中獎 再接再厲，觸發正常抽獎
第592次：未中獎 再接再厲，觸發正常抽獎
第593次：未中獎 再接再厲，觸發正常抽獎
第594次：未中獎 再接再厲，觸發正常抽獎
第595次：未中獎 再接再厲，觸發正常抽獎
第596次：未中獎 再接再厲，觸發正常抽獎
第597次：未中獎 再接再厲，觸發正常抽獎
第598次：未中獎 再接再厲，觸發正常抽獎
第599次：未中獎 再接再厲，觸發正常抽獎
第600次：未中獎 再接再厲，觸發正常抽獎
第601次：頭獎 500 元，觸發正常抽獎
第602次：未中獎 再接再厲，觸發正常抽獎
第603次：未中獎 再接再厲，觸發正常抽獎
第604次：未中獎 再接再厲，觸發正常抽獎
第605次：未中獎 再接再厲，觸發正常抽獎
第606次：未中獎 再接再厲，觸發正常抽獎
第607次：未中獎 再接再厲，觸發正常抽獎
第608次：未中獎 再接再厲，觸發正常抽獎
第609次：未中獎 再接再厲，觸發正常抽獎
第610次：未中獎 再接再厲，觸發正常抽獎
第611次：未中獎 再接再厲，觸發正常抽獎
第612次：貳獎 200元，觸發正常抽獎
第613次：貳獎 200元，觸發正常抽獎
第614次：未中獎 再接再厲，觸發正常抽獎
第615次：未中獎 再接再厲，觸發正常抽獎
第616次：未中獎 再接再厲，觸發正常抽獎
第617次：未中獎 再接再厲，觸發正常抽獎
第618次：貳獎 200元，觸發正常抽獎
第619次：未中獎 再接再厲，觸發正常抽獎
第620次：貳獎 200元，觸發正常抽獎
第621次：未中獎 再接再厲，觸發正常抽獎
第622次：未中獎 再接再厲，觸發正常抽獎
第623次：未中獎 再接再厲，觸發正常抽獎
第624次：貳獎 200元，觸發正常抽獎
第625次：未中獎 再接再厲，觸發正常抽獎
第626次：未中獎 再接再厲，觸發正常抽獎
第627次：未中獎 再接再厲，觸發正常抽獎
第628次：未中獎 再接再厲，觸發正常抽獎
第629次：未中獎 再接再厲，觸發正常抽獎
第630次：未中獎 再接再厲，觸發正常抽獎
第631次：未中獎 再接再厲，觸發正常抽獎
第632次：未中獎 再接再厲，觸發正常抽獎
第633次：未中獎 再接再厲，觸發正常抽獎
第634次：未中獎 再接再厲，觸發正常抽獎
第635次：未中獎 再接再厲，觸發正常抽獎
第636次：未中獎 再接再厲，觸發正常抽獎
第637次：未中獎 再接再厲，觸發正常抽獎
第638次：未中獎 再接再厲，觸發正常抽獎
第639次：未中獎 再接再厲，觸發正常抽獎
第640次：未中獎 再接再厲，觸發正常抽獎
第641次：未中獎 再接再厲，觸發正常抽獎
第642次：未中獎 再接再厲，觸發正常抽獎
第643次：貳獎 200元，觸發正常抽獎
第644次：未中獎 再接再厲，觸發正常抽獎
第645次：貳獎 200元，觸發正常抽獎
第646次：未中獎 再接再厲，觸發正常抽獎
第647次：未中獎 再接再厲，觸發正常抽獎
第648次：未中獎 再接再厲，觸發正常抽獎
第649次：未中獎 再接再厲，觸發正常抽獎
第650次：未中獎 再接再厲，觸發正常抽獎
第651次：未中獎 再接再厲，觸發正常抽獎
第652次：未中獎 再接再厲，觸發正常抽獎
第653次：未中獎 再接再厲，觸發正常抽獎
第654次：未中獎 再接再厲，觸發正常抽獎
第655次：頭獎 500 元，觸發正常抽獎
第656次：未中獎 再接再厲，觸發正常抽獎
第657次：未中獎 再接再厲，觸發正常抽獎
第658次：頭獎 500 元，觸發正常抽獎
第659次：未中獎 再接再厲，觸發正常抽獎
第660次：貳獎 200元，觸發正常抽獎
第661次：頭獎 500 元，觸發正常抽獎
第662次：未中獎 再接再厲，觸發正常抽獎
第663次：未中獎 再接再厲，觸發正常抽獎
第664次：未中獎 再接再厲，觸發正常抽獎
第665次：未中獎 再接再厲，觸發正常抽獎
第666次：未中獎 再接再厲，觸發正常抽獎
第667次：未中獎 再接再厲，觸發正常抽獎
第668次：未中獎 再接再厲，觸發正常抽獎
第669次：未中獎 再接再厲，觸發正常抽獎
第670次：未中獎 再接再厲，觸發正常抽獎
第671次：未中獎 再接再厲，觸發正常抽獎
第672次：未中獎 再接再厲，觸發正常抽獎
第673次：未中獎 再接再厲，觸發正常抽獎
第674次：未中獎 再接再厲，觸發正常抽獎
第675次：未中獎 再接再厲，觸發正常抽獎
第676次：未中獎 再接再厲，觸發正常抽獎
第677次：貳獎 200元，觸發正常抽獎
第678次：未中獎 再接再厲，觸發正常抽獎
第679次：未中獎 再接再厲，觸發正常抽獎
第680次：未中獎 再接再厲，觸發正常抽獎
第681次：未中獎 再接再厲，觸發正常抽獎
第682次：未中獎 再接再厲，觸發正常抽獎
第683次：未中獎 再接再厲，觸發正常抽獎
第684次：未中獎 再接再厲，觸發正常抽獎
第685次：未中獎 再接再厲，觸發正常抽獎
第686次：未中獎 再接再厲，觸發正常抽獎
第687次：未中獎 再接再厲，觸發正常抽獎
第688次：未中獎 再接再厲，觸發正常抽獎
第689次：未中獎 再接再厲，觸發正常抽獎
第690次：未中獎 再接再厲，觸發正常抽獎
第691次：未中獎 再接再厲，觸發正常抽獎
第692次：貳獎 200元，觸發正常抽獎
第693次：未中獎 再接再厲，觸發正常抽獎
第694次：未中獎 再接再厲，觸發正常抽獎
第695次：未中獎 再接再厲，觸發正常抽獎
第696次：未中獎 再接再厲，觸發正常抽獎
第697次：未中獎 再接再厲，觸發正常抽獎
第698次：未中獎 再接再厲，觸發正常抽獎
第699次：未中獎 再接再厲，觸發正常抽獎
第700次：未中獎 再接再厲，觸發正常抽獎
第701次：未中獎 再接再厲，觸發正常抽獎
第702次：未中獎 再接再厲，觸發正常抽獎
第703次：未中獎 再接再厲，觸發正常抽獎
第704次：未中獎 再接再厲，觸發正常抽獎
第705次：未中獎 再接再厲，觸發正常抽獎
第706次：未中獎 再接再厲，觸發正常抽獎
第707次：未中獎 再接再厲，觸發正常抽獎
第708次：未中獎 再接再厲，觸發正常抽獎
第709次：未中獎 再接再厲，觸發正常抽獎
第710次：未中獎 再接再厲，觸發正常抽獎
第711次：未中獎 再接再厲，觸發正常抽獎
第712次：頭獎 500 元，觸發20抽大保
第713次：未中獎 再接再厲，觸發正常抽獎
第714次：未中獎 再接再厲，觸發正常抽獎
第715次：未中獎 再接再厲，觸發正常抽獎
第716次：未中獎 再接再厲，觸發正常抽獎
第717次：未中獎 再接再厲，觸發正常抽獎
第718次：未中獎 再接再厲，觸發正常抽獎
第719次：未中獎 再接再厲，觸發正常抽獎
第720次：未中獎 再接再厲，觸發正常抽獎
第721次：未中獎 再接再厲，觸發正常抽獎
第722次：貳獎 200元，觸發正常抽獎
第723次：未中獎 再接再厲，觸發正常抽獎
第724次：未中獎 再接再厲，觸發正常抽獎
第725次：未中獎 再接再厲，觸發正常抽獎
第726次：未中獎 再接再厲，觸發正常抽獎
第727次：未中獎 再接再厲，觸發正常抽獎
第728次：貳獎 200元，觸發正常抽獎
第729次：未中獎 再接再厲，觸發正常抽獎
第730次：未中獎 再接再厲，觸發正常抽獎
第731次：未中獎 再接再厲，觸發正常抽獎
第732次：未中獎 再接再厲，觸發正常抽獎
第733次：未中獎 再接再厲，觸發正常抽獎
第734次：貳獎 200元，觸發正常抽獎
第735次：未中獎 再接再厲，觸發正常抽獎
第736次：未中獎 再接再厲，觸發正常抽獎
第737次：未中獎 再接再厲，觸發正常抽獎
第738次：未中獎 再接再厲，觸發正常抽獎
第739次：未中獎 再接再厲，觸發正常抽獎
第740次：未中獎 再接再厲，觸發正常抽獎
第741次：未中獎 再接再厲，觸發正常抽獎
第742次：未中獎 再接再厲，觸發正常抽獎
第743次：貳獎 200元，觸發正常抽獎
第744次：貳獎 200元，觸發正常抽獎
第745次：貳獎 200元，觸發正常抽獎
第746次：貳獎 200元，觸發正常抽獎
第747次：未中獎 再接再厲，觸發正常抽獎
第748次：頭獎 500 元，觸發正常抽獎
第749次：未中獎 再接再厲，觸發正常抽獎
第750次：未中獎 再接再厲，觸發正常抽獎
第751次：未中獎 再接再厲，觸發正常抽獎
第752次：未中獎 再接再厲，觸發正常抽獎
第753次：貳獎 200元，觸發正常抽獎
第754次：貳獎 200元，觸發正常抽獎
第755次：未中獎 再接再厲，觸發正常抽獎
第756次：未中獎 再接再厲，觸發正常抽獎
第757次：未中獎 再接再厲，觸發正常抽獎
第758次：未中獎 再接再厲，觸發正常抽獎
第759次：未中獎 再接再厲，觸發正常抽獎
第760次：未中獎 再接再厲，觸發正常抽獎
第761次：未中獎 再接再厲，觸發正常抽獎
第762次：未中獎 再接再厲，觸發正常抽獎
第763次：未中獎 再接再厲，觸發正常抽獎
第764次：貳獎 200元，觸發正常抽獎
第765次：貳獎 200元，觸發正常抽獎
第766次：未中獎 再接再厲，觸發正常抽獎
第767次：未中獎 再接再厲，觸發正常抽獎
第768次：未中獎 再接再厲，觸發正常抽獎
第769次：未中獎 再接再厲，觸發正常抽獎
第770次：未中獎 再接再厲，觸發正常抽獎
第771次：未中獎 再接再厲，觸發正常抽獎
第772次：未中獎 再接再厲，觸發正常抽獎
第773次：未中獎 再接再厲，觸發正常抽獎
第774次：未中獎 再接再厲，觸發正常抽獎
第775次：未中獎 再接再厲，觸發正常抽獎
第776次：頭獎 500 元，觸發正常抽獎
第777次：未中獎 再接再厲，觸發正常抽獎
第778次：未中獎 再接再厲，觸發正常抽獎
第779次：未中獎 再接再厲，觸發正常抽獎
第780次：貳獎 200元，觸發正常抽獎
第781次：未中獎 再接再厲，觸發正常抽獎
第782次：未中獎 再接再厲，觸發正常抽獎
第783次：未中獎 再接再厲，觸發正常抽獎
第784次：未中獎 再接再厲，觸發正常抽獎
第785次：未中獎 再接再厲，觸發正常抽獎
第786次：頭獎 500 元，觸發正常抽獎
第787次：未中獎 再接再厲，觸發正常抽獎
第788次：未中獎 再接再厲，觸發正常抽獎
第789次：未中獎 再接再厲，觸發正常抽獎
第790次：未中獎 再接再厲，觸發正常抽獎
第791次：未中獎 再接再厲，觸發正常抽獎
第792次：未中獎 再接再厲，觸發正常抽獎
第793次：頭獎 500 元，觸發正常抽獎
第794次：貳獎 200元，觸發正常抽獎
第795次：未中獎 再接再厲，觸發正常抽獎
第796次：頭獎 500 元，觸發正常抽獎
第797次：未中獎 再接再厲，觸發正常抽獎
第798次：未中獎 再接再厲，觸發正常抽獎
第799次：未中獎 再接再厲，觸發正常抽獎
第800次：頭獎 500 元，觸發正常抽獎
第801次：未中獎 再接再厲，觸發正常抽獎
第802次：未中獎 再接再厲，觸發正常抽獎
第803次：未中獎 再接再厲，觸發正常抽獎
第804次：未中獎 再接再厲，觸發正常抽獎
第805次：未中獎 再接再厲，觸發正常抽獎
第806次：未中獎 再接再厲，觸發正常抽獎
第807次：未中獎 再接再厲，觸發正常抽獎
第808次：未中獎 再接再厲，觸發正常抽獎
第809次：未中獎 再接再厲，觸發正常抽獎
第810次：未中獎 再接再厲，觸發正常抽獎
第811次：未中獎 再接再厲，觸發正常抽獎
第812次：未中獎 再接再厲，觸發正常抽獎
第813次：未中獎 再接再厲，觸發正常抽獎
第814次：未中獎 再接再厲，觸發正常抽獎
第815次：未中獎 再接再厲，觸發正常抽獎
第816次：未中獎 再接再厲，觸發正常抽獎
第817次：未中獎 再接再厲，觸發正常抽獎
第818次：未中獎 再接再厲，觸發正常抽獎
第819次：未中獎 再接再厲，觸發正常抽獎
第820次：頭獎 500 元，觸發20抽大保
第821次：未中獎 再接再厲，觸發正常抽獎
第822次：未中獎 再接再厲，觸發正常抽獎
第823次：未中獎 再接再厲，觸發正常抽獎
第824次：未中獎 再接再厲，觸發正常抽獎
第825次：貳獎 200元，觸發正常抽獎
第826次：未中獎 再接再厲，觸發正常抽獎
第827次：未中獎 再接再厲，觸發正常抽獎
第828次：未中獎 再接再厲，觸發正常抽獎
第829次：未中獎 再接再厲，觸發正常抽獎
第830次：未中獎 再接再厲，觸發正常抽獎
第831次：未中獎 再接再厲，觸發正常抽獎
第832次：未中獎 再接再厲，觸發正常抽獎
第833次：未中獎 再接再厲，觸發正常抽獎
第834次：未中獎 再接再厲，觸發正常抽獎
第835次：頭獎 500 元，觸發正常抽獎
第836次：未中獎 再接再厲，觸發正常抽獎
第837次：未中獎 再接再厲，觸發正常抽獎
第838次：未中獎 再接再厲，觸發正常抽獎
第839次：未中獎 再接再厲，觸發正常抽獎
第840次：未中獎 再接再厲，觸發正常抽獎
第841次：未中獎 再接再厲，觸發正常抽獎
第842次：未中獎 再接再厲，觸發正常抽獎
第843次：未中獎 再接再厲，觸發正常抽獎
第844次：未中獎 再接再厲，觸發正常抽獎
第845次：未中獎 再接再厲，觸發正常抽獎
第846次：貳獎 200元，觸發正常抽獎
第847次：貳獎 200元，觸發正常抽獎
第848次：未中獎 再接再厲，觸發正常抽獎
第849次：未中獎 再接再厲，觸發正常抽獎
第850次：未中獎 再接再厲，觸發正常抽獎
第851次：未中獎 再接再厲，觸發正常抽獎
第852次：未中獎 再接再厲，觸發正常抽獎
第853次：未中獎 再接再厲，觸發正常抽獎
第854次：未中獎 再接再厲，觸發正常抽獎
第855次：未中獎 再接再厲，觸發正常抽獎
第856次：未中獎 再接再厲，觸發正常抽獎
第857次：貳獎 200元，觸發正常抽獎
第858次：未中獎 再接再厲，觸發正常抽獎
第859次：貳獎 200元，觸發正常抽獎
第860次：未中獎 再接再厲，觸發正常抽獎
第861次：未中獎 再接再厲，觸發正常抽獎
第862次：貳獎 200元，觸發正常抽獎
第863次：未中獎 再接再厲，觸發正常抽獎
第864次：貳獎 200元，觸發正常抽獎
第865次：貳獎 200元，觸發正常抽獎
第866次：未中獎 再接再厲，觸發正常抽獎
第867次：貳獎 200元，觸發正常抽獎
第868次：未中獎 再接再厲，觸發正常抽獎
第869次：未中獎 再接再厲，觸發正常抽獎
第870次：未中獎 再接再厲，觸發正常抽獎
第871次：未中獎 再接再厲，觸發正常抽獎
第872次：未中獎 再接再厲，觸發正常抽獎
第873次：未中獎 再接再厲，觸發正常抽獎
第874次：貳獎 200元，觸發正常抽獎
第875次：貳獎 200元，觸發正常抽獎
第876次：貳獎 200元，觸發正常抽獎
第877次：未中獎 再接再厲，觸發正常抽獎
第878次：未中獎 再接再厲，觸發正常抽獎
第879次：未中獎 再接再厲，觸發正常抽獎
第880次：未中獎 再接再厲，觸發正常抽獎
第881次：未中獎 再接再厲，觸發正常抽獎
第882次：未中獎 再接再厲，觸發正常抽獎
第883次：未中獎 再接再厲，觸發正常抽獎
第884次：未中獎 再接再厲，觸發正常抽獎
第885次：未中獎 再接再厲，觸發正常抽獎
第886次：未中獎 再接再厲，觸發正常抽獎
第887次：未中獎 再接再厲，觸發正常抽獎
第888次：頭獎 500 元，觸發正常抽獎
第889次：未中獎 再接再厲，觸發正常抽獎
第890次：未中獎 再接再厲，觸發正常抽獎
第891次：未中獎 再接再厲，觸發正常抽獎
第892次：未中獎 再接再厲，觸發正常抽獎
第893次：頭獎 500 元，觸發正常抽獎
第894次：未中獎 再接再厲，觸發正常抽獎
第895次：未中獎 再接再厲，觸發正常抽獎
第896次：未中獎 再接再厲，觸發正常抽獎
第897次：貳獎 200元，觸發正常抽獎
第898次：未中獎 再接再厲，觸發正常抽獎
第899次：未中獎 再接再厲，觸發正常抽獎
第900次：未中獎 再接再厲，觸發正常抽獎
第901次：頭獎 500 元，觸發正常抽獎
第902次：未中獎 再接再厲，觸發正常抽獎
第903次：未中獎 再接再厲，觸發正常抽獎
第904次：未中獎 再接再厲，觸發正常抽獎
第905次：頭獎 500 元，觸發正常抽獎
第906次：貳獎 200元，觸發正常抽獎
第907次：未中獎 再接再厲，觸發正常抽獎
第908次：未中獎 再接再厲，觸發正常抽獎
第909次：未中獎 再接再厲，觸發正常抽獎
第910次：頭獎 500 元，觸發正常抽獎
第911次：未中獎 再接再厲，觸發正常抽獎
第912次：未中獎 再接再厲，觸發正常抽獎
第913次：未中獎 再接再厲，觸發正常抽獎
第914次：未中獎 再接再厲，觸發正常抽獎
第915次：未中獎 再接再厲，觸發正常抽獎
第916次：未中獎 再接再厲，觸發正常抽獎

    樣本數 單次遊玩獎金期望值估計   標準誤   CI下界   CI上界
0  5000       42.82  1.63  39.62  46.02

帳號：1，已存在玩家資料
目前狀態：非新手期，您不具有新手保底
開始遊玩5000次
第1次：未中獎 再接再厲，觸發正常抽獎
第2次：未中獎 再接再厲，觸發正常抽獎
第3次：貳獎 200元，觸發正常抽獎
第4次：未中獎 再接再厲，觸發正常抽獎
第5次：未中獎 再接再厲，觸發正常抽獎
第6次：未中獎 再接再厲，觸發正常抽獎
第7次：未中獎 再接再厲，觸發正常抽獎
第8次：未中獎 再接再厲，觸發正常抽獎
第9次：未中獎 再接再厲，觸發正常抽獎
第10次：未中獎 再接再厲，觸發正常抽獎
第11次：未中獎 再接再厲，觸發正常抽獎
第12次：未中獎 再接再厲，觸發正常抽獎
第13次：未中獎 再接再厲，觸發正常抽獎
第14次：未中獎 再接再厲，觸發正常抽獎
第15次：未中獎 再接再厲，觸發正常抽獎
第16次：未中獎 再接再厲，觸發正常抽獎
第17次：未中獎 再接再厲，觸發正常抽獎
第18次：未中獎 再接再厲，觸發正常抽獎
第19次：未中獎 再接再厲，觸發正常抽獎
第20次：未中獎 再接再厲，觸發正常抽獎
第21次：未中獎 再接再厲，觸發正常抽獎
第22次：未中獎 再接再厲，觸發正常抽獎
第23次：頭獎 500 元，觸發20抽大保
第24次：未中獎 再接再厲，觸發正常抽獎
第25次：未中獎 再接再厲，觸發正常抽獎
第26次：未中獎 再接再厲，觸發正常抽獎
第27次：未中獎 再接再厲，觸發正常抽獎
第28次：頭獎 500 元，觸發正常抽獎
第29次：未中獎 再接再厲，觸發正常抽獎
第30次：未中獎 再接再厲，觸發正常抽獎
第31次：未中獎 再接再厲，觸發正常抽獎
第32次：未中獎 再接再厲，觸發正常抽獎
第33次：未中獎 再接再厲，觸發正常抽獎
第34次：未中獎 再接再厲，觸發正常抽獎
第35次：未中獎 再接再厲，觸發正常抽獎
第36次：未中獎 再接再厲，觸發正常抽獎
第37次：貳獎 200元，觸發正常抽獎
第38次：未中獎 再接再厲，觸發正常抽獎
第39次：未中獎 再接再厲，觸發正常抽獎
第40次：頭獎 500 元，觸發正常抽獎
第41次：未中獎 再接再厲，觸發正常抽獎
第42次：未中獎 再接再厲，觸發正常抽獎
第43次：未中獎 再接再厲，觸發正常抽獎
第44次：未中獎 再接再厲，觸發正常抽獎
第45次：貳獎 200元，觸發正常抽獎
第46次：未中獎 再接再厲，觸發正常抽獎
第47次：未中獎 再接再厲，觸發正常抽獎
第48次：未中獎 再接再厲，觸發正常抽獎
第49次：未中獎 再接再厲，觸發正常抽獎
第50次：未中獎 再接再厲，觸發正常抽獎
第51次：未中獎 再接再厲，觸發正常抽獎
第52次：未中獎 再接再厲，觸發正常抽獎
第53次：貳獎 200元，觸發正常抽獎
第54次：未中獎 再接再厲，觸發正常抽獎
第55次：未中獎 再接再厲，觸發正常抽獎
第56次：未中獎 再接再厲，觸發正常抽獎
第57次：貳獎 200元，觸發正常抽獎
第58次：未中獎 再接再厲，觸發正常抽獎
第59次：未中獎 再接再厲，觸發正常抽獎
第60次：未中獎 再接再厲，觸發正常抽獎
第61次：未中獎 再接再厲，觸發正常抽獎
第62次：未中獎 再接再厲，觸發正常抽獎
第63次：未中獎 再接再厲，觸發正常抽獎
第64次：未中獎 再接再厲，觸發正常抽獎
第65次：未中獎 再接再厲，觸發正常抽獎
第66次：貳獎 200元，觸發正常抽獎
第67次：未中獎 再接再厲，觸發正常抽獎
第68次：未中獎 再接再厲，觸發正常抽獎
第69次：未中獎 再接再厲，觸發正常抽獎
第70次：未中獎 再接再厲，觸發正常抽獎
第71次：未中獎 再接再厲，觸發正常抽獎
第72次：未中獎 再接再厲，觸發正常抽獎
第73次：未中獎 再接再厲，觸發正常抽獎
第74次：未中獎 再接再厲，觸發正常抽獎
第75次：貳獎 200元，觸發正常抽獎
第76次：未中獎 再接再厲，觸發正常抽獎
第77次：未中獎 再接再厲，觸發正常抽獎
第78次：未中獎 再接再厲，觸發正常抽獎
第79次：未中獎 再接再厲，觸發正常抽獎
第80次：頭獎 500 元，觸發正常抽獎
第81次：未中獎 再接再厲，觸發正常抽獎
第82次：未中獎 再接再厲，觸發正常抽獎
第83次：未中獎 再接再厲，觸發正常抽獎
第84次：未中獎 再接再厲，觸發正常抽獎
第85次：頭獎 500 元，觸發正常抽獎
第86次：貳獎 200元，觸發正常抽獎
第87次：未中獎 再接再厲，觸發正常抽獎
第88次：未中獎 再接再厲，觸發正常抽獎
第89次：未中獎 再接再厲，觸發正常抽獎
第90次：未中獎 再接再厲，觸發正常抽獎
第91次：頭獎 500 元，觸發正常抽獎
第92次：未中獎 再接再厲，觸發正常抽獎
第93次：未中獎 再接再厲，觸發正常抽獎
第94次：未中獎 再接再厲，觸發正常抽獎
第95次：未中獎 再接再厲，觸發正常抽獎
第96次：未中獎 再接再厲，觸發正常抽獎
第97次：未中獎 再接再厲，觸發正常抽獎
第98次：未中獎 再接再厲，觸發正常抽獎
第99次：未中獎 再接再厲，觸發正常抽獎
第100次：未中獎 再接再厲，觸發正常抽獎
第101次：未中獎 再接再厲，觸發正常抽獎
第102次：未中獎 再接再厲，觸發正常抽獎
第103次：貳獎 200元，觸發正常抽獎
第104次：未中獎 再接再厲，觸發正常抽獎
第105次：未中獎 再接再厲，觸發正常抽獎
第106次：未中獎 再接再厲，觸發正常抽獎
第107次：未中獎 再接再厲，觸發正常抽獎
第108次：未中獎 再接再厲，觸發正常抽獎
第109次：未中獎 再接再厲，觸發正常抽獎
第110次：未中獎 再接再厲，觸發正常抽獎
第111次：未中獎 再接再厲，觸發正常抽獎
第112次：未中獎 再接再厲，觸發正常抽獎
第113次：未中獎 再接再厲，觸發正常抽獎
第114次：未中獎 再接再厲，觸發正常抽獎
第115次：未中獎 再接再厲，觸發正常抽獎
第116次：未中獎 再接再厲，觸發正常抽獎
第117次：未中獎 再接再厲，觸發正常抽獎
第118次：未中獎 再接再厲，觸發正常抽獎
第119次：未中獎 再接再厲，觸發正常抽獎
第120次：貳獎 200元，觸發正常抽獎
第121次：未中獎 再接再厲，觸發正常抽獎
第122次：未中獎 再接再厲，觸發正常抽獎
第123次：未中獎 再接再厲，觸發正常抽獎
第124次：未中獎 再接再厲，觸發正常抽獎
第125次：未中獎 再接再厲，觸發正常抽獎
第126次：未中獎 再接再厲，觸發正常抽獎
第127次：未中獎 再接再厲，觸發正常抽獎
第128次：未中獎 再接再厲，觸發正常抽獎
第129次：未中獎 再接再厲，觸發正常抽獎
第130次：未中獎 再接再厲，觸發正常抽獎
第131次：未中獎 再接再厲，觸發正常抽獎
第132次：未中獎 再接再厲，觸發正常抽獎
第133次：未中獎 再接再厲，觸發正常抽獎
第134次：未中獎 再接再厲，觸發正常抽獎
第135次：未中獎 再接再厲，觸發正常抽獎
第136次：未中獎 再接再厲，觸發正常抽獎
第137次：未中獎 再接再厲，觸發正常抽獎
第138次：貳獎 200元，觸發正常抽獎
第139次：未中獎 再接再厲，觸發正常抽獎
第140次：未中獎 再接再厲，觸發正常抽獎
第141次：頭獎 500 元，觸發正常抽獎
第142次：未中獎 再接再厲，觸發正常抽獎
第143次：未中獎 再接再厲，觸發正常抽獎
第144次：未中獎 再接再厲，觸發正常抽獎
第145次：未中獎 再接再厲，觸發正常抽獎
第146次：未中獎 再接再厲，觸發正常抽獎
第147次：未中獎 再接再厲，觸發正常抽獎
第148次：未中獎 再接再厲，觸發正常抽獎
第149次：未中獎 再接再厲，觸發正常抽獎
第150次：未中獎 再接再厲，觸發正常抽獎
第151次：未中獎 再接再厲，觸發正常抽獎
第152次：未中獎 再接再厲，觸發正常抽獎
第153次：未中獎 再接再厲，觸發正常抽獎
第154次：未中獎 再接再厲，觸發正常抽獎
第155次：未中獎 再接再厲，觸發正常抽獎
第156次：未中獎 再接再厲，觸發正常抽獎
第157次：未中獎 再接再厲，觸發正常抽獎
第158次：未中獎 再接再厲，觸發正常抽獎
第159次：未中獎 再接再厲，觸發正常抽獎
第160次：未中獎 再接再厲，觸發正常抽獎
第161次：貳獎 200元，觸發20抽大保
第162次：未中獎 再接再厲，觸發正常抽獎
第163次：未中獎 再接再厲，觸發正常抽獎
第164次：未中獎 再接再厲，觸發正常抽獎
第165次：未中獎 再接再厲，觸發正常抽獎
第166次：未中獎 再接再厲，觸發正常抽獎
第167次：未中獎 再接再厲，觸發正常抽獎
第168次：未中獎 再接再厲，觸發正常抽獎
第169次：未中獎 再接再厲，觸發正常抽獎
第170次：未中獎 再接再厲，觸發正常抽獎
第171次：未中獎 再接再厲，觸發正常抽獎
第172次：未中獎 再接再厲，觸發正常抽獎
第173次：未中獎 再接再厲，觸發正常抽獎
第174次：未中獎 再接再厲，觸發正常抽獎
第175次：未中獎 再接再厲，觸發正常抽獎
第176次：未中獎 再接再厲，觸發正常抽獎
第177次：未中獎 再接再厲，觸發正常抽獎
第178次：未中獎 再接再厲，觸發正常抽獎
第179次：未中獎 再接再厲，觸發正常抽獎
第180次：未中獎 再接再厲，觸發正常抽獎
第181次：貳獎 200元，觸發20抽大保
第182次：未中獎 再接再厲，觸發正常抽獎
第183次：未中獎 再接再厲，觸發正常抽獎
第184次：未中獎 再接再厲，觸發正常抽獎
第185次：未中獎 再接再厲，觸發正常抽獎
第186次：未中獎 再接再厲，觸發正常抽獎
第187次：未中獎 再接再厲，觸發正常抽獎
第188次：未中獎 再接再厲，觸發正常抽獎
第189次：未中獎 再接再厲，觸發正常抽獎
第190次：未中獎 再接再厲，觸發正常抽獎
第191次：未中獎 再接再厲，觸發正常抽獎
第192次：未中獎 再接再厲，觸發正常抽獎
第193次：未中獎 再接再厲，觸發正常抽獎
第194次：貳獎 200元，觸發正常抽獎
第195次：未中獎 再接再厲，觸發正常抽獎
第196次：未中獎 再接再厲，觸發正常抽獎
第197次：未中獎 再接再厲，觸發正常抽獎
第198次：未中獎 再接再厲，觸發正常抽獎
第199次：未中獎 再接再厲，觸發正常抽獎
第200次：未中獎 再接再厲，觸發正常抽獎
第201次：未中獎 再接再厲，觸發正常抽獎
第202次：未中獎 再接再厲，觸發正常抽獎
第203次：未中獎 再接再厲，觸發正常抽獎
第204次：未中獎 再接再厲，觸發正常抽獎
第205次：未中獎 再接再厲，觸發正常抽獎
第206次：貳獎 200元，觸發正常抽獎
第207次：未中獎 再接再厲，觸發正常抽獎
第208次：未中獎 再接再厲，觸發正常抽獎
第209次：貳獎 200元，觸發正常抽獎
第210次：未中獎 再接再厲，觸發正常抽獎
第211次：未中獎 再接再厲，觸發正常抽獎
第212次：未中獎 再接再厲，觸發正常抽獎
第213次：未中獎 再接再厲，觸發正常抽獎
第214次：未中獎 再接再厲，觸發正常抽獎
第215次：頭獎 500 元，觸發正常抽獎
第216次：貳獎 200元，觸發正常抽獎
第217次：未中獎 再接再厲，觸發正常抽獎
第218次：貳獎 200元，觸發正常抽獎
第219次：未中獎 再接再厲，觸發正常抽獎
第220次：未中獎 再接再厲，觸發正常抽獎
第221次：未中獎 再接再厲，觸發正常抽獎
第222次：未中獎 再接再厲，觸發正常抽獎
第223次：未中獎 再接再厲，觸發正常抽獎
第224次：頭獎 500 元，觸發正常抽獎
第225次：未中獎 再接再厲，觸發正常抽獎
第226次：未中獎 再接再厲，觸發正常抽獎
第227次：未中獎 再接再厲，觸發正常抽獎
第228次：未中獎 再接再厲，觸發正常抽獎
第229次：貳獎 200元，觸發正常抽獎
第230次：未中獎 再接再厲，觸發正常抽獎
第231次：未中獎 再接再厲，觸發正常抽獎
第232次：未中獎 再接再厲，觸發正常抽獎
第233次：貳獎 200元，觸發正常抽獎
第234次：未中獎 再接再厲，觸發正常抽獎
第235次：未中獎 再接再厲，觸發正常抽獎
第236次：頭獎 500 元，觸發正常抽獎
第237次：頭獎 500 元，觸發正常抽獎
第238次：未中獎 再接再厲，觸發正常抽獎
第239次：未中獎 再接再厲，觸發正常抽獎
第240次：未中獎 再接再厲，觸發正常抽獎
第241次：未中獎 再接再厲，觸發正常抽獎
第242次：未中獎 再接再厲，觸發正常抽獎
第243次：未中獎 再接再厲，觸發正常抽獎
第244次：未中獎 再接再厲，觸發正常抽獎
第245次：未中獎 再接再厲，觸發正常抽獎
第246次：未中獎 再接再厲，觸發正常抽獎
第247次：未中獎 再接再厲，觸發正常抽獎
第248次：未中獎 再接再厲，觸發正常抽獎
第249次：未中獎 再接再厲，觸發正常抽獎
第250次：未中獎 再接再厲，觸發正常抽獎
第251次：未中獎 再接再厲，觸發正常抽獎
第252次：貳獎 200元，觸發正常抽獎
第253次：未中獎 再接再厲，觸發正常抽獎
第254次：未中獎 再接再厲，觸發正常抽獎
第255次：未中獎 再接再厲，觸發正常抽獎
第256次：未中獎 再接再厲，觸發正常抽獎
第257次：貳獎 200元，觸發正常抽獎
第258次：未中獎 再接再厲，觸發正常抽獎
第259次：未中獎 再接再厲，觸發正常抽獎
第260次：未中獎 再接再厲，觸發正常抽獎
第261次：未中獎 再接再厲，觸發正常抽獎
第262次：未中獎 再接再厲，觸發正常抽獎
第263次：未中獎 再接再厲，觸發正常抽獎
第264次：未中獎 再接再厲，觸發正常抽獎
第265次：貳獎 200元，觸發正常抽獎
第266次：未中獎 再接再厲，觸發正常抽獎
第267次：未中獎 再接再厲，觸發正常抽獎
第268次：未中獎 再接再厲，觸發正常抽獎
第269次：未中獎 再接再厲，觸發正常抽獎
第270次：未中獎 再接再厲，觸發正常抽獎
第271次：未中獎 再接再厲，觸發正常抽獎
第272次：頭獎 500 元，觸發正常抽獎
第273次：未中獎 再接再厲，觸發正常抽獎
第274次：未中獎 再接再厲，觸發正常抽獎
第275次：未中獎 再接再厲，觸發正常抽獎
第276次：未中獎 再接再厲，觸發正常抽獎
第277次：未中獎 再接再厲，觸發正常抽獎
第278次：未中獎 再接再厲，觸發正常抽獎
第279次：未中獎 再接再厲，觸發正常抽獎
第280次：未中獎 再接再厲，觸發正常抽獎
第281次：未中獎 再接再厲，觸發正常抽獎
第282次：未中獎 再接再厲，觸發正常抽獎
第283次：未中獎 再接再厲，觸發正常抽獎
第284次：頭獎 500 元，觸發正常抽獎
第285次：未中獎 再接再厲，觸發正常抽獎
第286次：未中獎 再接再厲，觸發正常抽獎
第287次：未中獎 再接再厲，觸發正常抽獎
第288次：未中獎 再接再厲，觸發正常抽獎
第289次：未中獎 再接再厲，觸發正常抽獎
第290次：貳獎 200元，觸發正常抽獎
第291次：貳獎 200元，觸發正常抽獎
第292次：未中獎 再接再厲，觸發正常抽獎
第293次：未中獎 再接再厲，觸發正常抽獎
第294次：未中獎 再接再厲，觸發正常抽獎
第295次：未中獎 再接再厲，觸發正常抽獎
第296次：未中獎 再接再厲，觸發正常抽獎
第297次：未中獎 再接再厲，觸發正常抽獎
第298次：貳獎 200元，觸發正常抽獎
第299次：頭獎 500 元，觸發正常抽獎
第300次：未中獎 再接再厲，觸發正常抽獎
第301次：未中獎 再接再厲，觸發正常抽獎
第302次：未中獎 再接再厲，觸發正常抽獎
第303次：未中獎 再接再厲，觸發正常抽獎
第304次：未中獎 再接再厲，觸發正常抽獎
第305次：未中獎 再接再厲，觸發正常抽獎
第306次：未中獎 再接再厲，觸發正常抽獎
第307次：未中獎 再接再厲，觸發正常抽獎
第308次：未中獎 再接再厲，觸發正常抽獎
第309次：未中獎 再接再厲，觸發正常抽獎
第310次：頭獎 500 元，觸發正常抽獎
第311次：未中獎 再接再厲，觸發正常抽獎
第312次：頭獎 500 元，觸發正常抽獎
第313次：未中獎 再接再厲，觸發正常抽獎
第314次：貳獎 200元，觸發正常抽獎
第315次：未中獎 再接再厲，觸發正常抽獎
第316次：頭獎 500 元，觸發正常抽獎
第317次：頭獎 500 元，觸發正常抽獎
第318次：未中獎 再接再厲，觸發正常抽獎
第319次：未中獎 再接再厲，觸發正常抽獎
第320次：未中獎 再接再厲，觸發正常抽獎
第321次：未中獎 再接再厲，觸發正常抽獎
第322次：未中獎 再接再厲，觸發正常抽獎
第323次：未中獎 再接再厲，觸發正常抽獎
第324次：頭獎 500 元，觸發正常抽獎
第325次：頭獎 500 元，觸發正常抽獎
第326次：未中獎 再接再厲，觸發正常抽獎
第327次：未中獎 再接再厲，觸發正常抽獎
第328次：未中獎 再接再厲，觸發正常抽獎
第329次：未中獎 再接再厲，觸發正常抽獎
第330次：未中獎 再接再厲，觸發正常抽獎
第331次：未中獎 再接再厲，觸發正常抽獎
第332次：未中獎 再接再厲，觸發正常抽獎
第333次：未中獎 再接再厲，觸發正常抽獎
第334次：未中獎 再接再厲，觸發正常抽獎
第335次：未中獎 再接再厲，觸發正常抽獎
第336次：未中獎 再接再厲，觸發正常抽獎
第337次：貳獎 200元，觸發正常抽獎
第338次：未中獎 再接再厲，觸發正常抽獎
第339次：貳獎 200元，觸發正常抽獎
第340次：貳獎 200元，觸發正常抽獎
第341次：未中獎 再接再厲，觸發正常抽獎
第342次：未中獎 再接再厲，觸發正常抽獎
第343次：未中獎 再接再厲，觸發正常抽獎
第344次：未中獎 再接再厲，觸發正常抽獎
第345次：未中獎 再接再厲，觸發正常抽獎
第346次：未中獎 再接再厲，觸發正常抽獎
第347次：未中獎 再接再厲，觸發正常抽獎
第348次：未中獎 再接再厲，觸發正常抽獎
第349次：未中獎 再接再厲，觸發正常抽獎
第350次：未中獎 再接再厲，觸發正常抽獎
第351次：未中獎 再接再厲，觸發正常抽獎
第352次：未中獎 再接再厲，觸發正常抽獎
第353次：未中獎 再接再厲，觸發正常抽獎
第354次：貳獎 200元，觸發正常抽獎
第355次：未中獎 再接再厲，觸發正常抽獎
第356次：未中獎 再接再厲，觸發正常抽獎
第357次：未中獎 再接再厲，觸發正常抽獎
第358次：未中獎 再接再厲，觸發正常抽獎
第359次：未中獎 再接再厲，觸發正常抽獎
第360次：未中獎 再接再厲，觸發正常抽獎
第361次：未中獎 再接再厲，觸發正常抽獎
第362次：未中獎 再接再厲，觸發正常抽獎
第363次：未中獎 再接再厲，觸發正常抽獎
第364次：頭獎 500 元，觸發正常抽獎
第365次：未中獎 再接再厲，觸發正常抽獎
第366次：未中獎 再接再厲，觸發正常抽獎
第367次：未中獎 再接再厲，觸發正常抽獎
第368次：貳獎 200元，觸發正常抽獎
第369次：未中獎 再接再厲，觸發正常抽獎
第370次：未中獎 再接再厲，觸發正常抽獎
第371次：未中獎 再接再厲，觸發正常抽獎
第372次：未中獎 再接再厲，觸發正常抽獎
第373次：未中獎 再接再厲，觸發正常抽獎
第374次：頭獎 500 元，觸發正常抽獎
第375次：未中獎 再接再厲，觸發正常抽獎
第376次：頭獎 500 元，觸發正常抽獎
第377次：未中獎 再接再厲，觸發正常抽獎
第378次：未中獎 再接再厲，觸發正常抽獎
第379次：未中獎 再接再厲，觸發正常抽獎
第380次：貳獎 200元，觸發正常抽獎
第381次：未中獎 再接再厲，觸發正常抽獎
第382次：未中獎 再接再厲，觸發正常抽獎
第383次：未中獎 再接再厲，觸發正常抽獎
第384次：未中獎 再接再厲，觸發正常抽獎
第385次：未中獎 再接再厲，觸發正常抽獎
第386次：未中獎 再接再厲，觸發正常抽獎
第387次：未中獎 再接再厲，觸發正常抽獎
第388次：頭獎 500 元，觸發正常抽獎
第389次：未中獎 再接再厲，觸發正常抽獎
第390次：未中獎 再接再厲，觸發正常抽獎
第391次：未中獎 再接再厲，觸發正常抽獎
第392次：未中獎 再接再厲，觸發正常抽獎
第393次：未中獎 再接再厲，觸發正常抽獎
第394次：貳獎 200元，觸發正常抽獎
第395次：頭獎 500 元，觸發正常抽獎
第396次：未中獎 再接再厲，觸發正常抽獎
第397次：未中獎 再接再厲，觸發正常抽獎
第398次：未中獎 再接再厲，觸發正常抽獎
第399次：未中獎 再接再厲，觸發正常抽獎
第400次：未中獎 再接再厲，觸發正常抽獎
第401次：貳獎 200元，觸發正常抽獎
第402次：未中獎 再接再厲，觸發正常抽獎
第403次：未中獎 再接再厲，觸發正常抽獎
第404次：未中獎 再接再厲，觸發正常抽獎
第405次：未中獎 再接再厲，觸發正常抽獎
第406次：未中獎 再接再厲，觸發正常抽獎
第407次：未中獎 再接再厲，觸發正常抽獎
第408次：未中獎 再接再厲，觸發正常抽獎
第409次：未中獎 再接再厲，觸發正常抽獎
第410次：未中獎 再接再厲，觸發正常抽獎
第411次：未中獎 再接再厲，觸發正常抽獎
第412次：未中獎 再接再厲，觸發正常抽獎
第413次：未中獎 再接再厲，觸發正常抽獎
第414次：未中獎 再接再厲，觸發正常抽獎
第415次：未中獎 再接再厲，觸發正常抽獎
第416次：未中獎 再接再厲，觸發正常抽獎
第417次：未中獎 再接再厲，觸發正常抽獎
第418次：未中獎 再接再厲，觸發正常抽獎
第419次：未中獎 再接再厲，觸發正常抽獎
第420次：未中獎 再接再厲，觸發正常抽獎
第421次：貳獎 200元，觸發20抽大保
第422次：未中獎 再接再厲，觸發正常抽獎
第423次：未中獎 再接再厲，觸發正常抽獎
第424次：未中獎 再接再厲，觸發正常抽獎
第425次：未中獎 再接再厲，觸發正常抽獎
第426次：未中獎 再接再厲，觸發正常抽獎
第427次：未中獎 再接再厲，觸發正常抽獎
第428次：未中獎 再接再厲，觸發正常抽獎
第429次：未中獎 再接再厲，觸發正常抽獎
第430次：未中獎 再接再厲，觸發正常抽獎
第431次：未中獎 再接再厲，觸發正常抽獎
第432次：未中獎 再接再厲，觸發正常抽獎
第433次：未中獎 再接再厲，觸發正常抽獎
第434次：貳獎 200元，觸發正常抽獎
第435次：未中獎 再接再厲，觸發正常抽獎
第436次：未中獎 再接再厲，觸發正常抽獎
第437次：未中獎 再接再厲，觸發正常抽獎
第438次：未中獎 再接再厲，觸發正常抽獎
第439次：未中獎 再接再厲，觸發正常抽獎
第440次：未中獎 再接再厲，觸發正常抽獎
第441次：貳獎 200元，觸發正常抽獎
第442次：未中獎 再接再厲，觸發正常抽獎
第443次：未中獎 再接再厲，觸發正常抽獎
第444次：貳獎 200元，觸發正常抽獎
第445次：頭獎 500 元，觸發正常抽獎
第446次：未中獎 再接再厲，觸發正常抽獎
第447次：頭獎 500 元，觸發正常抽獎
第448次：頭獎 500 元，觸發正常抽獎
第449次：未中獎 再接再厲，觸發正常抽獎
第450次：未中獎 再接再厲，觸發正常抽獎
第451次：貳獎 200元，觸發正常抽獎
第452次：貳獎 200元，觸發正常抽獎
第453次：未中獎 再接再厲，觸發正常抽獎
第454次：貳獎 200元，觸發正常抽獎
第455次：未中獎 再接再厲，觸發正常抽獎
第456次：未中獎 再接再厲，觸發正常抽獎
第457次：未中獎 再接再厲，觸發正常抽獎
第458次：未中獎 再接再厲，觸發正常抽獎
第459次：未中獎 再接再厲，觸發正常抽獎
第460次：未中獎 再接再厲，觸發正常抽獎
第461次：未中獎 再接再厲，觸發正常抽獎
第462次：未中獎 再接再厲，觸發正常抽獎
第463次：未中獎 再接再厲，觸發正常抽獎
第464次：未中獎 再接再厲，觸發正常抽獎
第465次：未中獎 再接再厲，觸發正常抽獎
第466次：未中獎 再接再厲，觸發正常抽獎
第467次：未中獎 再接再厲，觸發正常抽獎
第468次：未中獎 再接再厲，觸發正常抽獎
第469次：未中獎 再接再厲，觸發正常抽獎
第470次：未中獎 再接再厲，觸發正常抽獎
第471次：未中獎 再接再厲，觸發正常抽獎
第472次：未中獎 再接再厲，觸發正常抽獎
第473次：未中獎 再接再厲，觸發正常抽獎
第474次：貳獎 200元，觸發20抽大保
第475次：未中獎 再接再厲，觸發正常抽獎
第476次：未中獎 再接再厲，觸發正常抽獎
第477次：未中獎 再接再厲，觸發正常抽獎
第478次：未中獎 再接再厲，觸發正常抽獎
第479次：未中獎 再接再厲，觸發正常抽獎
第480次：未中獎 再接再厲，觸發正常抽獎
第481次：未中獎 再接再厲，觸發正常抽獎
第482次：未中獎 再接再厲，觸發正常抽獎
第483次：未中獎 再接再厲，觸發正常抽獎
第484次：未中獎 再接再厲，觸發正常抽獎
第485次：未中獎 再接再厲，觸發正常抽獎
第486次：未中獎 再接再厲，觸發正常抽獎
第487次：未中獎 再接再厲，觸發正常抽獎
第488次：貳獎 200元，觸發正常抽獎
第489次：未中獎 再接再厲，觸發正常抽獎
第490次：未中獎 再接再厲，觸發正常抽獎
第491次：未中獎 再接再厲，觸發正常抽獎
第492次：未中獎 再接再厲，觸發正常抽獎
第493次：未中獎 再接再厲，觸發正常抽獎
第494次：未中獎 再接再厲，觸發正常抽獎
第495次：未中獎 再接再厲，觸發正常抽獎
第496次：未中獎 再接再厲，觸發正常抽獎
第497次：未中獎 再接再厲，觸發正常抽獎
第498次：未中獎 再接再厲，觸發正常抽獎
第499次：未中獎 再接再厲，觸發正常抽獎
第500次：未中獎 再接再厲，觸發正常抽獎
第501次：貳獎 200元，觸發正常抽獎
第502次：貳獎 200元，觸發正常抽獎
第503次：未中獎 再接再厲，觸發正常抽獎
第504次：貳獎 200元，觸發正常抽獎
第505次：貳獎 200元，觸發正常抽獎
第506次：未中獎 再接再厲，觸發正常抽獎
第507次：未中獎 再接再厲，觸發正常抽獎
第508次：未中獎 再接再厲，觸發正常抽獎
第509次：未中獎 再接再厲，觸發正常抽獎
第510次：未中獎 再接再厲，觸發正常抽獎
第511次：未中獎 再接再厲，觸發正常抽獎
第512次：頭獎 500 元，觸發正常抽獎
第513次：未中獎 再接再厲，觸發正常抽獎
第514次：頭獎 500 元，觸發正常抽獎
第515次：未中獎 再接再厲，觸發正常抽獎
第516次：未中獎 再接再厲，觸發正常抽獎
第517次：未中獎 再接再厲，觸發正常抽獎
第518次：未中獎 再接再厲，觸發正常抽獎
第519次：未中獎 再接再厲，觸發正常抽獎
第520次：未中獎 再接再厲，觸發正常抽獎
第521次：未中獎 再接再厲，觸發正常抽獎
第522次：未中獎 再接再厲，觸發正常抽獎
第523次：未中獎 再接再厲，觸發正常抽獎
第524次：未中獎 再接再厲，觸發正常抽獎
第525次：未中獎 再接再厲，觸發正常抽獎
第526次：未中獎 再接再厲，觸發正常抽獎
第527次：頭獎 500 元，觸發正常抽獎
第528次：頭獎 500 元，觸發正常抽獎
第529次：未中獎 再接再厲，觸發正常抽獎
第530次：未中獎 再接再厲，觸發正常抽獎
第531次：未中獎 再接再厲，觸發正常抽獎
第532次：未中獎 再接再厲，觸發正常抽獎
第533次：未中獎 再接再厲，觸發正常抽獎
第534次：頭獎 500 元，觸發正常抽獎
第535次：未中獎 再接再厲，觸發正常抽獎
第536次：未中獎 再接再厲，觸發正常抽獎
第537次：未中獎 再接再厲，觸發正常抽獎
第538次：未中獎 再接再厲，觸發正常抽獎
第539次：未中獎 再接再厲，觸發正常抽獎
第540次：未中獎 再接再厲，觸發正常抽獎
第541次：未中獎 再接再厲，觸發正常抽獎
第542次：貳獎 200元，觸發正常抽獎
第543次：未中獎 再接再厲，觸發正常抽獎
第544次：未中獎 再接再厲，觸發正常抽獎
第545次：未中獎 再接再厲，觸發正常抽獎
第546次：頭獎 500 元，觸發正常抽獎
第547次：未中獎 再接再厲，觸發正常抽獎
第548次：未中獎 再接再厲，觸發正常抽獎
第549次：未中獎 再接再厲，觸發正常抽獎
第550次：未中獎 再接再厲，觸發正常抽獎
第551次：未中獎 再接再厲，觸發正常抽獎
第552次：未中獎 再接再厲，觸發正常抽獎
第553次：未中獎 再接再厲，觸發正常抽獎
第554次：貳獎 200元，觸發正常抽獎
第555次：未中獎 再接再厲，觸發正常抽獎
第556次：未中獎 再接再厲，觸發正常抽獎
第557次：未中獎 再接再厲，觸發正常抽獎
第558次：未中獎 再接再厲，觸發正常抽獎
第559次：未中獎 再接再厲，觸發正常抽獎
第560次：未中獎 再接再厲，觸發正常抽獎
第561次：未中獎 再接再厲，觸發正常抽獎
第562次：未中獎 再接再厲，觸發正常抽獎
第563次：未中獎 再接再厲，觸發正常抽獎
第564次：未中獎 再接再厲，觸發正常抽獎
第565次：未中獎 再接再厲，觸發正常抽獎
第566次：貳獎 200元，觸發正常抽獎
第567次：未中獎 再接再厲，觸發正常抽獎
第568次：未中獎 再接再厲，觸發正常抽獎
第569次：未中獎 再接再厲，觸發正常抽獎
第570次：貳獎 200元，觸發正常抽獎
第571次：未中獎 再接再厲，觸發正常抽獎
第572次：頭獎 500 元，觸發正常抽獎
第573次：未中獎 再接再厲，觸發正常抽獎
第574次：未中獎 再接再厲，觸發正常抽獎
第575次：未中獎 再接再厲，觸發正常抽獎
第576次：未中獎 再接再厲，觸發正常抽獎
第577次：未中獎 再接再厲，觸發正常抽獎
第578次：未中獎 再接再厲，觸發正常抽獎
第579次：未中獎 再接再厲，觸發正常抽獎
第580次：頭獎 500 元，觸發正常抽獎
第581次：未中獎 再接再厲，觸發正常抽獎
第582次：貳獎 200元，觸發正常抽獎
第583次：頭獎 500 元，觸發正常抽獎
第584次：未中獎 再接再厲，觸發正常抽獎
第585次：未中獎 再接再厲，觸發正常抽獎
第586次：貳獎 200元，觸發正常抽獎
第587次：頭獎 500 元，觸發正常抽獎
第588次：貳獎 200元，觸發正常抽獎
第589次：未中獎 再接再厲，觸發正常抽獎
第590次：未中獎 再接再厲，觸發正常抽獎
第591次：未中獎 再接再厲，觸發正常抽獎
第592次：未中獎 再接再厲，觸發正常抽獎
第593次：未中獎 再接再厲，觸發正常抽獎
第594次：未中獎 再接再厲，觸發正常抽獎
第595次：未中獎 再接再厲，觸發正常抽獎
第596次：未中獎 再接再厲，觸發正常抽獎
第597次：貳獎 200元，觸發正常抽獎
第598次：未中獎 再接再厲，觸發正常抽獎
第599次：未中獎 再接再厲，觸發正常抽獎
第600次：未中獎 再接再厲，觸發正常抽獎
第601次：未中獎 再接再厲，觸發正常抽獎
第602次：未中獎 再接再厲，觸發正常抽獎
第603次：未中獎 再接再厲，觸發正常抽獎
第604次：未中獎 再接再厲，觸發正常抽獎
第605次：未中獎 再接再厲，觸發正常抽獎
第606次：貳獎 200元，觸發正常抽獎
第607次：未中獎 再接再厲，觸發正常抽獎
第608次：頭獎 500 元，觸發正常抽獎
第609次：未中獎 再接再厲，觸發正常抽獎
第610次：未中獎 再接再厲，觸發正常抽獎
第611次：未中獎 再接再厲，觸發正常抽獎
第612次：未中獎 再接再厲，觸發正常抽獎
第613次：未中獎 再接再厲，觸發正常抽獎
第614次：未中獎 再接再厲，觸發正常抽獎
第615次：未中獎 再接再厲，觸發正常抽獎
第616次：貳獎 200元，觸發正常抽獎
第617次：未中獎 再接再厲，觸發正常抽獎
第618次：未中獎 再接再厲，觸發正常抽獎
第619次：頭獎 500 元，觸發正常抽獎
第620次：未中獎 再接再厲，觸發正常抽獎
第621次：未中獎 再接再厲，觸發正常抽獎
第622次：未中獎 再接再厲，觸發正常抽獎
第623次：未中獎 再接再厲，觸發正常抽獎
第624次：未中獎 再接再厲，觸發正常抽獎
第625次：貳獎 200元，觸發正常抽獎
第626次：貳獎 200元，觸發正常抽獎
第627次：未中獎 再接再厲，觸發正常抽獎
第628次：未中獎 再接再厲，觸發正常抽獎
第629次：未中獎 再接再厲，觸發正常抽獎
第630次：頭獎 500 元，觸發正常抽獎
第631次：未中獎 再接再厲，觸發正常抽獎
第632次：未中獎 再接再厲，觸發正常抽獎
第633次：貳獎 200元，觸發正常抽獎
第634次：未中獎 再接再厲，觸發正常抽獎
第635次：未中獎 再接再厲，觸發正常抽獎
第636次：未中獎 再接再厲，觸發正常抽獎
第637次：頭獎 500 元，觸發正常抽獎
第638次：未中獎 再接再厲，觸發正常抽獎
第639次：未中獎 再接再厲，觸發正常抽獎
第640次：未中獎 再接再厲，觸發正常抽獎
第641次：未中獎 再接再厲，觸發正常抽獎
第642次：未中獎 再接再厲，觸發正常抽獎
第643次：未中獎 再接再厲，觸發正常抽獎
第644次：貳獎 200元，觸發正常抽獎
第645次：未中獎 再接再厲，觸發正常抽獎
第646次：頭獎 500 元，觸發正常抽獎
第647次：未中獎 再接再厲，觸發正常抽獎
第648次：未中獎 再接再厲，觸發正常抽獎
第649次：未中獎 再接再厲，觸發正常抽獎
第650次：未中獎 再接再厲，觸發正常抽獎
第651次：未中獎 再接再厲，觸發正常抽獎
第652次：未中獎 再接再厲，觸發正常抽獎
第653次：未中獎 再接再厲，觸發正常抽獎
第654次：未中獎 再接再厲，觸發正常抽獎
第655次：未中獎 再接再厲，觸發正常抽獎
第656次：未中獎 再接再厲，觸發正常抽獎
第657次：未中獎 再接再厲，觸發正常抽獎
第658次：未中獎 再接再厲，觸發正常抽獎
第659次：未中獎 再接再厲，觸發正常抽獎
第660次：未中獎 再接再厲，觸發正常抽獎
第661次：未中獎 再接再厲，觸發正常抽獎
第662次：未中獎 再接再厲，觸發正常抽獎
第663次：貳獎 200元，觸發正常抽獎
第664次：未中獎 再接再厲，觸發正常抽獎
第665次：貳獎 200元，觸發正常抽獎
第666次：未中獎 再接再厲，觸發正常抽獎
第667次：未中獎 再接再厲，觸發正常抽獎
第668次：貳獎 200元，觸發正常抽獎
第669次：未中獎 再接再厲，觸發正常抽獎
第670次：未中獎 再接再厲，觸發正常抽獎
第671次：未中獎 再接再厲，觸發正常抽獎
第672次：未中獎 再接再厲，觸發正常抽獎
第673次：貳獎 200元，觸發正常抽獎
第674次：未中獎 再接再厲，觸發正常抽獎
第675次：未中獎 再接再厲，觸發正常抽獎
第676次：未中獎 再接再厲，觸發正常抽獎
第677次：未中獎 再接再厲，觸發正常抽獎
第678次：頭獎 500 元，觸發正常抽獎
第679次：未中獎 再接再厲，觸發正常抽獎
第680次：未中獎 再接再厲，觸發正常抽獎
第681次：未中獎 再接再厲，觸發正常抽獎
第682次：貳獎 200元，觸發正常抽獎
第683次：未中獎 再接再厲，觸發正常抽獎
第684次：未中獎 再接再厲，觸發正常抽獎
第685次：未中獎 再接再厲，觸發正常抽獎
第686次：未中獎 再接再厲，觸發正常抽獎
第687次：未中獎 再接再厲，觸發正常抽獎
第688次：未中獎 再接再厲，觸發正常抽獎
第689次：未中獎 再接再厲，觸發正常抽獎
第690次：未中獎 再接再厲，觸發正常抽獎
第691次：未中獎 再接再厲，觸發正常抽獎
第692次：未中獎 再接再厲，觸發正常抽獎
第693次：頭獎 500 元，觸發正常抽獎
第694次：未中獎 再接再厲，觸發正常抽獎
第695次：未中獎 再接再厲，觸發正常抽獎
第696次：未中獎 再接再厲，觸發正常抽獎
第697次：未中獎 再接再厲，觸發正常抽獎
第698次：頭獎 500 元，觸發正常抽獎
第699次：未中獎 再接再厲，觸發正常抽獎
第700次：未中獎 再接再厲，觸發正常抽獎
第701次：未中獎 再接再厲，觸發正常抽獎
第702次：未中獎 再接再厲，觸發正常抽獎
第703次：未中獎 再接再厲，觸發正常抽獎
第704次：未中獎 再接再厲，觸發正常抽獎
第705次：未中獎 再接再厲，觸發正常抽獎
第706次：未中獎 再接再厲，觸發正常抽獎
第707次：貳獎 200元，觸發正常抽獎
第708次：未中獎 再接再厲，觸發正常抽獎
第709次：未中獎 再接再厲，觸發正常抽獎
第710次：未中獎 再接再厲，觸發正常抽獎
第711次：未中獎 再接再厲，觸發正常抽獎
第712次：未中獎 再接再厲，觸發正常抽獎
第713次：頭獎 500 元，觸發正常抽獎
第714次：未中獎 再接再厲，觸發正常抽獎
第715次：未中獎 再接再厲，觸發正常抽獎
第716次：未中獎 再接再厲，觸發正常抽獎
第717次：頭獎 500 元，觸發正常抽獎
第718次：未中獎 再接再厲，觸發正常抽獎
第719次：未中獎 再接再厲，觸發正常抽獎
第720次：未中獎 再接再厲，觸發正常抽獎
第721次：未中獎 再接再厲，觸發正常抽獎
第722次：未中獎 再接再厲，觸發正常抽獎
第723次：未中獎 再接再厲，觸發正常抽獎
第724次：未中獎 再接再厲，觸發正常抽獎
第725次：未中獎 再接再厲，觸發正常抽獎
第726次：未中獎 再接再厲，觸發正常抽獎
第727次：未中獎 再接再厲，觸發正常抽獎
第728次：未中獎 再接再厲，觸發正常抽獎
第729次：貳獎 200元，觸發正常抽獎
第730次：頭獎 500 元，觸發正常抽獎
第731次：未中獎 再接再厲，觸發正常抽獎
第732次：頭獎 500 元，觸發正常抽獎
第733次：未中獎 再接再厲，觸發正常抽獎
第734次：未中獎 再接再厲，觸發正常抽獎
第735次：未中獎 再接再厲，觸發正常抽獎
第736次：貳獎 200元，觸發正常抽獎
第737次：未中獎 再接再厲，觸發正常抽獎
第738次：未中獎 再接再厲，觸發正常抽獎
第739次：未中獎 再接再厲，觸發正常抽獎
第740次：未中獎 再接再厲，觸發正常抽獎
第741次：未中獎 再接再厲，觸發正常抽獎
第742次：未中獎 再接再厲，觸發正常抽獎
第743次：未中獎 再接再厲，觸發正常抽獎
第744次：未中獎 再接再厲，觸發正常抽獎
第745次：未中獎 再接再厲，觸發正常抽獎
第746次：未中獎 再接再厲，觸發正常抽獎
第747次：未中獎 再接再厲，觸發正常抽獎
第748次：頭獎 500 元，觸發正常抽獎
第749次：未中獎 再接再厲，觸發正常抽獎
第750次：未中獎 再接再厲，觸發正常抽獎
第751次：未中獎 再接再厲，觸發正常抽獎
第752次：未中獎 再接再厲，觸發正常抽獎
第753次：未中獎 再接再厲，觸發正常抽獎
第754次：未中獎 再接再厲，觸發正常抽獎
第755次：未中獎 再接再厲，觸發正常抽獎
第756次：未中獎 再接再厲，觸發正常抽獎
第757次：未中獎 再接再厲，觸發正常抽獎
第758次：未中獎 再接再厲，觸發正常抽獎
第759次：未中獎 再接再厲，觸發正常抽獎
第760次：未中獎 再接再厲，觸發正常抽獎
第761次：未中獎 再接再厲，觸發正常抽獎
第762次：未中獎 再接再厲，觸發正常抽獎
第763次：未中獎 再接再厲，觸發正常抽獎
第764次：頭獎 500 元，觸發正常抽獎
第765次：未中獎 再接再厲，觸發正常抽獎
第766次：未中獎 再接再厲，觸發正常抽獎
第767次：貳獎 200元，觸發正常抽獎
第768次：未中獎 再接再厲，觸發正常抽獎
第769次：未中獎 再接再厲，觸發正常抽獎
第770次：未中獎 再接再厲，觸發正常抽獎
第771次：貳獎 200元，觸發正常抽獎
第772次：未中獎 再接再厲，觸發正常抽獎
第773次：未中獎 再接再厲，觸發正常抽獎
第774次：未中獎 再接再厲，觸發正常抽獎
第775次：未中獎 再接再厲，觸發正常抽獎
第776次：未中獎 再接再厲，觸發正常抽獎
第777次：未中獎 再接再厲，觸發正常抽獎
第778次：未中獎 再接再厲，觸發正常抽獎
第779次：未中獎 再接再厲，觸發正常抽獎
第780次：未中獎 再接再厲，觸發正常抽獎
第781次：未中獎 再接再厲，觸發正常抽獎
第782次：未中獎 再接再厲，觸發正常抽獎
第783次：未中獎 再接再厲，觸發正常抽獎
第784次：未中獎 再接再厲，觸發正常抽獎
第785次：未中獎 再接再厲，觸發正常抽獎
第786次：頭獎 500 元，觸發正常抽獎
第787次：未中獎 再接再厲，觸發正常抽獎
第788次：未中獎 再接再厲，觸發正常抽獎
第789次：未中獎 再接再厲，觸發正常抽獎
第790次：未中獎 再接再厲，觸發正常抽獎
第791次：未中獎 再接再厲，觸發正常抽獎
第792次：未中獎 再接再厲，觸發正常抽獎
第793次：未中獎 再接再厲，觸發正常抽獎
第794次：未中獎 再接再厲，觸發正常抽獎
第795次：未中獎 再接再厲，觸發正常抽獎
第796次：未中獎 再接再厲，觸發正常抽獎
第797次：未中獎 再接再厲，觸發正常抽獎
第798次：未中獎 再接再厲，觸發正常抽獎
第799次：頭獎 500 元，觸發正常抽獎
第800次：未中獎 再接再厲，觸發正常抽獎
第801次：未中獎 再接再厲，觸發正常抽獎
第802次：貳獎 200元，觸發正常抽獎
第803次：貳獎 200元，觸發正常抽獎
第804次：未中獎 再接再厲，觸發正常抽獎
第805次：未中獎 再接再厲，觸發正常抽獎
第806次：未中獎 再接再厲，觸發正常抽獎
第807次：未中獎 再接再厲，觸發正常抽獎
第808次：未中獎 再接再厲，觸發正常抽獎
第809次：未中獎 再接再厲，觸發正常抽獎
第810次：未中獎 再接再厲，觸發正常抽獎
第811次：未中獎 再接再厲，觸發正常抽獎
第812次：未中獎 再接再厲，觸發正常抽獎
第813次：頭獎 500 元，觸發正常抽獎
第814次：未中獎 再接再厲，觸發正常抽獎
第815次：未中獎 再接再厲，觸發正常抽獎
第816次：未中獎 再接再厲，觸發正常抽獎
第817次：未中獎 再接再厲，觸發正常抽獎
第818次：未中獎 再接再厲，觸發正常抽獎
第819次：未中獎 再接再厲，觸發正常抽獎
第820次：未中獎 再接再厲，觸發正常抽獎
第821次：未中獎 再接再厲，觸發正常抽獎
第822次：貳獎 200元，觸發正常抽獎
第823次：未中獎 再接再厲，觸發正常抽獎
第824次：未中獎 再接再厲，觸發正常抽獎
第825次：未中獎 再接再厲，觸發正常抽獎
第826次：未中獎 再接再厲，觸發正常抽獎
第827次：未中獎 再接再厲，觸發正常抽獎
第828次：未中獎 再接再厲，觸發正常抽獎
第829次：貳獎 200元，觸發正常抽獎
第830次：未中獎 再接再厲，觸發正常抽獎
第831次：未中獎 再接再厲，觸發正常抽獎
第832次：未中獎 再接再厲，觸發正常抽獎
第833次：未中獎 再接再厲，觸發正常抽獎
第834次：未中獎 再接再厲，觸發正常抽獎
第835次：未中獎 再接再厲，觸發正常抽獎
第836次：未中獎 再接再厲，觸發正常抽獎
第837次：未中獎 再接再厲，觸發正常抽獎
第838次：未中獎 再接再厲，觸發正常抽獎
第839次：未中獎 再接再厲，觸發正常抽獎
第840次：未中獎 再接再厲，觸發正常抽獎
第841次：未中獎 再接再厲，觸發正常抽獎
第842次：未中獎 再接再厲，觸發正常抽獎
第843次：未中獎 再接再厲，觸發正常抽獎
第844次：未中獎 再接再厲，觸發正常抽獎
第845次：未中獎 再接再厲，觸發正常抽獎
第846次：貳獎 200元，觸發正常抽獎
第847次：未中獎 再接再厲，觸發正常抽獎
第848次：未中獎 再接再厲，觸發正常抽獎
第849次：頭獎 500 元，觸發正常抽獎
第850次：未中獎 再接再厲，觸發正常抽獎
第851次：未中獎 再接再厲，觸發正常抽獎
第852次：未中獎 再接再厲，觸發正常抽獎
第853次：未中獎 再接再厲，觸發正常抽獎
第854次：未中獎 再接再厲，觸發正常抽獎
第855次：未中獎 再接再厲，觸發正常抽獎
第856次：未中獎 再接再厲，觸發正常抽獎
第857次：未中獎 再接再厲，觸發正常抽獎
第858次：未中獎 再接再厲，觸發正常抽獎
第859次：頭獎 500 元，觸發正常抽獎
第860次：未中獎 再接再厲，觸發正常抽獎
第861次：未中獎 再接再厲，觸發正常抽獎
第862次：未中獎 再接再厲，觸發正常抽獎
第863次：未中獎 再接再厲，觸發正常抽獎
第864次：未中獎 再接再厲，觸發正常抽獎
第865次：頭獎 500 元，觸發正常抽獎
第866次：貳獎 200元，觸發正常抽獎
第867次：貳獎 200元，觸發正常抽獎
第868次：未中獎 再接再厲，觸發正常抽獎
第869次：未中獎 再接再厲，觸發正常抽獎
第870次：未中獎 再接再厲，觸發正常抽獎
第871次：未中獎 再接再厲，觸發正常抽獎
第872次：貳獎 200元，觸發正常抽獎
第873次：未中獎 再接再厲，觸發正常抽獎
第874次：未中獎 再接再厲，觸發正常抽獎
第875次：未中獎 再接再厲，觸發正常抽獎
第876次：未中獎 再接再厲，觸發正常抽獎
第877次：未中獎 再接再厲，觸發正常抽獎
第878次：未中獎 再接再厲，觸發正常抽獎
第879次：未中獎 再接再厲，觸發正常抽獎
第880次：頭獎 500 元，觸發正常抽獎
第881次：未中獎 再接再厲，觸發正常抽獎
第882次：未中獎 再接再厲，觸發正常抽獎
第883次：貳獎 200元，觸發正常抽獎
第884次：未中獎 再接再厲，觸發正常抽獎
第885次：未中獎 再接再厲，觸發正常抽獎
第886次：未中獎 再接再厲，觸發正常抽獎
第887次：未中獎 再接再厲，觸發正常抽獎
第888次：未中獎 再接再厲，觸發正常抽獎
第889次：未中獎 再接再厲，觸發正常抽獎
第890次：未中獎 再接再厲，觸發正常抽獎
第891次：未中獎 再接再厲，觸發正常抽獎
第892次：未中獎 再接再厲，觸發正常抽獎
第893次：未中獎 再接再厲，觸發正常抽獎
第894次：未中獎 再接再厲，觸發正常抽獎
第895次：未中獎 再接再厲，觸發正常抽獎
第896次：未中獎 再接再厲，觸發正常抽獎
第897次：未中獎 再接再厲，觸發正常抽獎
第898次：未中獎 再接再厲，觸發正常抽獎
第899次：未中獎 再接再厲，觸發正常抽獎
第900次：未中獎 再接再厲，觸發正常抽獎
第901次：未中獎 再接再厲，觸發正常抽獎
第902次：未中獎 再接再厲，觸發正常抽獎
第903次：頭獎 500 元，觸發20抽大保
第904次：未中獎 再接再厲，觸發正常抽獎
第905次：未中獎 再接再厲，觸發正常抽獎
第906次：未中獎 再接再厲，觸發正常抽獎
第907次：未中獎 再接再厲，觸發正常抽獎
第908次：未中獎 再接再厲，觸發正常抽獎
第909次：未中獎 再接再厲，觸發正常抽獎
第910次：未中獎 再接再厲，觸發正常抽獎
第911次：頭獎 500 元，觸發正常抽獎
第912次：未中獎 再接再厲，觸發正常抽獎
第913次：未中獎 再接再厲，觸發正常抽獎
第914次：未中獎 再接再厲，觸發正常抽獎
第915次：頭獎 500 元，觸發正常抽獎

    樣本數 單次遊玩獎金期望值估計   標準誤   CI下界   CI上界
0  5000       46.04  1.73  42.64  49.44

帳號：1，已存在玩家資料
目前狀態：非新手期，您不具有新手保底
開始遊玩5000次
第1次：未中獎 再接再厲，觸發正常抽獎
第2次：未中獎 再接再厲，觸發正常抽獎
第3次：未中獎 再接再厲，觸發正常抽獎
第4次：未中獎 再接再厲，觸發正常抽獎
第5次：未中獎 再接再厲，觸發正常抽獎
第6次：未中獎 再接再厲，觸發正常抽獎
第7次：未中獎 再接再厲，觸發正常抽獎
第8次：未中獎 再接再厲，觸發正常抽獎
第9次：未中獎 再接再厲，觸發正常抽獎
第10次：未中獎 再接再厲，觸發正常抽獎
第11次：貳獎 200元，觸發正常抽獎
第12次：未中獎 再接再厲，觸發正常抽獎
第13次：貳獎 200元，觸發正常抽獎
第14次：頭獎 500 元，觸發正常抽獎
第15次：貳獎 200元，觸發正常抽獎
第16次：未中獎 再接再厲，觸發正常抽獎
第17次：未中獎 再接再厲，觸發正常抽獎
第18次：未中獎 再接再厲，觸發正常抽獎
第19次：未中獎 再接再厲，觸發正常抽獎
第20次：未中獎 再接再厲，觸發正常抽獎
第21次：未中獎 再接再厲，觸發正常抽獎
第22次：未中獎 再接再厲，觸發正常抽獎
第23次：未中獎 再接再厲，觸發正常抽獎
第24次：未中獎 再接再厲，觸發正常抽獎
第25次：未中獎 再接再厲，觸發正常抽獎
第26次：未中獎 再接再厲，觸發正常抽獎
第27次：未中獎 再接再厲，觸發正常抽獎
第28次：未中獎 再接再厲，觸發正常抽獎
第29次：未中獎 再接再厲，觸發正常抽獎
第30次：未中獎 再接再厲，觸發正常抽獎
第31次：貳獎 200元，觸發正常抽獎
第32次：未中獎 再接再厲，觸發正常抽獎
第33次：未中獎 再接再厲，觸發正常抽獎
第34次：貳獎 200元，觸發正常抽獎
第35次：未中獎 再接再厲，觸發正常抽獎
第36次：未中獎 再接再厲，觸發正常抽獎
第37次：未中獎 再接再厲，觸發正常抽獎
第38次：未中獎 再接再厲，觸發正常抽獎
第39次：未中獎 再接再厲，觸發正常抽獎
第40次：未中獎 再接再厲，觸發正常抽獎
第41次：未中獎 再接再厲，觸發正常抽獎
第42次：未中獎 再接再厲，觸發正常抽獎
第43次：未中獎 再接再厲，觸發正常抽獎
第44次：貳獎 200元，觸發正常抽獎
第45次：未中獎 再接再厲，觸發正常抽獎
第46次：未中獎 再接再厲，觸發正常抽獎
第47次：未中獎 再接再厲，觸發正常抽獎
第48次：未中獎 再接再厲，觸發正常抽獎
第49次：未中獎 再接再厲，觸發正常抽獎
第50次：未中獎 再接再厲，觸發正常抽獎
第51次：未中獎 再接再厲，觸發正常抽獎
第52次：未中獎 再接再厲，觸發正常抽獎
第53次：未中獎 再接再厲，觸發正常抽獎
第54次：未中獎 再接再厲，觸發正常抽獎
第55次：未中獎 再接再厲，觸發正常抽獎
第56次：未中獎 再接再厲，觸發正常抽獎
第57次：未中獎 再接再厲，觸發正常抽獎
第58次：未中獎 再接再厲，觸發正常抽獎
第59次：未中獎 再接再厲，觸發正常抽獎
第60次：未中獎 再接再厲，觸發正常抽獎
第61次：未中獎 再接再厲，觸發正常抽獎
第62次：未中獎 再接再厲，觸發正常抽獎
第63次：未中獎 再接再厲，觸發正常抽獎
第64次：貳獎 200元，觸發20抽大保
第65次：未中獎 再接再厲，觸發正常抽獎
第66次：未中獎 再接再厲，觸發正常抽獎
第67次：未中獎 再接再厲，觸發正常抽獎
第68次：未中獎 再接再厲，觸發正常抽獎
第69次：未中獎 再接再厲，觸發正常抽獎
第70次：未中獎 再接再厲，觸發正常抽獎
第71次：未中獎 再接再厲，觸發正常抽獎
第72次：未中獎 再接再厲，觸發正常抽獎
第73次：未中獎 再接再厲，觸發正常抽獎
第74次：未中獎 再接再厲，觸發正常抽獎
第75次：未中獎 再接再厲，觸發正常抽獎
第76次：未中獎 再接再厲，觸發正常抽獎
第77次：未中獎 再接再厲，觸發正常抽獎
第78次：貳獎 200元，觸發正常抽獎
第79次：頭獎 500 元，觸發正常抽獎
第80次：未中獎 再接再厲，觸發正常抽獎
第81次：未中獎 再接再厲，觸發正常抽獎
第82次：未中獎 再接再厲，觸發正常抽獎
第83次：未中獎 再接再厲，觸發正常抽獎
第84次：未中獎 再接再厲，觸發正常抽獎
第85次：未中獎 再接再厲，觸發正常抽獎
第86次：未中獎 再接再厲，觸發正常抽獎
第87次：未中獎 再接再厲，觸發正常抽獎
第88次：未中獎 再接再厲，觸發正常抽獎
第89次：頭獎 500 元，觸發正常抽獎
第90次：未中獎 再接再厲，觸發正常抽獎
第91次：未中獎 再接再厲，觸發正常抽獎
第92次：未中獎 再接再厲，觸發正常抽獎
第93次：未中獎 再接再厲，觸發正常抽獎
第94次：未中獎 再接再厲，觸發正常抽獎
第95次：貳獎 200元，觸發正常抽獎
第96次：未中獎 再接再厲，觸發正常抽獎
第97次：未中獎 再接再厲，觸發正常抽獎
第98次：未中獎 再接再厲，觸發正常抽獎
第99次：貳獎 200元，觸發正常抽獎
第100次：未中獎 再接再厲，觸發正常抽獎
第101次：未中獎 再接再厲，觸發正常抽獎
第102次：未中獎 再接再厲，觸發正常抽獎
第103次：未中獎 再接再厲，觸發正常抽獎
第104次：頭獎 500 元，觸發正常抽獎
第105次：未中獎 再接再厲，觸發正常抽獎
第106次：貳獎 200元，觸發正常抽獎
第107次：未中獎 再接再厲，觸發正常抽獎
第108次：未中獎 再接再厲，觸發正常抽獎
第109次：未中獎 再接再厲，觸發正常抽獎
第110次：未中獎 再接再厲，觸發正常抽獎
第111次：頭獎 500 元，觸發正常抽獎
第112次：未中獎 再接再厲，觸發正常抽獎
第113次：未中獎 再接再厲，觸發正常抽獎
第114次：未中獎 再接再厲，觸發正常抽獎
第115次：未中獎 再接再厲，觸發正常抽獎
第116次：貳獎 200元，觸發正常抽獎
第117次：未中獎 再接再厲，觸發正常抽獎
第118次：未中獎 再接再厲，觸發正常抽獎
第119次：未中獎 再接再厲，觸發正常抽獎
第120次：未中獎 再接再厲，觸發正常抽獎
第121次：未中獎 再接再厲，觸發正常抽獎
第122次：頭獎 500 元，觸發正常抽獎
第123次：未中獎 再接再厲，觸發正常抽獎
第124次：未中獎 再接再厲，觸發正常抽獎
第125次：貳獎 200元，觸發正常抽獎
第126次：未中獎 再接再厲，觸發正常抽獎
第127次：未中獎 再接再厲，觸發正常抽獎
第128次：未中獎 再接再厲，觸發正常抽獎
第129次：未中獎 再接再厲，觸發正常抽獎
第130次：未中獎 再接再厲，觸發正常抽獎
第131次：未中獎 再接再厲，觸發正常抽獎
第132次：頭獎 500 元，觸發正常抽獎
第133次：頭獎 500 元，觸發正常抽獎
第134次：未中獎 再接再厲，觸發正常抽獎
第135次：未中獎 再接再厲，觸發正常抽獎
第136次：頭獎 500 元，觸發正常抽獎
第137次：未中獎 再接再厲，觸發正常抽獎
第138次：頭獎 500 元，觸發正常抽獎
第139次：未中獎 再接再厲，觸發正常抽獎
第140次：未中獎 再接再厲，觸發正常抽獎
第141次：未中獎 再接再厲，觸發正常抽獎
第142次：未中獎 再接再厲，觸發正常抽獎
第143次：未中獎 再接再厲，觸發正常抽獎
第144次：未中獎 再接再厲，觸發正常抽獎
第145次：未中獎 再接再厲，觸發正常抽獎
第146次：未中獎 再接再厲，觸發正常抽獎
第147次：未中獎 再接再厲，觸發正常抽獎
第148次：貳獎 200元，觸發正常抽獎
第149次：未中獎 再接再厲，觸發正常抽獎
第150次：貳獎 200元，觸發正常抽獎
第151次：頭獎 500 元，觸發正常抽獎
第152次：未中獎 再接再厲，觸發正常抽獎
第153次：未中獎 再接再厲，觸發正常抽獎
第154次：未中獎 再接再厲，觸發正常抽獎
第155次：未中獎 再接再厲，觸發正常抽獎
第156次：未中獎 再接再厲，觸發正常抽獎
第157次：未中獎 再接再厲，觸發正常抽獎
第158次：未中獎 再接再厲，觸發正常抽獎
第159次：未中獎 再接再厲，觸發正常抽獎
第160次：未中獎 再接再厲，觸發正常抽獎
第161次：未中獎 再接再厲，觸發正常抽獎
第162次：未中獎 再接再厲，觸發正常抽獎
第163次：未中獎 再接再厲，觸發正常抽獎
第164次：未中獎 再接再厲，觸發正常抽獎
第165次：貳獎 200元，觸發正常抽獎
第166次：未中獎 再接再厲，觸發正常抽獎
第167次：頭獎 500 元，觸發正常抽獎
第168次：未中獎 再接再厲，觸發正常抽獎
第169次：未中獎 再接再厲，觸發正常抽獎
第170次：未中獎 再接再厲，觸發正常抽獎
第171次：未中獎 再接再厲，觸發正常抽獎
第172次：未中獎 再接再厲，觸發正常抽獎
第173次：未中獎 再接再厲，觸發正常抽獎
第174次：未中獎 再接再厲，觸發正常抽獎
第175次：未中獎 再接再厲，觸發正常抽獎
第176次：未中獎 再接再厲，觸發正常抽獎
第177次：未中獎 再接再厲，觸發正常抽獎
第178次：未中獎 再接再厲，觸發正常抽獎
第179次：貳獎 200元，觸發正常抽獎
第180次：未中獎 再接再厲，觸發正常抽獎
第181次：未中獎 再接再厲，觸發正常抽獎
第182次：未中獎 再接再厲，觸發正常抽獎
第183次：未中獎 再接再厲，觸發正常抽獎
第184次：未中獎 再接再厲，觸發正常抽獎
第185次：未中獎 再接再厲，觸發正常抽獎
第186次：未中獎 再接再厲，觸發正常抽獎
第187次：未中獎 再接再厲，觸發正常抽獎
第188次：未中獎 再接再厲，觸發正常抽獎
第189次：未中獎 再接再厲，觸發正常抽獎
第190次：未中獎 再接再厲，觸發正常抽獎
第191次：未中獎 再接再厲，觸發正常抽獎
第192次：未中獎 再接再厲，觸發正常抽獎
第193次：未中獎 再接再厲，觸發正常抽獎
第194次：未中獎 再接再厲，觸發正常抽獎
第195次：未中獎 再接再厲，觸發正常抽獎
第196次：未中獎 再接再厲，觸發正常抽獎
第197次：未中獎 再接再厲，觸發正常抽獎
第198次：未中獎 再接再厲，觸發正常抽獎
第199次：頭獎 500 元，觸發20抽大保
第200次：未中獎 再接再厲，觸發正常抽獎
第201次：未中獎 再接再厲，觸發正常抽獎
第202次：貳獎 200元，觸發正常抽獎
第203次：未中獎 再接再厲，觸發正常抽獎
第204次：未中獎 再接再厲，觸發正常抽獎
第205次：未中獎 再接再厲，觸發正常抽獎
第206次：未中獎 再接再厲，觸發正常抽獎
第207次：未中獎 再接再厲，觸發正常抽獎
第208次：未中獎 再接再厲，觸發正常抽獎
第209次：未中獎 再接再厲，觸發正常抽獎
第210次：未中獎 再接再厲，觸發正常抽獎
第211次：貳獎 200元，觸發正常抽獎
第212次：未中獎 再接再厲，觸發正常抽獎
第213次：未中獎 再接再厲，觸發正常抽獎
第214次：頭獎 500 元，觸發正常抽獎
第215次：未中獎 再接再厲，觸發正常抽獎
第216次：未中獎 再接再厲，觸發正常抽獎
第217次：未中獎 再接再厲，觸發正常抽獎
第218次：未中獎 再接再厲，觸發正常抽獎
第219次：未中獎 再接再厲，觸發正常抽獎
第220次：未中獎 再接再厲，觸發正常抽獎
第221次：未中獎 再接再厲，觸發正常抽獎
第222次：未中獎 再接再厲，觸發正常抽獎
第223次：未中獎 再接再厲，觸發正常抽獎
第224次：未中獎 再接再厲，觸發正常抽獎
第225次：未中獎 再接再厲，觸發正常抽獎
第226次：未中獎 再接再厲，觸發正常抽獎
第227次：未中獎 再接再厲，觸發正常抽獎
第228次：未中獎 再接再厲，觸發正常抽獎
第229次：未中獎 再接再厲，觸發正常抽獎
第230次：未中獎 再接再厲，觸發正常抽獎
第231次：未中獎 再接再厲，觸發正常抽獎
第232次：貳獎 200元，觸發正常抽獎
第233次：未中獎 再接再厲，觸發正常抽獎
第234次：未中獎 再接再厲，觸發正常抽獎
第235次：未中獎 再接再厲，觸發正常抽獎
第236次：貳獎 200元，觸發正常抽獎
第237次：未中獎 再接再厲，觸發正常抽獎
第238次：未中獎 再接再厲，觸發正常抽獎
第239次：未中獎 再接再厲，觸發正常抽獎
第240次：未中獎 再接再厲，觸發正常抽獎
第241次：未中獎 再接再厲，觸發正常抽獎
第242次：未中獎 再接再厲，觸發正常抽獎
第243次：未中獎 再接再厲，觸發正常抽獎
第244次：未中獎 再接再厲，觸發正常抽獎
第245次：未中獎 再接再厲，觸發正常抽獎
第246次：未中獎 再接再厲，觸發正常抽獎
第247次：頭獎 500 元，觸發正常抽獎
第248次：未中獎 再接再厲，觸發正常抽獎
第249次：未中獎 再接再厲，觸發正常抽獎
第250次：未中獎 再接再厲，觸發正常抽獎
第251次：未中獎 再接再厲，觸發正常抽獎
第252次：未中獎 再接再厲，觸發正常抽獎
第253次：未中獎 再接再厲，觸發正常抽獎
第254次：未中獎 再接再厲，觸發正常抽獎
第255次：未中獎 再接再厲，觸發正常抽獎
第256次：未中獎 再接再厲，觸發正常抽獎
第257次：未中獎 再接再厲，觸發正常抽獎
第258次：未中獎 再接再厲，觸發正常抽獎
第259次：未中獎 再接再厲，觸發正常抽獎
第260次：未中獎 再接再厲，觸發正常抽獎
第261次：未中獎 再接再厲，觸發正常抽獎
第262次：未中獎 再接再厲，觸發正常抽獎
第263次：未中獎 再接再厲，觸發正常抽獎
第264次：未中獎 再接再厲，觸發正常抽獎
第265次：貳獎 200元，觸發正常抽獎
第266次：未中獎 再接再厲，觸發正常抽獎
第267次：貳獎 200元，觸發正常抽獎
第268次：未中獎 再接再厲，觸發正常抽獎
第269次：未中獎 再接再厲，觸發正常抽獎
第270次：未中獎 再接再厲，觸發正常抽獎
第271次：未中獎 再接再厲，觸發正常抽獎
第272次：未中獎 再接再厲，觸發正常抽獎
第273次：未中獎 再接再厲，觸發正常抽獎
第274次：未中獎 再接再厲，觸發正常抽獎
第275次：未中獎 再接再厲，觸發正常抽獎
第276次：未中獎 再接再厲，觸發正常抽獎
第277次：未中獎 再接再厲，觸發正常抽獎
第278次：未中獎 再接再厲，觸發正常抽獎
第279次：未中獎 再接再厲，觸發正常抽獎
第280次：頭獎 500 元，觸發正常抽獎
第281次：未中獎 再接再厲，觸發正常抽獎
第282次：未中獎 再接再厲，觸發正常抽獎
第283次：未中獎 再接再厲，觸發正常抽獎
第284次：未中獎 再接再厲，觸發正常抽獎
第285次：未中獎 再接再厲，觸發正常抽獎
第286次：未中獎 再接再厲，觸發正常抽獎
第287次：未中獎 再接再厲，觸發正常抽獎
第288次：未中獎 再接再厲，觸發正常抽獎
第289次：未中獎 再接再厲，觸發正常抽獎
第290次：未中獎 再接再厲，觸發正常抽獎
第291次：貳獎 200元，觸發正常抽獎
第292次：未中獎 再接再厲，觸發正常抽獎
第293次：未中獎 再接再厲，觸發正常抽獎
第294次：未中獎 再接再厲，觸發正常抽獎
第295次：未中獎 再接再厲，觸發正常抽獎
第296次：未中獎 再接再厲，觸發正常抽獎
第297次：未中獎 再接再厲，觸發正常抽獎
第298次：貳獎 200元，觸發正常抽獎
第299次：未中獎 再接再厲，觸發正常抽獎
第300次：未中獎 再接再厲，觸發正常抽獎
第301次：未中獎 再接再厲，觸發正常抽獎
第302次：貳獎 200元，觸發正常抽獎
第303次：未中獎 再接再厲，觸發正常抽獎
第304次：未中獎 再接再厲，觸發正常抽獎
第305次：未中獎 再接再厲，觸發正常抽獎
第306次：未中獎 再接再厲，觸發正常抽獎
第307次：未中獎 再接再厲，觸發正常抽獎
第308次：未中獎 再接再厲，觸發正常抽獎
第309次：未中獎 再接再厲，觸發正常抽獎
第310次：頭獎 500 元，觸發正常抽獎
第311次：未中獎 再接再厲，觸發正常抽獎
第312次：未中獎 再接再厲，觸發正常抽獎
第313次：未中獎 再接再厲，觸發正常抽獎
第314次：未中獎 再接再厲，觸發正常抽獎
第315次：未中獎 再接再厲，觸發正常抽獎
第316次：貳獎 200元，觸發正常抽獎
第317次：未中獎 再接再厲，觸發正常抽獎
第318次：未中獎 再接再厲，觸發正常抽獎
第319次：未中獎 再接再厲，觸發正常抽獎
第320次：未中獎 再接再厲，觸發正常抽獎
第321次：未中獎 再接再厲，觸發正常抽獎
第322次：未中獎 再接再厲，觸發正常抽獎
第323次：未中獎 再接再厲，觸發正常抽獎
第324次：未中獎 再接再厲，觸發正常抽獎
第325次：未中獎 再接再厲，觸發正常抽獎
第326次：貳獎 200元，觸發正常抽獎
第327次：未中獎 再接再厲，觸發正常抽獎
第328次：未中獎 再接再厲，觸發正常抽獎
第329次：未中獎 再接再厲，觸發正常抽獎
第330次：未中獎 再接再厲，觸發正常抽獎
第331次：未中獎 再接再厲，觸發正常抽獎
第332次：未中獎 再接再厲，觸發正常抽獎
第333次：貳獎 200元，觸發正常抽獎
第334次：未中獎 再接再厲，觸發正常抽獎
第335次：貳獎 200元，觸發正常抽獎
第336次：未中獎 再接再厲，觸發正常抽獎
第337次：未中獎 再接再厲，觸發正常抽獎
第338次：未中獎 再接再厲，觸發正常抽獎
第339次：未中獎 再接再厲，觸發正常抽獎
第340次：未中獎 再接再厲，觸發正常抽獎
第341次：未中獎 再接再厲，觸發正常抽獎
第342次：貳獎 200元，觸發正常抽獎
第343次：未中獎 再接再厲，觸發正常抽獎
第344次：未中獎 再接再厲，觸發正常抽獎
第345次：未中獎 再接再厲，觸發正常抽獎
第346次：未中獎 再接再厲，觸發正常抽獎
第347次：未中獎 再接再厲，觸發正常抽獎
第348次：頭獎 500 元，觸發正常抽獎
第349次：未中獎 再接再厲，觸發正常抽獎
第350次：未中獎 再接再厲，觸發正常抽獎
第351次：未中獎 再接再厲，觸發正常抽獎
第352次：未中獎 再接再厲，觸發正常抽獎
第353次：未中獎 再接再厲，觸發正常抽獎
第354次：未中獎 再接再厲，觸發正常抽獎
第355次：未中獎 再接再厲，觸發正常抽獎
第356次：未中獎 再接再厲，觸發正常抽獎
第357次：未中獎 再接再厲，觸發正常抽獎
第358次：未中獎 再接再厲，觸發正常抽獎
第359次：貳獎 200元，觸發正常抽獎
第360次：未中獎 再接再厲，觸發正常抽獎
第361次：未中獎 再接再厲，觸發正常抽獎
第362次：未中獎 再接再厲，觸發正常抽獎
第363次：未中獎 再接再厲，觸發正常抽獎
第364次：未中獎 再接再厲，觸發正常抽獎
第365次：頭獎 500 元，觸發正常抽獎
第366次：未中獎 再接再厲，觸發正常抽獎
第367次：頭獎 500 元，觸發正常抽獎
第368次：未中獎 再接再厲，觸發正常抽獎
第369次：未中獎 再接再厲，觸發正常抽獎
第370次：未中獎 再接再厲，觸發正常抽獎
第371次：未中獎 再接再厲，觸發正常抽獎
第372次：頭獎 500 元，觸發正常抽獎
第373次：未中獎 再接再厲，觸發正常抽獎
第374次：未中獎 再接再厲，觸發正常抽獎
第375次：未中獎 再接再厲，觸發正常抽獎
第376次：未中獎 再接再厲，觸發正常抽獎
第377次：未中獎 再接再厲，觸發正常抽獎
第378次：未中獎 再接再厲，觸發正常抽獎
第379次：未中獎 再接再厲，觸發正常抽獎
第380次：未中獎 再接再厲，觸發正常抽獎
第381次：未中獎 再接再厲，觸發正常抽獎
第382次：未中獎 再接再厲，觸發正常抽獎
第383次：未中獎 再接再厲，觸發正常抽獎
第384次：未中獎 再接再厲，觸發正常抽獎
第385次：未中獎 再接再厲，觸發正常抽獎
第386次：未中獎 再接再厲，觸發正常抽獎
第387次：未中獎 再接再厲，觸發正常抽獎
第388次：頭獎 500 元，觸發正常抽獎
第389次：頭獎 500 元，觸發正常抽獎
第390次：未中獎 再接再厲，觸發正常抽獎
第391次：未中獎 再接再厲，觸發正常抽獎
第392次：未中獎 再接再厲，觸發正常抽獎
第393次：未中獎 再接再厲，觸發正常抽獎
第394次：未中獎 再接再厲，觸發正常抽獎
第395次：未中獎 再接再厲，觸發正常抽獎
第396次：未中獎 再接再厲，觸發正常抽獎
第397次：未中獎 再接再厲，觸發正常抽獎
第398次：頭獎 500 元，觸發正常抽獎
第399次：未中獎 再接再厲，觸發正常抽獎
第400次：未中獎 再接再厲，觸發正常抽獎
第401次：未中獎 再接再厲，觸發正常抽獎
第402次：未中獎 再接再厲，觸發正常抽獎
第403次：未中獎 再接再厲，觸發正常抽獎
第404次：未中獎 再接再厲，觸發正常抽獎
第405次：未中獎 再接再厲，觸發正常抽獎
第406次：未中獎 再接再厲，觸發正常抽獎
第407次：未中獎 再接再厲，觸發正常抽獎
第408次：未中獎 再接再厲，觸發正常抽獎
第409次：未中獎 再接再厲，觸發正常抽獎
第410次：未中獎 再接再厲，觸發正常抽獎
第411次：未中獎 再接再厲，觸發正常抽獎
第412次：未中獎 再接再厲，觸發正常抽獎
第413次：未中獎 再接再厲，觸發正常抽獎
第414次：頭獎 500 元，觸發正常抽獎
第415次：貳獎 200元，觸發正常抽獎
第416次：未中獎 再接再厲，觸發正常抽獎
第417次：頭獎 500 元，觸發正常抽獎
第418次：未中獎 再接再厲，觸發正常抽獎
第419次：未中獎 再接再厲，觸發正常抽獎
第420次：未中獎 再接再厲，觸發正常抽獎
第421次：貳獎 200元，觸發正常抽獎
第422次：未中獎 再接再厲，觸發正常抽獎
第423次：未中獎 再接再厲，觸發正常抽獎
第424次：未中獎 再接再厲，觸發正常抽獎
第425次：未中獎 再接再厲，觸發正常抽獎
第426次：未中獎 再接再厲，觸發正常抽獎
第427次：未中獎 再接再厲，觸發正常抽獎
第428次：未中獎 再接再厲，觸發正常抽獎
第429次：未中獎 再接再厲，觸發正常抽獎
第430次：未中獎 再接再厲，觸發正常抽獎
第431次：未中獎 再接再厲，觸發正常抽獎
第432次：未中獎 再接再厲，觸發正常抽獎
第433次：未中獎 再接再厲，觸發正常抽獎
第434次：未中獎 再接再厲，觸發正常抽獎
第435次：未中獎 再接再厲，觸發正常抽獎
第436次：未中獎 再接再厲，觸發正常抽獎
第437次：未中獎 再接再厲，觸發正常抽獎
第438次：未中獎 再接再厲，觸發正常抽獎
第439次：貳獎 200元，觸發正常抽獎
第440次：未中獎 再接再厲，觸發正常抽獎
第441次：未中獎 再接再厲，觸發正常抽獎
第442次：未中獎 再接再厲，觸發正常抽獎
第443次：未中獎 再接再厲，觸發正常抽獎
第444次：未中獎 再接再厲，觸發正常抽獎
第445次：貳獎 200元，觸發正常抽獎
第446次：未中獎 再接再厲，觸發正常抽獎
第447次：未中獎 再接再厲，觸發正常抽獎
第448次：未中獎 再接再厲，觸發正常抽獎
第449次：貳獎 200元，觸發正常抽獎
第450次：未中獎 再接再厲，觸發正常抽獎
第451次：未中獎 再接再厲，觸發正常抽獎
第452次：未中獎 再接再厲，觸發正常抽獎
第453次：未中獎 再接再厲，觸發正常抽獎
第454次：未中獎 再接再厲，觸發正常抽獎
第455次：未中獎 再接再厲，觸發正常抽獎
第456次：未中獎 再接再厲，觸發正常抽獎
第457次：未中獎 再接再厲，觸發正常抽獎
第458次：未中獎 再接再厲，觸發正常抽獎
第459次：未中獎 再接再厲，觸發正常抽獎
第460次：未中獎 再接再厲，觸發正常抽獎
第461次：未中獎 再接再厲，觸發正常抽獎
第462次：未中獎 再接再厲，觸發正常抽獎
第463次：貳獎 200元，觸發正常抽獎
第464次：未中獎 再接再厲，觸發正常抽獎
第465次：未中獎 再接再厲，觸發正常抽獎
第466次：未中獎 再接再厲，觸發正常抽獎
第467次：未中獎 再接再厲，觸發正常抽獎
第468次：未中獎 再接再厲，觸發正常抽獎
第469次：未中獎 再接再厲，觸發正常抽獎
第470次：未中獎 再接再厲，觸發正常抽獎
第471次：貳獎 200元，觸發正常抽獎
第472次：未中獎 再接再厲，觸發正常抽獎
第473次：未中獎 再接再厲，觸發正常抽獎
第474次：未中獎 再接再厲，觸發正常抽獎
第475次：未中獎 再接再厲，觸發正常抽獎
第476次：未中獎 再接再厲，觸發正常抽獎
第477次：未中獎 再接再厲，觸發正常抽獎
第478次：貳獎 200元，觸發正常抽獎
第479次：未中獎 再接再厲，觸發正常抽獎
第480次：未中獎 再接再厲，觸發正常抽獎
第481次：未中獎 再接再厲，觸發正常抽獎
第482次：未中獎 再接再厲，觸發正常抽獎
第483次：未中獎 再接再厲，觸發正常抽獎
第484次：未中獎 再接再厲，觸發正常抽獎
第485次：未中獎 再接再厲，觸發正常抽獎
第486次：未中獎 再接再厲，觸發正常抽獎
第487次：未中獎 再接再厲，觸發正常抽獎
第488次：未中獎 再接再厲，觸發正常抽獎
第489次：未中獎 再接再厲，觸發正常抽獎
第490次：未中獎 再接再厲，觸發正常抽獎
第491次：未中獎 再接再厲，觸發正常抽獎
第492次：未中獎 再接再厲，觸發正常抽獎
第493次：未中獎 再接再厲，觸發正常抽獎
第494次：未中獎 再接再厲，觸發正常抽獎
第495次：未中獎 再接再厲，觸發正常抽獎
第496次：未中獎 再接再厲，觸發正常抽獎
第497次：未中獎 再接再厲，觸發正常抽獎
第498次：頭獎 500 元，觸發20抽大保
第499次：貳獎 200元，觸發正常抽獎
第500次：未中獎 再接再厲，觸發正常抽獎
第501次：頭獎 500 元，觸發正常抽獎
第502次：未中獎 再接再厲，觸發正常抽獎
第503次：貳獎 200元，觸發正常抽獎
第504次：未中獎 再接再厲，觸發正常抽獎
第505次：未中獎 再接再厲，觸發正常抽獎
第506次：未中獎 再接再厲，觸發正常抽獎
第507次：未中獎 再接再厲，觸發正常抽獎
第508次：未中獎 再接再厲，觸發正常抽獎
第509次：未中獎 再接再厲，觸發正常抽獎
第510次：未中獎 再接再厲，觸發正常抽獎
第511次：未中獎 再接再厲，觸發正常抽獎
第512次：貳獎 200元，觸發正常抽獎
第513次：未中獎 再接再厲，觸發正常抽獎
第514次：未中獎 再接再厲，觸發正常抽獎
第515次：未中獎 再接再厲，觸發正常抽獎
第516次：貳獎 200元，觸發正常抽獎
第517次：未中獎 再接再厲，觸發正常抽獎
第518次：未中獎 再接再厲，觸發正常抽獎
第519次：未中獎 再接再厲，觸發正常抽獎
第520次：未中獎 再接再厲，觸發正常抽獎
第521次：未中獎 再接再厲，觸發正常抽獎
第522次：未中獎 再接再厲，觸發正常抽獎
第523次：未中獎 再接再厲，觸發正常抽獎
第524次：貳獎 200元，觸發正常抽獎
第525次：未中獎 再接再厲，觸發正常抽獎
第526次：未中獎 再接再厲，觸發正常抽獎
第527次：貳獎 200元，觸發正常抽獎
第528次：未中獎 再接再厲，觸發正常抽獎
第529次：未中獎 再接再厲，觸發正常抽獎
第530次：未中獎 再接再厲，觸發正常抽獎
第531次：未中獎 再接再厲，觸發正常抽獎
第532次：未中獎 再接再厲，觸發正常抽獎
第533次：貳獎 200元，觸發正常抽獎
第534次：未中獎 再接再厲，觸發正常抽獎
第535次：未中獎 再接再厲，觸發正常抽獎
第536次：未中獎 再接再厲，觸發正常抽獎
第537次：未中獎 再接再厲，觸發正常抽獎
第538次：未中獎 再接再厲，觸發正常抽獎
第539次：未中獎 再接再厲，觸發正常抽獎
第540次：貳獎 200元，觸發正常抽獎
第541次：未中獎 再接再厲，觸發正常抽獎
第542次：未中獎 再接再厲，觸發正常抽獎
第543次：未中獎 再接再厲，觸發正常抽獎
第544次：未中獎 再接再厲，觸發正常抽獎
第545次：未中獎 再接再厲，觸發正常抽獎
第546次：未中獎 再接再厲，觸發正常抽獎
第547次：未中獎 再接再厲，觸發正常抽獎
第548次：未中獎 再接再厲，觸發正常抽獎
第549次：未中獎 再接再厲，觸發正常抽獎
第550次：未中獎 再接再厲，觸發正常抽獎
第551次：未中獎 再接再厲，觸發正常抽獎
第552次：未中獎 再接再厲，觸發正常抽獎
第553次：未中獎 再接再厲，觸發正常抽獎
第554次：未中獎 再接再厲，觸發正常抽獎
第555次：未中獎 再接再厲，觸發正常抽獎
第556次：未中獎 再接再厲，觸發正常抽獎
第557次：未中獎 再接再厲，觸發正常抽獎
第558次：未中獎 再接再厲，觸發正常抽獎
第559次：未中獎 再接再厲，觸發正常抽獎
第560次：頭獎 500 元，觸發20抽大保
第561次：未中獎 再接再厲，觸發正常抽獎
第562次：未中獎 再接再厲，觸發正常抽獎
第563次：未中獎 再接再厲，觸發正常抽獎
第564次：未中獎 再接再厲，觸發正常抽獎
第565次：未中獎 再接再厲，觸發正常抽獎
第566次：頭獎 500 元，觸發正常抽獎
第567次：頭獎 500 元，觸發正常抽獎
第568次：未中獎 再接再厲，觸發正常抽獎
第569次：未中獎 再接再厲，觸發正常抽獎
第570次：未中獎 再接再厲，觸發正常抽獎
第571次：頭獎 500 元，觸發正常抽獎
第572次：貳獎 200元，觸發正常抽獎
第573次：未中獎 再接再厲，觸發正常抽獎
第574次：未中獎 再接再厲，觸發正常抽獎
第575次：未中獎 再接再厲，觸發正常抽獎
第576次：未中獎 再接再厲，觸發正常抽獎
第577次：未中獎 再接再厲，觸發正常抽獎
第578次：未中獎 再接再厲，觸發正常抽獎
第579次：未中獎 再接再厲，觸發正常抽獎
第580次：未中獎 再接再厲，觸發正常抽獎
第581次：未中獎 再接再厲，觸發正常抽獎
第582次：未中獎 再接再厲，觸發正常抽獎
第583次：未中獎 再接再厲，觸發正常抽獎
第584次：未中獎 再接再厲，觸發正常抽獎
第585次：頭獎 500 元，觸發正常抽獎
第586次：未中獎 再接再厲，觸發正常抽獎
第587次：未中獎 再接再厲，觸發正常抽獎
第588次：頭獎 500 元，觸發正常抽獎
第589次：未中獎 再接再厲，觸發正常抽獎
第590次：未中獎 再接再厲，觸發正常抽獎
第591次：未中獎 再接再厲，觸發正常抽獎
第592次：未中獎 再接再厲，觸發正常抽獎
第593次：未中獎 再接再厲，觸發正常抽獎
第594次：未中獎 再接再厲，觸發正常抽獎
第595次：貳獎 200元，觸發正常抽獎
第596次：未中獎 再接再厲，觸發正常抽獎
第597次：未中獎 再接再厲，觸發正常抽獎
第598次：未中獎 再接再厲，觸發正常抽獎
第599次：未中獎 再接再厲，觸發正常抽獎
第600次：未中獎 再接再厲，觸發正常抽獎
第601次：未中獎 再接再厲，觸發正常抽獎
第602次：未中獎 再接再厲，觸發正常抽獎
第603次：未中獎 再接再厲，觸發正常抽獎
第604次：未中獎 再接再厲，觸發正常抽獎
第605次：未中獎 再接再厲，觸發正常抽獎
第606次：貳獎 200元，觸發正常抽獎
第607次：未中獎 再接再厲，觸發正常抽獎
第608次：未中獎 再接再厲，觸發正常抽獎
第609次：未中獎 再接再厲，觸發正常抽獎
第610次：未中獎 再接再厲，觸發正常抽獎
第611次：未中獎 再接再厲，觸發正常抽獎
第612次：未中獎 再接再厲，觸發正常抽獎
第613次：貳獎 200元，觸發正常抽獎
第614次：未中獎 再接再厲，觸發正常抽獎
第615次：未中獎 再接再厲，觸發正常抽獎
第616次：未中獎 再接再厲，觸發正常抽獎
第617次：未中獎 再接再厲，觸發正常抽獎
第618次：未中獎 再接再厲，觸發正常抽獎
第619次：未中獎 再接再厲，觸發正常抽獎
第620次：未中獎 再接再厲，觸發正常抽獎
第621次：未中獎 再接再厲，觸發正常抽獎
第622次：未中獎 再接再厲，觸發正常抽獎
第623次：貳獎 200元，觸發正常抽獎
第624次：貳獎 200元，觸發正常抽獎
第625次：未中獎 再接再厲，觸發正常抽獎
第626次：貳獎 200元，觸發正常抽獎
第627次：未中獎 再接再厲，觸發正常抽獎
第628次：未中獎 再接再厲，觸發正常抽獎
第629次：未中獎 再接再厲，觸發正常抽獎
第630次：未中獎 再接再厲，觸發正常抽獎
第631次：未中獎 再接再厲，觸發正常抽獎
第632次：未中獎 再接再厲，觸發正常抽獎
第633次：未中獎 再接再厲，觸發正常抽獎
第634次：未中獎 再接再厲，觸發正常抽獎
第635次：貳獎 200元，觸發正常抽獎
第636次：貳獎 200元，觸發正常抽獎
第637次：未中獎 再接再厲，觸發正常抽獎
第638次：未中獎 再接再厲，觸發正常抽獎
第639次：未中獎 再接再厲，觸發正常抽獎
第640次：未中獎 再接再厲，觸發正常抽獎
第641次：未中獎 再接再厲，觸發正常抽獎
第642次：未中獎 再接再厲，觸發正常抽獎
第643次：未中獎 再接再厲，觸發正常抽獎
第644次：未中獎 再接再厲，觸發正常抽獎
第645次：未中獎 再接再厲，觸發正常抽獎
第646次：未中獎 再接再厲，觸發正常抽獎
第647次：貳獎 200元，觸發正常抽獎
第648次：未中獎 再接再厲，觸發正常抽獎
第649次：未中獎 再接再厲，觸發正常抽獎
第650次：未中獎 再接再厲，觸發正常抽獎
第651次：貳獎 200元，觸發正常抽獎
第652次：未中獎 再接再厲，觸發正常抽獎
第653次：未中獎 再接再厲，觸發正常抽獎
第654次：頭獎 500 元，觸發正常抽獎
第655次：未中獎 再接再厲，觸發正常抽獎
第656次：未中獎 再接再厲，觸發正常抽獎
第657次：未中獎 再接再厲，觸發正常抽獎
第658次：未中獎 再接再厲，觸發正常抽獎
第659次：貳獎 200元，觸發正常抽獎
第660次：未中獎 再接再厲，觸發正常抽獎
第661次：未中獎 再接再厲，觸發正常抽獎
第662次：未中獎 再接再厲，觸發正常抽獎
第663次：未中獎 再接再厲，觸發正常抽獎
第664次：未中獎 再接再厲，觸發正常抽獎
第665次：未中獎 再接再厲，觸發正常抽獎
第666次：未中獎 再接再厲，觸發正常抽獎
第667次：貳獎 200元，觸發正常抽獎
第668次：未中獎 再接再厲，觸發正常抽獎
第669次：未中獎 再接再厲，觸發正常抽獎
第670次：貳獎 200元，觸發正常抽獎
第671次：未中獎 再接再厲，觸發正常抽獎
第672次：未中獎 再接再厲，觸發正常抽獎
第673次：貳獎 200元，觸發正常抽獎
第674次：未中獎 再接再厲，觸發正常抽獎
第675次：未中獎 再接再厲，觸發正常抽獎
第676次：未中獎 再接再厲，觸發正常抽獎
第677次：未中獎 再接再厲，觸發正常抽獎
第678次：未中獎 再接再厲，觸發正常抽獎
第679次：未中獎 再接再厲，觸發正常抽獎
第680次：未中獎 再接再厲，觸發正常抽獎
第681次：未中獎 再接再厲，觸發正常抽獎
第682次：未中獎 再接再厲，觸發正常抽獎
第683次：未中獎 再接再厲，觸發正常抽獎
第684次：未中獎 再接再厲，觸發正常抽獎
第685次：未中獎 再接再厲，觸發正常抽獎
第686次：未中獎 再接再厲，觸發正常抽獎
第687次：貳獎 200元，觸發正常抽獎
第688次：未中獎 再接再厲，觸發正常抽獎
第689次：未中獎 再接再厲，觸發正常抽獎
第690次：貳獎 200元，觸發正常抽獎
第691次：未中獎 再接再厲，觸發正常抽獎
第692次：頭獎 500 元，觸發正常抽獎
第693次：未中獎 再接再厲，觸發正常抽獎
第694次：貳獎 200元，觸發正常抽獎
第695次：未中獎 再接再厲，觸發正常抽獎
第696次：未中獎 再接再厲，觸發正常抽獎
第697次：未中獎 再接再厲，觸發正常抽獎
第698次：未中獎 再接再厲，觸發正常抽獎
第699次：頭獎 500 元，觸發正常抽獎
第700次：未中獎 再接再厲，觸發正常抽獎
第701次：未中獎 再接再厲，觸發正常抽獎
第702次：未中獎 再接再厲，觸發正常抽獎
第703次：未中獎 再接再厲，觸發正常抽獎
第704次：頭獎 500 元，觸發正常抽獎
第705次：未中獎 再接再厲，觸發正常抽獎
第706次：頭獎 500 元，觸發正常抽獎
第707次：貳獎 200元，觸發正常抽獎
第708次：未中獎 再接再厲，觸發正常抽獎
第709次：貳獎 200元，觸發正常抽獎
第710次：未中獎 再接再厲，觸發正常抽獎
第711次：未中獎 再接再厲，觸發正常抽獎
第712次：未中獎 再接再厲，觸發正常抽獎
第713次：未中獎 再接再厲，觸發正常抽獎
第714次：未中獎 再接再厲，觸發正常抽獎
第715次：未中獎 再接再厲，觸發正常抽獎
第716次：未中獎 再接再厲，觸發正常抽獎
第717次：未中獎 再接再厲，觸發正常抽獎
第718次：未中獎 再接再厲，觸發正常抽獎
第719次：貳獎 200元，觸發正常抽獎
第720次：未中獎 再接再厲，觸發正常抽獎
第721次：未中獎 再接再厲，觸發正常抽獎
第722次：未中獎 再接再厲，觸發正常抽獎
第723次：未中獎 再接再厲，觸發正常抽獎
第724次：未中獎 再接再厲，觸發正常抽獎
第725次：未中獎 再接再厲，觸發正常抽獎
第726次：未中獎 再接再厲，觸發正常抽獎
第727次：未中獎 再接再厲，觸發正常抽獎
第728次：貳獎 200元，觸發正常抽獎
第729次：貳獎 200元，觸發正常抽獎
第730次：未中獎 再接再厲，觸發正常抽獎
第731次：未中獎 再接再厲，觸發正常抽獎
第732次：貳獎 200元，觸發正常抽獎
第733次：未中獎 再接再厲，觸發正常抽獎
第734次：貳獎 200元，觸發正常抽獎
第735次：未中獎 再接再厲，觸發正常抽獎
第736次：未中獎 再接再厲，觸發正常抽獎
第737次：未中獎 再接再厲，觸發正常抽獎
第738次：未中獎 再接再厲，觸發正常抽獎
第739次：未中獎 再接再厲，觸發正常抽獎
第740次：未中獎 再接再厲，觸發正常抽獎
第741次：未中獎 再接再厲，觸發正常抽獎
第742次：未中獎 再接再厲，觸發正常抽獎
第743次：未中獎 再接再厲，觸發正常抽獎
第744次：未中獎 再接再厲，觸發正常抽獎
第745次：未中獎 再接再厲，觸發正常抽獎
第746次：未中獎 再接再厲，觸發正常抽獎
第747次：未中獎 再接再厲，觸發正常抽獎
第748次：未中獎 再接再厲，觸發正常抽獎
第749次：貳獎 200元，觸發正常抽獎
第750次：未中獎 再接再厲，觸發正常抽獎
第751次：未中獎 再接再厲，觸發正常抽獎
第752次：未中獎 再接再厲，觸發正常抽獎
第753次：未中獎 再接再厲，觸發正常抽獎
第754次：頭獎 500 元，觸發正常抽獎
第755次：未中獎 再接再厲，觸發正常抽獎
第756次：未中獎 再接再厲，觸發正常抽獎
第757次：未中獎 再接再厲，觸發正常抽獎
第758次：未中獎 再接再厲，觸發正常抽獎
第759次：貳獎 200元，觸發正常抽獎
第760次：未中獎 再接再厲，觸發正常抽獎
第761次：未中獎 再接再厲，觸發正常抽獎
第762次：未中獎 再接再厲，觸發正常抽獎
第763次：未中獎 再接再厲，觸發正常抽獎
第764次：貳獎 200元，觸發正常抽獎
第765次：未中獎 再接再厲，觸發正常抽獎
第766次：未中獎 再接再厲，觸發正常抽獎
第767次：未中獎 再接再厲，觸發正常抽獎
第768次：未中獎 再接再厲，觸發正常抽獎
第769次：未中獎 再接再厲，觸發正常抽獎
第770次：未中獎 再接再厲，觸發正常抽獎
第771次：未中獎 再接再厲，觸發正常抽獎
第772次：未中獎 再接再厲，觸發正常抽獎
第773次：未中獎 再接再厲，觸發正常抽獎
第774次：貳獎 200元，觸發正常抽獎
第775次：未中獎 再接再厲，觸發正常抽獎
第776次：未中獎 再接再厲，觸發正常抽獎
第777次：未中獎 再接再厲，觸發正常抽獎
第778次：貳獎 200元，觸發正常抽獎
第779次：未中獎 再接再厲，觸發正常抽獎
第780次：未中獎 再接再厲，觸發正常抽獎
第781次：未中獎 再接再厲，觸發正常抽獎
第782次：頭獎 500 元，觸發正常抽獎
第783次：頭獎 500 元，觸發正常抽獎
第784次：頭獎 500 元，觸發正常抽獎
第785次：未中獎 再接再厲，觸發正常抽獎
第786次：貳獎 200元，觸發正常抽獎
第787次：未中獎 再接再厲，觸發正常抽獎
第788次：未中獎 再接再厲，觸發正常抽獎
第789次：未中獎 再接再厲，觸發正常抽獎
第790次：未中獎 再接再厲，觸發正常抽獎
第791次：未中獎 再接再厲，觸發正常抽獎
第792次：未中獎 再接再厲，觸發正常抽獎
第793次：未中獎 再接再厲，觸發正常抽獎
第794次：未中獎 再接再厲，觸發正常抽獎
第795次：未中獎 再接再厲，觸發正常抽獎
第796次：未中獎 再接再厲，觸發正常抽獎
第797次：未中獎 再接再厲，觸發正常抽獎
第798次：未中獎 再接再厲，觸發正常抽獎
第799次：未中獎 再接再厲，觸發正常抽獎
第800次：未中獎 再接再厲，觸發正常抽獎
第801次：未中獎 再接再厲，觸發正常抽獎
第802次：貳獎 200元，觸發正常抽獎
第803次：未中獎 再接再厲，觸發正常抽獎
第804次：未中獎 再接再厲，觸發正常抽獎
第805次：未中獎 再接再厲，觸發正常抽獎
第806次：未中獎 再接再厲，觸發正常抽獎
第807次：貳獎 200元，觸發正常抽獎
第808次：未中獎 再接再厲，觸發正常抽獎
第809次：未中獎 再接再厲，觸發正常抽獎
第810次：頭獎 500 元，觸發正常抽獎
第811次：未中獎 再接再厲，觸發正常抽獎
第812次：貳獎 200元，觸發正常抽獎
第813次：未中獎 再接再厲，觸發正常抽獎
第814次：未中獎 再接再厲，觸發正常抽獎
第815次：未中獎 再接再厲，觸發正常抽獎
第816次：貳獎 200元，觸發正常抽獎
第817次：未中獎 再接再厲，觸發正常抽獎
第818次：貳獎 200元，觸發正常抽獎
第819次：未中獎 再接再厲，觸發正常抽獎
第820次：未中獎 再接再厲，觸發正常抽獎
第821次：未中獎 再接再厲，觸發正常抽獎
第822次：未中獎 再接再厲，觸發正常抽獎
第823次：未中獎 再接再厲，觸發正常抽獎
第824次：未中獎 再接再厲，觸發正常抽獎
第825次：未中獎 再接再厲，觸發正常抽獎
第826次：貳獎 200元，觸發正常抽獎
第827次：未中獎 再接再厲，觸發正常抽獎
第828次：未中獎 再接再厲，觸發正常抽獎
第829次：未中獎 再接再厲，觸發正常抽獎
第830次：未中獎 再接再厲，觸發正常抽獎
第831次：頭獎 500 元，觸發正常抽獎
第832次：未中獎 再接再厲，觸發正常抽獎
第833次：未中獎 再接再厲，觸發正常抽獎
第834次：頭獎 500 元，觸發正常抽獎
第835次：未中獎 再接再厲，觸發正常抽獎
第836次：未中獎 再接再厲，觸發正常抽獎
第837次：未中獎 再接再厲，觸發正常抽獎
第838次：未中獎 再接再厲，觸發正常抽獎
第839次：未中獎 再接再厲，觸發正常抽獎
第840次：未中獎 再接再厲，觸發正常抽獎
第841次：未中獎 再接再厲，觸發正常抽獎
第842次：未中獎 再接再厲，觸發正常抽獎
第843次：未中獎 再接再厲，觸發正常抽獎
第844次：未中獎 再接再厲，觸發正常抽獎
第845次：未中獎 再接再厲，觸發正常抽獎
第846次：貳獎 200元，觸發正常抽獎
第847次：未中獎 再接再厲，觸發正常抽獎
第848次：貳獎 200元，觸發正常抽獎
第849次：頭獎 500 元，觸發正常抽獎
第850次：未中獎 再接再厲，觸發正常抽獎
第851次：未中獎 再接再厲，觸發正常抽獎
第852次：未中獎 再接再厲，觸發正常抽獎
第853次：未中獎 再接再厲，觸發正常抽獎
第854次：未中獎 再接再厲，觸發正常抽獎
第855次：未中獎 再接再厲，觸發正常抽獎
第856次：未中獎 再接再厲，觸發正常抽獎
第857次：未中獎 再接再厲，觸發正常抽獎
第858次：未中獎 再接再厲，觸發正常抽獎
第859次：未中獎 再接再厲，觸發正常抽獎
第860次：未中獎 再接再厲，觸發正常抽獎
第861次：未中獎 再接再厲，觸發正常抽獎
第862次：未中獎 再接再厲，觸發正常抽獎
第863次：頭獎 500 元，觸發正常抽獎
第864次：頭獎 500 元，觸發正常抽獎
第865次：未中獎 再接再厲，觸發正常抽獎
第866次：未中獎 再接再厲，觸發正常抽獎
第867次：未中獎 再接再厲，觸發正常抽獎
第868次：未中獎 再接再厲，觸發正常抽獎
第869次：未中獎 再接再厲，觸發正常抽獎
第870次：未中獎 再接再厲，觸發正常抽獎
第871次：未中獎 再接再厲，觸發正常抽獎
第872次：未中獎 再接再厲，觸發正常抽獎
第873次：未中獎 再接再厲，觸發正常抽獎
第874次：未中獎 再接再厲，觸發正常抽獎
第875次：未中獎 再接再厲，觸發正常抽獎
第876次：未中獎 再接再厲，觸發正常抽獎
第877次：頭獎 500 元，觸發正常抽獎
第878次：未中獎 再接再厲，觸發正常抽獎
第879次：未中獎 再接再厲，觸發正常抽獎
第880次：未中獎 再接再厲，觸發正常抽獎
第881次：未中獎 再接再厲，觸發正常抽獎
第882次：未中獎 再接再厲，觸發正常抽獎
第883次：未中獎 再接再厲，觸發正常抽獎
第884次：貳獎 200元，觸發正常抽獎
第885次：未中獎 再接再厲，觸發正常抽獎
第886次：未中獎 再接再厲，觸發正常抽獎
第887次：貳獎 200元，觸發正常抽獎
第888次：未中獎 再接再厲，觸發正常抽獎
第889次：未中獎 再接再厲，觸發正常抽獎
第890次：未中獎 再接再厲，觸發正常抽獎
第891次：未中獎 再接再厲，觸發正常抽獎
第892次：未中獎 再接再厲，觸發正常抽獎
第893次：未中獎 再接再厲，觸發正常抽獎
第894次：未中獎 再接再厲，觸發正常抽獎
第895次：未中獎 再接再厲，觸發正常抽獎
第896次：未中獎 再接再厲，觸發正常抽獎
第897次：貳獎 200元，觸發正常抽獎
第898次：未中獎 再接再厲，觸發正常抽獎
第899次：未中獎 再接再厲，觸發正常抽獎
第900次：未中獎 再接再厲，觸發正常抽獎
第901次：未中獎 再接再厲，觸發正常抽獎
第902次：未中獎 再接再厲，觸發正常抽獎
第903次：未中獎 再接再厲，觸發正常抽獎
第904次：貳獎 200元，觸發正常抽獎
第905次：未中獎 再接再厲，觸發正常抽獎
第906次：未中獎 再接再厲，觸發正常抽獎
第907次：未中獎 再接再厲，觸發正常抽獎
第908次：未中獎 再接再厲，觸發正常抽獎
第909次：未中獎 再接再厲，觸發正常抽獎
第910次：未中獎 再接再厲，觸發正常抽獎
第911次：未中獎 再接再厲，觸發正常抽獎
第912次：未中獎 再接再厲，觸發正常抽獎
第913次：未中獎 再接再厲，觸發正常抽獎
第914次：未中獎 再接再厲，觸發正常抽獎
第915次：未中獎 再接再厲，觸發正常抽獎
第916次：未中獎 再接再厲，觸發正常抽獎

    樣本數 單次遊玩獎金期望值估計   標準誤  CI下界   CI上界
0  5000       44.28  1.68  41.0  47.56

帳號：1，已存在玩家資料
目前狀態：非新手期，您不具有新手保底
開始遊玩5000次
第1次：未中獎 再接再厲，觸發正常抽獎
第2次：未中獎 再接再厲，觸發正常抽獎
第3次：未中獎 再接再厲，觸發正常抽獎
第4次：未中獎 再接再厲，觸發正常抽獎
第5次：貳獎 200元，觸發正常抽獎
第6次：未中獎 再接再厲，觸發正常抽獎
第7次：未中獎 再接再厲，觸發正常抽獎
第8次：未中獎 再接再厲，觸發正常抽獎
第9次：貳獎 200元，觸發正常抽獎
第10次：未中獎 再接再厲，觸發正常抽獎
第11次：未中獎 再接再厲，觸發正常抽獎
第12次：未中獎 再接再厲，觸發正常抽獎
第13次：未中獎 再接再厲，觸發正常抽獎
第14次：貳獎 200元，觸發正常抽獎
第15次：未中獎 再接再厲，觸發正常抽獎
第16次：未中獎 再接再厲，觸發正常抽獎
第17次：未中獎 再接再厲，觸發正常抽獎
第18次：未中獎 再接再厲，觸發正常抽獎
第19次：頭獎 500 元，觸發正常抽獎
第20次：未中獎 再接再厲，觸發正常抽獎
第21次：未中獎 再接再厲，觸發正常抽獎
第22次：頭獎 500 元，觸發正常抽獎
第23次：未中獎 再接再厲，觸發正常抽獎
第24次：未中獎 再接再厲，觸發正常抽獎
第25次：未中獎 再接再厲，觸發正常抽獎
第26次：未中獎 再接再厲，觸發正常抽獎
第27次：未中獎 再接再厲，觸發正常抽獎
第28次：未中獎 再接再厲，觸發正常抽獎
第29次：未中獎 再接再厲，觸發正常抽獎
第30次：貳獎 200元，觸發正常抽獎
第31次：未中獎 再接再厲，觸發正常抽獎
第32次：未中獎 再接再厲，觸發正常抽獎
第33次：未中獎 再接再厲，觸發正常抽獎
第34次：未中獎 再接再厲，觸發正常抽獎
第35次：未中獎 再接再厲，觸發正常抽獎
第36次：未中獎 再接再厲，觸發正常抽獎
第37次：未中獎 再接再厲，觸發正常抽獎
第38次：未中獎 再接再厲，觸發正常抽獎
第39次：未中獎 再接再厲，觸發正常抽獎
第40次：未中獎 再接再厲，觸發正常抽獎
第41次：未中獎 再接再厲，觸發正常抽獎
第42次：未中獎 再接再厲，觸發正常抽獎
第43次：未中獎 再接再厲，觸發正常抽獎
第44次：未中獎 再接再厲，觸發正常抽獎
第45次：貳獎 200元，觸發正常抽獎
第46次：未中獎 再接再厲，觸發正常抽獎
第47次：未中獎 再接再厲，觸發正常抽獎
第48次：未中獎 再接再厲，觸發正常抽獎
第49次：未中獎 再接再厲，觸發正常抽獎
第50次：未中獎 再接再厲，觸發正常抽獎
第51次：未中獎 再接再厲，觸發正常抽獎
第52次：未中獎 再接再厲，觸發正常抽獎
第53次：未中獎 再接再厲，觸發正常抽獎
第54次：未中獎 再接再厲，觸發正常抽獎
第55次：未中獎 再接再厲，觸發正常抽獎
第56次：未中獎 再接再厲，觸發正常抽獎
第57次：未中獎 再接再厲，觸發正常抽獎
第58次：未中獎 再接再厲，觸發正常抽獎
第59次：未中獎 再接再厲，觸發正常抽獎
第60次：未中獎 再接再厲，觸發正常抽獎
第61次：貳獎 200元，觸發正常抽獎
第62次：貳獎 200元，觸發正常抽獎
第63次：未中獎 再接再厲，觸發正常抽獎
第64次：未中獎 再接再厲，觸發正常抽獎
第65次：未中獎 再接再厲，觸發正常抽獎
第66次：未中獎 再接再厲，觸發正常抽獎
第67次：未中獎 再接再厲，觸發正常抽獎
第68次：未中獎 再接再厲，觸發正常抽獎
第69次：未中獎 再接再厲，觸發正常抽獎
第70次：未中獎 再接再厲，觸發正常抽獎
第71次：頭獎 500 元，觸發正常抽獎
第72次：未中獎 再接再厲，觸發正常抽獎
第73次：未中獎 再接再厲，觸發正常抽獎
第74次：未中獎 再接再厲，觸發正常抽獎
第75次：未中獎 再接再厲，觸發正常抽獎
第76次：未中獎 再接再厲，觸發正常抽獎
第77次：貳獎 200元，觸發正常抽獎
第78次：未中獎 再接再厲，觸發正常抽獎
第79次：未中獎 再接再厲，觸發正常抽獎
第80次：頭獎 500 元，觸發正常抽獎
第81次：未中獎 再接再厲，觸發正常抽獎
第82次：貳獎 200元，觸發正常抽獎
第83次：未中獎 再接再厲，觸發正常抽獎
第84次：未中獎 再接再厲，觸發正常抽獎
第85次：未中獎 再接再厲，觸發正常抽獎
第86次：未中獎 再接再厲，觸發正常抽獎
第87次：未中獎 再接再厲，觸發正常抽獎
第88次：未中獎 再接再厲，觸發正常抽獎
第89次：頭獎 500 元，觸發正常抽獎
第90次：貳獎 200元，觸發正常抽獎
第91次：未中獎 再接再厲，觸發正常抽獎
第92次：未中獎 再接再厲，觸發正常抽獎
第93次：未中獎 再接再厲，觸發正常抽獎
第94次：未中獎 再接再厲，觸發正常抽獎
第95次：未中獎 再接再厲，觸發正常抽獎
第96次：未中獎 再接再厲，觸發正常抽獎
第97次：未中獎 再接再厲，觸發正常抽獎
第98次：未中獎 再接再厲，觸發正常抽獎
第99次：貳獎 200元，觸發正常抽獎
第100次：貳獎 200元，觸發正常抽獎
第101次：未中獎 再接再厲，觸發正常抽獎
第102次：未中獎 再接再厲，觸發正常抽獎
第103次：貳獎 200元，觸發正常抽獎
第104次：頭獎 500 元，觸發正常抽獎
第105次：未中獎 再接再厲，觸發正常抽獎
第106次：頭獎 500 元，觸發正常抽獎
第107次：未中獎 再接再厲，觸發正常抽獎
第108次：未中獎 再接再厲，觸發正常抽獎
第109次：未中獎 再接再厲，觸發正常抽獎
第110次：未中獎 再接再厲，觸發正常抽獎
第111次：未中獎 再接再厲，觸發正常抽獎
第112次：未中獎 再接再厲，觸發正常抽獎
第113次：未中獎 再接再厲，觸發正常抽獎
第114次：頭獎 500 元，觸發正常抽獎
第115次：未中獎 再接再厲，觸發正常抽獎
第116次：未中獎 再接再厲，觸發正常抽獎
第117次：未中獎 再接再厲，觸發正常抽獎
第118次：未中獎 再接再厲，觸發正常抽獎
第119次：貳獎 200元，觸發正常抽獎
第120次：未中獎 再接再厲，觸發正常抽獎
第121次：貳獎 200元，觸發正常抽獎
第122次：未中獎 再接再厲，觸發正常抽獎
第123次：未中獎 再接再厲，觸發正常抽獎
第124次：未中獎 再接再厲，觸發正常抽獎
第125次：未中獎 再接再厲，觸發正常抽獎
第126次：未中獎 再接再厲，觸發正常抽獎
第127次：未中獎 再接再厲，觸發正常抽獎
第128次：未中獎 再接再厲，觸發正常抽獎
第129次：未中獎 再接再厲，觸發正常抽獎
第130次：未中獎 再接再厲，觸發正常抽獎
第131次：未中獎 再接再厲，觸發正常抽獎
第132次：未中獎 再接再厲，觸發正常抽獎
第133次：未中獎 再接再厲，觸發正常抽獎
第134次：未中獎 再接再厲，觸發正常抽獎
第135次：未中獎 再接再厲，觸發正常抽獎
第136次：貳獎 200元，觸發正常抽獎
第137次：貳獎 200元，觸發正常抽獎
第138次：未中獎 再接再厲，觸發正常抽獎
第139次：未中獎 再接再厲，觸發正常抽獎
第140次：未中獎 再接再厲，觸發正常抽獎
第141次：未中獎 再接再厲，觸發正常抽獎
第142次：未中獎 再接再厲，觸發正常抽獎
第143次：未中獎 再接再厲，觸發正常抽獎
第144次：未中獎 再接再厲，觸發正常抽獎
第145次：未中獎 再接再厲，觸發正常抽獎
第146次：未中獎 再接再厲，觸發正常抽獎
第147次：未中獎 再接再厲，觸發正常抽獎
第148次：未中獎 再接再厲，觸發正常抽獎
第149次：未中獎 再接再厲，觸發正常抽獎
第150次：頭獎 500 元，觸發正常抽獎
第151次：未中獎 再接再厲，觸發正常抽獎
第152次：未中獎 再接再厲，觸發正常抽獎
第153次：未中獎 再接再厲，觸發正常抽獎
第154次：頭獎 500 元，觸發正常抽獎
第155次：未中獎 再接再厲，觸發正常抽獎
第156次：頭獎 500 元，觸發正常抽獎
第157次：未中獎 再接再厲，觸發正常抽獎
第158次：貳獎 200元，觸發正常抽獎
第159次：未中獎 再接再厲，觸發正常抽獎
第160次：未中獎 再接再厲，觸發正常抽獎
第161次：未中獎 再接再厲，觸發正常抽獎
第162次：未中獎 再接再厲，觸發正常抽獎
第163次：未中獎 再接再厲，觸發正常抽獎
第164次：頭獎 500 元，觸發正常抽獎
第165次：未中獎 再接再厲，觸發正常抽獎
第166次：未中獎 再接再厲，觸發正常抽獎
第167次：未中獎 再接再厲，觸發正常抽獎
第168次：未中獎 再接再厲，觸發正常抽獎
第169次：未中獎 再接再厲，觸發正常抽獎
第170次：未中獎 再接再厲，觸發正常抽獎
第171次：未中獎 再接再厲，觸發正常抽獎
第172次：未中獎 再接再厲，觸發正常抽獎
第173次：貳獎 200元，觸發正常抽獎
第174次：未中獎 再接再厲，觸發正常抽獎
第175次：未中獎 再接再厲，觸發正常抽獎
第176次：未中獎 再接再厲，觸發正常抽獎
第177次：未中獎 再接再厲，觸發正常抽獎
第178次：未中獎 再接再厲，觸發正常抽獎
第179次：貳獎 200元，觸發正常抽獎
第180次：未中獎 再接再厲，觸發正常抽獎
第181次：未中獎 再接再厲，觸發正常抽獎
第182次：未中獎 再接再厲，觸發正常抽獎
第183次：未中獎 再接再厲，觸發正常抽獎
第184次：未中獎 再接再厲，觸發正常抽獎
第185次：未中獎 再接再厲，觸發正常抽獎
第186次：未中獎 再接再厲，觸發正常抽獎
第187次：貳獎 200元，觸發正常抽獎
第188次：未中獎 再接再厲，觸發正常抽獎
第189次：未中獎 再接再厲，觸發正常抽獎
第190次：未中獎 再接再厲，觸發正常抽獎
第191次：未中獎 再接再厲，觸發正常抽獎
第192次：未中獎 再接再厲，觸發正常抽獎
第193次：未中獎 再接再厲，觸發正常抽獎
第194次：未中獎 再接再厲，觸發正常抽獎
第195次：未中獎 再接再厲，觸發正常抽獎
第196次：未中獎 再接再厲，觸發正常抽獎
第197次：未中獎 再接再厲，觸發正常抽獎
第198次：未中獎 再接再厲，觸發正常抽獎
第199次：未中獎 再接再厲，觸發正常抽獎
第200次：未中獎 再接再厲，觸發正常抽獎
第201次：未中獎 再接再厲，觸發正常抽獎
第202次：未中獎 再接再厲，觸發正常抽獎
第203次：未中獎 再接再厲，觸發正常抽獎
第204次：未中獎 再接再厲，觸發正常抽獎
第205次：未中獎 再接再厲，觸發正常抽獎
第206次：未中獎 再接再厲，觸發正常抽獎
第207次：貳獎 200元，觸發20抽大保
第208次：未中獎 再接再厲，觸發正常抽獎
第209次：未中獎 再接再厲，觸發正常抽獎
第210次：未中獎 再接再厲，觸發正常抽獎
第211次：未中獎 再接再厲，觸發正常抽獎
第212次：未中獎 再接再厲，觸發正常抽獎
第213次：未中獎 再接再厲，觸發正常抽獎
第214次：未中獎 再接再厲，觸發正常抽獎
第215次：未中獎 再接再厲，觸發正常抽獎
第216次：未中獎 再接再厲，觸發正常抽獎
第217次：未中獎 再接再厲，觸發正常抽獎
第218次：貳獎 200元，觸發正常抽獎
第219次：貳獎 200元，觸發正常抽獎
第220次：未中獎 再接再厲，觸發正常抽獎
第221次：未中獎 再接再厲，觸發正常抽獎
第222次：未中獎 再接再厲，觸發正常抽獎
第223次：未中獎 再接再厲，觸發正常抽獎
第224次：未中獎 再接再厲，觸發正常抽獎
第225次：未中獎 再接再厲，觸發正常抽獎
第226次：貳獎 200元，觸發正常抽獎
第227次：貳獎 200元，觸發正常抽獎
第228次：貳獎 200元，觸發正常抽獎
第229次：未中獎 再接再厲，觸發正常抽獎
第230次：未中獎 再接再厲，觸發正常抽獎
第231次：未中獎 再接再厲，觸發正常抽獎
第232次：未中獎 再接再厲，觸發正常抽獎
第233次：未中獎 再接再厲，觸發正常抽獎
第234次：未中獎 再接再厲，觸發正常抽獎
第235次：未中獎 再接再厲，觸發正常抽獎
第236次：未中獎 再接再厲，觸發正常抽獎
第237次：未中獎 再接再厲，觸發正常抽獎
第238次：未中獎 再接再厲，觸發正常抽獎
第239次：未中獎 再接再厲，觸發正常抽獎
第240次：未中獎 再接再厲，觸發正常抽獎
第241次：未中獎 再接再厲，觸發正常抽獎
第242次：未中獎 再接再厲，觸發正常抽獎
第243次：未中獎 再接再厲，觸發正常抽獎
第244次：未中獎 再接再厲，觸發正常抽獎
第245次：未中獎 再接再厲，觸發正常抽獎
第246次：未中獎 再接再厲，觸發正常抽獎
第247次：未中獎 再接再厲，觸發正常抽獎
第248次：貳獎 200元，觸發20抽大保
第249次：未中獎 再接再厲，觸發正常抽獎
第250次：未中獎 再接再厲，觸發正常抽獎
第251次：未中獎 再接再厲，觸發正常抽獎
第252次：貳獎 200元，觸發正常抽獎
第253次：未中獎 再接再厲，觸發正常抽獎
第254次：未中獎 再接再厲，觸發正常抽獎
第255次：未中獎 再接再厲，觸發正常抽獎
第256次：未中獎 再接再厲，觸發正常抽獎
第257次：未中獎 再接再厲，觸發正常抽獎
第258次：未中獎 再接再厲，觸發正常抽獎
第259次：未中獎 再接再厲，觸發正常抽獎
第260次：未中獎 再接再厲，觸發正常抽獎
第261次：未中獎 再接再厲，觸發正常抽獎
第262次：未中獎 再接再厲，觸發正常抽獎
第263次：未中獎 再接再厲，觸發正常抽獎
第264次：貳獎 200元，觸發正常抽獎
第265次：未中獎 再接再厲，觸發正常抽獎
第266次：未中獎 再接再厲，觸發正常抽獎
第267次：未中獎 再接再厲，觸發正常抽獎
第268次：未中獎 再接再厲，觸發正常抽獎
第269次：未中獎 再接再厲，觸發正常抽獎
第270次：未中獎 再接再厲，觸發正常抽獎
第271次：未中獎 再接再厲，觸發正常抽獎
第272次：未中獎 再接再厲，觸發正常抽獎
第273次：未中獎 再接再厲，觸發正常抽獎
第274次：未中獎 再接再厲，觸發正常抽獎
第275次：頭獎 500 元，觸發正常抽獎
第276次：未中獎 再接再厲，觸發正常抽獎
第277次：未中獎 再接再厲，觸發正常抽獎
第278次：未中獎 再接再厲，觸發正常抽獎
第279次：未中獎 再接再厲，觸發正常抽獎
第280次：未中獎 再接再厲，觸發正常抽獎
第281次：未中獎 再接再厲，觸發正常抽獎
第282次：未中獎 再接再厲，觸發正常抽獎
第283次：未中獎 再接再厲，觸發正常抽獎
第284次：未中獎 再接再厲，觸發正常抽獎
第285次：未中獎 再接再厲，觸發正常抽獎
第286次：未中獎 再接再厲，觸發正常抽獎
第287次：未中獎 再接再厲，觸發正常抽獎
第288次：未中獎 再接再厲，觸發正常抽獎
第289次：未中獎 再接再厲，觸發正常抽獎
第290次：貳獎 200元，觸發正常抽獎
第291次：貳獎 200元，觸發正常抽獎
第292次：未中獎 再接再厲，觸發正常抽獎
第293次：未中獎 再接再厲，觸發正常抽獎
第294次：未中獎 再接再厲，觸發正常抽獎
第295次：貳獎 200元，觸發正常抽獎
第296次：未中獎 再接再厲，觸發正常抽獎
第297次：貳獎 200元，觸發正常抽獎
第298次：未中獎 再接再厲，觸發正常抽獎
第299次：未中獎 再接再厲，觸發正常抽獎
第300次：貳獎 200元，觸發正常抽獎
第301次：未中獎 再接再厲，觸發正常抽獎
第302次：未中獎 再接再厲，觸發正常抽獎
第303次：未中獎 再接再厲，觸發正常抽獎
第304次：貳獎 200元，觸發正常抽獎
第305次：未中獎 再接再厲，觸發正常抽獎
第306次：未中獎 再接再厲，觸發正常抽獎
第307次：未中獎 再接再厲，觸發正常抽獎
第308次：未中獎 再接再厲，觸發正常抽獎
第309次：未中獎 再接再厲，觸發正常抽獎
第310次：貳獎 200元，觸發正常抽獎
第311次：貳獎 200元，觸發正常抽獎
第312次：貳獎 200元，觸發正常抽獎
第313次：未中獎 再接再厲，觸發正常抽獎
第314次：貳獎 200元，觸發正常抽獎
第315次：未中獎 再接再厲，觸發正常抽獎
第316次：未中獎 再接再厲，觸發正常抽獎
第317次：未中獎 再接再厲，觸發正常抽獎
第318次：未中獎 再接再厲，觸發正常抽獎
第319次：未中獎 再接再厲，觸發正常抽獎
第320次：未中獎 再接再厲，觸發正常抽獎
第321次：未中獎 再接再厲，觸發正常抽獎
第322次：未中獎 再接再厲，觸發正常抽獎
第323次：未中獎 再接再厲，觸發正常抽獎
第324次：貳獎 200元，觸發正常抽獎
第325次：未中獎 再接再厲，觸發正常抽獎
第326次：未中獎 再接再厲，觸發正常抽獎
第327次：未中獎 再接再厲，觸發正常抽獎
第328次：未中獎 再接再厲，觸發正常抽獎
第329次：未中獎 再接再厲，觸發正常抽獎
第330次：貳獎 200元，觸發正常抽獎
第331次：未中獎 再接再厲，觸發正常抽獎
第332次：未中獎 再接再厲，觸發正常抽獎
第333次：未中獎 再接再厲，觸發正常抽獎
第334次：未中獎 再接再厲，觸發正常抽獎
第335次：未中獎 再接再厲，觸發正常抽獎
第336次：未中獎 再接再厲，觸發正常抽獎
第337次：未中獎 再接再厲，觸發正常抽獎
第338次：未中獎 再接再厲，觸發正常抽獎
第339次：未中獎 再接再厲，觸發正常抽獎
第340次：未中獎 再接再厲，觸發正常抽獎
第341次：貳獎 200元，觸發正常抽獎
第342次：未中獎 再接再厲，觸發正常抽獎
第343次：未中獎 再接再厲，觸發正常抽獎
第344次：未中獎 再接再厲，觸發正常抽獎
第345次：貳獎 200元，觸發正常抽獎
第346次：未中獎 再接再厲，觸發正常抽獎
第347次：頭獎 500 元，觸發正常抽獎
第348次：未中獎 再接再厲，觸發正常抽獎
第349次：未中獎 再接再厲，觸發正常抽獎
第350次：未中獎 再接再厲，觸發正常抽獎
第351次：未中獎 再接再厲，觸發正常抽獎
第352次：未中獎 再接再厲，觸發正常抽獎
第353次：貳獎 200元，觸發正常抽獎
第354次：未中獎 再接再厲，觸發正常抽獎
第355次：未中獎 再接再厲，觸發正常抽獎
第356次：未中獎 再接再厲，觸發正常抽獎
第357次：頭獎 500 元，觸發正常抽獎
第358次：未中獎 再接再厲，觸發正常抽獎
第359次：未中獎 再接再厲，觸發正常抽獎
第360次：未中獎 再接再厲，觸發正常抽獎
第361次：未中獎 再接再厲，觸發正常抽獎
第362次：未中獎 再接再厲，觸發正常抽獎
第363次：未中獎 再接再厲，觸發正常抽獎
第364次：未中獎 再接再厲，觸發正常抽獎
第365次：未中獎 再接再厲，觸發正常抽獎
第366次：未中獎 再接再厲，觸發正常抽獎
第367次：未中獎 再接再厲，觸發正常抽獎
第368次：未中獎 再接再厲，觸發正常抽獎
第369次：未中獎 再接再厲，觸發正常抽獎
第370次：未中獎 再接再厲，觸發正常抽獎
第371次：未中獎 再接再厲，觸發正常抽獎
第372次：貳獎 200元，觸發正常抽獎
第373次：未中獎 再接再厲，觸發正常抽獎
第374次：未中獎 再接再厲，觸發正常抽獎
第375次：貳獎 200元，觸發正常抽獎
第376次：未中獎 再接再厲，觸發正常抽獎
第377次：未中獎 再接再厲，觸發正常抽獎
第378次：未中獎 再接再厲，觸發正常抽獎
第379次：未中獎 再接再厲，觸發正常抽獎
第380次：未中獎 再接再厲，觸發正常抽獎
第381次：未中獎 再接再厲，觸發正常抽獎
第382次：未中獎 再接再厲，觸發正常抽獎
第383次：頭獎 500 元，觸發正常抽獎
第384次：未中獎 再接再厲，觸發正常抽獎
第385次：未中獎 再接再厲，觸發正常抽獎
第386次：未中獎 再接再厲，觸發正常抽獎
第387次：未中獎 再接再厲，觸發正常抽獎
第388次：未中獎 再接再厲，觸發正常抽獎
第389次：未中獎 再接再厲，觸發正常抽獎
第390次：未中獎 再接再厲，觸發正常抽獎
第391次：未中獎 再接再厲，觸發正常抽獎
第392次：未中獎 再接再厲，觸發正常抽獎
第393次：未中獎 再接再厲，觸發正常抽獎
第394次：未中獎 再接再厲，觸發正常抽獎
第395次：未中獎 再接再厲，觸發正常抽獎
第396次：頭獎 500 元，觸發正常抽獎
第397次：未中獎 再接再厲，觸發正常抽獎
第398次：未中獎 再接再厲，觸發正常抽獎
第399次：未中獎 再接再厲，觸發正常抽獎
第400次：未中獎 再接再厲，觸發正常抽獎
第401次：未中獎 再接再厲，觸發正常抽獎
第402次：未中獎 再接再厲，觸發正常抽獎
第403次：未中獎 再接再厲，觸發正常抽獎
第404次：未中獎 再接再厲，觸發正常抽獎
第405次：未中獎 再接再厲，觸發正常抽獎
第406次：未中獎 再接再厲，觸發正常抽獎
第407次：未中獎 再接再厲，觸發正常抽獎
第408次：未中獎 再接再厲，觸發正常抽獎
第409次：未中獎 再接再厲，觸發正常抽獎
第410次：貳獎 200元，觸發正常抽獎
第411次：未中獎 再接再厲，觸發正常抽獎
第412次：未中獎 再接再厲，觸發正常抽獎
第413次：未中獎 再接再厲，觸發正常抽獎
第414次：未中獎 再接再厲，觸發正常抽獎
第415次：未中獎 再接再厲，觸發正常抽獎
第416次：貳獎 200元，觸發正常抽獎
第417次：未中獎 再接再厲，觸發正常抽獎
第418次：貳獎 200元，觸發正常抽獎
第419次：未中獎 再接再厲，觸發正常抽獎
第420次：未中獎 再接再厲，觸發正常抽獎
第421次：未中獎 再接再厲，觸發正常抽獎
第422次：未中獎 再接再厲，觸發正常抽獎
第423次：未中獎 再接再厲，觸發正常抽獎
第424次：未中獎 再接再厲，觸發正常抽獎
第425次：貳獎 200元，觸發正常抽獎
第426次：未中獎 再接再厲，觸發正常抽獎
第427次：未中獎 再接再厲，觸發正常抽獎
第428次：未中獎 再接再厲，觸發正常抽獎
第429次：未中獎 再接再厲，觸發正常抽獎
第430次：未中獎 再接再厲，觸發正常抽獎
第431次：未中獎 再接再厲，觸發正常抽獎
第432次：未中獎 再接再厲，觸發正常抽獎
第433次：未中獎 再接再厲，觸發正常抽獎
第434次：未中獎 再接再厲，觸發正常抽獎
第435次：未中獎 再接再厲，觸發正常抽獎
第436次：未中獎 再接再厲，觸發正常抽獎
第437次：未中獎 再接再厲，觸發正常抽獎
第438次：未中獎 再接再厲，觸發正常抽獎
第439次：未中獎 再接再厲，觸發正常抽獎
第440次：未中獎 再接再厲，觸發正常抽獎
第441次：未中獎 再接再厲，觸發正常抽獎
第442次：未中獎 再接再厲，觸發正常抽獎
第443次：未中獎 再接再厲，觸發正常抽獎
第444次：未中獎 再接再厲，觸發正常抽獎
第445次：貳獎 200元，觸發20抽大保
第446次：貳獎 200元，觸發正常抽獎
第447次：未中獎 再接再厲，觸發正常抽獎
第448次：貳獎 200元，觸發正常抽獎
第449次：未中獎 再接再厲，觸發正常抽獎
第450次：未中獎 再接再厲，觸發正常抽獎
第451次：未中獎 再接再厲，觸發正常抽獎
第452次：未中獎 再接再厲，觸發正常抽獎
第453次：未中獎 再接再厲，觸發正常抽獎
第454次：未中獎 再接再厲，觸發正常抽獎
第455次：未中獎 再接再厲，觸發正常抽獎
第456次：未中獎 再接再厲，觸發正常抽獎
第457次：未中獎 再接再厲，觸發正常抽獎
第458次：未中獎 再接再厲，觸發正常抽獎
第459次：貳獎 200元，觸發正常抽獎
第460次：未中獎 再接再厲，觸發正常抽獎
第461次：未中獎 再接再厲，觸發正常抽獎
第462次：未中獎 再接再厲，觸發正常抽獎
第463次：未中獎 再接再厲，觸發正常抽獎
第464次：未中獎 再接再厲，觸發正常抽獎
第465次：未中獎 再接再厲，觸發正常抽獎
第466次：未中獎 再接再厲，觸發正常抽獎
第467次：未中獎 再接再厲，觸發正常抽獎
第468次：未中獎 再接再厲，觸發正常抽獎
第469次：頭獎 500 元，觸發正常抽獎
第470次：未中獎 再接再厲，觸發正常抽獎
第471次：貳獎 200元，觸發正常抽獎
第472次：未中獎 再接再厲，觸發正常抽獎
第473次：未中獎 再接再厲，觸發正常抽獎
第474次：未中獎 再接再厲，觸發正常抽獎
第475次：未中獎 再接再厲，觸發正常抽獎
第476次：未中獎 再接再厲，觸發正常抽獎
第477次：未中獎 再接再厲，觸發正常抽獎
第478次：未中獎 再接再厲，觸發正常抽獎
第479次：未中獎 再接再厲，觸發正常抽獎
第480次：未中獎 再接再厲，觸發正常抽獎
第481次：貳獎 200元，觸發正常抽獎
第482次：未中獎 再接再厲，觸發正常抽獎
第483次：未中獎 再接再厲，觸發正常抽獎
第484次：未中獎 再接再厲，觸發正常抽獎
第485次：頭獎 500 元，觸發正常抽獎
第486次：未中獎 再接再厲，觸發正常抽獎
第487次：貳獎 200元，觸發正常抽獎
第488次：未中獎 再接再厲，觸發正常抽獎
第489次：未中獎 再接再厲，觸發正常抽獎
第490次：未中獎 再接再厲，觸發正常抽獎
第491次：頭獎 500 元，觸發正常抽獎
第492次：頭獎 500 元，觸發正常抽獎
第493次：未中獎 再接再厲，觸發正常抽獎
第494次：未中獎 再接再厲，觸發正常抽獎
第495次：未中獎 再接再厲，觸發正常抽獎
第496次：未中獎 再接再厲，觸發正常抽獎
第497次：未中獎 再接再厲，觸發正常抽獎
第498次：未中獎 再接再厲，觸發正常抽獎
第499次：未中獎 再接再厲，觸發正常抽獎
第500次：未中獎 再接再厲，觸發正常抽獎
第501次：未中獎 再接再厲，觸發正常抽獎
第502次：未中獎 再接再厲，觸發正常抽獎
第503次：貳獎 200元，觸發正常抽獎
第504次：未中獎 再接再厲，觸發正常抽獎
第505次：未中獎 再接再厲，觸發正常抽獎
第506次：未中獎 再接再厲，觸發正常抽獎
第507次：頭獎 500 元，觸發正常抽獎
第508次：未中獎 再接再厲，觸發正常抽獎
第509次：未中獎 再接再厲，觸發正常抽獎
第510次：未中獎 再接再厲，觸發正常抽獎
第511次：未中獎 再接再厲，觸發正常抽獎
第512次：未中獎 再接再厲，觸發正常抽獎
第513次：未中獎 再接再厲，觸發正常抽獎
第514次：未中獎 再接再厲，觸發正常抽獎
第515次：未中獎 再接再厲，觸發正常抽獎
第516次：未中獎 再接再厲，觸發正常抽獎
第517次：未中獎 再接再厲，觸發正常抽獎
第518次：未中獎 再接再厲，觸發正常抽獎
第519次：未中獎 再接再厲，觸發正常抽獎
第520次：貳獎 200元，觸發正常抽獎
第521次：未中獎 再接再厲，觸發正常抽獎
第522次：未中獎 再接再厲，觸發正常抽獎
第523次：未中獎 再接再厲，觸發正常抽獎
第524次：貳獎 200元，觸發正常抽獎
第525次：未中獎 再接再厲，觸發正常抽獎
第526次：未中獎 再接再厲，觸發正常抽獎
第527次：未中獎 再接再厲，觸發正常抽獎
第528次：未中獎 再接再厲，觸發正常抽獎
第529次：未中獎 再接再厲，觸發正常抽獎
第530次：未中獎 再接再厲，觸發正常抽獎
第531次：未中獎 再接再厲，觸發正常抽獎
第532次：未中獎 再接再厲，觸發正常抽獎
第533次：未中獎 再接再厲，觸發正常抽獎
第534次：未中獎 再接再厲，觸發正常抽獎
第535次：未中獎 再接再厲，觸發正常抽獎
第536次：未中獎 再接再厲，觸發正常抽獎
第537次：貳獎 200元，觸發正常抽獎
第538次：未中獎 再接再厲，觸發正常抽獎
第539次：未中獎 再接再厲，觸發正常抽獎
第540次：未中獎 再接再厲，觸發正常抽獎
第541次：未中獎 再接再厲，觸發正常抽獎
第542次：未中獎 再接再厲，觸發正常抽獎
第543次：未中獎 再接再厲，觸發正常抽獎
第544次：未中獎 再接再厲，觸發正常抽獎
第545次：未中獎 再接再厲，觸發正常抽獎
第546次：未中獎 再接再厲，觸發正常抽獎
第547次：未中獎 再接再厲，觸發正常抽獎
第548次：頭獎 500 元，觸發正常抽獎
第549次：未中獎 再接再厲，觸發正常抽獎
第550次：未中獎 再接再厲，觸發正常抽獎
第551次：未中獎 再接再厲，觸發正常抽獎
第552次：未中獎 再接再厲，觸發正常抽獎
第553次：未中獎 再接再厲，觸發正常抽獎
第554次：未中獎 再接再厲，觸發正常抽獎
第555次：未中獎 再接再厲，觸發正常抽獎
第556次：頭獎 500 元，觸發正常抽獎
第557次：未中獎 再接再厲，觸發正常抽獎
第558次：未中獎 再接再厲，觸發正常抽獎
第559次：未中獎 再接再厲，觸發正常抽獎
第560次：貳獎 200元，觸發正常抽獎
第561次：未中獎 再接再厲，觸發正常抽獎
第562次：未中獎 再接再厲，觸發正常抽獎
第563次：未中獎 再接再厲，觸發正常抽獎
第564次：未中獎 再接再厲，觸發正常抽獎
第565次：未中獎 再接再厲，觸發正常抽獎
第566次：未中獎 再接再厲，觸發正常抽獎
第567次：貳獎 200元，觸發正常抽獎
第568次：未中獎 再接再厲，觸發正常抽獎
第569次：貳獎 200元，觸發正常抽獎
第570次：未中獎 再接再厲，觸發正常抽獎
第571次：未中獎 再接再厲，觸發正常抽獎
第572次：未中獎 再接再厲，觸發正常抽獎
第573次：未中獎 再接再厲，觸發正常抽獎
第574次：未中獎 再接再厲，觸發正常抽獎
第575次：未中獎 再接再厲，觸發正常抽獎
第576次：未中獎 再接再厲，觸發正常抽獎
第577次：未中獎 再接再厲，觸發正常抽獎
第578次：未中獎 再接再厲，觸發正常抽獎
第579次：未中獎 再接再厲，觸發正常抽獎
第580次：未中獎 再接再厲，觸發正常抽獎
第581次：未中獎 再接再厲，觸發正常抽獎
第582次：未中獎 再接再厲，觸發正常抽獎
第583次：未中獎 再接再厲，觸發正常抽獎
第584次：未中獎 再接再厲，觸發正常抽獎
第585次：未中獎 再接再厲，觸發正常抽獎
第586次：未中獎 再接再厲，觸發正常抽獎
第587次：未中獎 再接再厲，觸發正常抽獎
第588次：未中獎 再接再厲，觸發正常抽獎
第589次：頭獎 500 元，觸發20抽大保
第590次：未中獎 再接再厲，觸發正常抽獎
第591次：未中獎 再接再厲，觸發正常抽獎
第592次：未中獎 再接再厲，觸發正常抽獎
第593次：未中獎 再接再厲，觸發正常抽獎
第594次：未中獎 再接再厲，觸發正常抽獎
第595次：未中獎 再接再厲，觸發正常抽獎
第596次：未中獎 再接再厲，觸發正常抽獎
第597次：未中獎 再接再厲，觸發正常抽獎
第598次：未中獎 再接再厲，觸發正常抽獎
第599次：未中獎 再接再厲，觸發正常抽獎
第600次：未中獎 再接再厲，觸發正常抽獎
第601次：未中獎 再接再厲，觸發正常抽獎
第602次：未中獎 再接再厲，觸發正常抽獎
第603次：未中獎 再接再厲，觸發正常抽獎
第604次：未中獎 再接再厲，觸發正常抽獎
第605次：未中獎 再接再厲，觸發正常抽獎
第606次：未中獎 再接再厲，觸發正常抽獎
第607次：貳獎 200元，觸發正常抽獎
第608次：未中獎 再接再厲，觸發正常抽獎
第609次：未中獎 再接再厲，觸發正常抽獎
第610次：未中獎 再接再厲，觸發正常抽獎
第611次：未中獎 再接再厲，觸發正常抽獎
第612次：未中獎 再接再厲，觸發正常抽獎
第613次：貳獎 200元，觸發正常抽獎
第614次：未中獎 再接再厲，觸發正常抽獎
第615次：未中獎 再接再厲，觸發正常抽獎
第616次：未中獎 再接再厲，觸發正常抽獎
第617次：未中獎 再接再厲，觸發正常抽獎
第618次：未中獎 再接再厲，觸發正常抽獎
第619次：貳獎 200元，觸發正常抽獎
第620次：未中獎 再接再厲，觸發正常抽獎
第621次：未中獎 再接再厲，觸發正常抽獎
第622次：未中獎 再接再厲，觸發正常抽獎
第623次：未中獎 再接再厲，觸發正常抽獎
第624次：未中獎 再接再厲，觸發正常抽獎
第625次：未中獎 再接再厲，觸發正常抽獎
第626次：未中獎 再接再厲，觸發正常抽獎
第627次：未中獎 再接再厲，觸發正常抽獎
第628次：未中獎 再接再厲，觸發正常抽獎
第629次：貳獎 200元，觸發正常抽獎
第630次：未中獎 再接再厲，觸發正常抽獎
第631次：未中獎 再接再厲，觸發正常抽獎
第632次：未中獎 再接再厲，觸發正常抽獎
第633次：未中獎 再接再厲，觸發正常抽獎
第634次：未中獎 再接再厲，觸發正常抽獎
第635次：未中獎 再接再厲，觸發正常抽獎
第636次：未中獎 再接再厲，觸發正常抽獎
第637次：未中獎 再接再厲，觸發正常抽獎
第638次：貳獎 200元，觸發正常抽獎
第639次：未中獎 再接再厲，觸發正常抽獎
第640次：未中獎 再接再厲，觸發正常抽獎
第641次：未中獎 再接再厲，觸發正常抽獎
第642次：未中獎 再接再厲，觸發正常抽獎
第643次：未中獎 再接再厲，觸發正常抽獎
第644次：未中獎 再接再厲，觸發正常抽獎
第645次：未中獎 再接再厲，觸發正常抽獎
第646次：未中獎 再接再厲，觸發正常抽獎
第647次：未中獎 再接再厲，觸發正常抽獎
第648次：未中獎 再接再厲，觸發正常抽獎
第649次：頭獎 500 元，觸發正常抽獎
第650次：未中獎 再接再厲，觸發正常抽獎
第651次：頭獎 500 元，觸發正常抽獎
第652次：未中獎 再接再厲，觸發正常抽獎
第653次：未中獎 再接再厲，觸發正常抽獎
第654次：未中獎 再接再厲，觸發正常抽獎
第655次：未中獎 再接再厲，觸發正常抽獎
第656次：未中獎 再接再厲，觸發正常抽獎
第657次：未中獎 再接再厲，觸發正常抽獎
第658次：未中獎 再接再厲，觸發正常抽獎
第659次：未中獎 再接再厲，觸發正常抽獎
第660次：未中獎 再接再厲，觸發正常抽獎
第661次：頭獎 500 元，觸發正常抽獎
第662次：未中獎 再接再厲，觸發正常抽獎
第663次：未中獎 再接再厲，觸發正常抽獎
第664次：未中獎 再接再厲，觸發正常抽獎
第665次：未中獎 再接再厲，觸發正常抽獎
第666次：未中獎 再接再厲，觸發正常抽獎
第667次：未中獎 再接再厲，觸發正常抽獎
第668次：未中獎 再接再厲，觸發正常抽獎
第669次：未中獎 再接再厲，觸發正常抽獎
第670次：未中獎 再接再厲，觸發正常抽獎
第671次：未中獎 再接再厲，觸發正常抽獎
第672次：未中獎 再接再厲，觸發正常抽獎
第673次：貳獎 200元，觸發正常抽獎
第674次：貳獎 200元，觸發正常抽獎
第675次：未中獎 再接再厲，觸發正常抽獎
第676次：未中獎 再接再厲，觸發正常抽獎
第677次：未中獎 再接再厲，觸發正常抽獎
第678次：未中獎 再接再厲，觸發正常抽獎
第679次：未中獎 再接再厲，觸發正常抽獎
第680次：未中獎 再接再厲，觸發正常抽獎
第681次：頭獎 500 元，觸發正常抽獎
第682次：未中獎 再接再厲，觸發正常抽獎
第683次：未中獎 再接再厲，觸發正常抽獎
第684次：未中獎 再接再厲，觸發正常抽獎
第685次：未中獎 再接再厲，觸發正常抽獎
第686次：頭獎 500 元，觸發正常抽獎
第687次：未中獎 再接再厲，觸發正常抽獎
第688次：未中獎 再接再厲，觸發正常抽獎
第689次：未中獎 再接再厲，觸發正常抽獎
第690次：未中獎 再接再厲，觸發正常抽獎
第691次：未中獎 再接再厲，觸發正常抽獎
第692次：未中獎 再接再厲，觸發正常抽獎
第693次：未中獎 再接再厲，觸發正常抽獎
第694次：貳獎 200元，觸發正常抽獎
第695次：未中獎 再接再厲，觸發正常抽獎
第696次：未中獎 再接再厲，觸發正常抽獎
第697次：未中獎 再接再厲，觸發正常抽獎
第698次：未中獎 再接再厲，觸發正常抽獎
第699次：頭獎 500 元，觸發正常抽獎
第700次：貳獎 200元，觸發正常抽獎
第701次：未中獎 再接再厲，觸發正常抽獎
第702次：貳獎 200元，觸發正常抽獎
第703次：未中獎 再接再厲，觸發正常抽獎
第704次：未中獎 再接再厲，觸發正常抽獎
第705次：未中獎 再接再厲，觸發正常抽獎
第706次：未中獎 再接再厲，觸發正常抽獎
第707次：未中獎 再接再厲，觸發正常抽獎
第708次：未中獎 再接再厲，觸發正常抽獎
第709次：貳獎 200元，觸發正常抽獎
第710次：未中獎 再接再厲，觸發正常抽獎
第711次：貳獎 200元，觸發正常抽獎
第712次：未中獎 再接再厲，觸發正常抽獎
第713次：頭獎 500 元，觸發正常抽獎
第714次：未中獎 再接再厲，觸發正常抽獎
第715次：未中獎 再接再厲，觸發正常抽獎
第716次：未中獎 再接再厲，觸發正常抽獎
第717次：未中獎 再接再厲，觸發正常抽獎
第718次：未中獎 再接再厲，觸發正常抽獎
第719次：未中獎 再接再厲，觸發正常抽獎
第720次：未中獎 再接再厲，觸發正常抽獎
第721次：未中獎 再接再厲，觸發正常抽獎
第722次：未中獎 再接再厲，觸發正常抽獎
第723次：未中獎 再接再厲，觸發正常抽獎
第724次：未中獎 再接再厲，觸發正常抽獎
第725次：未中獎 再接再厲，觸發正常抽獎
第726次：未中獎 再接再厲，觸發正常抽獎
第727次：未中獎 再接再厲，觸發正常抽獎
第728次：未中獎 再接再厲，觸發正常抽獎
第729次：貳獎 200元，觸發正常抽獎
第730次：未中獎 再接再厲，觸發正常抽獎
第731次：未中獎 再接再厲，觸發正常抽獎
第732次：未中獎 再接再厲，觸發正常抽獎
第733次：貳獎 200元，觸發正常抽獎
第734次：貳獎 200元，觸發正常抽獎
第735次：未中獎 再接再厲，觸發正常抽獎
第736次：頭獎 500 元，觸發正常抽獎
第737次：未中獎 再接再厲，觸發正常抽獎
第738次：未中獎 再接再厲，觸發正常抽獎
第739次：貳獎 200元，觸發正常抽獎
第740次：未中獎 再接再厲，觸發正常抽獎
第741次：未中獎 再接再厲，觸發正常抽獎
第742次：未中獎 再接再厲，觸發正常抽獎
第743次：貳獎 200元，觸發正常抽獎
第744次：未中獎 再接再厲，觸發正常抽獎
第745次：未中獎 再接再厲，觸發正常抽獎
第746次：未中獎 再接再厲，觸發正常抽獎
第747次：未中獎 再接再厲，觸發正常抽獎
第748次：貳獎 200元，觸發正常抽獎
第749次：未中獎 再接再厲，觸發正常抽獎
第750次：未中獎 再接再厲，觸發正常抽獎
第751次：未中獎 再接再厲，觸發正常抽獎
第752次：頭獎 500 元，觸發正常抽獎
第753次：未中獎 再接再厲，觸發正常抽獎
第754次：未中獎 再接再厲，觸發正常抽獎
第755次：未中獎 再接再厲，觸發正常抽獎
第756次：未中獎 再接再厲，觸發正常抽獎
第757次：貳獎 200元，觸發正常抽獎
第758次：未中獎 再接再厲，觸發正常抽獎
第759次：未中獎 再接再厲，觸發正常抽獎
第760次：未中獎 再接再厲，觸發正常抽獎
第761次：未中獎 再接再厲，觸發正常抽獎
第762次：未中獎 再接再厲，觸發正常抽獎
第763次：未中獎 再接再厲，觸發正常抽獎
第764次：未中獎 再接再厲，觸發正常抽獎
第765次：未中獎 再接再厲，觸發正常抽獎
第766次：未中獎 再接再厲，觸發正常抽獎
第767次：未中獎 再接再厲，觸發正常抽獎
第768次：未中獎 再接再厲，觸發正常抽獎
第769次：未中獎 再接再厲，觸發正常抽獎
第770次：未中獎 再接再厲，觸發正常抽獎
第771次：未中獎 再接再厲，觸發正常抽獎
第772次：未中獎 再接再厲，觸發正常抽獎
第773次：未中獎 再接再厲，觸發正常抽獎
第774次：未中獎 再接再厲，觸發正常抽獎
第775次：未中獎 再接再厲，觸發正常抽獎
第776次：未中獎 再接再厲，觸發正常抽獎
第777次：貳獎 200元，觸發20抽大保
第778次：未中獎 再接再厲，觸發正常抽獎
第779次：未中獎 再接再厲，觸發正常抽獎
第780次：未中獎 再接再厲，觸發正常抽獎
第781次：未中獎 再接再厲，觸發正常抽獎
第782次：未中獎 再接再厲，觸發正常抽獎
第783次：貳獎 200元，觸發正常抽獎
第784次：未中獎 再接再厲，觸發正常抽獎
第785次：未中獎 再接再厲，觸發正常抽獎
第786次：未中獎 再接再厲，觸發正常抽獎
第787次：未中獎 再接再厲，觸發正常抽獎
第788次：未中獎 再接再厲，觸發正常抽獎
第789次：未中獎 再接再厲，觸發正常抽獎
第790次：未中獎 再接再厲，觸發正常抽獎
第791次：未中獎 再接再厲，觸發正常抽獎
第792次：未中獎 再接再厲，觸發正常抽獎
第793次：未中獎 再接再厲，觸發正常抽獎
第794次：未中獎 再接再厲，觸發正常抽獎
第795次：頭獎 500 元，觸發正常抽獎
第796次：未中獎 再接再厲，觸發正常抽獎
第797次：未中獎 再接再厲，觸發正常抽獎
第798次：未中獎 再接再厲，觸發正常抽獎
第799次：未中獎 再接再厲，觸發正常抽獎
第800次：未中獎 再接再厲，觸發正常抽獎
第801次：未中獎 再接再厲，觸發正常抽獎
第802次：未中獎 再接再厲，觸發正常抽獎
第803次：未中獎 再接再厲，觸發正常抽獎
第804次：未中獎 再接再厲，觸發正常抽獎
第805次：未中獎 再接再厲，觸發正常抽獎
第806次：未中獎 再接再厲，觸發正常抽獎
第807次：未中獎 再接再厲，觸發正常抽獎
第808次：貳獎 200元，觸發正常抽獎
第809次：未中獎 再接再厲，觸發正常抽獎
第810次：未中獎 再接再厲，觸發正常抽獎
第811次：未中獎 再接再厲，觸發正常抽獎
第812次：未中獎 再接再厲，觸發正常抽獎
第813次：貳獎 200元，觸發正常抽獎
第814次：未中獎 再接再厲，觸發正常抽獎
第815次：未中獎 再接再厲，觸發正常抽獎
第816次：未中獎 再接再厲，觸發正常抽獎
第817次：貳獎 200元，觸發正常抽獎
第818次：未中獎 再接再厲，觸發正常抽獎
第819次：未中獎 再接再厲，觸發正常抽獎
第820次：未中獎 再接再厲，觸發正常抽獎
第821次：未中獎 再接再厲，觸發正常抽獎
第822次：未中獎 再接再厲，觸發正常抽獎
第823次：貳獎 200元，觸發正常抽獎
第824次：未中獎 再接再厲，觸發正常抽獎
第825次：未中獎 再接再厲，觸發正常抽獎
第826次：未中獎 再接再厲，觸發正常抽獎
第827次：貳獎 200元，觸發正常抽獎
第828次：未中獎 再接再厲，觸發正常抽獎
第829次：未中獎 再接再厲，觸發正常抽獎
第830次：未中獎 再接再厲，觸發正常抽獎
第831次：貳獎 200元，觸發正常抽獎
第832次：貳獎 200元，觸發正常抽獎
第833次：未中獎 再接再厲，觸發正常抽獎
第834次：貳獎 200元，觸發正常抽獎
第835次：未中獎 再接再厲，觸發正常抽獎
第836次：未中獎 再接再厲，觸發正常抽獎
第837次：未中獎 再接再厲，觸發正常抽獎
第838次：未中獎 再接再厲，觸發正常抽獎
第839次：未中獎 再接再厲，觸發正常抽獎
第840次：未中獎 再接再厲，觸發正常抽獎
第841次：貳獎 200元，觸發正常抽獎
第842次：未中獎 再接再厲，觸發正常抽獎
第843次：未中獎 再接再厲，觸發正常抽獎
第844次：未中獎 再接再厲，觸發正常抽獎
第845次：未中獎 再接再厲，觸發正常抽獎
第846次：未中獎 再接再厲，觸發正常抽獎
第847次：未中獎 再接再厲，觸發正常抽獎
第848次：未中獎 再接再厲，觸發正常抽獎
第849次：未中獎 再接再厲，觸發正常抽獎
第850次：未中獎 再接再厲，觸發正常抽獎
第851次：未中獎 再接再厲，觸發正常抽獎
第852次：未中獎 再接再厲，觸發正常抽獎
第853次：未中獎 再接再厲，觸發正常抽獎
第854次：未中獎 再接再厲，觸發正常抽獎
第855次：未中獎 再接再厲，觸發正常抽獎
第856次：未中獎 再接再厲，觸發正常抽獎
第857次：未中獎 再接再厲，觸發正常抽獎
第858次：未中獎 再接再厲，觸發正常抽獎
第859次：頭獎 500 元，觸發正常抽獎
第860次：貳獎 200元，觸發正常抽獎
第861次：未中獎 再接再厲，觸發正常抽獎
第862次：未中獎 再接再厲，觸發正常抽獎
第863次：未中獎 再接再厲，觸發正常抽獎
第864次：未中獎 再接再厲，觸發正常抽獎
第865次：未中獎 再接再厲，觸發正常抽獎
第866次：未中獎 再接再厲，觸發正常抽獎
第867次：頭獎 500 元，觸發正常抽獎
第868次：未中獎 再接再厲，觸發正常抽獎
第869次：貳獎 200元，觸發正常抽獎
第870次：貳獎 200元，觸發正常抽獎
第871次：未中獎 再接再厲，觸發正常抽獎
第872次：未中獎 再接再厲，觸發正常抽獎
第873次：頭獎 500 元，觸發正常抽獎
第874次：未中獎 再接再厲，觸發正常抽獎
第875次：未中獎 再接再厲，觸發正常抽獎
第876次：未中獎 再接再厲，觸發正常抽獎
第877次：未中獎 再接再厲，觸發正常抽獎
第878次：未中獎 再接再厲，觸發正常抽獎
第879次：未中獎 再接再厲，觸發正常抽獎
第880次：未中獎 再接再厲，觸發正常抽獎
第881次：貳獎 200元，觸發正常抽獎
第882次：未中獎 再接再厲，觸發正常抽獎
第883次：貳獎 200元，觸發正常抽獎
第884次：未中獎 再接再厲，觸發正常抽獎
第885次：未中獎 再接再厲，觸發正常抽獎
第886次：未中獎 再接再厲，觸發正常抽獎
第887次：未中獎 再接再厲，觸發正常抽獎
第888次：未中獎 再接再厲，觸發正常抽獎
第889次：未中獎 再接再厲，觸發正常抽獎
第890次：未中獎 再接再厲，觸發正常抽獎
第891次：未中獎 再接再厲，觸發正常抽獎
第892次：頭獎 500 元，觸發正常抽獎
第893次：未中獎 再接再厲，觸發正常抽獎
第894次：未中獎 再接再厲，觸發正常抽獎
第895次：未中獎 再接再厲，觸發正常抽獎
第896次：未中獎 再接再厲，觸發正常抽獎
第897次：貳獎 200元，觸發正常抽獎
第898次：未中獎 再接再厲，觸發正常抽獎
第899次：未中獎 再接再厲，觸發正常抽獎
第900次：未中獎 再接再厲，觸發正常抽獎
第901次：貳獎 200元，觸發正常抽獎
第902次：未中獎 再接再厲，觸發正常抽獎
第903次：未中獎 再接再厲，觸發正常抽獎
第904次：未中獎 再接再厲，觸發正常抽獎
第905次：未中獎 再接再厲，觸發正常抽獎
第906次：未中獎 再接再厲，觸發正常抽獎
第907次：未中獎 再接再厲，觸發正常抽獎
第908次：貳獎 200元，觸發正常抽獎
第909次：貳獎 200元，觸發正常抽獎
第910次：貳獎 200元，觸發正常抽獎
第911次：未中獎 再接再厲，觸發正常抽獎
第912次：未中獎 再接再厲，觸發正常抽獎
第913次：未中獎 再接再厲，觸發正常抽獎
第914次：頭獎 500 元，觸發正常抽獎
第915次：未中獎 再接再厲，觸發正常抽獎
第916次：未中獎 再接再厲，觸發正常抽獎

    樣本數 單次遊玩獎金期望值估計   標準誤   CI下界  CI上界
0  5000       45.94  1.71  42.58  49.3

程式結束