In [156]:
import pandas as pd
# df = pd.read_spss(r"C:\Users\USER\Downloads\D00224_2\data.sav")
# df.to_csv('Dataset.csv', encoding='utf-8-sig', index=False)
df = pd.read_csv(r"C:\Users\USER\Documents\GitHub\psychic-spoon\0 2025資料科學漫步\Dataset.csv")
df.head()

,id,startdate,enddate,duration_in_seconds,q1,q2,q3,q3_other,q4,q4_88_text,...,q39_1,q40_1,q41_1,q42_1,rq21a,rq37a,qrq2,rrq2,weight,r
0,1030252,2021-06-23 23:48:22,2021-06-24 00:13:26,1503.0,女,54.0,(02)台北市,NaN,(20)碩士,NaN,...,快樂,65.0,65.0,維持現狀,答對,答對,56.0,50-59歲,0.349006,符合
1,1030607N,2021-07-02 17:35:01,2021-07-02 17:49:30,869.0,男,47.0,(02)台北市,NaN,(08)高職(高商、高工),NaN,...,快樂,1.0,76.0,獨立,答錯,答對,63.0,60-69歲,4.909428,符合
2,1040123,2021-06-26 10:41:56,2021-06-29 17:20:32,283115.0,男,58.0,(02)台北市,NaN,(21)博士,NaN,...,普通,非常冰冷,90.0,獨立,答對,答對,52.0,50-59歲,0.450735,符合
3,1040131,2021-07-19 10:15:01,2021-07-19 10:32:31,1050.0,女,73.0,(03)新北市,NaN,(20)碩士,NaN,...,普通,50.0,35.0,維持現狀,答對,答對,37.0,30-39歲,0.225117,符合
4,1040139,2021-06-27 10:30:00,2021-06-27 10:39:36,575.0,男,86.0,(02)台北市,NaN,(20)碩士,NaN,...,普通,2.0,70.0,獨立,答對,答對,24.0,18-29歲,0.372256,符合

In [157]:
df.columns.to_list()

['id',
 'startdate',
 'enddate',
 'duration_in_seconds',
 'q1',
 'q2',
 'q3',
 'q3_other',
 'q4',
 'q4_88_text',
 'q5_1',
 'q6_h',
 'q6_m',
 'q7_h',
 'q7_m',
 'q8_1',
 'q8_2',
 'q8_3',
 'q8_4',
 'q8_5',
 'q8_6',
 'q8_88',
 'q8_88_text',
 'q8_90',
 'q9_1',
 'q9_2',
 'q9_3',
 'q9_4',
 'q9_5',
 'q9_6',
 'q9_7',
 'q9_8',
 'q9_88',
 'q9_88_text',
 'q9_90',
 'q10_1',
 'q10_2',
 'q10_3',
 'q10_4',
 'q10_5',
 'q10_6',
 'q10_7',
 'q10_8',
 'q10_9',
 'q10_10',
 'q10_88',
 'q10_88_text',
 'q10_90',
 'q11_1',
 'q11_2',
 'q11_3',
 'q11_4',
 'q11_5',
 'q11_6',
 'q11_7',
 'q11_8',
 'q11_88',
 'q11_88_text',
 'q11_90',
 'q12_1',
 'q12_2',
 'q12_3',
 'q12_4',
 'q12_5',
 'q12_6',
 'q12_7',
 'q12_8',
 'q12_8_text',
 'q12_9',
 'q13_01_1',
 'q13_02_1',
 'q13_02_2',
 'q13_02_3',
 'q13_02_4',
 'q13_02_5',
 'q13_02_6',
 'q13_02_7',
 'q13_02_8',
 'q13_02_8_text',
 'q13_02_9',
 'q13_02_10',
 'q13_03_1',
 'q13_03_2',
 'q13_03_3',
 'q13_03_4',
 'q13_03_5',
 'q13_03_5_text',
 'q13_03_6',
 'q13_03_7',
 'q13_04_1',
 'q13_04_2',
 'q13_04_3',
 'q13_04_4',
 'q13_04_5',
 'q13_04_6',
 'q13_04_7',
 'q13_04_8',
 'q13_04_8_text',
 'q13_04_9',
 'q13_04_10',
 'q13_05_1',
 'q13_05_2',
 'q13_05_3',
 'q13_05_4',
 'q13_05_5',
 'q13_05_5_text',
 'q13_05_6',
 'q13_05_7',
 'q14_01_1',
 'q14_01_2',
 'q14_01_3',
 'q14_01_4',
 'q14_01_5',
 'q14_01_5_text',
 'q14_02_1',
 'q14_02_2',
 'q14_02_3',
 'q14_02_4',
 'q14_02_5',
 'q14_02_5_text',
 'q14_03_1',
 'q14_03_2',
 'q14_03_3',
 'q14_03_4',
 'q14_03_4_text',
 'q15_01',
 'q15_02_1',
 'q15_02_2',
 'q15_02_3',
 'q15_02_4',
 'q15_02_5',
 'q15_02_6',
 'q15_02_7',
 'q15_02_8',
 'q15_02_9',
 'q15_02_10',
 'q15_02_11',
 'q15_02_12',
 'q15_02_13',
 'q15_02_13_text',
 'q15_03_1',
 'q16',
 'q17_01',
 'q17_02',
 'q18',
 'q19_01',
 'q19_02',
 'q20_01_1',
 'q20_02_1',
 'q21a_1',
 'q21a_2',
 'q21a_3',
 'q21a_4',
 'q21a_5',
 'q21a_6',
 'q21a_6_text',
 'q22_01_1',
 'q22_02_1',
 'q22_03_1',
 'q22_04_1',
 'q22_05_1',
 'q23_01_1',
 'q23_02_1',
 'q23_03_1',
 'q23_04_1',
 'q23_05_1',
 'q24_01_1',
 'q24_02_1',
 'q24_03_1',
 'q24_04_1',
 'q24_05_1',
 'q25_01_1',
 'q25_02_1',
 'q25_03_1',
 'q25_04_1',
 'q26_01_1',
 'q26_02_1',
 'q26_03_1',
 'q27_1',
 'q28_1',
 'q28_2',
 'q28_3',
 'q28_4',
 'q28_4_text',
 'q28_5',
 'q29_1',
 'q29_2',
 'q29_3',
 'q29_4',
 'q29_5',
 'q29_5_text',
 'q30_1',
 'q31_1',
 'q32_1',
 'q33_1',
 'q34_1',
 'q35_1',
 'q36_1',
 'q37a',
 'q38_01_1',
 'q38_02_1',
 'q39_1',
 'q40_1',
 'q41_1',
 'q42_1',
 'rq21a',
 'rq37a',
 'qrq2',
 'rrq2',
 'weight',
 'r']

### 篩選有效樣本中的注意力題答對的樣本

In [158]:
df = df[df['rq21a'] == '答對'].reset_index(drop=True)

In [159]:
df.shape

(685, 211)

In [160]:
df['rrq2'].value_counts()

rrq2
18-29歲    205
30-39歲    188
40-49歲    147
50-59歲     88
60-69歲     45
70歲以上      12
Name: count, dtype: int64

In [161]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 685 entries, 0 to 684
Columns: 211 entries, id to r
dtypes: float64(8), int64(4), object(199)
memory usage: 1.1+ MB

In [162]:
df.head()

,id,startdate,enddate,duration_in_seconds,q1,q2,q3,q3_other,q4,q4_88_text,...,q39_1,q40_1,q41_1,q42_1,rq21a,rq37a,qrq2,rrq2,weight,r
0,1030252,2021-06-23 23:48:22,2021-06-24 00:13:26,1503.0,女,54.0,(02)台北市,NaN,(20)碩士,NaN,...,快樂,65.0,65.0,維持現狀,答對,答對,56.0,50-59歲,0.349006,符合
1,1040123,2021-06-26 10:41:56,2021-06-29 17:20:32,283115.0,男,58.0,(02)台北市,NaN,(21)博士,NaN,...,普通,非常冰冷,90.0,獨立,答對,答對,52.0,50-59歲,0.450735,符合
2,1040131,2021-07-19 10:15:01,2021-07-19 10:32:31,1050.0,女,73.0,(03)新北市,NaN,(20)碩士,NaN,...,普通,50.0,35.0,維持現狀,答對,答對,37.0,30-39歲,0.225117,符合
3,1040139,2021-06-27 10:30:00,2021-06-27 10:39:36,575.0,男,86.0,(02)台北市,NaN,(20)碩士,NaN,...,普通,2.0,70.0,獨立,答對,答對,24.0,18-29歲,0.372256,符合
4,1040208,2021-07-17 11:15:52,2021-07-17 11:28:00,727.0,女,85.0,(02)台北市,NaN,(19)大學,NaN,...,快樂,40.0,60.0,3.0,答對,答對,25.0,18-29歲,0.281218,符合

In [163]:
df['q4'].value_counts()

q4
(19)大學           277
(18)技術學院、科大      111
(20)碩士           110
(11)二專            55
(08)高職(高商、高工)     38
(07)高中職業科         34
(10)五專            22
(04)國(初)中         11
(21)博士             8
(17)軍警官校或大學        6
(06)高中普通科          5
(16)空中大學           3
(12)三專             2
(13)軍警專修班          1
(15)空中行專           1
(14)軍警專科班          1
Name: count, dtype: int64

In [164]:
df['q3'].value_counts()

q3
(02)台北市    101
(03)新北市     86
(14)台南市     74
(15)高雄市     72
(09)台中市     61
(10)彰化縣     59
(04)桃園市     35
(16)屏東縣     34
(11)雲林縣     32
(17)宜蘭縣     22
(12)嘉義縣     20
(06)新竹市     17
(08)南投縣     16
(07)苗栗縣     16
(18)花蓮縣     10
(13)嘉義市      8
(01)基隆市      7
(88)其他       6
(05)新竹縣      5
(19)台東縣      4
Name: count, dtype: int64

In [165]:
for i in range(1, 9):
    print(df[f'q11_{i}'].value_counts())

q11_1
(01)YouTube    655
Name: count, dtype: int64
q11_2
(02)愛奇藝    141
Name: count, dtype: int64
q11_3
(03)Netflix 網飛    238
Name: count, dtype: int64
q11_4
(04)KKTV    38
Name: count, dtype: int64
q11_5
(05)LINE TV    111
Name: count, dtype: int64
q11_6
(06)Li TV    54
Name: count, dtype: int64
q11_7
(07)Twitch    56
Name: count, dtype: int64
q11_8
(08)friDay影音    40
Name: count, dtype: int64